'use strict';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE_KEY='yanis-guided-lilate-b1-cabin-mock-v2';
const state={mode:'guided',voice:'en-GB',answers:{},docAnswers:{},manuals:{},readiness:{},checks:{},values:{},finalSet:0,savedAt:null};
const recordings={};

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}

function setMode(mode){state.mode=mode;document.body.classList.toggle('exam-mode',mode==='exam');$('#guidedMode').classList.toggle('active',mode==='guided');$('#examMode').classList.toggle('active',mode==='exam');save(false);toast(mode==='exam'?'Exam mode: support hidden':'Guided mode: support visible')}
function setVoice(v){state.voice=v;$('#voiceUK').classList.toggle('active',v==='en-GB');$('#voiceUS').classList.toggle('active',v==='en-US');save(false)}
function speak(text,rate=1){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.voice;u.rate=rate;const voices=speechSynthesis.getVoices();u.voice=voices.find(x=>x.lang===state.voice)||voices.find(x=>x.lang.startsWith(state.voice.slice(0,2)))||null;speechSynthesis.speak(u)}

$('#guidedMode').onclick=()=>setMode('guided');$('#examMode').onclick=()=>setMode('exam');$('#voiceUK').onclick=()=>setVoice('en-GB');$('#voiceUS').onclick=()=>setVoice('en-US');$('#stopAudio').onclick=()=>speechSynthesis.cancel();
$('#toggleFrench').onclick=()=>{document.body.classList.toggle('hide-fr');$('#toggleFrench').textContent=document.body.classList.contains('hide-fr')?'FR: hidden':'FR: visible';save(false)};
document.addEventListener('click',e=>{const s=e.target.closest('.speak');if(s)speak(s.dataset.say||'');const sc=e.target.closest('[data-scroll]');if(sc)$(sc.dataset.scroll)?.scrollIntoView({behavior:'smooth'});});

const grammarData=[
 {q:'The flight ___ at 14:20 every day.',o:['leaves','is leaving','left'],a:'leaves',w:'A timetable or routine uses the present simple.'},
 {q:'Passengers ___ now, so please keep the aisle clear.',o:['board','are boarding','boarded'],a:'are boarding',w:'An action happening now uses the present continuous.'},
 {q:'The gate ___ from A7 to B12. Please go to B12 now.',o:['has changed','changed yesterday','changes'],a:'has changed',w:'A recent change with a result now uses the present perfect naturally.'},
 {q:'The passenger ___ her passport at security this morning.',o:['lost','has lose','is losing'],a:'lost',w:'A finished event at a finished time uses the past simple.'},
 {q:'If seat 18C is free, I ___ you there.',o:['will move','would move','moved'],a:'will move',w:'Real future possibility: if + present, will + base verb.'},
 {q:'If a passenger felt unwell, I ___ the senior crew member.',o:['would call','will call','called'],a:'would call',w:'Hypothetical response: if + past, would + base verb.'},
 {q:'For safety, you ___ keep your seat belt fastened.',o:['must','could','might'],a:'must',w:'Must expresses a strong obligation.'},
 {q:'___ you place your bag under the seat, please?',o:['Could','Must','Did'],a:'Could',w:'Could is a polite professional request.'},
 {q:'According to the captain, we ___ in about twenty minutes.',o:['will land','landed','would landed'],a:'will land',w:'You are relaying future operational information.'},
 {q:'If I understand correctly, you ___ a vegetarian meal.',o:['ordered','have ordering','would ordered'],a:'ordered',w:'The passenger placed the order in the past.'},
 {q:'The passenger is anxious because this is the first time she ___ alone.',o:['has travelled','travelled yesterday','is travel'],a:'has travelled',w:'“The first time” with life experience commonly uses present perfect.'},
 {q:'You ___ remain seated until the seat-belt sign is switched off.',o:['have to','could','might'],a:'have to',w:'This is an operational requirement.'},
 {q:'The crew ___ the cabin at the moment.',o:['is checking','checks yesterday','checked every day'],a:'is checking',w:'“At the moment” signals present continuous.'},
 {q:'We ___ the service ten minutes ago.',o:['started','have start','are starting yesterday'],a:'started',w:'“Ten minutes ago” requires the past simple.'},
 {q:'If the passenger needs assistance, we ___ the senior crew member.',o:['will inform','would informed','informed tomorrow'],a:'will inform',w:'This is a realistic future condition.'}
];

function renderGrammar(){const w=$('#grammarQuiz');w.innerHTML='';grammarData.forEach((it,i)=>{const d=document.createElement('article');d.className='quiz-item';d.innerHTML=`<p><b>${i+1}.</b> ${esc(it.q)}</p><div class="options">${shuffle(it.o).map(o=>`<button class="option" type="button" data-v="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="feedback"></div>`;const prior=state.answers['g'+i];if(prior)paintQuiz(d,it,prior);$$('.option',d).forEach(b=>b.onclick=()=>{state.answers['g'+i]=b.dataset.v;paintQuiz(d,it,b.dataset.v);updateScores();save(false)});w.appendChild(d)})}
function paintQuiz(d,it,v){$$('.option',d).forEach(b=>{b.classList.remove('correct','wrong');if(b.dataset.v===it.a)b.classList.add('correct');if(b.dataset.v===v&&v!==it.a)b.classList.add('wrong')});const f=$('.feedback',d);f.textContent=(v===it.a?'✓ Correct. ':'✗ Review. ')+it.w;f.className='feedback '+(v===it.a?'good':'bad')}

const p1=[
 {title:'Seat conflict during boarding',role:'You are cabin crew during boarding.',prompt:'Excuse me, I think someone is sitting in my seat. My boarding pass says 14A, but the passenger says this is his seat.',follow:['What would you do if both boarding passes showed 14A?','What information would you check first?','How would you keep both passengers calm?'],frame:'Acknowledge → ask to see both boarding passes → verify names/seat numbers → explain the next step.',a2:'I’m sorry. Can I see both boarding passes, please? I will check the seat numbers.',b1:'I’m sorry about the confusion. Could I see both boarding passes, please? I’ll check the names and seat numbers. If the same seat has been assigned twice, I’ll contact the gate agent or senior crew member and explain the next step.',plus:'I understand the confusion. Let me verify both boarding passes first. If there is a duplicate seat assignment, I’ll keep both passengers informed and contact the relevant colleague before promising a replacement seat.'},
 {title:'Tight connection before landing',role:'You are cabin crew shortly before landing.',prompt:'My next flight leaves in thirty-five minutes. I’m in row 29 and I’m really worried I’ll miss it. Can I get off first?',follow:['What would you say if you cannot guarantee priority exit?','Which details do you need?','How would you reformulate the concern?'],frame:'Show understanding → ask flight number/destination → avoid false promise → offer to check information.',a2:'I understand. What is your next flight number? I will check the information.',b1:'I understand you’re worried about your connection. Could you give me your next flight number and destination? I can check the latest information, but I cannot promise that you will leave the aircraft first.',plus:'I understand the time is tight. Let me check the flight number, departure gate and current connection status. I cannot guarantee priority disembarkation, but I can give you the most accurate information available and inform the senior crew member if assistance may be needed.'},
 {title:'Special meal and allergy',role:'You are serving meals.',prompt:'I ordered a vegetarian meal, but this looks like chicken. I’m also allergic to nuts. Can you bring me something else?',follow:['What safety question should you ask?','What should you avoid promising?','How would you confirm the request?'],frame:'Apologise → clarify allergy → reformulate → check meal information → confirm next action.',a2:'I’m sorry. You ordered a vegetarian meal and you have a nut allergy. I will check another meal.',b1:'I’m sorry about that. Let me confirm: you ordered a vegetarian meal and you also have a nut allergy. Could you tell me how serious the allergy is? I’ll check the meal information before I offer another option.',plus:'I’m sorry for the mistake. I understand that you need a vegetarian meal and that you have a nut allergy. I’ll verify the label and allergen information before offering anything else, and I’ll involve the senior crew member if necessary.'},
 {title:'Overhead locker is full',role:'You are helping during boarding.',prompt:'There’s no space above my seat and I don’t want to check my bag. I have medication and a laptop inside.',follow:['Which items might need to stay accessible?','How would you avoid making a promise?','What would you check first?'],frame:'Acknowledge → identify important contents → check safe stowage options → explain what you can do.',a2:'I understand. You have medication and a laptop. Let me check if there is safe space nearby.',b1:'I understand you need access to your medication and you have a laptop in the bag. Let me check whether there is safe stowage space nearby. If the bag has to be moved or tagged, I’ll explain the options before we do anything.',plus:'I understand why you want to keep those items accessible. I’ll first check for compliant stowage space in the cabin. If that is not possible, I’ll explain the baggage procedure and make sure you can remove any essential items before the bag is handled.'},
 {title:'Passenger feels anxious',role:'You are cabin crew after take-off.',prompt:'I’m really nervous. This is my first flight alone and the turbulence is making me panic. Is something wrong?',follow:['How would you reassure without making a false safety claim?','What could you ask?','What practical help could you offer?'],frame:'Acknowledge feeling → give calm factual reassurance → ask what would help → offer a practical next step.',a2:'I understand. Turbulence can feel uncomfortable. Please keep your seat belt fastened. I can stay nearby for a moment.',b1:'I understand that this feels stressful, especially because you’re travelling alone. Turbulence can be uncomfortable. Please keep your seat belt fastened, and I can check on you again in a few minutes. Would some water help?',plus:'I understand why you’re anxious. The important thing is to remain seated with your seat belt fastened while the sign is on. I’ll stay attentive and come back to check on you. If you feel unwell, please tell me immediately.'},
 {title:'Lost phone after boarding',role:'You are cabin crew before departure.',prompt:'I can’t find my phone. I had it at the gate, and I think I left it near the boarding scanner. Can I go back and get it?',follow:['What information would you need?','Who might you contact?','What can you avoid promising?'],frame:'Clarify where/when → explain that leaving may not be possible → contact relevant colleague → give next step.',a2:'Where did you last see the phone? I will ask the gate staff.',b1:'If I understand correctly, you last had your phone near the boarding scanner. We may not be able to let you leave the aircraft now, but I can contact the gate team and ask them to check the area.',plus:'Let me confirm: you last saw the phone at the boarding gate near the scanner. I cannot promise that you can return to the gate once boarding is closing, but I can alert the gate staff and give them a description so they can check for it.'}
];
function renderP1(){const s=$('#p1Select');s.innerHTML=p1.map((x,i)=>`<option value="${i}">${i+1}. ${esc(x.title)}</option>`).join('');s.onchange=showP1;showP1()}
function showP1(){const x=p1[+$('#p1Select').value||0];$('#p1Scenario').innerHTML=`<div class="small">${esc(x.role)}</div><h3>${esc(x.title)}</h3><p><strong>Passenger:</strong> “${esc(x.prompt)}”</p>`;$('#p1Framework').innerHTML=`<b>Answer map:</b> ${esc(x.frame)}`;$('#p1Models').innerHTML=`<div class="model-level"><b>A2 minimum</b><p>${esc(x.a2)}</p></div><div class="model-level"><b>B1 target</b><p>${esc(x.b1)}</p></div><div class="model-level"><b>B1+ strong</b><p>${esc(x.plus)}</p></div>`;$('#p1Framework').classList.remove('show');$('#p1Models').classList.remove('show')}
$('#p1Play').onclick=()=>speak(p1[+$('#p1Select').value||0].prompt);$('#p1Follow').onclick=()=>{const x=p1[+$('#p1Select').value||0];const q=x.follow[Math.floor(Math.random()*x.follow.length)];speak(q);toast('Examiner follow-up played')};$('#p1FrameworkBtn').onclick=()=>$('#p1Framework').classList.toggle('show');$('#p1ModelsBtn').onclick=()=>$('#p1Models').classList.toggle('show');

const p2=[
 {title:'Gate change + delay',context:'Airport operations update',audio:'Flight CL482 is delayed by thirty-five minutes because the incoming aircraft arrived late. Boarding will now start at sixteen ten from gate C four. Please make sure passengers use the new gate.',frame:'STATUS → REASON → NEW BOARDING TIME → NEW GATE → ACTION',model:'According to operations, flight CL482 is delayed by 35 minutes because the incoming aircraft arrived late. Boarding will start at 16:10 from gate C4. We need to make sure passengers go to the new gate.'},
 {title:'Medical assistance on arrival',context:'Senior crew briefing',audio:'Passenger twenty-two Delta has reduced mobility. Wheelchair assistance is confirmed for arrival. After landing, please ask the passenger to remain seated until the other passengers have left, then inform me so we can coordinate with the assistance team.',frame:'WHO → NEED → WHAT IS CONFIRMED → INSTRUCTION → NEXT ACTION',model:'Passenger 22D has reduced mobility and wheelchair assistance is confirmed on arrival. After landing, the passenger should remain seated until the others have left. Then I need to inform the senior crew member so we can coordinate with the assistance team.'},
 {title:'Allergy + wrong tray',context:'Cabin service message',audio:'The passenger in twenty-four Alpha says her gluten-free meal was confirmed online, but the tray delivered contains pasta. She also says she has a severe wheat allergy. Stop service to her until the label and allergen information have been checked.',frame:'PASSENGER → EXPECTATION → PROBLEM → SAFETY FACT → IMMEDIATE ACTION',model:'The passenger in 24A expected a gluten-free meal, but the tray delivered contains pasta and she has a severe wheat allergy. We should stop service to her and check the meal label and allergen information before offering anything else.'},
 {title:'Connection risk',context:'Arrival information',audio:'We are expected to arrive at seventeen thirty-five. Passengers connecting to Edinburgh have forty-two minutes before their next departure. Do not promise priority disembarkation. Give them the current connection information and tell the senior crew member if anyone may need assistance.',frame:'ARRIVAL → CONNECTION TIME → DO NOT PROMISE → INFORMATION TO GIVE → WHO TO INFORM',model:'We expect to arrive at 17:35, and passengers to Edinburgh have 42 minutes for their connection. We must not promise priority disembarkation. We should give the current connection information and inform the senior crew member if assistance may be needed.'},
 {title:'Missing cabin bag',context:'Passenger report',audio:'My black laptop bag was in the overhead locker above row twelve before boarding finished, but now it is gone. My work computer, passport and medication are inside.',frame:'ITEM → LAST LOCATION → PROBLEM → IMPORTANT CONTENTS → QUESTION/ACTION',model:'If I understand correctly, your black laptop bag was above row 12, but it is now missing. Your work computer, passport and medication are inside. I’ll report it to the crew immediately and check the nearby lockers. Could you also describe the bag or any label on it?'},
 {title:'Service interruption',context:'Captain / cabin instruction',audio:'The seat-belt sign will remain on for approximately twenty minutes because we expect moderate turbulence. Suspend hot drinks and ask passengers to remain seated. Cold water can be offered only if it can be done safely.',frame:'DURATION → REASON → SERVICE CHANGE → PASSENGER INSTRUCTION → EXCEPTION',model:'The seat-belt sign will stay on for about 20 minutes because moderate turbulence is expected. We need to stop hot drinks and ask passengers to remain seated. Cold water can be offered only if it is safe to do so.'}
];
function renderP2(){const s=$('#p2Select');s.innerHTML=p2.map((x,i)=>`<option value="${i}">${i+1}. ${esc(x.title)}</option>`).join('');s.onchange=showP2;showP2()}
function showP2(){const x=p2[+$('#p2Select').value||0];$('#p2Context').innerHTML=`<div class="small">${esc(x.context)}</div><h3>${esc(x.title)}</h3><p>Listen once. Take notes. Then reformulate.</p>`;$('#p2Transcript').textContent=x.audio;$('#p2Framework').innerHTML=`<b>Keep these blocks:</b> ${esc(x.frame)}`;$('#p2Models').innerHTML=`<b>B1 target</b><p>${esc(x.model)}</p>`;['p2Transcript','p2Framework','p2Models'].forEach(id=>$('#'+id).classList.remove('show'))}
$('#p2Play').onclick=()=>speak(p2[+$('#p2Select').value||0].audio);$('#p2TranscriptBtn').onclick=()=>$('#p2Transcript').classList.toggle('show');$('#p2FrameworkBtn').onclick=()=>$('#p2Framework').classList.toggle('show');$('#p2ModelsBtn').onclick=()=>$('#p2Models').classList.toggle('show');

const p3=[
 {title:'Medical team boards first',context:'Senior crew → you → passengers',audio:'After landing, keep passengers in rows one to eight seated for about two minutes so the medical team can board quickly through the front door. Ask everyone to keep the aisle clear until the team has passed.',constraints:['A passenger in row 3 asks why they must stay seated.','Someone stands up and blocks the aisle.','A passenger says they have a very tight connection.'],model:'After landing, passengers in rows 1 to 8 need to remain seated for about two minutes. A medical team must board through the front door, so please keep the aisle clear until they have passed. Thank you for your cooperation.'},
 {title:'Exit-row seat request',context:'Senior crew → you → passenger',audio:'The passenger in eighteen Delta wants to move to an exit-row seat. Explain that the change cannot be made until eligibility and availability have been checked. Do not suggest that the seat is guaranteed.',constraints:['The passenger says another crew member promised it.','The passenger becomes impatient.','The passenger asks what eligibility means.'],model:'I understand you would like an exit-row seat. Before any change, we need to check both availability and whether the passenger meets the exit-row requirements. I cannot guarantee the seat, but I can check the situation for you.'},
 {title:'Baggage tagging at the gate',context:'Gate agent → you → boarding passenger',audio:'Overhead space is limited on this flight. Larger cabin bags may need to be tagged at the gate. Passengers should remove medication, travel documents, valuables and spare lithium batteries before handing over a bag.',constraints:['The passenger says the bag contains a laptop.','The passenger refuses to remove medication.','The passenger asks if every bag will be tagged.'],model:'Overhead space is limited, so larger cabin bags may need to be tagged. Before handing over a bag, please remove medication, travel documents, valuables and any spare lithium batteries. I can help you check what needs to stay with you.'},
 {title:'Turbulence procedure',context:'Captain → you → cabin',audio:'We expect moderate turbulence for the next twenty minutes. Please secure the cabin, suspend hot-drink service, and make sure passengers remain seated with their seat belts fastened until the sign is switched off.',constraints:['A passenger asks to use the toilet.','A passenger wants a hot coffee now.','The turbulence starts before you finish service.'],model:'We expect moderate turbulence for about twenty minutes. For safety, please remain seated with your seat belt fastened. Hot-drink service is suspended until conditions improve and the seat-belt sign is switched off.'},
 {title:'Delay announcement',context:'Operations → you → passengers',audio:'Departure is delayed by twenty-five minutes because the aircraft is waiting for a new departure slot. The estimated departure time is fifteen forty. Please apologise and tell passengers that the time may change if air traffic control updates the slot.',constraints:['A passenger asks for a guarantee.','A passenger says they will miss a meeting.','The estimated time changes again.'],model:'I’m sorry, our departure is currently delayed by about 25 minutes because we are waiting for a new departure slot. The estimated departure time is 15:40, but this may change if air traffic control updates the slot. We’ll keep you informed.'},
 {title:'Wheelchair handover',context:'Cabin crew → you → assistance team',audio:'Passenger twenty-two Delta can walk short distances but cannot manage stairs. A wheelchair is confirmed at the aircraft door. The passenger is travelling alone and has one small cabin bag.',constraints:['The wheelchair is not at the door when you arrive.','The passenger asks if they can walk to the terminal.','The assistance agent asks if the passenger can use stairs.'],model:'Passenger 22D can walk short distances but cannot manage stairs. A wheelchair is confirmed at the aircraft door. The passenger is travelling alone and has one small cabin bag. Please let me know if the wheelchair is not available when we arrive.'}
];
function renderP3(){const s=$('#p3Select');s.innerHTML=p3.map((x,i)=>`<option value="${i}">${i+1}. ${esc(x.title)}</option>`).join('');s.onchange=showP3;showP3()}
function showP3(){const x=p3[+$('#p3Select').value||0];$('#p3Context').innerHTML=`<div class="small">${esc(x.context)}</div><h3>${esc(x.title)}</h3><p>Listen, then relay the message to the person named in the scenario.</p>`;$('#p3Transcript').textContent=x.audio;$('#p3Models').innerHTML=`<b>B1 target</b><p>${esc(x.model)}</p>`;$('#p3Transcript').classList.remove('show');$('#p3Models').classList.remove('show')}
$('#p3Play').onclick=()=>speak(p3[+$('#p3Select').value||0].audio);$('#p3Constraint').onclick=()=>{const x=p3[+$('#p3Select').value||0];speak(x.constraints[Math.floor(Math.random()*x.constraints.length)]);toast('New constraint played')};$('#p3TranscriptBtn').onclick=()=>$('#p3Transcript').classList.toggle('show');$('#p3ModelsBtn').onclick=()=>$('#p3Models').classList.toggle('show');

const docQ=[
 {q:'What time does boarding begin?',o:['13:25','14:05','14:25'],a:'13:25',w:'The briefing lists boarding at 13:25.'},
 {q:'Which passenger has confirmed mobility assistance?',o:['22D','18B','7A'],a:'22D',w:'Passenger 22D has wheelchair assistance confirmed on arrival.'},
 {q:'What may happen to larger cabin bags?',o:['They may be tagged at the gate','They must stay in the cabin','They must be left at security'],a:'They may be tagged at the gate',w:'Overhead space is limited, so larger cabin bags may be tagged.'},
 {q:'What must you avoid promising to Edinburgh passengers?',o:['Priority disembarkation','Connection information','Senior crew assistance'],a:'Priority disembarkation',w:'The crew instruction specifically says not to promise priority disembarkation.'},
 {q:'How much connection time do Edinburgh passengers have?',o:['42 minutes','24 minutes','52 minutes'],a:'42 minutes',w:'The connection note gives 42 minutes after scheduled arrival.'},
 {q:'How many vegetarian meals are loaded?',o:['Two','One','Three'],a:'Two',w:'The service note says two vegetarian meals.'},
 {q:'What should you verify before giving a special meal?',o:['The special-meal label','The passenger’s passport','The boarding time'],a:'The special-meal label',w:'The service note says to verify special-meal labels before service.'},
 {q:'If a connection passenger may need help, who should you notify?',o:['The senior crew member','Airport security','The pilot directly'],a:'The senior crew member',w:'The crew instruction says to notify the senior crew member.'}
];
function renderDocQuiz(){const w=$('#documentQuiz');w.innerHTML='';docQ.forEach((it,i)=>{const d=document.createElement('article');d.className='quiz-item';d.innerHTML=`<p><b>${i+1}.</b> ${esc(it.q)}</p><div class="options">${shuffle(it.o).map(o=>`<button class="option" data-v="${esc(o)}" type="button">${esc(o)}</button>`).join('')}</div><div class="feedback"></div>`;const prior=state.docAnswers['d'+i];if(prior)paintQuiz(d,it,prior);$$('.option',d).forEach(b=>b.onclick=()=>{state.docAnswers['d'+i]=b.dataset.v;paintQuiz(d,it,b.dataset.v);updateScores();save(false)});w.appendChild(d)})}
$('#docModelBtn').onclick=()=>$('#docModel').classList.toggle('show');

const finalSets=[
 [
  {type:'PART 1 · INTERACT',title:'Seat 21C problem',prompt:'A passenger says seat 21C is broken and asks to move to business class. Respond, clarify and give a next step.'},
  {type:'PART 2 · REFORMULATE',title:'Listen: delay + gate',audio:'Flight CL906 is delayed by forty minutes. Boarding will start at eighteen twenty-five from gate D seven. The delay is due to a late inbound aircraft.',prompt:'Reformulate the essential information in your own words.'},
  {type:'PART 3 · TRANSMIT',title:'Relay a cabin instruction',audio:'Please tell passengers in rows twenty to thirty that they must keep the aisle clear while we move a medical kit to the rear galley.',prompt:'Relay the instruction clearly and give the reason.'},
  {type:'PART 4 · EXPLOIT',title:'Use the crew brief',prompt:'Using the document above, explain what you would tell an Edinburgh passenger with a short connection.'}
 ],
 [
  {type:'PART 1 · INTERACT',title:'Passenger wants to change seats',prompt:'A passenger wants to move next to a friend, but boarding is still in progress. Respond professionally.'},
  {type:'PART 2 · REFORMULATE',title:'Listen: special meal',audio:'Passenger nine Alpha requested a vegetarian meal, but only the standard tray is at the seat. Ask the crew member to verify whether the special meal is still in the galley before offering another option.',prompt:'Reformulate the situation and action.'},
  {type:'PART 3 · TRANSMIT',title:'Relay turbulence instructions',audio:'Moderate turbulence is expected for fifteen minutes. Stop hot drinks and ask passengers to remain seated until the seat-belt sign is off.',prompt:'Make a passenger announcement in clear English.'},
  {type:'PART 4 · EXPLOIT',title:'Use baggage information',prompt:'Using the crew brief, explain what you would tell a passenger with a larger cabin bag.'}
 ],
 [
  {type:'PART 1 · INTERACT',title:'Anxious first-time solo traveller',prompt:'A passenger says they are scared of turbulence and asks if something is wrong. Respond and keep the interaction going.'},
  {type:'PART 2 · REFORMULATE',title:'Listen: wheelchair arrival',audio:'Passenger fifteen Foxtrot has wheelchair assistance confirmed at the aircraft door and cannot use stairs. Please ask the passenger to remain seated until the aisle is clear.',prompt:'Reformulate the key information.'},
  {type:'PART 3 · TRANSMIT',title:'Relay a lost-item report',audio:'The passenger in twelve Bravo has lost a black phone. The last known location was the boarding gate near the scanner. Please inform the gate team and ask them to check the area.',prompt:'Relay the message to the gate team.'},
  {type:'PART 4 · EXPLOIT',title:'Use special-meal information',prompt:'Using the crew brief, explain what you should check before giving a special meal.'}
 ]
];
function renderFinal(){const set=finalSets[state.finalSet%finalSets.length],w=$('#finalCards');w.innerHTML='';set.forEach((x,i)=>{const d=document.createElement('article');d.className='final-card';d.innerHTML=`<span>${esc(x.type)}</span><h3>${esc(x.title)}</h3>${x.audio?'<p>Listen to the examiner message, then answer.</p>':''}<p>${esc(x.prompt)}</p>${x.audio?`<button class="secondary final-audio" type="button" data-final-audio="${i}">🔊 Play message</button>`:''}<textarea rows="4" data-final-note="${i}" placeholder="Your notes / teacher notes"></textarea>`;w.appendChild(d)});$$('[data-final-audio]').forEach(b=>b.onclick=()=>speak(set[+b.dataset.finalAudio].audio));restoreValueFields()}
$('#newFinalSet').onclick=()=>{state.finalSet=(state.finalSet+1)%finalSets.length;renderFinal();save(false);toast('New exam set loaded')};

const timers={};
function startTimer(key,seconds,display){if(timers[key]?.int){clearInterval(timers[key].int)}timers[key]={left:seconds};const tick=()=>{const m=Math.floor(timers[key].left/60),s=timers[key].left%60;display.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(timers[key].left<=0){clearInterval(timers[key].int);timers[key].int=null;toast('Time is up');return}timers[key].left--};tick();timers[key].int=setInterval(tick,1000)}
$$('[data-timer]').forEach(b=>b.onclick=()=>{const k=b.dataset.timer,sec=k==='p1'?90:120;startTimer(k,sec,$('#'+k+'Timer'))});
let master={left:3600,int:null,running:false};function paintMaster(){const m=Math.floor(master.left/60),s=master.left%60;$('#masterTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
$('#startMaster').onclick=()=>{if(master.running)return;master.running=true;master.int=setInterval(()=>{if(master.left<=0){clearInterval(master.int);master.running=false;toast('60-minute mock complete');return}master.left--;paintMaster()},1000)};$('#pauseMaster').onclick=()=>{if(master.int)clearInterval(master.int);master.int=null;master.running=false};$('#resetMaster').onclick=()=>{if(master.int)clearInterval(master.int);master={left:3600,int:null,running:false};paintMaster()};

async function beginRecording(key){if(!navigator.mediaDevices?.getUserMedia){toast('Recording is not supported in this browser');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream);const chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});recordings[key]={blob,url:URL.createObjectURL(blob)};const audio=$('#audio-'+key);audio.src=recordings[key].url;audio.classList.remove('hidden');const dl=$(`.rec-download[data-rec="${key}"]`);if(dl)dl.disabled=false;stream.getTracks().forEach(t=>t.stop());toast('Recording ready')};recordings[key]={rec,stream};rec.start();$(`.rec-start[data-rec="${key}"]`).disabled=true;$(`.rec-stop[data-rec="${key}"]`).disabled=false;toast('Recording started')}catch(e){toast('Microphone permission is required')}}
function stopRecording(key){const r=recordings[key]?.rec;if(r&&r.state!=='inactive')r.stop();$(`.rec-start[data-rec="${key}"]`).disabled=false;$(`.rec-stop[data-rec="${key}"]`).disabled=true}
$$('.rec-start').forEach(b=>b.onclick=()=>beginRecording(b.dataset.rec));$$('.rec-stop').forEach(b=>b.onclick=()=>stopRecording(b.dataset.rec));$$('.rec-download').forEach(b=>b.onclick=()=>{const r=recordings[b.dataset.rec];if(!r?.url)return;const a=document.createElement('a');a.href=r.url;a.download=`Yanis-${b.dataset.rec}-recording.webm`;a.click()});

function scoredTotals(){let correct=0,total=grammarData.length+docQ.length;grammarData.forEach((x,i)=>{if(state.answers['g'+i]===x.a)correct++});docQ.forEach((x,i)=>{if(state.docAnswers['d'+i]===x.a)correct++});return{correct,total}}
function statusLabel(v){return({'not-started':'Not started','in-progress':'In progress','achieved':'Achieved','not-achieved':'Not achieved'})[v]||v}
function updateScores(){const {correct,total}=scoredTotals();$('#scoreNow').textContent=correct;$('#scoreTotal').textContent=total;const auto=total?Math.round(correct/total*100):0;$('#autoPercent').textContent=auto+'%';const allScored=[...grammarData.map((_,i)=>state.answers['g'+i]),...docQ.map((_,i)=>state.docAnswers['d'+i])];const closedDone=allScored.filter(Boolean).length;const manualVals=$$('[data-manual]').map(x=>x.value);const readyVals=$$('[data-readiness]').map(x=>x.value);const checks=$$('[data-check]').map(x=>x.checked);const textIds=['rescuePhrase1','rescuePhrase2','p1Notes','p2Who','p2Problem','p2Detail','p2Action','p2Answer','p3Notes','docOralNotes','strengths','priority','trainerComments'];const textDone=textIds.filter(id=>($('#'+id)?.value||'').trim()).length;const totalSteps=allScored.length+manualVals.length+readyVals.length+checks.length+textIds.length;const done=closedDone+manualVals.filter(v=>v!=='not-started').length+readyVals.filter(v=>v!=='not-started').length+checks.filter(Boolean).length+textDone;const comp=totalSteps?Math.round(done/totalSteps*100):0;$('#completionPercent').textContent=comp+'%';$('#completionLabel').textContent=comp+'% completed';$('#progressBar').style.width=comp+'%';const achieved=readyVals.filter(v=>v==='achieved').length,notAch=readyVals.filter(v=>v==='not-achieved').length,inProg=readyVals.filter(v=>v==='in-progress').length;let sig='Not assessed';if(readyVals.some(v=>v!=='not-started')){if(achieved>=6&&notAch===0&&auto>=70)sig='B1 target looking strong';else if(achieved>=4&&notAch<=1&&auto>=60)sig='Close — reinforce key points';else if(notAch>=3||auto<50)sig='Priority review needed';else sig='Developing toward B1'}$('#readinessSignal').textContent=sig;const p1v=$('[data-manual="part1"]').value;$('#p1Status').textContent=statusLabel(p1v)}

function collectValues(){const vals={};$$('input,textarea,select').forEach(el=>{if(el.id)vals[el.id]=el.value});$$('[data-final-note]').forEach((el,i)=>vals['finalNote'+i]=el.value);return vals}
function save(announce=true){state.values=collectValues();state.checks={};$$('[data-check]').forEach(el=>state.checks[el.dataset.check]=el.checked);state.manuals={};$$('[data-manual]').forEach(el=>state.manuals[el.dataset.manual]=el.value);state.readiness={};$$('[data-readiness]').forEach(el=>state.readiness[el.dataset.readiness]=el.value);state.savedAt=new Date().toISOString();try{localStorage.setItem(STORAGE_KEY,JSON.stringify({state,hideFr:document.body.classList.contains('hide-fr')}));if(announce){$('#saveStatus').textContent='Saved in this browser · '+new Date().toLocaleString();toast('Progress saved')}}catch(e){if(announce)toast('Browser storage unavailable')}}
function restoreValueFields(){Object.entries(state.values||{}).forEach(([id,v])=>{if(id.startsWith('finalNote')){const i=+id.replace('finalNote','');const el=$(`[data-final-note="${i}"]`);if(el)el.value=v;return}const el=$('#'+id);if(el)el.value=v})}
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;const d=JSON.parse(raw);Object.assign(state,d.state||{});if(d.hideFr)document.body.classList.add('hide-fr')}catch(e){}}

function resetSection(name){if(!confirm('Reset this section only?'))return;const sec=$(`[data-section="${name}"]`);if(!sec)return;$$('input,textarea',sec).forEach(el=>{if(el.type==='checkbox')el.checked=false;else if(!['learnerName','trainerName','evalDate'].includes(el.id))el.value=''});$$('select',sec).forEach(el=>{if(el.dataset.manual||el.dataset.readiness)el.value='not-started';else el.selectedIndex=0});if(name==='grammar'){grammarData.forEach((_,i)=>delete state.answers['g'+i]);renderGrammar()}if(name==='part4'){docQ.forEach((_,i)=>delete state.docAnswers['d'+i]);renderDocQuiz();$('#docModel').classList.remove('show')}if(name==='part1'){$('[data-manual="part1"]').value='not-started';showP1()}if(name==='part2'){$('[data-manual="part2"]').value='not-started';showP2()}if(name==='part3'){$('[data-manual="part3"]').value='not-started';showP3()}if(name==='finalMock'){$('[data-manual="final"]').value='not-started';$$('[data-check]',sec).forEach(x=>x.checked=false);renderFinal();$('#resetMaster').click()}if(name==='evaluation'){$$('[data-readiness]',sec).forEach(x=>x.value='not-started');['strengths','priority','trainerComments'].forEach(id=>$('#'+id).value='')};save(false);updateScores();toast('Section reset')}
$$('[data-reset-section]').forEach(b=>b.onclick=()=>resetSection(b.dataset.resetSection));

function reportText(){const {correct,total}=scoredTotals(),pct=total?Math.round(correct/total*100):0;const manuals=$$('[data-manual]').map(x=>`${x.dataset.manual}: ${statusLabel(x.value)}`).join('\n');const readiness=$$('[data-readiness]').map(x=>`${x.parentElement.childNodes[0].textContent.trim()}: ${statusLabel(x.value)}`).join('\n');return `YANIS — GUIDED LILATE B1 CABIN CREW MOCK\nLearner: ${$('#learnerName').value}\nTrainer: ${$('#trainerName').value}\nDate: ${$('#evalDate').value}\nAutomatic score: ${correct}/${total} (${pct}%)\nCompletion: ${$('#completionPercent').textContent}\nB1 readiness: ${$('#readinessSignal').textContent}\n\nMOCK ASSESSMENTS\n${manuals}\n\nREADINESS GRID\n${readiness}\n\nSTRONG POINTS\n${$('#strengths').value}\n\nPRIORITY BEFORE EXAM\n${$('#priority').value}\n\nTRAINER COMMENTS\n${$('#trainerComments').value}\n`}
function reportHtml(){const {correct,total}=scoredTotals(),pct=total?Math.round(correct/total*100):0;const row=(label,val)=>`<tr><th>${esc(label)}</th><td>${esc(val)}</td></tr>`;const manualRows=$$('[data-manual]').map(x=>row(x.dataset.manual,statusLabel(x.value))).join('');const readinessRows=$$('[data-readiness]').map(x=>row(x.parentElement.childNodes[0].textContent.trim(),statusLabel(x.value))).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>Yanis Mock Exam Report</title><style>body{font-family:Arial,sans-serif;max-width:900px;margin:35px auto;padding:0 20px;color:#172432}h1{color:#0f5e61}table{width:100%;border-collapse:collapse;margin:15px 0}th,td{border:1px solid #d7dfe2;padding:9px;text-align:left}th{background:#f0f5f4;width:45%}.box{background:#eef5f4;padding:12px;border-left:4px solid #1c7a78;margin:12px 0;white-space:pre-wrap}</style></head><body><h1>Yanis — Guided LILATE B1 Cabin Crew Mock</h1><p><b>Learner:</b> ${esc($('#learnerName').value)}<br><b>Trainer:</b> ${esc($('#trainerName').value)}<br><b>Date:</b> ${esc($('#evalDate').value)}</p><h2>Results</h2><table>${row('Automatic score',`${correct}/${total} (${pct}%)`)}${row('Completion',$('#completionPercent').textContent)}${row('B1 readiness',$('#readinessSignal').textContent)}</table><h2>Mock assessments</h2><table>${manualRows}</table><h2>Readiness grid</h2><table>${readinessRows}</table><h2>Strong points</h2><div class="box">${esc($('#strengths').value)}</div><h2>Priority before exam</h2><div class="box">${esc($('#priority').value)}</div><h2>Trainer comments</h2><div class="box">${esc($('#trainerComments').value)}</div></body></html>`}
$('#saveProgress').onclick=()=>save(true);$('#copyReport').onclick=async()=>{try{await navigator.clipboard.writeText(reportText());toast('Report copied')}catch(e){toast('Copy blocked by browser')}};$('#downloadHtml').onclick=()=>{const blob=new Blob([reportHtml()],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Yanis-Guided-LILATE-B1-Mock-Report.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#printReport').onclick=()=>window.print();$('#resetAll').onclick=()=>{if(!confirm('Reset the whole lesson and delete saved progress in this browser?'))return;localStorage.removeItem(STORAGE_KEY);location.reload()};

function bindPersistence(){document.addEventListener('input',e=>{if(e.target.matches('input,textarea,select')){updateScores();save(false)}});document.addEventListener('change',e=>{if(e.target.matches('[data-manual],[data-readiness],[data-check]')){updateScores();save(false)}})}

const back=$('#backToTop');window.addEventListener('scroll',()=>back.classList.toggle('show',scrollY>700));back.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});

function init(){const d=new Date();$('#evalDate').value=d.toISOString().slice(0,10);load();renderGrammar();renderP1();renderP2();renderP3();renderDocQuiz();renderFinal();restoreValueFields();showP1();showP2();showP3();$$('[data-manual]').forEach(x=>{if(state.manuals?.[x.dataset.manual])x.value=state.manuals[x.dataset.manual]});$$('[data-readiness]').forEach(x=>{if(state.readiness?.[x.dataset.readiness])x.value=state.readiness[x.dataset.readiness]});$$('[data-check]').forEach(x=>{if(state.checks?.[x.dataset.check])x.checked=true});setMode(state.mode||'guided');setVoice(state.voice||'en-GB');$('#toggleFrench').textContent=document.body.classList.contains('hide-fr')?'FR: hidden':'FR: visible';paintMaster();bindPersistence();updateScores();if(state.savedAt)$('#saveStatus').textContent='Saved in this browser · '+new Date(state.savedAt).toLocaleString()}

document.addEventListener('DOMContentLoaded',init);
