(() => {
'use strict';
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const KEY='cloe_made_clear_review_v1';
let state={fr:true,done:{},answers:{},final:{},checks:[],usefulness:'',confidence:'',priority:'',vocabCat:''};
try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)state={...state,...x}}catch(e){}
const skillInfo={Vocabulary:'Professional and everyday word choice, meaning and collocations.',Grammar:'Verb forms, sentence structure, prepositions, pronouns, conditionals, passive forms and more.',Expressions:'Useful language for requests, clarification, agreement, disagreement, suggestions and professional interaction.',Reading:'Purpose, detail, sequence, meaning in context and implied information.',Listening:'Announcements, messages, dialogues and monologues: gist, details, requests, reasons and opinions.'};
const mechanics=[
 ['Dropdown gap','Choose the word that fits meaning and grammar.','select','I have worked here ____ 2024.',['for','since','during'],'since','A starting point uses “since”.'],
 ['Typed gap','Supply the missing word yourself.','input','If the meeting is cancelled, I ____ call you.',[],'will','First conditional: if + present → will + verb.'],
 ['Word bank','Choose a proposed word for the gap.','bank','We need to ____ the problem before Friday.',['solve','borrow','arrive','spend'],'solve','Which verb naturally goes with “problem”?'],
 ['Sentence order','Build correct English word order.','order','Build the sentence.',['Could','you','send','me','the','file','please'],'Could you send me the file please','Modal + subject + base verb + object.'],
 ['Multiple choice','Only one answer is best.','mcq','A deadline is…',['a final time for completion','a meeting room','a salary increase'],'a final time for completion','Eliminate unrelated meanings first.'],
 ['Text order','Put ideas into a logical sequence.','order','Build the process.',['Open the portal','Select Expenses','Upload receipts','Submit the claim'],'Open the portal Select Expenses Upload receipts Submit the claim','Look for chronology: first → next → then → final action.']
];
const grammar=[
 ['Present tenses','Present simple vs present continuous','Use present simple for routines/facts. Use present continuous for actions happening now or temporary situations.','Présent simple = habitudes/faits. Présent continu = maintenant / temporaire.',['I usually <b>work</b> from home on Fridays.','I <b>am working</b> from home today.'],'At the moment, we ____ a new system.',['test','are testing','tested'],'are testing'],
 ['Past & present perfect','Past simple vs have/has + past participle','Use past simple with a finished past time. Use present perfect for a period linked to now.','Past simple = passé terminé. Present perfect = since/for/already/yet ou lien avec maintenant.',['I <b>met</b> the client yesterday.','I <b>have worked</b> here for three years.'],'She ____ in this team since January.',['worked','has worked','works yesterday'],'has worked'],
 ['Future forms','will / be going to / present continuous','Use will for decisions/predictions, going to for intentions/plans, and present continuous for arranged future plans.','will = décision/prédiction ; going to = intention ; présent continu = arrangement fixé.',['I <b>will call</b> you later.','We <b>are meeting</b> the supplier tomorrow.'],'We ____ the client tomorrow at 2 p.m. The appointment is confirmed.',['are meeting','meet yesterday','have met'],'are meeting'],
 ['Questions','Auxiliary + subject + verb?','Use do/does/did for ordinary verbs, be before the subject, and modals before the subject.','Attention à l’ordre des mots : auxiliaire + sujet + verbe.',['Where <b>do you work</b>?','When <b>did you arrive</b>?','<b>Could you send</b> the file?'],'Which question is correct?',['Where you work?','Where do you work?','Where does you work?'],'Where do you work?'],
 ['Modals','modal + base verb','Can/could for ability or requests; should for advice; must/have to for obligation; might/may for possibility.','Après un modal : verbe sans “to” (sauf have to).',['You <b>should check</b> the figures.','<b>Could you repeat</b> that?'],'You ____ speak to the manager if the problem continues.',['should','should to','should speaking'],'should'],
 ['Conditionals','If + present → will | If + past → would','First conditional = realistic future. Second conditional = hypothetical or less likely.','1er conditionnel = possible/réel. 2e = hypothétique.',['If it rains, we <b>will stay</b> inside.','If I had more time, I <b>would review</b> it.'],'If we had a larger budget, we ____ more staff.',['hire','will hire','would hire'],'would hire'],
 ['Passive voice','be + past participle','Use the passive when the action/result is more important than the person who performs it.','Passif = be + participe passé.',['The report <b>was approved</b> yesterday.','The documents <b>will be sent</b> tomorrow.'],'The new policy ____ last week.',['was introduced','introduced itself','was introduce'],'was introduced'],
 ['Relative clauses','who / which / that / where','Who for people; which/that for things; where for places.','who = personne ; which/that = chose ; where = lieu.',['The colleague <b>who</b> called me…','The system <b>which</b> we use…','The office <b>where</b> I work…'],'The person ____ manages the project is on leave.',['who','where','which place'],'who'],
 ['Comparisons','-er / more + adjective | the -est / most','Use comparatives for two things; superlatives for the highest/lowest in a group.','Comparatif = 2 éléments ; superlatif = le plus / le moins.',['This option is <b>cheaper than</b> the other one.','It is <b>the most practical</b> solution.'],'This process is ____ than the old one.',['more efficient','most efficient','efficiently'],'more efficient'],
 ['Prepositions','at / on / in · since / for · by / until','Memorise common combinations rather than translating directly from French.','at 3 p.m., on Monday, in September; since 2024, for two years; by Friday.',['<b>at</b> 2 p.m. · <b>on</b> Monday · <b>in</b> June','Send it <b>by</b> Friday.'],'The meeting is ____ Monday at 10 a.m.',['on','in','at Monday'],'on'],
 ['Gerund / infinitive','verb + -ing OR to + verb','High-value examples: enjoy doing, suggest doing, decide to do, need to do.','Certains verbes prennent -ing, d’autres “to + infinitif”.',['She suggested <b>postponing</b> the meeting.','We decided <b>to wait</b>.'],'They suggested ____ the launch until Monday.',['postponing','to postponing','postpone to'],'postponing'],
 ['Linking words','because / so / although / however / therefore','Use connectors to show cause, result, contrast and sequence.','because = cause ; so/therefore = conséquence ; although/however = contraste.',['We were late <b>because</b> the train was cancelled.','The idea is useful. <b>However</b>, it is expensive.'],'The results are positive. ____, we still need more data.',['However','Because','So that'],'However']
];
const vocab={
 'Work & organisation':[['deadline','date limite','the latest time by which something must be completed','The deadline is Friday.'],['schedule','planning / programme','a plan of times or activities','We need to change the schedule.'],['task','tâche','a piece of work to be done','I have three urgent tasks today.'],['responsibility','responsabilité','something you are expected to manage or do','Customer follow-up is one of my responsibilities.'],['colleague','collègue','a person you work with','I asked a colleague for help.'],['department','service','a division of an organisation','Please contact the finance department.']],
 'Problems & solutions':[['issue','problème / question','a problem or matter to deal with','We need to discuss this issue.'],['solve','résoudre','find an answer to a problem','We solved the problem quickly.'],['delay','retard','something happening later than planned','There is a two-day delay.'],['risk','risque','a possibility of something negative happening','We need to assess the risk.'],['improve','améliorer','make something better','We want to improve the process.'],['prevent','empêcher / prévenir','stop something from happening','This check can prevent errors.']],
 'Meetings & communication':[['agenda','ordre du jour','list of subjects for a meeting','I sent the meeting agenda.'],['minutes','compte rendu','official notes of a meeting','Could you send the meeting minutes?'],['clarify','clarifier','make something easier to understand','Could you clarify that point?'],['confirm','confirmer','state that something is certain or agreed','Please confirm the date.'],['update','mise à jour / mettre à jour','new information or make information current','I will send you an update tomorrow.'],['feedback','retour / commentaires','information about performance or a proposal','Thank you for your feedback.']],
 'Customers & service':[['complaint','réclamation','a statement that something is unsatisfactory','We received a customer complaint.'],['request','demande','an act of asking for something','I received your request.'],['refund','remboursement','money returned after a purchase','The customer requested a refund.'],['available','disponible','free or ready to be used/contacted','I am available after 3 p.m.'],['satisfied','satisfait','pleased with a product or service','The client was satisfied with the solution.'],['handle','gérer','deal with a situation or responsibility','I handle customer enquiries.']],
 'Business & results':[['revenue','chiffre d’affaires / revenus','money generated by business activity','Revenue increased last quarter.'],['cost','coût','amount of money needed for something','We need to reduce costs.'],['budget','budget','planned amount of money available','The project is within budget.'],['target','objectif','result you aim to achieve','We reached our sales target.'],['increase','augmenter','become or make larger','Sales increased by 8%.'],['decrease','diminuer','become or make smaller','Complaints decreased this month.']]
};
const vocabQuiz=[['The latest date for completing a task is the…',['deadline','department','refund'],'deadline'],['To make a process better means to…',['improve','borrow','attend'],'improve'],['Official notes from a meeting are called…',['minutes','targets','risks'],'minutes'],['Money generated by business activity is…',['revenue','agenda','schedule'],'revenue'],['A statement that something is unsatisfactory is a…',['complaint','colleague','budget'],'complaint'],['To deal with a customer request means to…',['handle it','lend it','postpone it always'],'handle it']];
const expr=[['Clarify',['Could you clarify that point?','What exactly do you mean by…?','Could you give me an example?']],['Ask to repeat',['Could you repeat that, please?','Sorry, I didn’t catch the last part.','Could you say that again a little more slowly?']],['Check understanding',['If I understand correctly, you need…','So, just to confirm…','Do you mean that…?']],['Make a request',['Could you send me the updated file?','Would it be possible to move the meeting?','Would you mind sending the figures today?']],['Suggest',['We could try…','Why don’t we…?','You might want to consider…']],['Agree / disagree',['I agree with that.','I see your point, but…','I’m not sure I completely agree because…']],['Apologise',['I’m sorry for the delay.','I apologise for the inconvenience.','I’m afraid there has been a problem.']],['Negotiate',['Would a partial delivery be possible?','Could we agree on a new deadline?','What alternatives can you offer?']],['Summarise',['So, we’ve agreed to…','To sum up…','The main point is that…']]];
const exprQuiz=[['You did not understand the question.',['Could you repeat the question, please?','Ask again.','You speak too fast.'],'Could you repeat the question, please?'],['You want to disagree politely.',['I see your point, but I have a different view.','No, you are wrong.','That is impossible.'],'I see your point, but I have a different view.'],['You want to verify what you heard.',['So, just to confirm, the deadline is Friday?','You say Friday.','Deadline Friday maybe.'],'So, just to confirm, the deadline is Friday?'],['You want to propose an alternative.',['Would Monday afternoon work instead?','Monday is better.','Change it to Monday.'],'Would Monday afternoon work instead?'],['You need a few seconds to think.',['Let me think for a moment.','I don’t know.','Wait.'],'Let me think for a moment.']];
const readings=[
 {tag:'PURPOSE',text:'Subject: Meeting change\nHello,\nUnfortunately, I am no longer available at 10 a.m. tomorrow. Would 3 p.m. tomorrow or 11 a.m. on Thursday work for you? Please let me know which option you prefer.\nKind regards,',q:'Why was this email sent?',opts:['To cancel a project','To propose alternative meeting times','To request a payment'],a:'To propose alternative meeting times',ex:'The writer cannot attend the original time and proposes two alternatives.'},
 {tag:'DETAIL',text:'NOTICE\nThe reception desk will close at 12:30 today for staff training and reopen at 2:00 p.m. Visitors arriving during this period should use the online check-in form.',q:'What should visitors do between 12:30 and 2:00?',opts:['Wait outside','Use the online check-in form','Call the finance team'],a:'Use the online check-in form',ex:'The final sentence gives the instruction.'},
 {tag:'MEANING',text:'The pilot results are encouraging overall. Error rates are lower and users are completing tasks faster. However, several new employees struggled during the first week.',q:'What does “encouraging” mean here?',opts:['promising / positive','confusing','finished'],a:'promising / positive',ex:'The next sentence gives positive evidence.'},
 {tag:'INFERENCE',text:'Rather than introduce the platform in every office at once, the team recommends testing it for six weeks in two locations. User adoption and support requests will be measured before a final decision.',q:'What can we infer?',opts:['The platform has already been fully launched','The team wants evidence before a wider rollout','The project has been cancelled'],a:'The team wants evidence before a wider rollout',ex:'A limited pilot before a final decision means evidence first.'},
 {tag:'SEQUENCE',text:'Expense claims follow four steps. First, open the employee portal. Then select “Expenses”. Next, upload all receipts. Finally, submit the claim to your manager.',q:'What happens immediately before submitting the claim?',opts:['Open the portal','Upload the receipts','Select another manager'],a:'Upload the receipts',ex:'Open → select → upload → submit.'}
];
const listenings=[
 {tag:'TIME',script:'Hello. I am calling to confirm our appointment tomorrow afternoon at half past three.',q:'What time is the appointment?',opts:['2:30 p.m.','3:30 p.m.','4:30 p.m.'],a:'3:30 p.m.',ex:'Half past three = 3:30.'},
 {tag:'REASON',script:'We need to move the deadline from Tuesday to Thursday because our supplier sent the final data two days later than expected.',q:'Why did the deadline change?',opts:['The supplier sent data late','The client cancelled','The budget was reduced'],a:'The supplier sent data late',ex:'The reason follows “because”.'},
 {tag:'REQUEST',script:'Could you update the figures in sections two and three and send me the revised report by Monday morning, please?',q:'What does the speaker want?',opts:['A revised report by Monday morning','A meeting on Tuesday','A new computer'],a:'A revised report by Monday morning',ex:'Listen for the action and deadline.'},
 {tag:'PROBLEM + SOLUTION',script:'I am afraid the full order cannot arrive tomorrow. We can, however, send the most urgent items by express delivery and the rest on Friday.',q:'What solution is offered?',opts:['Cancel the order','Send urgent items first','Wait until next month'],a:'Send urgent items first',ex:'Urgent items can be sent first.'},
 {tag:'OPINION',script:'Hybrid work can improve flexibility, but I do not think it should replace face-to-face contact completely. Teams still need regular time together.',q:'What is the speaker’s opinion?',opts:['Hybrid work should replace offices completely','Hybrid work can help, but balance is important','Hybrid work is always negative'],a:'Hybrid work can help, but balance is important',ex:'Useful, but not a total replacement.'}
];
const oral=[
 {name:'1 · Introduction',goal:'Talk naturally about your work, responsibilities and use of English.',steps:['Answer directly.','Add one useful detail.','Give an example or reason.'],prompt:'Tell me about your current role and your main responsibilities.',b1:'I work in a team and I organise several daily tasks. I communicate with colleagues and help solve problems. One of my main responsibilities is making sure information is clear.',b2:'In my current role, I coordinate several priorities and make sure information is shared clearly across the team. My responsibilities include planning, following up on ongoing tasks and dealing with unexpected issues. For example, I often need to adjust priorities when something changes at short notice.'},
 {name:'2 · Role-play',goal:'Create a real interaction: ask, react, clarify, negotiate and confirm.',steps:['Acknowledge the situation.','Ask 1–2 useful questions.','Explain the impact.','Propose or negotiate a solution.','Confirm the next action.'],prompt:'A supplier tells you an important delivery will be two days late. Respond and find a solution.',b1:'Thanks for letting me know. Can you tell me why the delivery is late? We need the items for an important project. Could you send part of the order earlier? Please confirm the new delivery date by email.',b2:'Thanks for informing me. Could you clarify what caused the delay and whether the whole order is affected? A two-day delay could create a serious problem for our schedule. Would it be possible to prioritise the most urgent items or arrange a partial delivery? If not, I would appreciate written confirmation of the revised date and any alternatives you can offer.'},
 {name:'3 · Discussion',goal:'Give an opinion, develop it, react to another viewpoint and use examples.',steps:['State your opinion.','Reason 1 + example.','Reason 2 or contrast.','React to the evaluator.','Conclude or qualify.'],prompt:'Should companies offer more hybrid working? Consider advantages and disadvantages.',b1:'I think hybrid work can be positive because people save commuting time and can concentrate better at home. However, teams still need face-to-face contact. In my opinion, a balance between home and office work is the best solution.',b2:'I am generally in favour of hybrid work because it can improve flexibility and reduce unnecessary commuting. It may also support focused work. That said, it is not suitable for every role, and teams can lose informal communication if they rarely meet in person. I therefore think companies should offer flexibility while keeping clear expectations and regular on-site contact.'}
];
const rescue=['Could you repeat the question, please?','If I understand correctly, you are asking about…','Let me think for a moment.','In my experience, the main point is…','I see your point, but I would also consider…','Could you clarify what you mean by that?'];
const pron=[['Sentence stress','Could you CONFIRM the REVISED DELIVERY DATE?','Stress important information words, not every word.'],['TH sounds','I THINK THIS is the best option.','Keep the tongue lightly between the teeth for TH.'],['-ed endings','The project was APPROVED yesterday.','Do not add an extra syllable to “approved”.'],['Linking','I have WORKED_HERE for three years.','Link words smoothly instead of separating every word.'],['Contrast intonation','Although the results are encouraging, we should remain cautious.','Use a small rise before the contrast, then fall at the end.'],['Chunking','If I understand correctly / you need the revised version / by Friday.','Speak in meaning groups to improve fluency.']];
const finalQs=[
 ['Vocabulary','The amount of money generated by sales is…',['revenue','agenda','complaint'],'revenue'],['Grammar','She ____ here since 2023.',['has worked','worked yesterday','is work'],'has worked'],['Expressions','You want clarification.',['Could you clarify what you mean?','Speak better.','I do not agree.'],'Could you clarify what you mean?'],['Reading','A notice says “Normal service resumes at 1 p.m.” What happens at 1 p.m.?',['The service starts again','The office closes','A meeting begins'],'The service starts again'],['Listening','The speaker says: “The call has been moved from two to half past three.” What is the new time?',['2:00','3:30','4:30'],'3:30'],['Grammar','If I had more time, I ____ the report again.',['would check','will check','checked tomorrow'],'would check'],['Vocabulary','To evaluate a risk means to…',['assess it','borrow it','attend it'],'assess it'],['Expressions','Choose the best polite disagreement.',['I see your point, but I have some concerns.','No. Wrong.','That makes no sense.'],'I see your point, but I have some concerns.'],['Grammar','The report ____ yesterday.',['was approved','was approve','approved by itself'],'was approved'],['Reading','A pilot runs in two offices before a final rollout decision. Why?',['To test the idea first','To cancel the system','To avoid all feedback'],'To test the idea first'],['Vocabulary','A date by which work must be completed is a…',['deadline','refund','department'],'deadline'],['Expressions','You need a moment to answer.',['Let me think for a moment.','Wait there.','I have no idea.'],'Let me think for a moment.'],['Grammar','The colleague ____ called me works in finance.',['who','where','which place'],'who'],['Reading','An email proposes Tuesday at 2 or Wednesday at 10. What is its purpose?',['Offer alternative times','Request a refund','Announce a promotion'],'Offer alternative times'],['Listening','The speaker says: “Please send the updated figures by Friday morning.” What is requested?',['Updated figures by Friday morning','A meeting on Friday','A new budget next month'],'Updated figures by Friday morning'],['Grammar','They suggested ____ the meeting.',['postponing','to postponing','postpone to'],'postponing'],['Vocabulary','A customer says the service was poor. This may be a…',['complaint','target','minute'],'complaint'],['Expressions','Best way to confirm understanding:',['So, if I understand correctly, the deadline is Monday?','Monday yes?','You said something about Monday.'],'So, if I understand correctly, the deadline is Monday?'],['Grammar','The meeting is ____ Monday at 9 a.m.',['on','in','at Monday'],'on'],['Vocabulary','To deal with a difficult situation means to…',['handle it','attend it','refund it'],'handle it']
];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s){return String(s||'').toLowerCase().replace(/[?.!,]/g,'').replace(/\s+/g,' ').trim()}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
function persist(msg=false){state.usefulness=$('usefulness')?.value||state.usefulness;state.confidence=$('confidence')?.value||state.confidence;state.priority=$('priority')?.value||state.priority;localStorage.setItem(KEY,JSON.stringify(state));updateProgress();if(msg)toast('Progress saved')}
function mark(k){state.done[k]=true;persist()}
function updateProgress(){const keys=['format','mechanics','grammar','vocabulary','expressions','reading','listening','oral','pronunciation','final'];const n=keys.filter(k=>state.done[k]).length;$('progress').textContent=Math.round(n/keys.length*100)+'%'}
function speak(text){if(!('speechSynthesis'in window))return toast('Audio is unavailable in this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/_/g,' '));u.lang=$('accent').value;u.rate=.92;speechSynthesis.speak(u)}
function applyFr(){document.body.classList.toggle('fr-off',!state.fr);$('frToggle').textContent='FR help: '+(state.fr?'ON':'OFF')}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.go).scrollIntoView({behavior:'smooth'})));$('startBtn').addEventListener('click',()=>$('ch1').scrollIntoView({behavior:'smooth'}));$('frToggle').addEventListener('click',()=>{state.fr=!state.fr;applyFr();persist()});$('saveBtn').addEventListener('click',()=>persist(true));$('resetBtn').addEventListener('click',()=>{if(confirm('Reset all lesson progress and answers?')){localStorage.removeItem(KEY);location.reload()}});$('downloadBtn').addEventListener('click',downloadReport);
$$('[data-skill]').forEach(b=>b.addEventListener('click',()=>{$('skillInfo').innerHTML='<b>'+b.dataset.skill+':</b> '+skillInfo[b.dataset.skill]}));
$$('.choices').forEach(g=>g.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{if(g.dataset.locked)return;g.dataset.locked='1';const good=b.dataset.v===g.dataset.correct;g.querySelectorAll('button').forEach(x=>{if(x.dataset.v===g.dataset.correct)x.classList.add('correct')});if(!good)b.classList.add('wrong');const f=g.parentElement.querySelector('.feedback');f.textContent=good?'✓ Correct.':'✕ The correct answer is highlighted.';f.className='feedback '+(good?'ok':'bad');mark('format')})));
function renderMechanics(){
 $('mechanics').innerHTML=mechanics.map((m,i)=>`<article class="lab"><div class="eyebrow">TYPE ${i+1}</div><h3>${esc(m[0])}</h3><p>${esc(m[1])}</p><div class="demo" id="mech${i}"><b>${esc(m[3])}</b><div class="control"></div><div class="feedback"></div></div><small class="muted">Strategy: ${esc(m[6])}</small></article>`).join('');
 mechanics.forEach((m,i)=>{const box=$('mech'+i),c=box.querySelector('.control'),f=box.querySelector('.feedback');let answer=[];const finish=v=>{const good=norm(v)===norm(m[5]);f.textContent=good?'✓ Correct. '+m[6]:'✕ Try again. '+m[6];f.className='feedback '+(good?'ok':'bad');if(good)mark('mechanics')};if(m[2]==='select'){c.innerHTML='<select><option>— choose —</option>'+shuffle(m[4]).map(x=>`<option>${esc(x)}</option>`).join('')+'</select>';c.querySelector('select').addEventListener('change',e=>finish(e.target.value))}else if(m[2]==='input'){c.innerHTML='<input placeholder="Type the missing word and press Enter">';c.querySelector('input').addEventListener('keydown',e=>{if(e.key==='Enter')finish(e.target.value)})}else if(m[2]==='bank'||m[2]==='mcq'){c.innerHTML='<div class="bank">'+shuffle(m[4]).map(x=>`<button>${esc(x)}</button>`).join('')+'</div>';c.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>finish(b.textContent)))}else{c.innerHTML='<div class="answerline"></div><div class="bank">'+shuffle(m[4]).map((x,j)=>`<button data-token="${esc(x)}">${esc(x)}</button>`).join('')+'</div><button class="secondary checkOrder" style="margin-top:8px">Check order</button>';const line=c.querySelector('.answerline');c.querySelectorAll('.bank button').forEach(b=>b.addEventListener('click',()=>{if(b.disabled)return;answer.push(b.dataset.token);b.disabled=true;line.innerHTML=answer.map(x=>`<span>${esc(x)}</span>`).join('')}));c.querySelector('.checkOrder').addEventListener('click',()=>finish(answer.join(' ')))}})
}
renderMechanics();
let gi=0;function renderGrammarTabs(){$('grammarTabs').innerHTML=grammar.map((g,i)=>`<button class="${i===gi?'active':''}" data-g="${i}">${esc(g[0])}</button>`).join('');$$('[data-g]').forEach(b=>b.addEventListener('click',()=>{gi=+b.dataset.g;renderGrammarTabs();renderGrammar()}))}
function renderGrammar(){const g=grammar[gi];$('grammarPanel').innerHTML=`<div class="rulegrid"><div class="rulebox"><div class="eyebrow">RULE</div><h3>${esc(g[0])}</h3><div class="formula">${esc(g[1])}</div><p>${esc(g[2])}</p><div class="frhelp">${esc(g[3])}</div>${g[4].map(x=>`<div class="example">${x}</div>`).join('')}</div><div class="rulebox"><div class="eyebrow">GUIDED CHECK</div><h3>${esc(g[5])}</h3><div class="taskopts">${shuffle(g[6]).map(x=>`<button data-ga="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="feedback"></div></div></div>`;$$('[data-ga]').forEach(b=>b.addEventListener('click',()=>{const good=b.dataset.ga===g[7];const f=$('grammarPanel').querySelector('.feedback');f.textContent=good?'✓ Correct.':'✕ Re-read the signal and rule.';f.className='feedback '+(good?'ok':'bad');if(good)mark('grammar')}))}
renderGrammarTabs();renderGrammar();
function renderVocab(){const cats=Object.keys(vocab);$('vocabCat').innerHTML=cats.map(x=>`<option>${esc(x)}</option>`).join('');$('vocabCat').value=state.vocabCat&&cats.includes(state.vocabCat)?state.vocabCat:cats[0];drawVocab()}
function drawVocab(){const cat=$('vocabCat').value;state.vocabCat=cat;persist();$('vocabCards').innerHTML=vocab[cat].map(v=>`<article class="vocab"><div class="vword"><b>${esc(v[0])}</b><button class="audio" data-speak="${esc(v[0])}">▶</button></div><div class="fr">${esc(v[1])}</div><p>${esc(v[2])}</p><small>${esc(v[3])}</small></article>`).join('');$$('[data-speak]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.speak)))}
$('vocabCat').addEventListener('change',drawVocab);$('randomWord').addEventListener('click',()=>{const c=Object.keys(vocab);$('vocabCat').value=c[Math.floor(Math.random()*c.length)];drawVocab()});renderVocab();
function simpleQuiz(id,data,key){const h=$(id);h.innerHTML='<h3>Mini challenge</h3>'+data.map((q,i)=>`<div class="quizItem" data-i="${i}"><b>${i+1}. ${esc(q[0])}</b><div class="taskopts">${shuffle(q[1]).map(x=>`<button data-val="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="feedback"></div></div>`).join('');h.querySelectorAll('.quizItem').forEach(box=>{const q=data[+box.dataset.i];box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{if(box.dataset.done)return;box.dataset.done='1';const good=b.dataset.val===q[2];if(good)b.classList.add('correct');else b.classList.add('wrong');box.querySelectorAll('button').forEach(x=>{if(x.dataset.val===q[2])x.classList.add('correct')});box.querySelector('.feedback').textContent=good?'✓ Correct.':'✕ Correct answer: '+q[2];box.querySelector('.feedback').className='feedback '+(good?'ok':'bad');state.answers[key+'-'+box.dataset.i]=good;if(data.every((_,j)=>state.answers[key+'-'+j]!==undefined))mark(key);persist()}))})}
simpleQuiz('vocabQuiz',vocabQuiz,'vocabulary');
$('expressions').innerHTML=expr.map(e=>`<article class="expr"><h3>${esc(e[0])}</h3>${e[1].map(p=>`<button class="phrase" data-p="${esc(p)}">${esc(p)}</button>`).join('')}</article>`).join('');$$('[data-p]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.p)));simpleQuiz('exprQuiz',exprQuiz,'expressions');
function renderReading(){$('readingLab').innerHTML=readings.map((r,i)=>`<article class="reading" data-r="${i}"><span class="tag">${esc(r.tag)}</span><div class="passage">${esc(r.text)}</div><h3>${esc(r.q)}</h3><div class="taskopts">${shuffle(r.opts).map(x=>`<button data-val="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="feedback"></div></article>`).join('');$$('.reading').forEach(box=>{const r=readings[+box.dataset.r];box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{if(box.dataset.done)return;box.dataset.done='1';const good=b.dataset.val===r.a;if(good)b.classList.add('correct');else b.classList.add('wrong');box.querySelectorAll('button').forEach(x=>{if(x.dataset.val===r.a)x.classList.add('correct')});box.querySelector('.feedback').innerHTML=(good?'✓ Correct. ':'✕ Correct answer: <b>'+esc(r.a)+'</b>. ')+esc(r.ex);box.querySelector('.feedback').className='feedback '+(good?'ok':'bad');state.answers['read-'+box.dataset.r]=good;if(readings.every((_,i)=>state.answers['read-'+i]!==undefined))mark('reading');persist()}))})}
renderReading();
function renderListening(){$('listeningLab').innerHTML=listenings.map((l,i)=>`<article class="listening" data-l="${i}" data-plays="0"><span class="tag">${esc(l.tag)}</span><div class="listenTop"><button class="secondary play">▶ Listen</button><span class="plays">2 plays available</span><button class="ghost transcriptBtn hidden">Show transcript</button></div><h3>${esc(l.q)}</h3><div class="taskopts">${shuffle(l.opts).map(x=>`<button data-val="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="feedback"></div><div class="transcript hidden">${esc(l.script)}</div></article>`).join('');$$('.listening').forEach(box=>{const l=listenings[+box.dataset.l],play=box.querySelector('.play'),p=box.querySelector('.plays'),tb=box.querySelector('.transcriptBtn'),tr=box.querySelector('.transcript');play.addEventListener('click',()=>{let n=+box.dataset.plays;if(n>=2)return;n++;box.dataset.plays=n;speak(l.script);p.textContent=(2-n)+' play'+(2-n===1?'':'s')+' available';if(n>=2)play.disabled=true});box.querySelectorAll('.taskopts button').forEach(b=>b.addEventListener('click',()=>{if(box.dataset.done)return;box.dataset.done='1';const good=b.dataset.val===l.a;if(good)b.classList.add('correct');else b.classList.add('wrong');box.querySelectorAll('.taskopts button').forEach(x=>{if(x.dataset.val===l.a)x.classList.add('correct')});box.querySelector('.feedback').innerHTML=(good?'✓ Correct. ':'✕ Correct answer: <b>'+esc(l.a)+'</b>. ')+esc(l.ex);box.querySelector('.feedback').className='feedback '+(good?'ok':'bad');tb.classList.remove('hidden');state.answers['listen-'+box.dataset.l]=good;if(listenings.every((_,i)=>state.answers['listen-'+i]!==undefined))mark('listening');persist()}));tb.addEventListener('click',()=>{tr.classList.toggle('hidden');tb.textContent=tr.classList.contains('hidden')?'Show transcript':'Hide transcript'})})}
renderListening();
let oi=0,rec=null,chunks=[],stream=null,url=null;function renderOralTabs(){$('oralTabs').innerHTML=oral.map((o,i)=>`<button class="${i===oi?'active':''}" data-o="${i}">${esc(o.name)}</button>`).join('');$$('[data-o]').forEach(b=>b.addEventListener('click',()=>{oi=+b.dataset.o;renderOralTabs();renderOral()}))}
function renderOral(){const o=oral[oi];$('oralPanel').innerHTML=`<div class="oralgrid"><div class="framework"><div class="eyebrow">WHAT TO DO</div><h3>${esc(o.goal)}</h3><ol>${o.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="frhelp">Une réponse claire et développée vaut mieux qu'une réponse très rapide mais trop courte. Interagissez avec l'évaluateur.</div></div><div class="framework"><div class="eyebrow">PRACTICE</div><div class="prompt">${esc(o.prompt)}</div><textarea id="oralNotes" placeholder="Build keywords or a short answer here…"></textarea><div class="oralBtns"><button id="b1" class="ghost">Model B1</button><button id="b2" class="ghost">Model B2</button><button id="recStart" class="secondary">● Record</button><button id="recStop" class="ghost hidden">■ Stop</button></div><audio id="audioPlayback" class="hidden" controls></audio><div id="model" class="model hidden"></div></div></div>`;$('b1').addEventListener('click',()=>{$('model').innerHTML='<b>B1 model</b><p>'+esc(o.b1)+'</p>';$('model').classList.remove('hidden')});$('b2').addEventListener('click',()=>{$('model').innerHTML='<b>B2 model</b><p>'+esc(o.b2)+'</p>';$('model').classList.remove('hidden')});$('oralNotes').value=state.answers['oral-'+oi]||'';$('oralNotes').addEventListener('input',()=>{state.answers['oral-'+oi]=$('oralNotes').value;mark('oral');persist()});$('recStart').addEventListener('click',startRec);$('recStop').addEventListener('click',stopRec)}
async function startRec(){if(!navigator.mediaDevices?.getUserMedia)return toast('Microphone recording is unavailable.');try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);$('audioPlayback').src=url;$('audioPlayback').classList.remove('hidden');stream.getTracks().forEach(t=>t.stop())};rec.start();$('recStart').classList.add('hidden');$('recStop').classList.remove('hidden');mark('oral')}catch(e){toast('Microphone permission was not available.')}}function stopRec(){if(rec&&rec.state!=='inactive')rec.stop();$('recStart').classList.remove('hidden');$('recStop').classList.add('hidden')}
renderOralTabs();renderOral();$('rescuePhrases').innerHTML=rescue.map(p=>`<button class="phrase" data-rp="${esc(p)}">${esc(p)}</button>`).join('');$$('[data-rp]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.rp)));
$('pronLab').innerHTML=pron.map((p,i)=>`<article class="pron"><div class="eyebrow">${esc(p[0])}</div><h3>Focus ${i+1}</h3><div class="line">${esc(p[1])}</div><p>${esc(p[2])}</p><button class="secondary" data-pron="${i}">▶ Hear model</button><button class="ghost practised" data-pi="${i}">✓ Practised</button></article>`).join('');$$('[data-pron]').forEach(b=>b.addEventListener('click',()=>speak(pron[+b.dataset.pron][1])));$$('.practised').forEach(b=>b.addEventListener('click',()=>{b.textContent='✓ Done';b.disabled=true;state.answers['pron-'+b.dataset.pi]=true;if(pron.every((_,i)=>state.answers['pron-'+i]))mark('pronunciation');persist()}));
function renderFinal(){$('finalQuiz').innerHTML=finalQs.map((q,i)=>`<div class="finalQ" data-f="${i}"><div class="meta">${esc(q[0])}</div><h3>${i+1}. ${esc(q[1])}</h3><div class="taskopts">${shuffle(q[2]).map(x=>`<button data-val="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`).join('')+'<button id="finishFinal" class="primary" style="margin-top:14px">Finish diagnostic</button>';$$('.finalQ').forEach(box=>box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{box.querySelectorAll('button').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');state.final[box.dataset.f]=b.dataset.val;persist()})));$('finishFinal').addEventListener('click',finishFinal)}
function finishFinal(){if(Object.keys(state.final).length<finalQs.length)return toast('Answer all 20 questions first.');let total=0,by={};finalQs.forEach((q,i)=>{const good=state.final[i]===q[3];if(good)total++;by[q[0]]=by[q[0]]||[0,0];by[q[0]][1]++;if(good)by[q[0]][0]++});const pct=Math.round(total/finalQs.length*100),priority=Object.entries(by).sort((a,b)=>(a[1][0]/a[1][1])-(b[1][0]/b[1][1]))[0][0];$('finalResult').innerHTML=`<h3>${total}/20 · ${pct}%</h3><p>${pct>=80?'Strong review result. Move to the full mock and focus on speed and oral spontaneity.':pct>=60?'Good foundation. Review the weakest area before the full mock.':'Return to the weakest two chapters before attempting the full mock.'}</p><div class="diag">${Object.entries(by).map(([k,v])=>`<div><b>${esc(k)}</b><span>${v[0]}/${v[1]}</span></div>`).join('')}</div><p><b>First priority:</b> ${esc(priority)}</p>`;$('finalResult').classList.remove('hidden');mark('final');persist()}
renderFinal();
$$('.examCheck').forEach((c,i)=>{c.checked=!!state.checks[i];c.addEventListener('change',()=>{state.checks[i]=c.checked;persist();updateChecklist()})});function updateChecklist(){const all=$$('.examCheck').every(c=>c.checked);$('ready').textContent=all?'✓ Exam-day routine complete. You are ready for the full mock.':'Complete the checklist to finish your review.';$('ready').classList.toggle('good',all)}updateChecklist();
$('usefulness').value=state.usefulness||'';$('confidence').value=state.confidence||'';$('priority').value=state.priority||'';['usefulness','confidence','priority'].forEach(id=>$(id).addEventListener('change',()=>persist()));
function downloadReport(){const score=(key,data)=>data.filter((_,i)=>state.answers[key+'-'+i]).length;let final='Not completed';if(Object.keys(state.final).length===finalQs.length)final=finalQs.filter((q,i)=>state.final[i]===q[3]).length+'/20';const txt=`CLOE Made Clear · Review Progress\nDate: ${new Date().toLocaleDateString()}\n\nCompleted modules: ${Object.keys(state.done).filter(k=>state.done[k]).join(', ')||'None yet'}\nVocabulary mini challenge: ${score('vocabulary',vocabQuiz)}/${vocabQuiz.length}\nExpressions mini challenge: ${score('expressions',exprQuiz)}/${exprQuiz.length}\nReading lab: ${score('read',readings)}/${readings.length}\nListening lab: ${score('listen',listenings)}/${listenings.length}\nFinal diagnostic: ${final}\n\nUsefulness: ${$('usefulness').value||'—'}\nConfidence: ${$('confidence').value||'—'}\nNext priority: ${$('priority').value||'—'}\n\nPedagogical review only — not an official CLOE result.`;const blob=new Blob([txt],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='CLOE_Review_Progress.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
applyFr();updateProgress();
})();
