(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='catherine-adriatic-cloe-v1';
const initialState={answers:{},completed:{},writing:'',notes:'',reflection:'',oralChecks:{},assessment:{},comments:{},mode:'practice',final:false,satisfaction:{}};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(initialState);
let voices=[]; let timerSeconds=1800,timerId=null; let mediaRecorder=null,mediaChunks=[]; let oralIndex=0;

const vocab=[
{cat:'city',en:'city walls',fr:'remparts',def:'fortified walls around a historic city',ex:'Dubrovnik is famous for its city walls.'},
{cat:'city',en:'old town',fr:'vieille ville',def:'the historic centre of a city',ex:'We are going to walk through the old town.'},
{cat:'city',en:'harbour',fr:'port',def:'a protected place where boats arrive and leave',ex:'The ferry leaves from the harbour.'},
{cat:'city',en:'narrow street',fr:'rue étroite',def:'a street with little space from side to side',ex:'The old town has many narrow streets.'},
{cat:'nature',en:'saltwater lake',fr:'lac salé',def:'a lake containing salt water',ex:'Mljet is known for beautiful saltwater lakes.'},
{cat:'nature',en:'forested',fr:'boisé',def:'covered with many trees',ex:'The island is green and heavily forested.'},
{cat:'nature',en:'shoreline',fr:'rivage',def:'the edge where land meets water',ex:'We would like to walk along the shoreline.'},
{cat:'nature',en:'peaceful',fr:'paisible',def:'calm and quiet',ex:'I prefer peaceful places where I can relax.'},
{cat:'mountains',en:'mountain scenery',fr:'paysage de montagne',def:'views formed by mountains and valleys',ex:'Durmitor offers dramatic mountain scenery.'},
{cat:'mountains',en:'hiking trail',fr:'sentier de randonnée',def:'a marked path for walking in nature',ex:'We may choose a short hiking trail.'},
{cat:'mountains',en:'canyon',fr:'canyon',def:'a deep valley with steep sides',ex:'The region has impressive canyons.'},
{cat:'mountains',en:'rugged',fr:'accidenté / escarpé',def:'rough, rocky and uneven',ex:'The landscape is beautiful but rugged.'},
{cat:'logistics',en:'itinerary',fr:'itinéraire',def:'a plan of places and travel stages',ex:'We changed our itinerary to spend more time in nature.'},
{cat:'logistics',en:'departure',fr:'départ',def:'the time or act of leaving',ex:'The morning departure has been cancelled.'},
{cat:'logistics',en:'accommodation',fr:'hébergement',def:'a place where you stay overnight',ex:'We need to contact our accommodation.'},
{cat:'logistics',en:'day trip',fr:'excursion à la journée',def:'a visit that begins and ends on the same day',ex:'Mljet can be visited as a day trip.'},
{cat:'connectors',en:'whereas',fr:'alors que / tandis que',def:'used to contrast two facts',ex:'Dubrovnik is lively, whereas Mljet is quieter.'},
{cat:'connectors',en:'however',fr:'cependant',def:'introduces a contrasting idea',ex:'The route is beautiful; however, it can be tiring.'},
{cat:'connectors',en:'although',fr:'bien que',def:'introduces an unexpected contrast',ex:'Although it is a long journey, I think it will be worth it.'},
{cat:'connectors',en:'which means that',fr:'ce qui signifie que',def:'introduces a consequence or explanation',ex:'The ferry is later, which means that we will arrive in the evening.'}
];
const categories={all:'All',city:'City & heritage',nature:'Island & nature',mountains:'Mountains',logistics:'Travel logistics',connectors:'Exam connectors'};

const quizzes={
vocabulary:[
{q:'We changed our ___ because we wanted more time in nature.',o:['itinerary','shoreline','canyon','departure'],a:'itinerary',h:'This word means the overall travel plan.'},
{q:'The boat leaves from the ___.',o:['harbour','rugged','forested','old town'],a:'harbour',h:'Think of the place where boats arrive and leave.'},
{q:'Durmitor is famous for dramatic mountain ___.',o:['scenery','accommodation','departure','shoreline'],a:'scenery',h:'This noun means the natural views of an area.'},
{q:'Mljet feels calm and ___.',o:['peaceful','narrow','cancelled','rugged'],a:'peaceful',h:'Opposite of noisy or stressful.'},
{q:'A marked path for walking in nature is a ___.',o:['hiking trail','day trip','city wall','harbour'],a:'hiking trail',h:'You follow it when you go walking in the mountains.'},
{q:'Dubrovnik is lively, ___ Mljet is much quieter.',o:['whereas','because','so','when'],a:'whereas',h:'You need a connector for contrast.'}
],
grammar:[
{q:'Mljet is an island ___ you can enjoy quiet nature.',o:['where','which','who','why'],a:'where',h:'The missing word refers to a place.'},
{q:'We chose a route ___ goes past the lake.',o:['which','where','who','when'],a:'which',h:'The missing word refers to a thing.'},
{q:'The guide ___ helped us spoke excellent English.',o:['who','where','which','why'],a:'who',h:'The missing word refers to a person.'},
{q:'We ___ in Dubrovnik for two nights. The hotel is already booked.',o:['are staying','stay','stayed','have stayed'],a:'are staying',h:'A fixed future arrangement can use the present continuous.'},
{q:'Last summer, we ___ Denmark to see family.',o:['visited','visit','have visit','are visiting'],a:'visited',h:'“Last summer” points to the past simple.'},
{q:'I ___ interested in travel for many years.',o:['have been','was','am being','will be'],a:'have been',h:'“For many years” links past and present.'},
{q:'Choose the natural word order.',o:['We are visiting the old town on Tuesday in Dubrovnik.','We are visiting the old town in Dubrovnik on Tuesday.','In Dubrovnik on Tuesday the old town we are visiting.','We on Tuesday are visiting in Dubrovnik the old town.'],a:'We are visiting the old town in Dubrovnik on Tuesday.',h:'Use object/detail + place + time.'},
{q:'If the weather ___ good, we will spend a day in the mountains.',o:['is','will be','was','be'],a:'is',h:'After “if” in a real future condition, use present simple.'}
],
expressions:[
{q:'You did not understand the departure time. What is the best response?',o:['Do you mean the boat leaves at two fifteen?','You say again time.','I not understand departure.','Why this time?'],a:'Do you mean the boat leaves at two fifteen?',h:'Use a short clarification question.'},
{q:'You need a few seconds to answer an oral question.',o:['Let me think for a moment.','I have no idea.','Wait.','You stop please.'],a:'Let me think for a moment.',h:'Use a natural phrase to gain time.'},
{q:'You want to check that you understood the problem.',o:['So, if I understand correctly, the morning boat is cancelled.','The problem is you.','I think no boat yes?','Repeat all.'],a:'So, if I understand correctly, the morning boat is cancelled.',h:'Reformulation shows active listening.'},
{q:'Choose the most natural contrast.',o:['Dubrovnik is lively, whereas Mljet is quieter.','Dubrovnik is lively because Mljet quieter.','Dubrovnik lively but Mljet is quietest because.','Whereas Dubrovnik because Mljet.'],a:'Dubrovnik is lively, whereas Mljet is quieter.',h:'“Whereas” directly contrasts two clauses.'}
],
reading:[
{q:'Why did the travellers change their itinerary?',o:['They wanted more time in nature.','Dubrovnik was closed.','They missed the ferry.','They wanted to go home earlier.'],a:'They wanted more time in nature.',h:'Look for the sentence with “because”.'},
{q:'How long are they now staying in Dubrovnik?',o:['Two nights','Three nights','One week','One night'],a:'Two nights',h:'The new plan is stated after “We are now”.'},
{q:'What do they hope to do on Mljet?',o:['Walk near the lakes and enjoy a quieter atmosphere.','Go skiing.','Attend a business meeting.','Visit a large shopping centre.'],a:'Walk near the lakes and enjoy a quieter atmosphere.',h:'Find the clause after “where we hope to”.'},
{q:'What will influence the possible Durmitor visit?',o:['The weather','The hotel price','The ferry company','A work meeting'],a:'The weather',h:'Look for the sentence beginning with “If”.'},
{q:'Why have they not booked every excursion?',o:['They want to keep part of the trip flexible.','They forgot to book.','Everything is sold out.','They do not like excursions.'],a:'They want to keep part of the trip flexible.',h:'The reason appears in the last sentence.'}
],
listening:[
{q:'Why was the morning departure cancelled?',o:['Strong wind','A technical exam','No passengers','Heavy traffic'],a:'Strong wind',h:'Listen for the reason after “because of”.'},
{q:'What time is the alternative boat?',o:['2:15 p.m.','12:15 p.m.','7:00 p.m.','8:00 a.m.'],a:'2:15 p.m.',h:'Listen for the number after “another boat at”.'},
{q:'What activity is still possible with the afternoon boat?',o:['The short lake walk','The long walking route','A full mountain day','A morning city tour'],a:'The short lake walk',h:'One option is shortened because arrival will be later.'},
{q:'What is the second option?',o:['Move the visit to Friday.','Cancel the entire holiday.','Take a taxi to Montenegro.','Stay in Dubrovnik for a week.'],a:'Move the visit to Friday.',h:'Listen for “or move your visit”.'},
{q:'What is the deadline for changing the date?',o:['Before 7 p.m. this evening','Before noon tomorrow','Before 2:15 p.m.','There is no deadline'],a:'Before 7 p.m. this evening',h:'The final sentence gives the deadline.'}
]};
const orderItems=[
{words:['We','are','visiting','the old town','in Dubrovnik','on Tuesday.'],answer:'We are visiting the old town in Dubrovnik on Tuesday.'},
{words:['Mljet','is','an island','where','you can enjoy','quiet nature.'],answer:'Mljet is an island where you can enjoy quiet nature.'}
];
const listeningScript='Hello. I’m calling about tomorrow’s boat trip. The morning departure has been cancelled because of strong wind, but there is another boat at two fifteen in the afternoon. It arrives later, so you will not have enough time for the long walking route. You can either take the afternoon boat and do the short lake walk, or move your visit to Friday, when the weather should be calmer. Please call us before seven this evening if you want to change the date.';
const oralPrompts=[
{cat:'PROFILE',q:'Tell me about yourself and what is important to you.',fr:'Présentez-vous et dites ce qui est important pour vous.',support:['Start with 3 facts.','Add one activity or interest.','Finish with what you are working on now.'],a2:'I live in France. I enjoy nature, travelling and spending time with my family. I am learning English because I want to communicate more easily.',a2p:'I live in France and I have an active life. I enjoy nature, travelling and meaningful activities. I am improving my English because I would like to communicate more naturally when I travel and in everyday situations.',b1:'I live in France and I try to keep a varied and active life. I especially enjoy nature, travelling and meaningful contact with other people. At the moment, I am focusing on my English because I want to speak more spontaneously and feel comfortable when a conversation becomes less predictable.'},
{cat:'TRAVEL PLAN',q:'Tell me about a trip you are planning. What are you going to do and why?',fr:'Parlez d’un voyage que vous préparez : que comptez-vous faire et pourquoi ?',support:['Say where and when.','Give 2–3 stages.','Use because / which / where.','Add what you are most looking forward to.'],a2:'In September, I am going to Croatia and Montenegro. I am going to visit Dubrovnik and Mljet. I would like to see nature and relax.',a2p:'In September, I am going to travel around Croatia and Montenegro. We are staying in Dubrovnik, and then we are going to Mljet, where I would like to walk near the lakes. I am looking forward to the trip because I enjoy both culture and nature.',b1:'From 15 to 25 September, I am travelling around the Adriatic region. We are starting in Dubrovnik, which I would like to explore for its old town and atmosphere, before going to Mljet, where we can spend more time in nature. We may also continue into Montenegro and visit a mountain area if the weather is good. I like this itinerary because it combines culture, the sea and quieter landscapes.'},
{cat:'COMPARE',q:'Would you prefer to spend a day in Dubrovnik or on Mljet? Explain your choice.',fr:'Préféreriez-vous passer une journée à Dubrovnik ou à Mljet ? Expliquez votre choix.',support:['Compare two features.','Use whereas / more… than.','State your preference.','Give a reason.'],a2:'I prefer Mljet because it is quieter. Dubrovnik is beautiful, but it is busier.',a2p:'I would prefer to spend a day on Mljet because it seems more peaceful than Dubrovnik. Dubrovnik has more historical sights, whereas Mljet offers more nature and quiet time.',b1:'I would probably choose Mljet for a full day. Dubrovnik is fascinating because of its history and lively atmosphere, whereas Mljet seems calmer and closer to nature. Since I enjoy peaceful places, I think I would appreciate having time to walk, enjoy the landscape and slow down.'},
{cat:'PROBLEM',q:'Your ferry has been cancelled. Explain the problem and find a solution with the agent.',fr:'Votre ferry est annulé. Expliquez le problème et trouvez une solution avec l’agent.',support:['Explain the situation.','Ask for alternatives.','Clarify one detail.','Confirm your choice.'],a2:'I’m sorry, our ferry is cancelled. Is there another boat today? What time does it leave?',a2p:'I’m sorry, but our morning ferry has been cancelled. Could you tell me if there is another departure today? Do you mean the next boat leaves at 2:15? If so, I would like to take that one.',b1:'I understand that the morning ferry has been cancelled because of the weather. Could you tell me what alternatives are available? If I understand correctly, we can either take the afternoon boat or travel tomorrow. I would prefer the afternoon departure, but could you confirm what time it arrives and whether we need to change our booking?'},
{cat:'OPINION',q:'Do you think travelling slowly is better than trying to see many places? Why?',fr:'Pensez-vous qu’il vaut mieux voyager lentement plutôt que d’essayer de voir beaucoup d’endroits ? Pourquoi ?',support:['Give your opinion.','Give one advantage.','Mention the opposite view.','Conclude.'],a2:'I prefer travelling slowly because it is less stressful. I can enjoy the place more.',a2p:'In my opinion, travelling slowly is better because you have more time to discover a place. A busy itinerary can be exciting, but it can also be tiring.',b1:'I generally prefer slower travel because it gives you time to understand a place instead of simply moving from one attraction to another. Of course, a faster itinerary allows you to see more, but I think you sometimes remember less. For me, a balanced trip with a few well-chosen places is more enjoyable.'},
{cat:'SURPRISE',q:'Tell me about a time when a plan changed unexpectedly. What did you do?',fr:'Racontez un moment où un plan a changé de façon imprévue. Qu’avez-vous fait ?',support:['Set the scene in the past.','Explain what changed.','Say what you did.','Finish with the result / feeling.'],a2:'One time, our plan changed because of bad weather. We changed the activity and did something inside. It was okay in the end.',a2p:'Last year, one of our plans changed because the weather was bad. We could not do the activity we wanted, so we chose another option. At first I was disappointed, but the day was still enjoyable.',b1:'I remember a day when bad weather changed our plans at the last minute. We had expected to spend most of the day outside, but it became clear that it was not a good idea. Instead of cancelling everything, we looked for another activity and reorganised the day. I was disappointed at first, but it reminded me that being flexible can make travel much less stressful.'}
];

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function save(show=false){
 state.mode=$('#lessonMode')?.value||state.mode; state.writing=$('#writingText')?.value||state.writing; state.notes=$('#finalNotes')?.value||state.notes; state.reflection=$('#speakingReflection')?.value||state.reflection;
 localStorage.setItem(KEY,JSON.stringify(state)); if(show)toast('Progress saved in this browser.');
}
function loadFields(){
 $('#lessonMode').value=state.mode||'practice'; document.body.classList.toggle('body-exam',$('#lessonMode').value==='exam');
 $('#writingText').value=state.writing||''; $('#finalNotes').value=state.notes||''; $('#speakingReflection').value=state.reflection||'';
 Object.entries(state.oralChecks||{}).forEach(([k,v])=>{const x=$(`[data-oral-check="${k}"]`);if(x)x.checked=v});
}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function speak(text){if(!('speechSynthesis'in window)){toast('Speech is not supported in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=$('#voiceAccent').value;u.rate=parseFloat($('#voiceRate').value||'.92');const preferred=voices.find(v=>v.lang===u.lang)||voices.find(v=>v.lang.startsWith(u.lang.slice(0,2)));if(preferred)u.voice=preferred;speechSynthesis.speak(u)}
function initVoices(){if(!('speechSynthesis'in window)){$('#voiceStatus').textContent='Speech synthesis is not available in this browser.';return}const set=()=>{voices=speechSynthesis.getVoices();$('#voiceStatus').textContent=`${voices.length?voices.length+' voices available. ':''}Audio is manual: nothing plays automatically.`};set();speechSynthesis.onvoiceschanged=set}
function bindAudio(){$$('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak));$$('[data-speak-target]').forEach(b=>b.onclick=()=>{const e=$('#'+b.dataset.speakTarget);speak(e?.innerText||e?.value||'')})}

function renderVocab(cat='all'){
 $('#vocabFilters').innerHTML=Object.entries(categories).map(([k,v])=>`<button class="${k===cat?'active':''}" data-vcat="${k}" type="button">${v}</button>`).join('');
 const list=cat==='all'?vocab:vocab.filter(v=>v.cat===cat);
 $('#vocabGrid').innerHTML=list.map(v=>`<article class="vocab-card"><button class="audio-mini" data-vocab-speak="${escapeAttr(v.ex)}" type="button">🔊</button><h3>${v.en}</h3><div class="fr-word fr">${v.fr}</div><p>${v.def}</p><p class="example"><b>Example:</b> ${v.ex}</p></article>`).join('');
 $$('[data-vcat]').forEach(b=>b.onclick=()=>renderVocab(b.dataset.vcat));$$('[data-vocab-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.vocabSpeak));
}
function escapeAttr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;')}

function qKey(section,i){return `${section}-${i}`}
function renderQuiz(section){
 const target=$('#'+section+'Quiz'),data=quizzes[section]; if(!target)return;
 target.innerHTML=data.map((q,i)=>{const key=qKey(section,i),saved=state.answers[key];const options=shuffle(q.o);return `<article class="question-card" data-qcard="${key}"><p>${i+1}. ${q.q}</p><div class="options">${options.map(o=>`<button class="option-btn ${saved?o===q.a?'correct':(o===saved&&saved!==q.a?'wrong':''):''}" data-answer="${escapeAttr(o)}" type="button" ${saved?'disabled':''}>${o}</button>`).join('')}</div><div class="feedback ${saved?(saved===q.a?'good':'bad'):''}">${saved?(saved===q.a?'✓ Correct.':'✗ Correct answer: '+q.a):''}</div><div class="hint-row support-only"><button class="text-button hint-btn" type="button">Hint</button><div class="hint">${q.h}</div></div></article>`}).join('');
 $$('.option-btn',target).forEach(btn=>btn.onclick=()=>answerQuiz(section,btn));$$('.hint-btn',target).forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('visible'));updateScores();
}
function answerQuiz(section,btn){const card=btn.closest('[data-qcard]'),key=card.dataset.qcard,i=Number(key.split('-').pop()),q=quizzes[section][i],answer=btn.dataset.answer;state.answers[key]=answer;$$('.option-btn',card).forEach(b=>{b.disabled=true;b.classList.toggle('correct',b.dataset.answer===q.a);b.classList.toggle('wrong',b===btn&&answer!==q.a)});const f=$('.feedback',card);f.textContent=answer===q.a?'✓ Correct.':'✗ Correct answer: '+q.a;f.className='feedback '+(answer===q.a?'good':'bad');save();updateScores();updateEvaluation()}
function sectionScore(section){return quizzes[section].reduce((n,q,i)=>n+(state.answers[qKey(section,i)]===q.a?1:0),0)}
function answeredCount(section){return quizzes[section].reduce((n,q,i)=>n+(state.answers[qKey(section,i)]!==undefined?1:0),0)}
function updateScores(){['vocabulary','grammar','expressions','reading','listening'].forEach(s=>{const e=$('#'+s+'Score');if(e)e.textContent=`${sectionScore(s)} / ${quizzes[s].length}`});const os=$('#orderScore');if(os)os.textContent=`${state.completed.order||0} / 2`}

function renderOrder(){
 const wrap=$('#orderBuilder');wrap.innerHTML=orderItems.map((item,i)=>{const saved=state.answers[`order-${i}`];const chosen=saved?.chosen||[];const available=item.words.filter((w,idx)=>!chosen.some((cw,ci)=>cw===w&&chosen.slice(0,ci).filter(x=>x===w).length===item.words.slice(0,idx).filter(x=>x===w).length));return `<div class="order-task" data-order="${i}"><p><b>${i+1}.</b> Build the natural sentence.</p><div class="word-bank">${available.map(w=>`<button class="word-chip" data-word="${escapeAttr(w)}" type="button">${w}</button>`).join('')}</div><div class="answer-bank">${chosen.map(w=>`<button class="word-chip" data-chosen="${escapeAttr(w)}" type="button">${w}</button>`).join('')}</div><div class="button-row"><button class="btn secondary small check-order" type="button">Check</button><button class="text-button clear-order" type="button">Clear</button></div><div class="feedback ${saved?.correct?'good':''}">${saved?.correct?'✓ Correct — say it aloud.':''}</div></div>`}).join('');
 $$('.order-task').forEach(task=>{const i=Number(task.dataset.order);$$('[data-word]',task).forEach(b=>b.onclick=()=>orderAdd(i,b.dataset.word));$$('[data-chosen]',task).forEach(b=>b.onclick=()=>orderRemove(i,b.dataset.chosen));$('.check-order',task).onclick=()=>checkOrder(i);$('.clear-order',task).onclick=()=>{delete state.answers[`order-${i}`];save();renderOrder();updateEvaluation()}});updateScores();
}
function getOrder(i){return state.answers[`order-${i}`]||{chosen:[],correct:false}}
function orderAdd(i,w){const d=getOrder(i);d.chosen.push(w);d.correct=false;state.answers[`order-${i}`]=d;save();renderOrder()}
function orderRemove(i,w){const d=getOrder(i),idx=d.chosen.indexOf(w);if(idx>=0)d.chosen.splice(idx,1);d.correct=false;state.answers[`order-${i}`]=d;save();renderOrder()}
function checkOrder(i){const d=getOrder(i),answer=d.chosen.join(' ');d.correct=answer===orderItems[i].answer;state.answers[`order-${i}`]=d;state.completed.order=orderItems.filter((_,j)=>state.answers[`order-${j}`]?.correct).length;save();renderOrder();const task=$(`[data-order="${i}"]`);if(task&&!d.correct){const f=$('.feedback',task);f.textContent='Not yet. Think: subject + verb + detail + place + time.';f.className='feedback bad'}updateEvaluation()}

function renderOral(){
 $('#oralTabs').innerHTML=oralPrompts.map((p,i)=>`<button class="${i===oralIndex?'active':''}" data-oral="${i}" type="button">${p.cat}</button>`).join('');
 const p=oralPrompts[oralIndex];$('#oralCategory').textContent=p.cat;$('#oralPrompt').textContent=p.q;$('#oralFr').textContent=p.fr;$('#oralSupport').innerHTML=`<h3>Support ladder</h3><ul>${p.support.map(x=>`<li>${x}</li>`).join('')}</ul><button class="btn ghost small" id="showModels" type="button">Show model levels</button>`;$('#modelA2').textContent=p.a2;$('#modelA2p').textContent=p.a2p;$('#modelB1').textContent=p.b1;$('#modelLadder').hidden=true;$('#oralSupport').hidden=true;
 $$('[data-oral]').forEach(b=>b.onclick=()=>{oralIndex=Number(b.dataset.oral);renderOral()});$('#showModels').onclick=()=>$('#modelLadder').hidden=!$('#modelLadder').hidden;
}

function analyseWriting(){const t=$('#writingText').value.trim();state.writing=t;const words=t?t.split(/\s+/).length:0;const connectors=(t.match(/\b(because|so|however|although|whereas|which means that|therefore|then|finally)\b/gi)||[]).length;const relative=(t.match(/\b(who|which|that|where|why)\b/gi)||[]).length;const polite=/could you|would it be possible|please|thank you/i.test(t);let msg=`<strong>${words} words</strong> · ${connectors} connector(s) · ${relative} relative-clause signal(s) · polite request: ${polite?'✓':'—'}<br>`;msg+=words<70?'Add more context, one consequence and a polite request.':words>120?'Try to remove repetition and keep the message concise.':'Good working length for this transfer task.';$('#writingAnalysis').innerHTML=msg;save();updateEvaluation()}

function startTimer(){if(timerId)return;timerId=setInterval(()=>{timerSeconds=Math.max(0,timerSeconds-1);renderTimer();if(!timerSeconds){clearInterval(timerId);timerId=null;toast('Time is up. Move to the oral interview.')}},1000)}function renderTimer(){const m=String(Math.floor(timerSeconds/60)).padStart(2,'0'),s=String(timerSeconds%60).padStart(2,'0');$('#timerDisplay').textContent=`${m}:${s}`}

function startRecording(){if(!navigator.mediaDevices?.getUserMedia){toast('Recording is not available in this browser.');return}navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{mediaChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)mediaChunks.push(e.data)};mediaRecorder.onstop=()=>{const blob=new Blob(mediaChunks,{type:mediaRecorder.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);$('#recordAudio').src=url;$('#recordAudio').hidden=false;$('#recordDownload').href=url;$('#recordDownload').hidden=false;stream.getTracks().forEach(t=>t.stop());$('#recordStatus').textContent='Recording ready. Listen once and improve one element.';state.completed.recording=true;save();updateEvaluation()};mediaRecorder.start();$('#recordStart').disabled=true;$('#recordStop').disabled=false;$('#recordStatus').textContent='Recording…';}).catch(()=>toast('Microphone permission was not granted.'))}

function statusLabel(v){return {achieved:'Objectif atteint',progress:'En cours d’acquisition','not-achieved':'Objectif non atteint','not-started':'Non commencé'}[v]}
function scorePct(section){return Math.round(sectionScore(section)/quizzes[section].length*100)}
function updateEvaluation(){
 const oralChecks=Object.values(state.oralChecks||{}).filter(Boolean).length;const writingWords=($('#writingText')?.value||state.writing||'').trim().split(/\s+/).filter(Boolean).length;const orderPct=Math.round((state.completed.order||0)/2*100);
 const skillData=[
{name:'Vocabulary',value:scorePct('vocabulary'),objective:'Retrieve travel and connector vocabulary in context',activity:'Vocabulary exam drill',mode:'QCM'},
{name:'Grammar',value:Math.round((scorePct('grammar')+orderPct)/2),objective:'Choose relative clauses, tense forms and word order',activity:'Grammar drill + sentence order',mode:'QCM + tap builder'},
{name:'Expressions',value:scorePct('expressions'),objective:'Use natural clarification, contrast and interaction chunks',activity:'Expression drill',mode:'QCM'},
{name:'Reading',value:scorePct('reading'),objective:'Identify key information and evidence in a short text',activity:'Travel reading',mode:'Reading comprehension'},
{name:'Listening',value:scorePct('listening'),objective:'Understand situation, problem, options and deadline',activity:'Travel message',mode:'Listening comprehension'},
{name:'Oral',value:Math.min(100,oralChecks*20+(state.completed.recording?10:0)),objective:'Give a structured answer and interact actively',activity:'CLOE oral interview',mode:'Manual check + recording'},
{name:'Writing',value:writingWords>=80?80:writingWords>=40?50:writingWords?25:0,objective:'Transfer exam language into a clear short message',activity:'Optional written transfer',mode:'Guided production'}];
 const overall=Math.round(skillData.reduce((s,x)=>s+x.value,0)/skillData.length);$('#evaluationHeroScore').textContent=overall+'%';$('#evaluationScoreValue').textContent=overall+'%';$('#evaluationDonut').style.setProperty('--score',overall+'%');
 $('#evaluationBreakdown').innerHTML=skillData.map(s=>`<div class="premium-breakdown-row"><strong>${s.name}</strong><div class="premium-breakdown-track"><span style="width:${s.value}%"></span></div><span>${s.value}%</span></div>`).join('');
 $('#evaluationRows').innerHTML=skillData.map(s=>{const st=s.value>=75?'achieved':s.value>0?'progress':'not-started';return `<tr><td><strong>${s.objective}</strong></td><td>${s.activity}</td><td>${s.mode}</td><td><strong>${s.value}%</strong><div class="table-progress"><span style="width:${s.value}%"></span></div></td><td><span class="status-badge ${st}">${statusLabel(st)}</span></td></tr>`}).join('');
 let h='Your progress will appear here',m='Complete the activities to generate a clear progress overview.';if(overall>=80){h='Strong exam transfer';m='Most skills are being retrieved with good independence. The next step is spontaneous oral interaction under time pressure.'}else if(overall>=55){h='Good consolidation in progress';m='Core language is becoming more accessible. Continue reducing support and increasing speed.'}else if(overall>0){h='Useful retrieval practice started';m='Continue the automatic sections, then repeat the oral mission with fewer prompts.'}$('#evaluationHeadline').textContent=h;$('#evaluationSummaryText').textContent=m;
 const autoAnswered=['vocabulary','grammar','expressions','reading','listening'].reduce((s,k)=>s+answeredCount(k),0)+(state.completed.order||0);const autoTotal=30;const manualProgress=Math.round(oralChecks/5*100);const completion=Math.min(100,Math.round((autoAnswered/autoTotal*70)+(manualProgress*.15)+(writingWords?7:0)+(state.final?8:0)));$('#progressText').textContent=completion+'%';$('#progressFill').style.width=completion+'%';
 const manualDone=['oral','writing'].filter(k=>(state.assessment||{})[k]&&state.assessment[k]!=='not-started').length;$('#overallResult').innerHTML=`<strong>${autoAnswered}/${autoTotal} automatic items completed</strong> · ${oralChecks}/5 oral indicators checked · ${manualDone}/2 manual assessments completed.<br><span style="color:var(--muted);font-weight:500">${m}</span>`;
 save(false)
}

function resetSection(section){if(!confirm(`Reset ${section} progress?`))return;if(quizzes[section])Object.keys(state.answers).filter(k=>k.startsWith(section+'-')).forEach(k=>delete state.answers[k]);if(section==='grammar'){Object.keys(state.answers).filter(k=>k.startsWith('order-')).forEach(k=>delete state.answers[k]);state.completed.order=0}if(section==='listening')$('#listeningTranscript').hidden=true;if(section==='oral'){state.oralChecks={};state.completed.recording=false;$$('[data-oral-check]').forEach(x=>x.checked=false);$('#speakingReflection').value='';state.reflection=''}if(section==='writing'){$('#writingText').value='';state.writing='';$('#writingAnalysis').textContent='Your word count and language signals will appear here.'}if(section==='final'){$('#finalNotes').value='';state.notes='';state.final=false}save();if(quizzes[section])renderQuiz(section);if(section==='grammar')renderOrder();updateEvaluation();toast('Section reset.')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function exportEvaluation(){save();updateEvaluation();const rows=$$('#evaluationRows tr').map(r=>'<tr>'+$$('td',r).map(td=>'<td>'+td.innerHTML+'</td>').join('')+'</tr>').join('');const doc=`<!doctype html><html><head><meta charset="utf-8"><title>Bilan Catherine — Adriatic CLOE</title><style>body{font-family:Arial,sans-serif;max-width:1100px;margin:30px auto;padding:20px;color:#173047}table{border-collapse:collapse;width:100%}th,td{border:1px solid #cbd7dc;padding:9px;text-align:left;vertical-align:top}h1,h2{color:#082b4a}.status-badge{font-weight:bold}.table-progress{display:none}</style></head><body><h1>Bilan Qualiopi — Catherine</h1><p><b>Lesson:</b> Adriatic CLOE Exam Mission</p><p><b>Date:</b> ${esc($('#evaluationDate').value)}</p><p><b>Automatic / lesson progress:</b> ${esc($('#evaluationHeroScore').textContent)}</p><h2>Learning objectives</h2><table><thead><tr><th>Objective</th><th>Activity</th><th>Assessment</th><th>Progress</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table><h2>Oral assessment</h2><p><b>Result:</b> ${esc($('[data-assessment="oral"]').value)}</p><p>${esc($('[data-comment="oral"]').value)}</p><h2>Written transfer assessment</h2><p><b>Result:</b> ${esc($('[data-assessment="writing"]').value)}</p><p>${esc($('[data-comment="writing"]').value)}</p><h2>Learner experience</h2><p><b>Satisfaction:</b> ${esc($('#satisfaction').value)}</p><p><b>Confidence:</b> ${esc($('#confidenceAfter').value)}</p><p><b>Most useful:</b> ${esc($('#mostUseful').value)}</p><p><b>Helped most:</b> ${esc($('#learnerComments').value)}</p><p><b>Practise again:</b> ${esc($('#learnerNextPractice').value)}</p><h2>Trainer conclusion</h2><p>${esc($('#trainerComments').value)}</p></body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([doc],{type:'text/html'}));a.download='Catherine-Adriatic-CLOE-Qualiopi.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function bind(){
 $('#lessonMode').onchange=()=>{document.body.classList.toggle('body-exam',$('#lessonMode').value==='exam');state.mode=$('#lessonMode').value;save();toast($('#lessonMode').value==='exam'?'Exam mode: support is hidden.':'Practice mode: support restored.')};
 $('#translationToggle').onchange=()=>document.body.classList.toggle('hide-fr',!$('#translationToggle').checked);$('#saveBtn').onclick=()=>save(true);$('#resumeBtn').onclick=()=>{loadFields();renderAll();toast('Saved work restored.')};$('#printBtn').onclick=()=>window.print();$('#backTop').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
 $$('.reset-section').forEach(b=>b.onclick=()=>resetSection(b.dataset.resetSection));
 $$('.rule-tab').forEach(b=>b.onclick=()=>{$$('.rule-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.rule-panel').forEach(p=>p.classList.toggle('active',p.id==='rule-'+b.dataset.rule))});
 $('#timerStart').onclick=startTimer;$('#timerPause').onclick=()=>{clearInterval(timerId);timerId=null};$('#timerReset').onclick=()=>{clearInterval(timerId);timerId=null;timerSeconds=1800;renderTimer()};
 $('#playListening').onclick=()=>speak(listeningScript);$('#replayListening').onclick=()=>speak(listeningScript);$('#showTranscript').onclick=()=>{const t=$('#listeningTranscript');t.hidden=!t.hidden;$('#showTranscript').textContent=t.hidden?'Show transcript':'Hide transcript'};
 $('#hearPrompt').onclick=()=>speak(oralPrompts[oralIndex].q);$('#showOralSupport').onclick=()=>{$('#oralSupport').hidden=!$('#oralSupport').hidden};
 $('#recordStart').onclick=startRecording;$('#recordStop').onclick=()=>{if(mediaRecorder&&mediaRecorder.state==='recording'){mediaRecorder.stop();$('#recordStart').disabled=false;$('#recordStop').disabled=true}};$('#recordClear').onclick=()=>{$('#recordAudio').hidden=true;$('#recordAudio').removeAttribute('src');$('#recordDownload').hidden=true;$('#recordStatus').textContent='Ready.';state.completed.recording=false;save();updateEvaluation()};
 $$('[data-oral-check]').forEach(x=>x.onchange=()=>{state.oralChecks[x.dataset.oralCheck]=x.checked;save();updateEvaluation()});
 $('#speakingReflection').oninput=()=>{state.reflection=$('#speakingReflection').value;save()};$('#writingText').oninput=()=>{state.writing=$('#writingText').value;save();updateEvaluation()};$('#analyseWriting').onclick=analyseWriting;$('#showWritingModels').onclick=()=>$('#writingModels').hidden=!$('#writingModels').hidden;$('#finalNotes').oninput=()=>{state.notes=$('#finalNotes').value;save()};$('#markFinalComplete').onclick=()=>{state.final=true;save();updateEvaluation();toast('Final mission marked complete.')};
 $$('[data-assessment]').forEach(x=>x.onchange=()=>{state.assessment[x.dataset.assessment]=x.value;save();updateEvaluation()});$$('[data-comment]').forEach(x=>x.oninput=()=>{state.comments[x.dataset.comment]=x.value;save()});
 ['satisfaction','confidenceAfter','mostUseful','learnerComments','learnerNextPractice','trainerComments','evaluationDate','learnerName','trainerName'].forEach(id=>{const e=$('#'+id);if(e)e.oninput=()=>{state.satisfaction[id]=e.value;save()}});$('#saveEvaluation').onclick=()=>{save();toast('Evaluation saved.')};$('#exportEvaluation').onclick=exportEvaluation;$('#resetAll').onclick=()=>{if(confirm('Reset all progress, answers and notes for this lesson?')){localStorage.removeItem(KEY);location.reload()}};
}
function restoreEvaluation(){Object.entries(state.assessment||{}).forEach(([k,v])=>{const x=$(`[data-assessment="${k}"]`);if(x)x.value=v});Object.entries(state.comments||{}).forEach(([k,v])=>{const x=$(`[data-comment="${k}"]`);if(x)x.value=v});Object.entries(state.satisfaction||{}).forEach(([k,v])=>{const x=$('#'+k);if(x)x.value=v})}
function renderAll(){renderVocab('all');['vocabulary','grammar','expressions','reading','listening'].forEach(renderQuiz);renderOrder();renderOral();updateScores();updateEvaluation()}
function init(){loadFields();initVoices();bindAudio();bind();restoreEvaluation();renderTimer();renderAll();document.body.classList.toggle('hide-fr',!$('#translationToggle').checked);setTimeout(bindAudio,50)}
document.addEventListener('DOMContentLoaded',init);
})();
