const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const STORAGE_KEY='eden_lesson_8_expectations_v1';
let voices=[], score={correct:0,total:0}, quizResults={};
const shuffle=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const vocab=[
 {c:'Expectations',w:'early visibility',fr:'visibilité en amont / rapidement',d:'Knowing about an important risk or change before it becomes a late surprise.',e:'What I need is early visibility of any issue that could affect the programme.'},
 {c:'Expectations',w:'material risk',fr:'risque significatif / matériel',d:'A risk important enough to affect a decision, schedule, cost, quality or programme outcome.',e:'I need early visibility of material risk, not every technical detail.'},
 {c:'Expectations',w:'clear ownership',fr:'responsabilité clairement attribuée',d:'A situation where it is explicit who is accountable for an action or deliverable.',e:'I need clear ownership of agreed actions before we close the meeting.'},
 {c:'Expectations',w:'follow-through',fr:'suivi jusqu’à l’achèvement',d:'The act of completing what was agreed, not just starting it.',e:'I value autonomy, but I also need reliable follow-through on commitments.'},
 {c:'Cooperation',w:'I’m counting on your cooperation.',fr:'Je compte sur votre coopération.',d:'A firm but collaborative way to state that cooperation is expected.',e:'I’m counting on your cooperation while we establish the new working rhythm.'},
 {c:'Cooperation',w:'work together smoothly',fr:'travailler ensemble de manière fluide',d:'To collaborate efficiently with low friction, clear roles and useful communication.',e:'I want us to define the right checkpoints so we can work together smoothly.'},
 {c:'Cooperation',w:'working relationship',fr:'relation de travail',d:'The practical and professional way two people collaborate over time.',e:'I want to establish a direct and transparent working relationship.'},
 {c:'Cooperation',w:'lightweight checkpoint',fr:'point de suivi léger',d:'A short, low-burden review that provides essential visibility without heavy reporting.',e:'Let’s define a lightweight checkpoint for risk and decision visibility.'},
 {c:'Decision language',w:'decision point',fr:'point de décision',d:'The moment or issue at which a decision is required.',e:'Let me bring this back to the decision point.'},
 {c:'Decision language',w:'programme impact',fr:'impact sur le programme',d:'The consequence for timing, cost, interfaces, risk, resources or commitments.',e:'What is the programme impact if we keep the current option?'},
 {c:'Decision language',w:'escalation trigger',fr:'seuil / déclencheur d’escalade',d:'A predefined condition that requires management involvement.',e:'Let’s agree on the escalation trigger before you continue independently.'},
 {c:'Decision language',w:'revisit the decision',fr:'réexaminer la décision',d:'To reconsider a previous decision because new information has emerged.',e:'We will revisit the decision if the next test exceeds the agreed threshold.'},
 {c:'Estimates',w:'estimate',fr:'estimation / estimation chiffrée',d:'An approximate figure, duration or cost; also a verb meaning to calculate approximately.',e:'Our current estimate is six weeks.'},
 {c:'Estimates',w:'estimation process',fr:'processus d’estimation',d:'The method or activity used to create estimates.',e:'The estimation process needs to make the assumptions more explicit.'},
 {c:'Estimates',w:'working assumption',fr:'hypothèse de travail',d:'A provisional assumption used for planning until better evidence is available.',e:'Six weeks is our working assumption until the next test result.'},
 {c:'Estimates',w:'confidence level',fr:'niveau de confiance',d:'How certain the team is that an estimate or conclusion is reliable.',e:'What confidence level do you have in that estimate?'},
 {c:'Autonomy',w:'decision space',fr:'marge / espace de décision',d:'The area within which someone can decide independently.',e:'I want the decision space to be clear so you can act without unnecessary approval.'},
 {c:'Autonomy',w:'technical ownership',fr:'responsabilité technique',d:'Responsibility for the technical analysis, judgement or solution.',e:'The technical ownership remains with you.'},
 {c:'Autonomy',w:'management visibility',fr:'visibilité managériale',d:'The level of information management needs to understand risk, decisions and commitments.',e:'The technical ownership stays with you, but I need management visibility on the risk.'},
 {c:'Autonomy',w:'unnecessary reporting',fr:'reporting inutile',d:'Reporting that adds workload without improving decisions, accountability or risk control.',e:'I do not want to create unnecessary reporting.'}
];

const quizzes={
 forceQuiz:[
  {q:'A senior expert is free to choose the technical method, but you need immediate notice if the safety risk changes.',a:['“Could you maybe tell me if anything changes?”','“I need immediate visibility if the safety risk changes.”','“You must report every technical step to me.”'],correct:1,h:'The requirement is firm, but it concerns the risk threshold—not the method.'},
  {q:'You want to explore the reasoning behind a recommendation.',a:['“Could you walk me through the main assumption?”','“I expect you to justify yourself.”','“You must change the recommendation.”'],correct:0,h:'Use an open question when you are testing judgement rather than imposing a boundary.'},
  {q:'An agreed action is mandatory before the review.',a:['“It could be useful if you have time.”','“I need the agreed action closed before the review.”','“Would you maybe think about it?”'],correct:1,h:'A required deliverable needs clear managerial language.'}
 ],
 cooperationQuiz:[
  {q:'Which sentence creates cooperation without sounding as if authority is optional?',a:['“I hope you will cooperate with me.”','“I’d like us to agree on how we work together.”','“Please manage me in the way you prefer.”'],correct:1,h:'Frame cooperation as a shared working agreement, not a request for permission.'},
  {q:'Which sentence best protects both autonomy and visibility?',a:['“Do whatever you want; I trust you.”','“I will need every technical detail.”','“I want you to have autonomy on the technical work, and I need visibility when the programme risk changes.”'],correct:2,h:'Strong management separates technical autonomy from the information needed for programme accountability.'}
 ],
 estimateQuiz:[
  {q:'Choose the most natural sentence.',a:['“Can you give me an estimation of the duration?”','“Can you give me an estimate of the duration?”','“Can you estimate me the duration?”'],correct:1,h:'For a specific approximate figure or duration, “estimate” is the normal noun.'},
  {q:'Choose the natural use of “estimation”.',a:['“The estimation process needs clearer assumptions.”','“Our estimation is six weeks.”','“Please send me an estimation by noon.”'],correct:0,h:'“Estimation” is most natural for the process or method.'},
  {q:'Choose the strongest management question about an uncertain estimate.',a:['“Are you sure?”','“What are the main assumptions behind the estimate, and what could move it?”','“Can you make the estimate smaller?”'],correct:1,h:'A useful management question exposes assumptions and sensitivity, not just confidence.'}
 ]
};

const gapFills={
 expectGapFill:[
  {before:'What I need ',blank:'from',after:' you is early risk visibility.',answers:['from'],h:'Collocation: “need something ___ someone”.'},
  {before:'I want you to have autonomy, but I need ',blank:'visibility',after:' when the risk changes.',answers:['visibility'],h:'The noun used throughout this lesson for “knowing about it early”.'},
  {before:'Let’s agree on the ',blank:'escalation',after:' trigger before you continue.',answers:['escalation'],h:'The word for the moment management gets involved.'},
  {before:'I need clear ',blank:'ownership',after:' of agreed actions.',answers:['ownership'],h:'Who is accountable — from the EXPECT column.'},
  {before:'You can expect me to give you enough ',blank:'autonomy',after:' to lead the technical work.',answers:['autonomy'],h:'The word from the ENABLE column meaning independence to decide.'}
 ]
};

const forceMatchPairs=[
 {force:'Tentative',example:'“I hope you can keep me informed.”'},
 {force:'Professional',example:'“I’d like you to keep me informed.”'},
 {force:'Managerial',example:'“What I need is early visibility of significant risks.”'},
 {force:'Collaborative + firm',example:'“What I need from you is early visibility of significant risks, and I want us to agree on what needs to be escalated.”'}
];

const reverseQuestions=[
 'What do you need from me to do your job effectively?',
 'What decisions do you expect me to own?',
 'Where do you need more autonomy?',
 'What information do you need from me?',
 'What usually slows your work down?',
 'When would you expect me to step in?',
 'What level of reporting is genuinely useful to you?',
 'What would make our collaboration work well from your perspective?'
];

const rewrites=[
 {bad:'I hope you can tell me if there is a problem.',b2:'I need early visibility of any issue that could affect the programme.',c1:'My requirement is early visibility as soon as an issue could materially affect the programme.'},
 {bad:'Can you maybe give me your opinion?',b2:'What is your recommendation?',c1:'What do you recommend, and what is the key evidence behind it?'},
 {bad:'I would like you to cooperate with me.',b2:'I’d like us to agree on how we work together.',c1:'Let’s define the working interface so you have autonomy and I have the visibility needed to manage the programme.'},
 {bad:'I need to know everything that is happening.',b2:'I don’t need every detail, but I do need visibility of material risks and decisions.',c1:'I do not need continuous technical detail; I need visibility where risk, assumptions or programme commitments change.'},
 {bad:'I hope we can work well together.',b2:'I want us to establish a direct and effective working relationship.',c1:'I want us to establish a relationship with clear autonomy, direct communication and predictable decision points.'},
 {bad:'You know more than me, so you should decide.',b2:'I’ll rely on your technical recommendation, and I’ll make the decision based on the programme priorities and risks.',c1:'You own the technical judgement; I will use that recommendation to make the programme-level trade-off explicit.'}
];

const scenarios=[
 {title:'The complete-answer preference',s:'A senior project leader only wants to escalate once the technical analysis is complete. You are concerned about late visibility.',target:'Clarify the difference between an early risk signal and a mature recommendation.',b2:'I understand that you want the analysis to be complete before making a recommendation. What I need earlier is visibility that a material issue exists. You can keep working the technical analysis, but please raise the risk as soon as it could affect the programme.',c1:'Let’s separate two things: early visibility and mature technical judgement. I do not need a premature recommendation, but I do need an early signal when the risk profile changes. You retain the analysis; I need enough visibility to protect the programme from late surprises.'},
 {title:'The reporting-resistant expert',s:'A respected technical leader says regular updates are a waste of time and should not be necessary for senior people.',target:'Protect autonomy while defining the minimum management interface.',b2:'I agree that senior people should not spend time on unnecessary reporting. I do need visibility of major risks, changes to the estimate and decisions that affect the programme. Let’s keep the checkpoint short and focused only on those points.',c1:'Trust is not the issue. The purpose of the checkpoint is not task control; it is programme visibility. Let’s keep the interface lightweight: material risk, changed assumptions, commitments and decisions only.'},
 {title:'The uncertain six-week estimate',s:'A technical lead gives a six-week estimate but admits that two interfaces are still poorly defined.',target:'Turn an estimate into a management-ready planning input.',b2:'Six weeks is useful as a starting point. What are the main assumptions behind it, and which interface could change the estimate the most? When will you be able to refine it?',c1:'I’ll use six weeks as a working assumption, but I need the uncertainty made explicit. Which variable has the highest sensitivity, what confidence level do you assign to the estimate, and when will we have evidence strong enough to re-baseline it?'},
 {title:'The “technical matter” boundary',s:'A senior expert tells you that a choice is technical and does not require your involvement.',target:'Respect technical ownership while defining the programme boundary.',b2:'I agree that the technical choice is yours to lead. I only need to be involved if it affects timing, cost, interfaces or programme risk. If it stays inside those boundaries, I’m comfortable with you owning the decision.',c1:'The technical judgement remains yours. My involvement starts when that judgement changes the programme exposure—timing, cost, interfaces, governance or material risk. Let’s use those as the escalation boundaries.'},
 {title:'Two expectations collide',s:'One expert wants total autonomy. Another asks you to make more detailed decisions because they want clearer direction.',target:'Use one management philosophy without treating both people identically.',b2:'I want both of you to have clear ownership, but autonomy does not have to look identical. I will clarify the outcome and boundaries, then we can agree the right decision points for each scope. My expectation is still the same: risks visible, recommendations clear and commitments closed.',c1:'Consistency does not mean identical supervision. The management standard is common—clear outcomes, explicit boundaries, risk visibility and accountability—but the operating interface can differ according to the maturity of the scope and the decision need.'}
];
const surprises=['“Why should I involve you if the risk is still only technical?”','“What if I disagree with your programme decision?”','“How much reporting do you actually expect?”','“What if the estimate changes again next week?”','“How will you avoid micromanaging us?”'];
const microPrompts={expect:['A risk is emerging but not yet confirmed.','A milestone is likely to slip.','An agreed action has no owner.','A recommendation is vague.'],cooperate:['An expert needs faster decisions from you.','A senior lead dislikes meetings.','You want to learn what slows the team down.','You want to define escalation boundaries.'],extract:['You have heard five minutes of technical detail.','Two options are still open.','A supplier changed an assumption.','The team says it needs more time.']};

function populateVoices(){if(!('speechSynthesis'in window))return;voices=speechSynthesis.getVoices();const lang=$('#accentSelect').value.toLowerCase();const list=voices.filter(v=>(v.lang||'').toLowerCase().startsWith(lang));const use=list.length?list:voices;$('#voiceSelect').innerHTML=use.map(v=>`<option value="${voices.indexOf(v)}">${esc(v.name)} (${esc(v.lang)})</option>`).join('')||'<option value="">Default voice</option>'}
function speak(text){if(!('speechSynthesis'in window))return alert('Text-to-speech is not supported on this device.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=$('#accentSelect').value;const v=voices[Number($('#voiceSelect').value)];if(v)u.voice=v;u.rate=.9;u.pitch=1;speechSynthesis.speak(u)}
function textOf(id){const el=$('#'+id);return el?el.innerText.replace(/\s+/g,' ').trim():''}

function renderQuiz(id,items){const host=$('#'+id);if(!host)return;host.innerHTML=items.map((it,idx)=>{const order=shuffle(it.a.map((t,i)=>({t,i})));return `<div class="exercise-card quiz" data-q="${id}-${idx}"><h3>${esc(it.q)}</h3><div class="choice-list">${order.map(o=>`<button class="choice-btn" data-answer="${o.i}" data-correct="${it.correct}">${esc(o.t)}</button>`).join('')}</div><div class="buttons"><button class="secondary hint-btn">Hint</button></div><div class="hint">${esc(it.h)}</div><div class="feedback"></div></div>`}).join('')}
function initQuizzes(){Object.entries(quizzes).forEach(([id,items])=>renderQuiz(id,items));document.addEventListener('click',e=>{const c=e.target.closest('.choice-btn');if(c){const quiz=c.closest('.quiz');const key=quiz.dataset.q;if(quiz.dataset.done||quizResults[key])return;quiz.dataset.done='1';const ok=c.dataset.answer===c.dataset.correct;quizResults[key]={answer:c.dataset.answer,correct:c.dataset.correct,ok};score.total=Object.keys(quizResults).length;score.correct=Object.values(quizResults).filter(x=>x.ok).length;c.classList.add(ok?'correct':'wrong');if(!ok){const right=quiz.querySelector(`[data-answer="${c.dataset.correct}"]`);right?.classList.add('correct')}const fb=$('.feedback',quiz);fb.textContent=ok?'Correct — strong managerial choice.':'Not quite — compare the level of force and the management objective.';fb.className='feedback '+(ok?'good':'bad');updateMetrics();saveProgress(false)}const h=e.target.closest('.hint-btn');if(h)h.closest('.quiz').querySelector('.hint').classList.toggle('visible')})}

function renderGapFill(id,items){const host=$('#'+id);if(!host)return;const bank=shuffle(items.map(it=>it.answers[0]));const bankHtml=`<div class="word-bank"><span class="word-bank-label">Word bank</span>${bank.map(w=>`<button type="button" class="word-chip">${esc(w)}</button>`).join('')}<span class="micro word-bank-hint">Tap a word to drop it into the next empty gap, or type it yourself. Each word is used once.</span></div>`;host.innerHTML=bankHtml+items.map((it,idx)=>`<div class="exercise-card quiz gapfill" data-q="${id}-${idx}"><p>${esc(it.before)}<input type="text" class="gap-input" autocomplete="off" spellcheck="false">${esc(it.after)}</p><div class="buttons"><button class="secondary checkGap">Check</button><button class="secondary hint-btn">Hint</button></div><div class="hint">${esc(it.h)}</div><div class="feedback"></div></div>`).join('')}
function initGapFills(){Object.entries(gapFills).forEach(([id,items])=>renderGapFill(id,items));document.addEventListener('click',e=>{const chip=e.target.closest('.word-chip');if(chip){const host=chip.closest('.word-bank').parentElement;const empty=$$('.gap-input',host).find(inp=>!inp.disabled&&!inp.value.trim());if(empty){empty.value=chip.textContent;empty.focus()}return}const btn=e.target.closest('.checkGap');if(!btn)return;const card=btn.closest('.quiz');const key=card.dataset.q;if(card.dataset.done||quizResults[key])return;const sep=key.lastIndexOf('-');const gid=key.slice(0,sep),idx=Number(key.slice(sep+1));const item=gapFills[gid]?.[idx];if(!item)return;const input=card.querySelector('.gap-input');const val=(input.value||'').trim().toLowerCase();const ok=item.answers.some(a=>a.toLowerCase()===val);card.dataset.done='1';quizResults[key]={answer:val,correct:item.answers[0],ok};score.total=Object.keys(quizResults).length;score.correct=Object.values(quizResults).filter(x=>x.ok).length;input.classList.add(ok?'correct':'wrong');input.disabled=true;const fb=$('.feedback',card);fb.textContent=ok?'Correct.':`Not quite — the expected word is “${item.answers[0]}”.`;fb.className='feedback '+(ok?'good':'bad');updateMetrics();saveProgress(false)})}

let selectedChip=null;
function renderForceMatch(){const host=$('#forceMatch');if(!host)return;const shuffled=shuffle(forceMatchPairs.map((p,i)=>({...p,idx:i})));host.innerHTML=`<div class="match-zones">${forceMatchPairs.map((p,i)=>`<div class="match-zone"><h4>${esc(p.force)}</h4><div class="drop-target" data-accept="${i}">Drop the matching sentence here</div></div>`).join('')}</div><div class="match-tray" id="matchTray">${shuffled.map(p=>`<div class="match-chip" draggable="true" data-answer="${p.idx}" tabindex="0">${esc(p.example)}</div>`).join('')}</div><p class="micro">Drag each sentence onto its force level, or tap a sentence then tap a level.</p><div class="feedback" id="matchFeedback"></div>`}
function initForceMatch(){renderForceMatch();const host=$('#forceMatch');if(!host)return;const total=forceMatchPairs.length;let matched=0;function place(chip,zoneIdx){const zone=host.querySelector(`.drop-target[data-accept="${zoneIdx}"]`);if(!zone||zone.classList.contains('filled'))return;const answer=Number(chip.dataset.answer);if(answer===zoneIdx){zone.textContent=chip.textContent;zone.classList.add('filled','correct');chip.remove();matched++;if(matched===total){const fb=$('#matchFeedback');if(fb){fb.textContent='All matched correctly.';fb.className='feedback good'}if(!quizResults.forceMatch){quizResults.forceMatch={answer:'matched',correct:'matched',ok:true};score.total=Object.keys(quizResults).length;score.correct=Object.values(quizResults).filter(x=>x.ok).length;updateMetrics();saveProgress(false)}}}else{zone.classList.add('wrong-flash');setTimeout(()=>zone.classList.remove('wrong-flash'),450)}}
 host.addEventListener('dragstart',e=>{const chip=e.target.closest('.match-chip');if(chip){e.dataTransfer.setData('text/plain',chip.dataset.answer);chip.classList.add('dragging')}});
 host.addEventListener('dragend',e=>{e.target.closest('.match-chip')?.classList.remove('dragging')});
 $$('.drop-target',host).forEach(zone=>{zone.addEventListener('dragover',e=>e.preventDefault());zone.addEventListener('drop',e=>{e.preventDefault();const answer=e.dataTransfer.getData('text/plain');const chip=host.querySelector(`.match-chip[data-answer="${answer}"]`);if(chip)place(chip,Number(zone.dataset.accept))})});
 host.addEventListener('click',e=>{const chip=e.target.closest('.match-chip');if(chip){$$('.match-chip',host).forEach(c=>c.classList.remove('selected'));chip.classList.add('selected');selectedChip=chip;return}const zone=e.target.closest('.drop-target');if(zone&&selectedChip){place(selectedChip,Number(zone.dataset.accept));selectedChip=null}});
}

function renderVocabCategories(){const cats=[...new Set(vocab.map(v=>v.c))];$('#vocabCategory').innerHTML=['All',...cats].map(c=>`<option>${esc(c)}</option>`).join('');renderVocab()}
function renderVocab(item=null){let pool=vocab;const c=$('#vocabCategory').value;if(c&&c!=='All')pool=vocab.filter(v=>v.c===c);const v=item||pool[0];if(!v)return;$('#vocabCard').innerHTML=`<article class="vocab-card"><div class="vocab-head"><div><span class="tag">${esc(v.c)}</span><h3 class="vocab-word">${esc(v.w)}</h3></div><button class="secondary" data-vocab-speak="${esc(v.e)}">Listen</button></div><div class="vocab-meta"><div><strong>French</strong>${esc(v.fr)}</div><div><strong>Definition</strong>${esc(v.d)}</div><div><strong>Example</strong>${esc(v.e)}</div></div></article>`}

function renderQuestionConsole(){const host=$('#questionConsole');host.innerHTML=`<div class="card-grid">${reverseQuestions.map((q,i)=>`<article class="card"><span class="number">${i+1}</span><p>${esc(q)}</p><button class="secondary" data-speak="${esc(q)}">Listen</button></article>`).join('')}</div>`}
function renderRewriteLab(){const host=$('#rewriteLab');host.innerHTML=rewrites.map((r,i)=>`<div class="exercise-card"><h3>Rewrite ${i+1}</h3><p><strong>Original:</strong> “${esc(r.bad)}”</p><textarea rows="3" placeholder="Your managerial version"></textarea><div class="buttons"><button class="secondary model-toggle" data-target="rewrite-${i}">Show B2 / C1 models</button></div><div class="model-block" id="rewrite-${i}"><span class="model-label">B2</span><p>${esc(r.b2)}</p><span class="model-label">C1</span><p>${esc(r.c1)}</p></div></div>`).join('')}

function renderScenarios(){const sel=$('#scenarioSelect');sel.innerHTML=scenarios.map((s,i)=>`<option value="${i}">${esc(s.title)}</option>`).join('');renderScenario(0)}
function renderScenario(i){const s=scenarios[i];$('#scenarioCard').innerHTML=`<div class="exercise-card"><span class="tag">Scenario ${i+1}</span><h3>${esc(s.title)}</h3><p>${esc(s.s)}</p><div class="note-box"><strong>Your objective:</strong> ${esc(s.target)}</div><textarea rows="5" placeholder="Cue words or written version"></textarea><div class="buttons"><button data-timer="90">Start 90 seconds</button><span class="timer">01:30</span><button class="secondary model-toggle" data-target="scenarioModels">Reveal B2 / C1 models</button></div><div class="surprise-box"><strong>Surprise:</strong> <span id="scenarioSurprise">No surprise challenge yet.</span></div><div class="model-block" id="scenarioModels"><span class="model-label">B2</span><p>${esc(s.b2)}</p><span class="model-label">C1</span><p>${esc(s.c1)}</p></div></div>`}

function initTimers(){document.addEventListener('click',e=>{const b=e.target.closest('[data-timer]');if(!b)return;const box=b.closest('.exercise-card,.panel');const display=box?.querySelector('.timer');if(!display)return;let left=Number(b.dataset.timer);if(b._timer)clearInterval(b._timer);b.disabled=true;const paint=()=>{const m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');display.textContent=`${m}:${s}`};paint();b._timer=setInterval(()=>{left--;paint();if(left<=0){clearInterval(b._timer);b.disabled=false;display.textContent='Time';}},1000)})}

function initRecorders(){if(!navigator.mediaDevices||!window.MediaRecorder){$$('.recorder').forEach(r=>r.innerHTML+='<p class="micro">Recording is not supported in this browser.</p>');return}$$('.recorder').forEach(r=>{let rec,chunks=[],stream;const start=$('.startRec',r),stop=$('.stopRec',r),audio=$('.playback',r),dl=$('.downloadRec',r),status=$('.rec-status',r);start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);audio.src=url;audio.classList.remove('hidden');dl.href=url;dl.classList.remove('hidden');stream.getTracks().forEach(t=>t.stop())};rec.start();r.classList.add('recording');status.lastChild.textContent=' Recording…';start.disabled=true;stop.disabled=false}catch(err){alert('Microphone access was not available.')}};stop.onclick=()=>{if(rec&&rec.state!=='inactive')rec.stop();r.classList.remove('recording');status.lastChild.textContent=' Ready';start.disabled=false;stop.disabled=true}})}

const checkpointNames={
 'flight-plan':'Leadership principle understood','baseline':'Baseline future-manager response','expectations':'State expectations clearly','cooperation':'Ask for cooperation confidently','vocabulary':'Use new leadership vocabulary','key-point':'Extract key decision information','estimate':'Use estimate / estimation accurately','framework':'Balance expectations and support','their-expectations':'Ask what senior experts need','reporting':'Create visibility without micromanaging','upgrade':'Upgrade deferential language','scenarios':'Lead realistic senior-expert scenarios','first-conversation':'Set the working relationship','disagreement':'Hold the management boundary','compression':'Deliver concise leadership language','cloe':'Transfer to professional oral exam','final-mission':'Integrate the full management approach'
};
function renderCheckpoints(){Object.entries(checkpointNames).forEach(([id,name])=>{const host=$(`[data-checkpoint="${id}"]`);if(!host)return;host.innerHTML=`<h3>Progress checkpoint</h3><div class="checkpoint-grid"><label>Status<select class="checkpoint-status" data-cp="${id}"><option value="not-started">Not started</option><option value="progress">In progress</option><option value="achieved">Achieved</option><option value="not-achieved">Not achieved</option></select></label><label>Observation<textarea rows="3" data-note="${id}" placeholder="What worked? What should improve?"></textarea></label></div>`});}
function progressData(){const cps={};Object.keys(checkpointNames).forEach(id=>cps[id]={status:$(`[data-cp="${id}"]`)?.value||'not-started',note:$(`[data-note="${id}"]`)?.value||''});const rubric={};$$('[data-rubric]').forEach(s=>rubric[s.dataset.rubric]=s.value);return {cps,rubric,learner:$('#learnerName').value,trainer:$('#trainerName').value,date:$('#evaluationDate').value,obs:$('#generalObservations').value,score,quizResults,lastSaved:new Date().toISOString()}}
function loadProgress(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!p)return;quizResults=p.quizResults||{};score.total=Object.keys(quizResults).length;score.correct=Object.values(quizResults).filter(x=>x.ok).length;Object.entries(p.cps||{}).forEach(([id,v])=>{const s=$(`[data-cp="${id}"]`),n=$(`[data-note="${id}"]`);if(s)s.value=v.status||'not-started';if(n)n.value=v.note||''});Object.entries(p.rubric||{}).forEach(([id,v])=>{const s=$(`[data-rubric="${id}"]`);if(s)s.value=v});$('#learnerName').value=p.learner||'';$('#trainerName').value=p.trainer||'Tisha DOUTY-DOSIERE';$('#evaluationDate').value=p.date||new Date().toISOString().slice(0,10);$('#generalObservations').value=p.obs||'';if(p.lastSaved)$('#lastSaved').textContent=new Date(p.lastSaved).toLocaleString();applyQuizResults()}catch(e){}}
function applyQuizResults(){if(quizResults.forceMatch?.ok){const host=$('#forceMatch');if(host)host.innerHTML='<p class="feedback good">All matched correctly (saved).</p>'}Object.entries(quizResults).forEach(([key,r])=>{if(key==='forceMatch')return;const quiz=document.querySelector(`.quiz[data-q="${key}"]`);if(!quiz)return;quiz.dataset.done='1';if(quiz.classList.contains('gapfill')){const input=quiz.querySelector('.gap-input');if(input){input.value=r.answer;input.disabled=true;input.classList.add(r.ok?'correct':'wrong')}const fb=quiz.querySelector('.feedback');if(fb){fb.textContent=r.ok?'Correct.':`Not quite — the expected word is “${r.correct}”.`;fb.className='feedback '+(r.ok?'good':'bad')}return}const chosen=quiz.querySelector(`[data-answer="${r.answer}"]`),right=quiz.querySelector(`[data-answer="${r.correct}"]`);chosen?.classList.add(r.ok?'correct':'wrong');right?.classList.add('correct');const fb=quiz.querySelector('.feedback');if(fb){fb.textContent=r.ok?'Correct — strong managerial choice.':'Not quite — compare the level of force and the management objective.';fb.className='feedback '+(r.ok?'good':'bad')}})}
function saveProgress(show=true){const p=progressData();localStorage.setItem(STORAGE_KEY,JSON.stringify(p));$('#lastSaved').textContent=new Date(p.lastSaved).toLocaleString();updateMetrics();if(show)alert('Progress saved.')}
function updateMetrics(){const statuses=$$('.checkpoint-status').map(s=>s.value);const started=statuses.filter(s=>s!=='not-started').length;const pct=statuses.length?Math.round(started/statuses.length*100):0;$('#scoreText').textContent=`${score.correct}/${score.total}`;$('#autoScore').textContent=`${score.correct}/${score.total}`;$('#progressText').textContent=`${pct}%`;$('#sectionProgress').textContent=`${pct}%`;const fs=finalScore();$('#finalScore').textContent=`${fs}/12`;$('#finalMetric').textContent=`${fs}/12`;let overall='not-started';if(started){overall=statuses.every(s=>s==='achieved')&&fs>=10?'achieved':statuses.some(s=>s==='not-achieved')?'not-achieved':'progress'}const os=$('#overallStatus');os.textContent=overall==='achieved'?'Achieved':overall==='progress'?'In progress':overall==='not-achieved'?'Needs reinforcement':'Not started';os.className='status '+overall;renderProgressRows()}

const rubricItems=[['expect','Expectations'],['autonomy','Autonomy / boundaries'],['cooperation','Cooperation'],['risk','Risk visibility'],['decision','Decision clarity'],['delivery','Executive delivery']];
function renderRubric(){$('#finalRubric').innerHTML=rubricItems.map(([id,label])=>`<label>${esc(label)}<select data-rubric="${id}"><option value="0">0 — Not shown</option><option value="1">1 — Developing</option><option value="2">2 — Strong</option></select></label>`).join('')}
function finalScore(){return $$('[data-rubric]').reduce((sum,s)=>sum+Number(s.value||0),0)}
function renderProgressRows(){$('#progressRows').innerHTML=Object.entries(checkpointNames).map(([id,name])=>{const s=$(`[data-cp="${id}"]`)?.value||'not-started',n=$(`[data-note="${id}"]`)?.value||'';const lab={"not-started":"Not started","progress":"In progress","achieved":"Achieved","not-achieved":"Not achieved"}[s];return `<tr><td>${esc(name)}</td><td>${esc(lab)}</td><td>${esc(n)||'—'}</td></tr>`}).join('')}
function reportText(){const p=progressData();const lines=['Lesson 8 — Setting Expectations & Building Cooperation','',`Learner: ${p.learner||'—'}`,`Trainer: ${p.trainer||'—'}`,`Date: ${p.date||'—'}`,`Automatic score: ${score.correct}/${score.total}`,`Sections started: ${$('#sectionProgress').textContent}`,`Final mission: ${finalScore()}/12`,`Overall: ${$('#overallStatus').textContent}`,'','Progress:'];Object.entries(checkpointNames).forEach(([id,name])=>{const v=p.cps[id];lines.push(`- ${name}: ${v.status}${v.note?` — ${v.note}`:''}`)});lines.push('','General observations:',p.obs||'—');return lines.join('\n')}
function reportHtml(){return `<!doctype html><meta charset="utf-8"><title>Lesson 8 Progress Report</title><style>body{font:16px Arial;max-width:900px;margin:40px auto;line-height:1.55;color:#10223b}h1{color:#0b1f3a}pre{white-space:pre-wrap;background:#f4f8fb;padding:20px;border-radius:16px}</style><h1>Lesson 8 Progress Report</h1><pre>${esc(reportText())}</pre>`}
function download(name,text,type='text/plain'){const b=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function copy(text){navigator.clipboard?.writeText(text).then(()=>alert('Copied.')).catch(()=>alert('Copy was not available in this browser.'))}

function feedbackText(){return `Lesson 8 learner feedback\nUseful for real work: ${$('#surveyUseful').value||'—'}\nConfidence after this lesson: ${$('#surveyConfidence').value||'—'}\nMost useful focus: ${$('#surveyFocus').value||'—'}\n\nComments:\n${$('#surveyComments').value||'—'}`}

function bindCommon(){document.addEventListener('click',e=>{const scroll=e.target.closest('[data-scroll]');if(scroll){$(scroll.dataset.scroll)?.scrollIntoView({behavior:'smooth'});return}const m=e.target.closest('.model-toggle');if(m){$('#'+m.dataset.target)?.classList.toggle('visible');return}const sp=e.target.closest('[data-speak]');if(sp){speak(sp.dataset.speak);return}const spi=e.target.closest('[data-speak-id]');if(spi){speak(textOf(spi.dataset.speakId));return}const vs=e.target.closest('[data-vocab-speak]');if(vs){speak(vs.dataset.vocabSpeak);return}});$('#toggleFrench').onclick=()=>{document.body.classList.toggle('all-french');$('#toggleFrench').textContent=document.body.classList.contains('all-french')?'Hide French support':'Show French support'};$('#toggleModels').onclick=()=>{document.body.classList.toggle('all-models');$('#toggleModels').textContent=document.body.classList.contains('all-models')?'Hide all models':'Show all models'};$('#stopAudio').onclick=()=>window.speechSynthesis?.cancel();$('#audioTest').onclick=()=>speak('Audio test. If you can hear this sentence, the listen buttons are working.');$('#refreshVoices').onclick=populateVoices;$('#accentSelect').onchange=populateVoices;$('#printPage').onclick=()=>window.print();$('#vocabCategory').onchange=()=>renderVocab();$('#randomVocab').onclick=()=>{const c=$('#vocabCategory').value;const pool=c==='All'?vocab:vocab.filter(v=>v.c===c);renderVocab(pool[Math.floor(Math.random()*pool.length)])};$('#scenarioSelect').onchange=e=>renderScenario(Number(e.target.value));$('#randomScenario').onclick=()=>{const i=Math.floor(Math.random()*scenarios.length);$('#scenarioSelect').value=i;renderScenario(i)};$('#surpriseScenario').onclick=()=>{const s=$('#scenarioSurprise');if(s)s.textContent=surprises[Math.floor(Math.random()*surprises.length)]};$$('.microPrompt').forEach(b=>b.onclick=()=>{const pool=microPrompts[b.dataset.kind];b.parentElement.querySelector('.micro-output').textContent=pool[Math.floor(Math.random()*pool.length)]});['finalSurprise1','finalSurprise2','finalSurprise3'].forEach((id,i)=>$('#'+id).onclick=()=>{$('#finalSurpriseText').textContent=surprises[(i+Math.floor(Math.random()*surprises.length))%surprises.length]});}

function initProgress(){renderCheckpoints();renderRubric();$('#evaluationDate').value=new Date().toISOString().slice(0,10);loadProgress();$$('.checkpoint-status,[data-note],[data-rubric],#learnerName,#trainerName,#evaluationDate,#generalObservations').forEach(el=>{el.addEventListener('change',()=>saveProgress(false));el.addEventListener('input',()=>saveProgress(false))});$('#saveProgress').onclick=()=>saveProgress(true);$('#copyReport').onclick=()=>{const r=reportText();$('#reportPreview').textContent=r;copy(r)};$('#downloadTxt').onclick=()=>download('lesson-8-progress-report.txt',reportText());$('#downloadHtml').onclick=()=>download('lesson-8-progress-report.html',reportHtml(),'text/html');$('#printReport').onclick=()=>window.print();$('#resetAll').onclick=()=>{if(confirm('Reset all saved progress for this lesson?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};updateMetrics()}
function initFeedback(){$('#copyFeedback').onclick=()=>copy(feedbackText());$('#downloadFeedback').onclick=()=>download('lesson-8-feedback.txt',feedbackText())}

function init(){if('speechSynthesis'in window){populateVoices();speechSynthesis.onvoiceschanged=populateVoices;setTimeout(populateVoices,500)}renderVocabCategories();renderQuestionConsole();renderRewriteLab();renderScenarios();initQuizzes();initGapFills();initForceMatch();initTimers();initRecorders();bindCommon();initProgress();initFeedback()}
document.addEventListener('DOMContentLoaded',init);
