(() => {
  'use strict';
  const KEY='olivier_israel_medtech_v2';
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const $=(s,r=document)=>r.querySelector(s);
  const sections=$$('.lesson-section');
  const state={sectionIndex:0,sessionSeconds:90*60,sessionTimer:null,quizCorrect:{},sprintIndex:0,sprintSeconds:20,sprintTimer:null,currentModel:'intro'};

  const feedbackText={
    p1:{good:'✓ Exactly. This keeps the expertise credible and transferable without pretending local systems are identical.',bad:'Not quite. Strong international positioning shows transferable expertise while respecting local requirements.'},
    v1:{good:'✓ “Launched” clearly communicates that you opened a new service.',bad:'Think about creating a genuinely new service. “Launched” is the precise executive verb.'},
    v2:{good:'✓ “Secured” works well for obtaining an important accreditation or authorization.',bad:'For an accreditation you successfully obtained, “secured” is stronger and more precise.'},
    v3:{good:'✓ “Drove” shows that you actively created momentum for change.',bad:'The clue is “actively pushed”. “Drove” communicates leadership and momentum.'},
    v4:{good:'✓ “Streamlined” means making a process simpler and more efficient.',bad:'The clue is reduced complexity. “Streamlined” is the executive verb for that result.'},
    g1:{good:'✓ Present perfect connects accumulated career experience to the present.',bad:'Use present perfect for career experience that remains relevant now: “I have managed…”'},
    g2:{good:'✓ Past simple is right for a completed role or achievement in a finished period.',bad:'Because the achievement belongs to a completed 2024–2025 period, use past simple: “led”.'},
    g3:{good:'✓ Present simple expresses the value your experience gives you now.',bad:'This sentence describes a present capability, so use “helps”.'},
    g4:{good:'✓ This is credible: it shows potential contribution without claiming certainty or local expertise you have not yet acquired.',bad:'Avoid absolute claims about a new market. “Could help…” is confident but credible.'},
    cv1:{good:'✓ The second version shows action, scope and concrete outcomes.',bad:'A strong international CV bullet needs evidence, not only responsibility.'},
    cv2:{good:'✓ This explicitly converts healthcare transformation experience into MedTech implementation value.',bad:'The goal is to make the transferable skill visible, not merely mention seniority.'},
    cv3:{good:'✓ Exactly. It presents a strong framework and makes adaptation to local Israeli requirements explicit.',bad:'Do not imply that French experience automatically equals knowledge of Israeli rules or systems.'},
    m1:{good:'✓ Strong. You contribute operational implementation thinking while local regulatory validation stays with the appropriate specialists.',bad:'Your value is operational implementation expertise — not replacing local Israeli regulatory specialists.'},
    m2:{good:'✓ Correct. Your French experience is especially valuable when an Israeli company needs to understand how French hospitals decide, operate and adopt change.',bad:'Your strongest contribution is healthcare-market and operational implementation insight, not engineering or Israeli legal drafting.'},
    m3:{good:'✓ Correct. Adoption is a change-management and workflow issue as much as a technology issue.',bad:'Technology adoption requires workflow, leadership, communication, training and stakeholder alignment.'},
    m4:{good:'✓ Exactly. You see the operational layer between strategy and real-world healthcare delivery.',bad:'Avoid claiming technical expertise you do not need. Your differentiated value is operational healthcare implementation.'},
    m5:{good:'✓ Correct. Cross-border work starts by aligning objectives, roles, decision criteria and local constraints.',bad:'Do not start with assumptions or a long system history. First align the project logic.'},
    m6:{good:'✓ Strong. It connects continuity, learning and future contribution without pretending you already know the local market in depth.',bad:'Position the move as a transfer of expertise plus local learning — not proof of expertise you have not yet acquired.'}
  };

  const vocab=[
    ['leadership','stakeholder alignment','alignement des parties prenantes','Getting people with different interests to work toward the same objective.','Stakeholder alignment is essential before a major transformation.'],
    ['leadership','decision authority','pouvoir décisionnel','Formal responsibility for making or approving decisions.','My previous roles involved significant decision authority.'],
    ['leadership','operational oversight','supervision opérationnelle','Senior-level responsibility for day-to-day operations and performance.','I had operational oversight of several healthcare sites.'],
    ['leadership','change management','conduite du changement','Structured work to help people and organizations adopt change.','Technology implementation requires strong change management.'],
    ['leadership','governance framework','cadre de gouvernance','The roles, rules and decision structures that guide a project or organization.','The pilot needs a clear governance framework.'],
    ['leadership','cross-functional team','équipe pluridisciplinaire','A team made up of people from different functions or specialties.','I am used to leading cross-functional teams.'],
    ['healthcare','patient pathway','parcours patient','The sequence of care and services experienced by a patient.','A new solution should improve the patient pathway, not complicate it.'],
    ['healthcare','care delivery','prestation / organisation des soins','How healthcare services are actually provided.','Digital tools can change the way care is delivered.'],
    ['healthcare','clinical workflow','flux de travail clinique','The practical sequence of tasks performed by clinical staff.','We need to understand the clinical workflow before implementation.'],
    ['healthcare','medical staff recruitment','recrutement médical','Attracting and hiring doctors or other medical professionals.','I have extensive experience in medical staff recruitment.'],
    ['healthcare','quality accreditation','certification qualité','Formal recognition that a healthcare organization meets quality standards.','I have led organizations through demanding quality accreditation processes.'],
    ['healthcare','continuity of care','continuité des soins','Coordinated, uninterrupted care across services or time.','Any change must protect continuity of care.'],
    ['healthcare','capacity planning','planification des capacités','Planning staff, beds, equipment or services to meet demand.','Capacity planning is critical when launching a new service.'],
    ['legal','regulatory requirement','exigence réglementaire','A rule or obligation imposed by the relevant authorities.','Local regulatory requirements must be validated before deployment.'],
    ['legal','risk exposure','exposition au risque','The degree to which an organization may be affected by a risk.','The implementation plan should identify risk exposure early.'],
    ['legal','due diligence','audit préalable / diligence raisonnable','A structured review before a major decision, investment or partnership.','Operational due diligence should include workflow and adoption questions.'],
    ['legal','compliance','conformité','Following applicable laws, standards, policies or rules.','Compliance is one part of implementation, but not the only one.'],
    ['legal','scope of responsibility','périmètre de responsabilité','What a person or team is accountable for.','We should define the scope of responsibility for each partner.'],
    ['legal','contractual obligation','obligation contractuelle','A duty created by a contract.','The team needs to distinguish operational goals from contractual obligations.'],
    ['medtech','implementation pathway','parcours de mise en œuvre','The sequence of steps for introducing a technology into real operations.','I can help structure the implementation pathway from pilot to routine use.'],
    ['medtech','technology adoption','adoption technologique','The process by which people begin to use a new technology effectively.','Technology adoption depends on more than product quality.'],
    ['medtech','pilot programme','programme pilote','A limited real-world test before wider deployment.','A pilot programme should have clear success criteria.'],
    ['medtech','workflow integration','intégration dans les processus','Making a technology fit naturally into existing or redesigned work processes.','Poor workflow integration can block adoption.'],
    ['medtech','clinical validation','validation clinique','Evidence that a solution performs appropriately in a clinical context.','Clinical validation and operational adoption answer different questions.'],
    ['medtech','user acceptance','acceptation par les utilisateurs','The willingness of intended users to adopt a solution.','User acceptance should be measured during the pilot.'],
    ['medtech','deployment','déploiement','Rolling out a solution into real use.','Deployment should be phased when operational risk is high.'],
    ['medtech','scalability','capacité de passage à l’échelle','The ability to grow or expand effectively.','A solution may work in one site but still face scalability challenges.'],
    ['international','transferable expertise','expertise transférable','Knowledge or skills that remain useful in a different context.','Healthcare operations and change management are highly transferable areas of expertise.'],
    ['international','local requirements','exigences locales','Rules, practices or expectations specific to a country or market.','The framework is transferable, but local requirements must be verified.'],
    ['international','market entry','entrée sur un marché','The process of starting commercial activity in a new market.','Hospital decision-making is an important part of MedTech market entry.'],
    ['international','cross-border collaboration','collaboration transfrontalière','Work involving people or organizations in different countries.','Cross-border collaboration requires explicit communication and role clarity.'],
    ['international','cultural expectations','attentes culturelles','Communication or working norms shaped by local professional culture.','Cultural expectations can affect negotiation and decision-making.'],
    ['international','relocation','installation / déménagement international','Moving to live and work in another country.','My relocation is part of a broader international professional transition.'],
    ['startup','value proposition','proposition de valeur','A clear explanation of why a product or service is useful to a target customer.','A hospital value proposition should include operational impact, not only technology features.'],
    ['startup','proof of concept','preuve de concept','An early test showing that an idea can work.','A proof of concept does not automatically prove large-scale adoption.'],
    ['startup','go-to-market strategy','stratégie de mise sur le marché','A plan for reaching customers and building adoption.','Healthcare go-to-market strategy must reflect how hospitals buy and implement solutions.'],
    ['startup','product-market fit','adéquation produit-marché','Evidence that a product solves a real problem for a target market.','Operational feedback can help a startup evaluate product-market fit.'],
    ['startup','implementation partner','partenaire de mise en œuvre','A person or organization helping a solution move into real operation.','An implementation partner can reduce the gap between sales and actual adoption.'],
    ['startup','decision-maker','décideur','A person with authority to approve or influence a decision.','The clinical user and the economic decision-maker may not be the same person.'],
    ['startup','adoption barrier','frein à l’adoption','A factor that prevents or slows acceptance and use.','Workflow complexity can become a major adoption barrier.']
  ];

  const sprints=[
    {cat:'Positioning',q:'What is the strongest reason an international MedTech company should speak with you?',m:'I bring more than twenty years of healthcare leadership experience. I have led complex hospital operations, transformation and quality programmes. That gives me a practical understanding of what healthcare organizations need before a new solution can be adopted successfully.'},
    {cat:'Israel transition',q:'Why are you interested in building the next stage of your career in Israel?',m:'I am preparing an international transition to Israel and I want to combine my healthcare leadership experience with a more innovation-driven environment. My objective is to learn the local ecosystem while contributing operational and strategic expertise.'},
    {cat:'Transferable value',q:'How is your French hospital experience relevant outside France?',m:'The rules and systems are different, but many operational challenges are transferable: stakeholder alignment, quality, risk, patient pathways, implementation and change management. I would adapt that framework to the local context rather than assume the systems are identical.'},
    {cat:'MedTech',q:'What can make a strong healthcare technology fail during implementation?',m:'A strong technology can fail if it does not fit clinical workflows or if users do not understand the value. Clear governance, training, stakeholder involvement and follow-up are essential for adoption.'},
    {cat:'Law & risk',q:'How does your legal background strengthen your healthcare leadership profile?',m:'My legal background trained me to analyse responsibility, risk and constraints precisely. In healthcare leadership, that helps me ask the right questions and balance operational objectives with quality, governance and compliance.'},
    {cat:'Startup',q:'What would you ask a startup before discussing a hospital pilot?',m:'I would first ask what problem the solution solves, who the users and decision-makers are, how it changes workflow, what evidence already exists and what success would look like. Then we can discuss implementation risks and the pilot design.'},
    {cat:'Cross-border',q:'How would you work with U.S., Israeli and French stakeholders on the same project?',m:'I would begin by aligning the objective, roles and decision criteria. Then I would identify local constraints and make sure key terms and expectations are understood in the same way across the teams.'},
    {cat:'Executive story',q:'In one short answer, what is the next chapter of your career?',m:'My next chapter is international healthcare and MedTech. I want to use my experience in hospital leadership, transformation and strategic decision-making in Israel while building bridges with international healthcare and technology partners.'}
  ];

  const models={
    intro:{title:'30-second international introduction',text:'I am a senior healthcare executive with more than twenty years of experience leading hospitals, multi-site operations and transformation projects in France. My background also includes law and strategic intelligence, which helps me approach healthcare decisions from operational, risk and stakeholder perspectives. I am now preparing a move to Israel and I am particularly interested in healthcare innovation, MedTech and international projects where I can bring practical implementation experience.',why:'It follows a simple sequence: senior identity → evidence → differentiator → future direction. Israel is clearly part of the future story, while France remains the evidence base.'},
    startup:{title:'Model — conversation with a U.S. MedTech startup',text:'My value would be at the point where technology meets healthcare operations. I have spent more than twenty years managing hospitals and transformation programmes, so I understand how clinical teams, management, quality requirements, workflows and financial constraints interact. If you are preparing a pilot in Israel, I could help structure the operational questions, stakeholder map and adoption risks, while local regulatory requirements would of course need to be validated by the appropriate Israeli specialists.',why:'This model avoids the old France-only implementation scenario. It positions you in Israel, uses your operational expertise and explicitly respects local regulatory expertise.'},
    israel:{title:'Model — “Why Israel?”',text:'I see Israel as the next stage of my professional career, not as a complete change of direction. I want to bring my experience in healthcare leadership, change management and e-health into a new environment and learn the local system in depth. I am particularly interested in organizations that connect healthcare delivery with innovation, because that is where my operational background can add value.',why:'It communicates motivation without pretending you already know the market. It also creates continuity between your previous career and your relocation.'},
    bridge:{title:'Model — your cross-border value',text:'I can act as a bridge between innovation and healthcare reality. For an Israeli company looking at Europe, I understand how French hospitals make decisions and what can slow adoption. For an international company working in Israel, I bring a structured way of looking at implementation, stakeholder alignment, quality, risk and operations. I would not assume that one system can simply be copied into another; my role would be to identify what is transferable and what must be adapted locally.',why:'This is the strongest international positioning because it makes your French expertise useful in both directions and builds credibility through nuance.'}
  };

  function init(){makeDots();bindNav();bindHeader();bindSessionTimer();bindSpeech();renderVocab();bindVocab();bindQuizzes();bindCvBuilder();bindSprint();bindModels();bindSave();bindResets();bindReport();restore();updateSprint();updateModel();updateScores();showSection(state.sectionIndex,false)}
  document.addEventListener('DOMContentLoaded',init);

  function makeDots(){const nav=$('#stepDots');sections.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.textContent=i+1;b.title=s.dataset.title||`Section ${i+1}`;b.addEventListener('click',()=>showSection(i));nav.appendChild(b)})}
  function showSection(i,scroll=true){state.sectionIndex=i;sections.forEach((s,j)=>s.classList.toggle('active',i===j));$('#progressBar').style.width=`${((i+1)/sections.length)*100}%`;$('#progressLabel').textContent=sections[i]?.dataset.title||'';$$('#stepDots button').forEach((b,j)=>b.classList.toggle('active',i===j));save();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
  function bindNav(){$$('[data-next]').forEach(b=>b.addEventListener('click',()=>showSection(Math.min(state.sectionIndex+1,sections.length-1))));$('#backTop')?.addEventListener('click',()=>showSection(0))}
  function bindHeader(){$('#translationToggle').addEventListener('click',()=>{const on=document.body.classList.toggle('show-fr');const b=$('#translationToggle');b.classList.toggle('active',on);b.textContent=on?'FR help · ON':'FR help · OFF';b.setAttribute('aria-pressed',String(on));save()});$('#printButton').addEventListener('click',()=>window.print())}
  function bindSessionTimer(){$('#timerStart').addEventListener('click',()=>{if(state.sessionTimer)return;state.sessionTimer=setInterval(()=>{state.sessionSeconds=Math.max(0,state.sessionSeconds-1);renderSessionTimer();if(state.sessionSeconds===0){clearInterval(state.sessionTimer);state.sessionTimer=null;toast('Time — finish with one clear takeaway.')}},1000)});$('#timerPause').addEventListener('click',()=>{if(state.sessionTimer){clearInterval(state.sessionTimer);state.sessionTimer=null}});$('#timerReset').addEventListener('click',()=>{if(state.sessionTimer)clearInterval(state.sessionTimer);state.sessionTimer=null;state.sessionSeconds=90*60;renderSessionTimer();save()});renderSessionTimer()}
  function renderSessionTimer(){const m=String(Math.floor(state.sessionSeconds/60)).padStart(2,'0');const s=String(state.sessionSeconds%60).padStart(2,'0');$('#sessionTimer').textContent=`${m}:${s}`}

  function speak(text,rate=1){if(!('speechSynthesis'in window))return toast('Speech synthesis is not available in this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=$('#accentSelect')?.value||'en-US';u.rate=rate;const voices=speechSynthesis.getVoices();const exact=voices.find(v=>v.lang===u.lang)||voices.find(v=>v.lang.startsWith(u.lang.slice(0,2)));if(exact)u.voice=exact;speechSynthesis.speak(u)}
  function bindSpeech(){$$('.speak-button').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.speak||'',b.dataset.rate?Number(b.dataset.rate):1)))}

  function renderVocab(){const filter=$('#vocabFilter')?.value||'all';const term=($('#vocabSearch')?.value||'').trim().toLowerCase();const list=vocab.filter(v=>(filter==='all'||v[0]===filter)&&(!term||v.join(' ').toLowerCase().includes(term)));$('#vocabCount').textContent=list.length;$('#vocabGrid').innerHTML=list.map((v,i)=>`<article class="vocab-card"><div class="vocab-top"><span class="cat">${escapeHtml(v[0])}</span><button type="button" data-vocab-speak="${escapeAttr(v[1])}">🔊 Listen</button></div><h3>${escapeHtml(v[1])}</h3><div class="fr-word">${escapeHtml(v[2])}</div><p>${escapeHtml(v[3])}</p><p class="ex">${escapeHtml(v[4])}</p></article>`).join('');$$('[data-vocab-speak]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.vocabSpeak)))}
  function bindVocab(){$('#vocabFilter').addEventListener('change',renderVocab);$('#vocabSearch').addEventListener('input',renderVocab)}

  function bindQuizzes(){$$('.quiz-item').forEach(item=>$$('button[data-choice]',item).forEach(btn=>btn.addEventListener('click',()=>grade(item,btn))))}
  function grade(item,btn){const qid=item.dataset.qid,ans=item.dataset.answer,choice=btn.dataset.choice;$$('button[data-choice]',item).forEach(b=>b.classList.remove('correct','wrong'));const correct=choice===ans;btn.classList.add(correct?'correct':'wrong');if(!correct){const good=$(`button[data-choice="${ans}"]`,item);good?.classList.add('correct')}state.quizCorrect[qid]=correct;const fb=$('.feedback',item);if(fb){fb.textContent=(feedbackText[qid]?.[correct?'good':'bad'])||(correct?'✓ Correct':'Try again.');fb.className=`feedback ${correct?'good':'bad'}`}save();updateScores()}

  function bindCvBuilder(){$('#buildCv').addEventListener('click',()=>{const a=$('#cvAction').value,s=$('#cvScope').value.trim(),o=$('#cvOutcome').value.trim();if(!s||!o)return toast('Add both the scope and the outcome first.');$('#cvBuilderOutput').textContent=`${a} ${s}, ${o.replace(/^./,c=>c.toLowerCase())}.`;save()})}

  function bindSprint(){$('#nextSprint').addEventListener('click',()=>{state.sprintIndex=(state.sprintIndex+1)%sprints.length;resetSprintTimer();updateSprint();save()});$('#showSprintModel').addEventListener('click',()=>{const box=$('#sprintModel');box.hidden=!box.hidden;if(!box.hidden)box.innerHTML=`<strong>Coaching model</strong><p>${escapeHtml(sprints[state.sprintIndex].m)}</p><button class="mini-button" id="listenSprint">🔊 Listen</button>`;$('#listenSprint')?.addEventListener('click',()=>speak(sprints[state.sprintIndex].m))});$('#sprintStart').addEventListener('click',()=>{if(state.sprintTimer)return;state.sprintTimer=setInterval(()=>{state.sprintSeconds=Math.max(0,state.sprintSeconds-1);renderSprintTimer();if(state.sprintSeconds===0){clearInterval(state.sprintTimer);state.sprintTimer=null;toast('20 seconds — finish with your relevance sentence.')}},1000)});$('#sprintReset').addEventListener('click',resetSprintTimer)}
  function updateSprint(){const x=sprints[state.sprintIndex];$('#sprintCount').textContent=`${state.sprintIndex+1} / ${sprints.length}`;$('#sprintCategory').textContent=x.cat;$('#sprintPrompt').textContent=x.q;$('#sprintModel').hidden=true;resetSprintTimer()}
  function resetSprintTimer(){if(state.sprintTimer)clearInterval(state.sprintTimer);state.sprintTimer=null;state.sprintSeconds=20;renderSprintTimer()}
  function renderSprintTimer(){$('#sprintTimer').textContent=`00:${String(state.sprintSeconds).padStart(2,'0')}`}

  function bindModels(){$$('.model-tab').forEach(b=>b.addEventListener('click',()=>{state.currentModel=b.dataset.model;updateModel();save()}));$('#listenModel').addEventListener('click',()=>speak(models[state.currentModel].text,1));$('#slowerModel').addEventListener('click',()=>speak(models[state.currentModel].text,.84))}
  function updateModel(){const m=models[state.currentModel];$$('.model-tab').forEach(b=>b.classList.toggle('active',b.dataset.model===state.currentModel));$('#modelPanel').innerHTML=`<h3>${escapeHtml(m.title)}</h3><p>${escapeHtml(m.text)}</p>`;$('#modelWhy').textContent=m.why;$('#modelWhyTitle').textContent=state.currentModel==='startup'?'International credibility':state.currentModel==='bridge'?'Transfer without overclaiming':'Structure before detail'}

  function bindSave(){$$('[data-save]').forEach(el=>{el.addEventListener('input',save);el.addEventListener('change',()=>{save();if(el.id==='confidenceSlider')updateConfidence()})});$$('input[data-check-score]').forEach(cb=>cb.addEventListener('change',()=>{save();updateScores()}));updateConfidence()}
  function save(){const data={sectionIndex:state.sectionIndex,sessionSeconds:state.sessionSeconds,quizCorrect:state.quizCorrect,sprintIndex:state.sprintIndex,currentModel:state.currentModel,showFr:document.body.classList.contains('show-fr'),fields:{},checks:{}};$$('[data-save]').forEach(el=>data.fields[el.dataset.save]=el.value);$$('input[data-check-score]').forEach((el,i)=>data.checks[i]=el.checked);try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}}
  function restore(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d)return;state.sectionIndex=Math.min(Number(d.sectionIndex)||0,sections.length-1);state.sessionSeconds=Number.isFinite(d.sessionSeconds)?d.sessionSeconds:90*60;state.quizCorrect=d.quizCorrect||{};state.sprintIndex=Math.min(Number(d.sprintIndex)||0,sprints.length-1);state.currentModel=models[d.currentModel]?d.currentModel:'intro';document.body.classList.toggle('show-fr',d.showFr!==false);const tb=$('#translationToggle');tb.classList.toggle('active',d.showFr!==false);tb.textContent=d.showFr===false?'FR help · OFF':'FR help · ON';$$('[data-save]').forEach(el=>{if(d.fields&&d.fields[el.dataset.save]!==undefined)el.value=d.fields[el.dataset.save]});$$('input[data-check-score]').forEach((el,i)=>el.checked=!!(d.checks&&d.checks[i]));$$('.quiz-item').forEach(item=>{if(state.quizCorrect[item.dataset.qid]){const good=$(`button[data-choice="${item.dataset.answer}"]`,item);good?.classList.add('correct');const fb=$('.feedback',item);if(fb){fb.textContent=feedbackText[item.dataset.qid]?.good||'✓ Correct';fb.className='feedback good'}}});renderSessionTimer();updateConfidence();updateSprint();updateModel()}catch(e){}}

  function bindResets(){$$('.reset-section').forEach(btn=>btn.addEventListener('click',()=>{const sec=btn.closest('.lesson-section');if(!sec)return;$$('textarea,input,select',sec).forEach(el=>{if(el.matches('[type="checkbox"]'))el.checked=false;else if(el.matches('[type="range"]'))el.value=el.defaultValue||5;else if(el.tagName==='SELECT')el.selectedIndex=0;else if(!['vocabSearch'].includes(el.id))el.value=''});$$('.quiz-item',sec).forEach(item=>{$$('button[data-choice]',item).forEach(b=>b.classList.remove('correct','wrong'));const fb=$('.feedback',item);if(fb){fb.textContent='';fb.className='feedback'}delete state.quizCorrect[item.dataset.qid]});if(sec.id==='sprint'){state.sprintIndex=0;updateSprint()}if(sec.id==='models'){state.currentModel='intro';updateModel()}if(sec.id==='vocab'){renderVocab()}updateConfidence();save();updateScores();toast('Section reset.')}));$('#resetAll').addEventListener('click',()=>{if(!confirm('Reset the whole lesson and delete saved progress?'))return;localStorage.removeItem(KEY);location.reload()})}

  function scoresBySkill(){const out={positioning:[0,0],verbs:[0,0],grammar:[0,0],cv:[0,0],medtech:[0,0]};$$('.quiz-item').forEach(item=>{const s=item.dataset.skill;if(out[s]){out[s][1]++;if(state.quizCorrect[item.dataset.qid])out[s][0]++}});return out}
  function updateScores(){const by=scoresBySkill();set('scorePositioning',fmt(by.positioning));set('scoreVerbs',fmt(by.verbs));set('scoreGrammar',fmt(by.grammar));set('scoreCv',fmt(by.cv));set('scoreMedtech',fmt(by.medtech));const manual=$$('input[data-check-score]:checked').length,manualTotal=$$('input[data-check-score]').length;const c=Object.values(by).reduce((a,x)=>a+x[0],0)+manual,t=Object.values(by).reduce((a,x)=>a+x[1],0)+manualTotal;set('scoreTop',`${c} / ${t}`);updateReportPreview()}
  function fmt(x){return `${x[0]} / ${x[1]}`}function set(id,text){const el=$('#'+id);if(el)el.textContent=text}
  function updateConfidence(){if($('#confidenceValue')&&$('#confidenceSlider'))$('#confidenceValue').textContent=`${$('#confidenceSlider').value} / 10`}

  function bindReport(){$('#confidenceSlider').addEventListener('input',()=>{updateConfidence();save();updateReportPreview()});$('#copyReport').addEventListener('click',()=>copyText(buildReportText()));$('#downloadReport').addEventListener('click',downloadReport);$('#printReport').addEventListener('click',()=>window.print())}
  function buildReportText(){const by=scoresBySkill(),statuses=$$('.manual-panel select').map(s=>`${s.parentElement.childNodes[0].textContent.trim()}: ${s.value}`);return `OLIVIER PELIKS — EXECUTIVE HEALTHCARE ENGLISH\nFrance → Israel · MedTech · International positioning\n\nOBJECTIVES\n• Position French healthcare leadership experience for an international / Israeli context.\n• Use stronger executive verbs with accurate meaning.\n• Distinguish past evidence, career experience, present value and future contribution.\n• Explain transferable expertise without overclaiming local-market knowledge.\n• Handle MedTech implementation and cross-border scenarios.\n• Transfer professional structures to CLOE speaking and writing.\n\nAUTOMATIC PRACTICE\nPositioning: ${fmt(by.positioning)}\nPower verbs: ${fmt(by.verbs)}\nGrammar: ${fmt(by.grammar)}\nCV precision: ${fmt(by.cv)}\nMedTech transfer: ${fmt(by.medtech)}\n\nTRAINER STATUS\n${statuses.join('\n')}\n\nSTRENGTHS\n${$('[data-save="report-strengths"]').value.trim()||'—'}\n\nPOINTS TO REINFORCE\n${$('[data-save="report-focus"]').value.trim()||'—'}\n\nNEXT LESSON PRIORITY\n${$('[data-save="report-next"]').value.trim()||'—'}\n\nCONFIDENCE — INTERNATIONAL PROFESSIONAL VALUE\n${$('#confidenceSlider').value} / 10\n\nCORE POSITIONING\nFrench healthcare leadership is the evidence base. Israel is the forward-looking professional context. International MedTech work connects both through implementation, operations, change management, quality, risk and stakeholder alignment.`}
  function updateReportPreview(){if($('#reportPreview'))$('#reportPreview').textContent=buildReportText()}
  function downloadReport(){const text=buildReportText();const html=`<!doctype html><html><head><meta charset="utf-8"><title>Olivier Peliks Lesson Report</title><style>body{font-family:Arial,sans-serif;background:#f6fbfa;color:#183038;margin:0}.page{max-width:900px;margin:30px auto;background:#fff;border:1px solid #dceae7;border-radius:18px;overflow:hidden}.head{background:#071821;color:#fff;padding:26px;border-bottom:5px solid #15b8a6}.body{padding:26px}pre{white-space:pre-wrap;font:14px/1.6 Arial,sans-serif}.foot{padding:18px 26px;background:#071821;color:#bdd3d5;font-size:12px}</style></head><body><div class="page"><div class="head"><h1>Executive Healthcare English</h1><p>France → Israel · MedTech · International positioning</p></div><div class="body"><pre>${escapeHtml(text)}</pre></div><div class="foot">SpeakEasyTisha · Qualiopi progress evidence</div></div></body></html>`;const blob=new Blob([html],{type:'text/html;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Olivier-Peliks-Progress-Report.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800);toast('HTML report downloaded.')}
  async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Report copied.')}catch(e){toast('Copy is not available in this browser.')}}

  function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),2200)}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#096;')}
})();
