(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='mamadou_lesson1_v2_persistent';
const DEFAULT={accent:'GB',french:false,answers:{},order:{},repair:{},manual:{},objectives:[],homework:[],fields:{},checks:{},reportFields:{},grammarMicro:{}};
let state=Object.assign({},DEFAULT,load());

function load(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return {}}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state))}catch(e){} updateScore();updateReport();}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),1700)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function norm(s=''){return String(s).toLowerCase().replace(/[’']/g,"'").replace(/[.,!?;:]/g,'').replace(/\s+/g,' ').trim()}
function pct(a,b){return b?Math.round(a/b*100):0}
function dateText(){return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
function confirmReset(msg){return window.confirm(msg)}

const quizData={
 diagnostic:[
  {q:'Choose the correct sentence for your usual job.',o:['I am work in railway safety.','I work in railway safety.','I working in railway safety.'],a:1,why:'A usual job is a stable situation → present simple.',fr:'Pour votre activité habituelle : I work.'},
  {q:'You are studying for the CLOE this week. Choose the best form.',o:['I study for the CLOE this week.','I am studying for the CLOE this week.','I have study for the CLOE.'],a:1,why:'This week describes a temporary current period → present continuous.',fr:'Cette semaine = période temporaire actuelle → present continuous.'},
  {q:'Complete: I ___ in this field for several years.',o:['work','am working','have worked'],a:2,why:'For + duration connected to now → present perfect.',fr:'for + durée jusqu’à maintenant → present perfect.'},
  {q:'Which word means a source or situation that can cause harm?',o:['hazard','schedule','meeting'],a:0,why:'A hazard is a source or situation with the potential to cause harm.',fr:'hazard = danger / source de danger.'},
  {q:'Choose the best professional question.',o:['What means this procedure?','What does this procedure mean?','What this procedure means?'],a:1,why:'Present simple question: What + does + subject + base verb?',fr:'Question au présent simple : What does + sujet + verbe ?'},
  {q:'Choose the correct obligation.',o:['Employees must wear the required PPE.','Employees must to wear the required PPE.','Employees must wearing the required PPE.'],a:0,why:'After must, use the base verb without to.',fr:'Après must : verbe sans to.'},
  {q:'Choose the clearest connector: “The route was blocked, ___ the team used another access point.”',o:['because','so','although'],a:1,why:'So introduces a consequence.',fr:'so = donc / conséquence.'},
  {q:'If you do not understand an oral question, what is the best strategy?',o:['Stay silent.','Guess quickly.','Ask the examiner to repeat or rephrase.'],a:2,why:'Clarification keeps the interaction active.',fr:'Demander de répéter ou reformuler maintient l’échange.'},
  {q:'Which sentence describes a finished event?',o:['I have checked the area since 9 a.m.','I checked the area yesterday.','I am checking the area every day.'],a:1,why:'Yesterday is a finished past time → past simple.',fr:'yesterday = période passée terminée → past simple.'},
  {q:'Choose the decided future plan.',o:['I am going to continue my studies next year.','I continued my studies next year.','I have continue my studies.'],a:0,why:'Going to is suitable for a plan already decided.',fr:'going to = projet déjà décidé.'}
 ],
 present:[
  {q:'You ___ risk assessments before major work starts.',o:['usually review','are usually reviewing','usually reviewing'],a:0,why:'Usually = routine → present simple.',fr:'usually = habitude → présent simple.'},
  {q:'At the moment, you ___ for the CLOE.',o:['prepare','are preparing','have prepare'],a:1,why:'At the moment = now → present continuous.',fr:'at the moment = maintenant → présent continu.'},
  {q:'Your team ___ a safety meeting every Monday.',o:['has','is having','have'],a:0,why:'Every Monday = regular schedule → present simple.',fr:'every Monday = habitude.'},
  {q:'Today, your team ___ a new environmental procedure.',o:['tests','is testing','test'],a:1,why:'Today + temporary current activity → present continuous.',fr:'today = activité temporaire actuelle.'},
  {q:'You ___ in safety and environmental risk management.',o:['are work','work','are working every day'],a:1,why:'Use present simple to state your professional field.',fr:'Pour votre métier : I work in…'},
  {q:'Why ___ you ___ English now?',o:['do / learn','are / learning','have / learn'],a:1,why:'Now → present continuous question.',fr:'now → Why are you learning…?'},
  {q:'You normally ___ access routes before work begins.',o:['check','are checking','checks'],a:0,why:'Normally = routine.',fr:'normally = habitude.'},
  {q:'This week, you ___ more English than usual.',o:['practise','are practising','practises'],a:1,why:'This week = temporary current period.',fr:'this week = période temporaire actuelle.'},
  {q:'Choose the sentence about a regular responsibility.',o:['I am reporting incidents now.','I report incidents when necessary.','I have reporting incidents.'],a:1,why:'A regular responsibility uses the present simple.',fr:'Une responsabilité habituelle utilise le présent simple.'},
  {q:'Choose the sentence about what is happening now.',o:['I check the barrier every morning.','I am checking the barrier right now.','I have checked the barrier every morning.'],a:1,why:'Right now is a strong present continuous signal.',fr:'right now = présent continu.'}
 ],
 perfect:[
  {q:'You ___ in this field for several years.',o:['work','have worked','worked last year'],a:1,why:'For + duration continuing to now → present perfect.',fr:'for + durée jusqu’au présent.'},
  {q:'You have worked in the railway sector ___ 2022.',o:['for','since','ago'],a:1,why:'Since + starting point.',fr:'since + point de départ.'},
  {q:'You have worked in this role ___ four years.',o:['since','for','last'],a:1,why:'For + duration.',fr:'for + durée.'},
  {q:'___ you ever ___ a near miss?',o:['Did / report yesterday','Have / reported','Are / report'],a:1,why:'Ever commonly introduces life experience → present perfect.',fr:'ever = expérience jusqu’à maintenant.'},
  {q:'You ___ a safety incident last month.',o:['have reported','reported','report since'],a:1,why:'Last month is a finished past time → past simple.',fr:'last month = passé terminé.'},
  {q:'You ___ the new procedure already.',o:['have reviewed','reviewed yesterday already','are review'],a:0,why:'Already often works with present perfect for a completed action connected to now.',fr:'already est souvent utilisé avec le present perfect.'},
  {q:'The team ___ the action plan yet.',o:['has not finished','did not finished','is not finish'],a:0,why:'Yet commonly appears with present perfect negatives/questions.',fr:'yet est fréquent avec le present perfect.'},
  {q:'Two days ago, you ___ the work area.',o:['have inspected','inspected','have inspect'],a:1,why:'Ago marks a finished past time.',fr:'ago → passé simple.'},
  {q:'Choose the correct pair.',o:['for 2022 / since three years','for three years / since 2022','for yesterday / since two hours'],a:1,why:'For + duration; since + starting point.',fr:'for + durée ; since + point de départ.'},
  {q:'So far, you ___ several key safety terms.',o:['learned yesterday','have learned','are learn'],a:1,why:'So far connects past progress to now.',fr:'so far = jusqu’à présent → present perfect.'}
 ],
 future:[
  {q:'You have decided to continue your studies. You ___ do a master’s degree.',o:['are going to','will yesterday','have going to'],a:0,why:'A decided intention uses going to.',fr:'Projet déjà décidé → going to.'},
  {q:'I think stronger English ___ help you professionally.',o:['is helping yesterday','will','has'],a:1,why:'I think + prediction → will.',fr:'I think + prédiction → will.'},
  {q:'You see a new hazard and decide immediately: “I ___ report it now.”',o:['am going to planned','will','have'],a:1,why:'An immediate decision can use will.',fr:'Décision immédiate → will.'},
  {q:'Next week, you ___ practise professional questions every day; this is already in your plan.',o:['are going to','were','have'],a:0,why:'Already planned → going to.',fr:'Projet prévu → going to.'},
  {q:'This control measure ___ probably reduce the risk.',o:['will','is yesterday','has'],a:0,why:'Probably signals a prediction → will.',fr:'probably = prédiction → will.'},
  {q:'You have booked your next training session. You ___ meet your trainer on Friday.',o:['are going to','will have yesterday','did'],a:0,why:'Arrangement/decided plan → going to is appropriate here.',fr:'Projet déjà prévu → going to.'},
  {q:'Choose the correct form after will.',o:['will to reduce','will reducing','will reduce'],a:2,why:'After will, use the base verb.',fr:'Après will : base verbale.'},
  {q:'Choose the correct going to structure.',o:['I going to study','I am going to study','I am go to studying'],a:1,why:'am/is/are + going to + base verb.',fr:'am/is/are + going to + verbe.'}
 ],
 reading:[
  {q:'What was the main problem?',o:['A person was injured.','A barrier was too close to an access route.','A vehicle broke down.'],a:1,why:'The barrier position created the potential risk.',fr:'Le problème principal était la position de la barrière.'},
  {q:'What type of event was recorded?',o:['A near miss','A serious accident','An environmental spill'],a:0,why:'Nobody was injured, but there was a potential collision risk.',fr:'Il s’agissait d’un presqu’accident.'},
  {q:'What did the supervisor do first?',o:['Ignored the problem.','Stopped the operation.','Called an external company.'],a:1,why:'The text says the supervisor stopped the operation.',fr:'Le superviseur a arrêté l’opération.'},
  {q:'Why was a review organised?',o:['To punish the team.','To understand the cause and prevent recurrence.','To change the maintenance vehicle.'],a:1,why:'The review focused on the cause and prevention.',fr:'Comprendre la cause et éviter la répétition.'},
  {q:'What cause did the team identify?',o:['The vehicle was too old.','The work area had not been checked carefully enough.','The supervisor was absent.'],a:1,why:'The text states that the work area had not been checked carefully enough.',fr:'La zone de travail n’avait pas été suffisamment vérifiée.'},
  {q:'What preventive action was agreed?',o:['Close the site permanently.','Verify access routes before each maintenance task.','Remove all vehicles from the company.'],a:1,why:'The team agreed to verify access routes before each maintenance task.',fr:'Vérifier les voies d’accès avant chaque tâche.'}
 ],
 listening:[
  {q:'What is the main risk today?',o:['Bad weather','Vehicle movement near the maintenance area','Electrical work'],a:1,why:'The briefing identifies vehicle movement as the main risk.',fr:'Le risque principal est la circulation de véhicules.'},
  {q:'Where should you walk?',o:['On the marked pedestrian route','Anywhere outside the track','In the access lane'],a:0,why:'The speaker says to use the marked pedestrian route.',fr:'Utilisez le chemin piéton balisé.'},
  {q:'What should you do if you notice a new hazard?',o:['Wait until lunch.','Stop, keep a safe distance and report it.','Move it alone immediately.'],a:1,why:'Those three actions are explicitly stated.',fr:'Arrêter, garder une distance sûre et signaler.'},
  {q:'When will changes to the work area be reviewed?',o:['At nine o’clock','At eleven o’clock','At the end of the week'],a:1,why:'The briefing says eleven o’clock.',fr:'À onze heures.'},
  {q:'What must remain clear?',o:['The access lane','The lunch room','The office door'],a:0,why:'The briefing says to keep the access lane clear.',fr:'La voie d’accès doit rester libre.'},
  {q:'Who should receive the hazard report?',o:['Your supervisor','A passenger','Nobody'],a:0,why:'The speaker says to report it to your supervisor.',fr:'Signalez le danger à votre superviseur.'}
 ]
};

const orderData=[
 {words:['every','morning,','You','check','the','access','route.'],answer:'You check the access route every morning.'},
 {words:['currently','You','are','preparing','for','the','CLOE.'],answer:'You are currently preparing for the CLOE.'},
 {words:['several','years.','You','have','worked','in','this','field','for'],answer:'You have worked in this field for several years.'},
 {words:['Yesterday,','you','reported','a','new','hazard.'],answer:'Yesterday, you reported a new hazard.'},
 {words:['next','year.','You','are','going','to','continue','your','studies'],answer:'You are going to continue your studies next year.'},
 {words:['immediately.','You','should','report','a','new','hazard'],answer:'You should report a new hazard immediately.'},
 {words:['before','work','starts.','You','usually','assess','the','risks'],answer:'You usually assess the risks before work starts.'},
 {words:['The','team','will','review','the','area','at','eleven','o’clock.'],answer:'The team will review the area at eleven o’clock.'}
];

const repairData=[
 {bad:'I am work in railway safety.',good:'I work in railway safety.',why:'Use present simple for your usual professional field.'},
 {bad:'I work here since three years.',good:'I have worked here for three years.',why:'Use present perfect + for + duration.'},
 {bad:'Yesterday I have reported a hazard.',good:'Yesterday I reported a hazard.',why:'Yesterday is a finished past time → past simple.'},
 {bad:'I am going continue my studies next year.',good:'I am going to continue my studies next year.',why:'Structure: am/is/are + going to + base verb.'},
 {bad:'Employees must to wear PPE.',good:'Employees must wear PPE.',why:'After must, use the base verb without to.'},
 {bad:'What means this procedure?',good:'What does this procedure mean?',why:'Present simple question: does + subject + base verb.'}
];

const grammar=[
 {cat:'Sentence foundations',name:'Basic word order',icon:'🧱',level:'A1→B1',def:'English normally follows Subject + Verb + Object. Add place and time after the main information.',fr:'Ordre de base : Sujet + Verbe + Complément. Puis lieu et temps.',keys:'Subject + verb + object + place + time',ex:'You review safety procedures at work every week.',tip:'Keep the main message together before adding place and time.',prompt:'Put in order: every day / you / risks / review',ans:'you review risks every day'},
 {cat:'Present tenses',name:'Present simple',icon:'🔁',level:'A1→A2',def:'Use it for routines, facts, responsibilities and permanent situations.',fr:'Habitudes, faits, responsabilités, situations stables.',keys:'usually · always · often · every… · normally · on Mondays',ex:'You usually analyse operational risks before work starts.',tip:'With I/you/we/they, use the base verb.',prompt:'Complete: You usually ___ risks before work. (review)',ans:'review'},
 {cat:'Present tenses',name:'Present continuous',icon:'⏳',level:'A1→A2',def:'Use am/is/are + verb-ing for actions happening now or temporary current situations.',fr:'am/is/are + -ing : action en cours ou situation temporaire.',keys:'now · right now · at the moment · today · this week · currently',ex:'You are currently preparing for the CLOE.',tip:'Do not use am/is/are before a present-simple main verb.',prompt:'Complete: You ___ ___ for the CLOE now. (prepare)',ans:'are preparing'},
 {cat:'Past & experience',name:'Past simple',icon:'↩️',level:'A2',def:'Use it for finished actions at a finished past time.',fr:'Actions terminées dans une période passée terminée.',keys:'yesterday · last… · …ago · in 2024 · when I was…',ex:'Last week, you reported a near miss.',tip:'A finished time marker usually excludes the present perfect.',prompt:'Complete: Yesterday, you ___ a hazard. (identify)',ans:'identified'},
 {cat:'Past & experience',name:'Present perfect',icon:'🧭',level:'A2→B1',def:'Use have/has + past participle for experience or a situation connected to now.',fr:'have/has + participe passé : expérience ou situation liée au présent.',keys:'for · since · already · yet · ever · never · so far · recently',ex:'You have worked in this field for several years.',tip:'Use for + duration and since + starting point.',prompt:'Complete: You ___ ___ here for three years. (work)',ans:'have worked'},
 {cat:'Future',name:'Going to',icon:'🗓️',level:'A2',def:'Use be going to + verb for intentions and plans already decided.',fr:'Intention ou projet déjà décidé.',keys:'tomorrow · next… · this weekend · I plan to… · I intend to…',ex:'You are going to continue your studies next year.',tip:'Form: am/is/are + going to + base verb.',prompt:'Complete: You ___ going to continue your studies.',ans:'are'},
 {cat:'Future',name:'Will',icon:'🔭',level:'A2→B1',def:'Use will + verb for predictions, instant decisions and future results.',fr:'Prédictions, décisions spontanées et résultats futurs.',keys:'I think · probably · maybe · I’m sure · in the future',ex:'This action will reduce the risk.',tip:'After will, use the base verb.',prompt:'Complete: This action ___ reduce the risk.',ans:'will'},
 {cat:'Modal verbs',name:'Must / should',icon:'🦺',level:'A2→B1',def:'Must expresses strong obligation. Should expresses advice or recommended action.',fr:'must = obligation forte ; should = conseil / recommandation.',keys:'must + base verb · should + base verb',ex:'You must wear PPE. You should report a new hazard immediately.',tip:'Never add to after must or should.',prompt:'Complete: You ___ report a new hazard. (recommendation)',ans:'should'}
];

const vocab=[
 ['Safety','hazard','danger / source de danger','A source or situation with the potential to cause harm.','You should report a new hazard immediately.'],
 ['Safety','risk','risque','The combination of likelihood and possible consequence.','You assess the risk before choosing a control measure.'],
 ['Safety','control measure','mesure de maîtrise / prévention','An action used to reduce or control a risk.','A barrier can be a control measure.'],
 ['Safety','near miss','presqu’accident','An event that could have caused harm but did not.','You should record a near miss and review the cause.'],
 ['Safety','incident','incident','An unplanned event that may affect safety or operations.','The incident was reported to the supervisor.'],
 ['Safety','PPE','EPI','Personal protective equipment used to reduce exposure to hazards.','You must wear the required PPE.'],
 ['Risk','risk assessment','évaluation des risques','A structured process used to identify hazards and evaluate risks.','You carry out a risk assessment before major work.'],
 ['Risk','likelihood','probabilité','How likely it is that an event will happen.','The likelihood is low, but the consequence could be serious.'],
 ['Risk','consequence','conséquence','The result or impact of an event.','You consider both likelihood and consequence.'],
 ['Risk','preventive action','action préventive','An action taken to stop a problem from occurring.','The team agreed on a preventive action.'],
 ['Environment','spill','déversement / fuite','An accidental release of liquid or another substance.','You must report an environmental spill immediately.'],
 ['Environment','waste','déchets','Material that is discarded after use.','You separate hazardous waste from general waste.'],
 ['Environment','emissions','émissions','Substances released into the air.','The company monitors emissions from operations.'],
 ['Environment','environmental impact','impact environnemental','The effect of an activity on the environment.','You assess the environmental impact of the operation.'],
 ['Railway','access route','voie d’accès','A route used to enter or move through a work area.','Keep the access route clear.'],
 ['Railway','maintenance area','zone de maintenance','An area where maintenance work is performed.','Vehicle movement is controlled near the maintenance area.'],
 ['Railway','barrier','barrière','A physical object used to separate or protect an area.','The barrier was moved to a safer position.'],
 ['Communication','report','signaler / rapporter','To communicate information about an event or hazard.','You report hazards to your supervisor.'],
 ['Communication','clarify','clarifier','To make information easier to understand.','Could you clarify the last point, please?'],
 ['Communication','rephrase','reformuler','To say the same idea in a different way.','Could you rephrase the question, please?']
];

function renderQuiz(name){const root=$(`[data-quiz="${name}"]`);if(!root)return;root.innerHTML='';(quizData[name]||[]).forEach((item,i)=>{const key=`quiz:${name}:${i}`;const saved=state.answers[key];const card=document.createElement('article');card.className='q-card';card.innerHTML=`<h4>${i+1}. ${escapeHtml(item.q)}</h4><div class="q-options">${item.o.map((o,j)=>`<button type="button" class="q-option" data-i="${j}">${escapeHtml(o)}</button>`).join('')}</div><div class="q-feedback"></div><div class="q-fr">${escapeHtml(item.fr)}</div>`;const fb=$('.q-feedback',card);$$('.q-option',card).forEach(btn=>btn.addEventListener('click',()=>answerQuiz(name,i,+btn.dataset.i,card)));if(saved!==undefined)paintQuiz(item,saved,card);root.appendChild(card)});}
function answerQuiz(name,i,choice,card){const key=`quiz:${name}:${i}`;state.answers[key]=choice;paintQuiz(quizData[name][i],choice,card);save();}
function paintQuiz(item,choice,card){const correct=choice===item.a;$$('.q-option',card).forEach((b,j)=>{b.classList.toggle('selected',j===choice);b.classList.toggle('correct',j===item.a && choice!==undefined);b.classList.toggle('wrong',j===choice && !correct)});const fb=$('.q-feedback',card);fb.className='q-feedback '+(correct?'ok':'no');fb.textContent=(correct?'✓ Correct — ':'✗ Review — ')+item.why;}

function quizStats(){const out={};Object.keys(quizData).forEach(name=>{let c=0,a=0;quizData[name].forEach((it,i)=>{const v=state.answers[`quiz:${name}:${i}`];if(v!==undefined){a++;if(v===it.a)c++;}});out[pretty(name)]=[c,a,quizData[name].length]});let oc=0,oa=0;orderData.forEach((it,i)=>{const s=state.order[i];if(s&&s.checked){oa++;if(s.correct)oc++;}});out['Sentence order']=[oc,oa,orderData.length];let rc=0,ra=0;repairData.forEach((it,i)=>{const s=state.repair[i];if(s&&s.checked){ra++;if(s.correct)rc++;}});out['Error repair']=[rc,ra,repairData.length];let gc=0,ga=0;grammar.forEach((it,i)=>{const s=state.grammarMicro[i];if(s&&s.checked){ga++;if(s.correct)gc++;}});out['Grammar micro-practice']=[gc,ga,grammar.length];return out;}
function pretty(n){return ({diagnostic:'Baseline diagnostic',present:'Present tenses',perfect:'Past vs present perfect',future:'Future forms',reading:'Reading',listening:'Listening'})[n]||n}
function scoreSummary(){const stats=quizStats();let correct=0,attempted=0,max=0;Object.values(stats).forEach(([c,a,m])=>{correct+=c;attempted+=a;max+=m});return {correct,attempted,max,pct:pct(correct,attempted)}}
function updateScore(){const s=scoreSummary();$('#scoreNow').textContent=s.correct;$('#scoreMax').textContent=s.max;$('#scorePct').textContent=s.attempted?s.pct+'%':'0%';}

function renderOrder(){const root=$('#orderExercises');root.innerHTML='';orderData.forEach((item,i)=>{let saved=state.order[i];if(!saved){const shuffled=shuffle([...item.words]);saved={bank:shuffled,sentence:[],checked:false,correct:false};state.order[i]=saved;}const card=document.createElement('div');card.className='order-card';card.innerHTML=`<h4>${i+1}. Build the sentence.</h4><div class="word-bank" data-bank></div><div class="sentence-zone" data-sentence aria-label="Your sentence"></div><div class="order-actions"><button class="tiny-btn" type="button" data-check>Check</button><span class="feedback"></span></div>`;const bank=$('[data-bank]',card),zone=$('[data-sentence]',card);function draw(){bank.innerHTML='';zone.innerHTML='';saved.bank.forEach((w,idx)=>bank.appendChild(wordButton(w,'bank',idx)));saved.sentence.forEach((w,idx)=>zone.appendChild(wordButton(w,'sentence',idx)));const fb=$('.feedback',card);if(saved.checked){fb.className='feedback '+(saved.correct?'ok':'no');fb.textContent=saved.correct?'✓ Correct':'✗ Not yet — click a word in your sentence to move it back.';}else{fb.textContent='';fb.className='feedback';}}function wordButton(w,where,idx){const b=document.createElement('button');b.type='button';b.className='word-chip';b.textContent=w;b.addEventListener('click',()=>{saved.checked=false;if(where==='bank'){saved.sentence.push(saved.bank.splice(idx,1)[0])}else{saved.bank.push(saved.sentence.splice(idx,1)[0])}state.order[i]=saved;save();draw();});return b;} $('[data-check]',card).addEventListener('click',()=>{const answer=saved.sentence.join(' ').replace(/\s+([,.!?])/g,'$1');saved.checked=true;saved.correct=norm(answer)===norm(item.answer);state.order[i]=saved;save();draw();});draw();root.appendChild(card)});save();}
function shuffle(arr){for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr;}
function resetOrder(){state.order={};save();renderOrder();toast('Sentence-order block reset');}

function renderRepair(){const root=$('#repairExercises');root.innerHTML='';repairData.forEach((item,i)=>{const s=state.repair[i]||{text:'',checked:false,correct:false};const card=document.createElement('div');card.className='repair-card';card.innerHTML=`<h4>${i+1}. Repair: <em>${escapeHtml(item.bad)}</em></h4><textarea placeholder="Write the corrected sentence…">${escapeHtml(s.text||'')}</textarea><div class="repair-actions"><button class="tiny-btn" type="button" data-check>Check</button><button class="tiny-btn" type="button" data-model>Show model</button><span class="feedback"></span></div><div class="model-line"><b>Model:</b> ${escapeHtml(item.good)}<br><small>${escapeHtml(item.why)}</small></div>`;const ta=$('textarea',card),fb=$('.feedback',card),model=$('.model-line',card);ta.addEventListener('input',()=>{s.text=ta.value;s.checked=false;state.repair[i]=s;save();fb.textContent='';});$('[data-check]',card).addEventListener('click',()=>{s.text=ta.value;s.checked=true;s.correct=norm(s.text)===norm(item.good);state.repair[i]=s;fb.className='feedback '+(s.correct?'ok':'no');fb.textContent=s.correct?'✓ Correct':'✗ Compare your tense, word order and auxiliaries.';save();});$('[data-model]',card).addEventListener('click',()=>model.classList.toggle('open'));if(s.checked){fb.className='feedback '+(s.correct?'ok':'no');fb.textContent=s.correct?'✓ Correct':'✗ Review the model.';}root.appendChild(card)});}

function setupGrammar(){const sel=$('#grammarSelect');sel.innerHTML=grammar.map((g,i)=>`<option value="${i}">${g.cat} — ${g.name}</option>`).join('');sel.addEventListener('change',()=>renderGrammar(+sel.value));renderGrammar(0);}
function renderGrammar(i){const g=grammar[i],s=state.grammarMicro[i]||{};$('#grammarDisplay').innerHTML=`<div class="grammar-card-head"><div><div class="grammar-meta"><span class="tag">${escapeHtml(g.cat)}</span><span class="tag">${escapeHtml(g.level)}</span></div><h3>${escapeHtml(g.name)}</h3></div><span class="grammar-icon">${g.icon}</span></div><div class="grammar-columns"><div><h4>How to use it</h4><p>${escapeHtml(g.def)}</p><p class="fr-help">${escapeHtml(g.fr)}</p></div><div><h4>Key words / structure</h4><p><strong>${escapeHtml(g.keys)}</strong></p><p>${escapeHtml(g.tip)}</p></div></div><div class="grammar-example"><b>Example:</b> ${escapeHtml(g.ex)}</div><div class="micro-practice"><div class="micro-card"><b>Quick practice:</b> ${escapeHtml(g.prompt)}<br><input id="microInput" value="${escapeHtml(s.text||'')}" placeholder="Type your answer"><button class="tiny-btn" id="microCheck" type="button">Check</button><span class="feedback ${s.checked?(s.correct?'ok':'no'):''}" id="microFeedback">${s.checked?(s.correct?'✓ Correct':'✗ Try again'):''}</span></div></div>`;const input=$('#microInput');input.addEventListener('input',()=>{state.grammarMicro[i]=Object.assign({},state.grammarMicro[i],{text:input.value,checked:false});save();$('#microFeedback').textContent='';});$('#microCheck').addEventListener('click',()=>{const correct=norm(input.value)===norm(g.ans);state.grammarMicro[i]={text:input.value,checked:true,correct};save();const fb=$('#microFeedback');fb.className='feedback '+(correct?'ok':'no');fb.textContent=correct?'✓ Correct':`✗ Model: ${g.ans}`;});}

function setupVocab(){const cat=$('#vocabCategory'),search=$('#vocabSearch');const cats=['All',...new Set(vocab.map(v=>v[0]))];cat.innerHTML=cats.map(c=>`<option>${escapeHtml(c)}</option>`).join('');function draw(){const c=cat.value,q=norm(search.value);const rows=vocab.filter(v=>(c==='All'||v[0]===c)&&(!q||norm(v.join(' ')).includes(q)));$('#vocabGrid').innerHTML=rows.map(v=>`<article class="vocab-card"><div class="vocab-top"><span class="vocab-word">${escapeHtml(v[1])}</span><span class="vocab-fr">${escapeHtml(v[2])}</span></div><div class="vocab-def">${escapeHtml(v[3])}</div><div class="vocab-example">${escapeHtml(v[4])}</div><button class="tiny-btn" type="button" data-vocab-speak="${escapeHtml(v[1])}">🔊 Listen</button></article>`).join('');$$('[data-vocab-speak]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.vocabSpeak)));}cat.addEventListener('change',draw);search.addEventListener('input',draw);draw();}

function speak(text){if(!('speechSynthesis' in window)){toast('Speech is not supported in this browser');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.accent==='US'?'en-US':'en-GB';const voices=speechSynthesis.getVoices();const target=voices.find(v=>v.lang===u.lang)||voices.find(v=>v.lang&&v.lang.startsWith(u.lang.slice(0,2)));if(target)u.voice=target;u.rate=.94;speechSynthesis.speak(u);}
function setupSpeech(){$$('[data-speak]').forEach(b=>b.addEventListener('click',()=>{const el=$(b.dataset.speak);if(el)speak(el.innerText)}));$$('.speak-text').forEach(b=>b.addEventListener('click',()=>{const host=b.closest('article');const h=$('h3',host);if(h)speak(h.textContent)}));$$('[data-accent]').forEach(b=>b.addEventListener('click',()=>{state.accent=b.dataset.accent;save();syncAccent();toast(state.accent==='US'?'US accent selected':'UK accent selected')}));syncAccent();}
function syncAccent(){$$('[data-accent]').forEach(b=>{const on=b.dataset.accent===state.accent;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}

function setupFrench(){document.body.classList.toggle('show-french',!!state.french);$('#globalFrenchBtn').setAttribute('aria-pressed',String(!!state.french));$('#globalFrenchBtn').addEventListener('click',()=>{state.french=!state.french;document.body.classList.toggle('show-french',state.french);$('#globalFrenchBtn').setAttribute('aria-pressed',String(state.french));save();});$$('[data-help]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.help)?.classList.toggle('open')));$('#readingFrenchBtn').addEventListener('click',()=>$('#readingFrench').classList.toggle('open'));$('#toggleListeningFrench').addEventListener('click',()=>$('#listeningFrench').classList.toggle('open'));}

function setupTranscript(){const b=$('#toggleTranscript'),t=$('#listeningScript');b.addEventListener('click',()=>{const show=t.hasAttribute('hidden');if(show)t.removeAttribute('hidden');else t.setAttribute('hidden','');b.textContent=show?'📄 Hide transcript':'📄 Show transcript';b.setAttribute('aria-expanded',String(show));});}

function setupPersistentFields(){$$('[data-persist]').forEach(el=>{const k=el.dataset.persist;if(state.fields[k]!==undefined)el.value=state.fields[k];else state.fields[k]=el.value;el.addEventListener('input',()=>{state.fields[k]=el.value;save();if(el.id==='writingText')updateWordCount();});});$$('[data-persist-check]').forEach(el=>{const k=el.dataset.persistCheck;el.checked=!!state.checks[k];el.addEventListener('change',()=>{state.checks[k]=el.checked;save();});});updateWordCount();$('#buildIntro').addEventListener('click',()=>{const parts=['intro-role','intro-sector','intro-exp','intro-studies','intro-goal'].map(k=>(state.fields[k]||'').trim()).filter(Boolean);const txt=parts.join(' ');$('#introOutput').value=txt;state.fields['intro-output']=txt;save();toast('Your introduction was built and saved');});}
function updateWordCount(){const el=$('#writingText');if(!el)return;const n=(el.value.trim().match(/\S+/g)||[]).length;$('#wordCount').textContent=n;}

function setupObjectivesHomework(){$$('.objective-check').forEach(c=>{c.checked=state.objectives.includes(c.dataset.objective);c.addEventListener('change',()=>{state.objectives=c.checked?[...new Set([...state.objectives,c.dataset.objective])]:state.objectives.filter(x=>x!==c.dataset.objective);save();});});$$('.hw-check').forEach(c=>{c.checked=state.homework.includes(c.dataset.homework);c.addEventListener('change',()=>{state.homework=c.checked?[...new Set([...state.homework,c.dataset.homework])]:state.homework.filter(x=>x!==c.dataset.homework);save();});});}

function setupManual(){$$('.manual-task').forEach(task=>{const id=task.dataset.manualId;const saved=state.manual[id]||{};const ta=$('.teacher-notes',task);if(saved.notes!==undefined)ta.value=saved.notes;$$('[data-skill]',task).forEach(s=>{if(saved.scores&&saved.scores[s.dataset.skill]!==undefined)s.value=saved.scores[s.dataset.skill];s.addEventListener('change',()=>autosaveManual(task,id,false));});ta.addEventListener('input',()=>autosaveManual(task,id,false));$('.save-manual',task)?.addEventListener('click',()=>autosaveManual(task,id,true));if(saved.savedAt){const st=$('.saved-state',task);if(st)st.textContent='Saved';}});}
function autosaveManual(task,id,announce){const notes=$('.teacher-notes',task)?.value||'';const scores={};$$('[data-skill]',task).forEach(s=>{if(s.value)scores[s.dataset.skill]=+s.value});state.manual[id]={title:$('.scenario h3',task)?.textContent||$('h3',task)?.textContent||id,notes,scores,savedAt:new Date().toISOString()};save();const st=$('.saved-state',task);if(st)st.textContent='Saved';if(announce)toast('Evidence saved');}

function setupReportFields(){$$('[data-report-field]').forEach(el=>{const k=el.dataset.reportField;if(state.reportFields[k]!==undefined)el.value=state.reportFields[k];el.addEventListener('input',()=>{state.reportFields[k]=el.value;save();});});}
function updateReport(){if(!$('#reportDate'))return;const s=scoreSummary();$('#reportDate').textContent=dateText();$('#reportPct').textContent=s.attempted?s.pct+'%':'0%';$('#reportAutoSummary').textContent=s.attempted?`${s.correct} correct answer${s.correct===1?'':'s'} from ${s.attempted} attempted scored items. ${s.max} scored items are available across the lesson.`:'Complete interactive exercises to populate this section.';$('#reportObjectives').innerHTML=state.objectives.length?state.objectives.map(x=>`<li>${escapeHtml(x)}</li>`).join(''):'<li>No objectives marked yet.</li>';$('#reportHomework').innerHTML=state.homework.length?state.homework.map(x=>`<li>${escapeHtml(x)}</li>`).join(''):'<li>Homework not marked yet.</li>';const stats=quizStats();$('#reportExerciseRows').innerHTML=Object.entries(stats).map(([name,[c,a,m]])=>{const p=pct(c,a),priority=!a?'Not attempted':p<60?'High':p<80?'Medium':'Low';return `<tr><td>${escapeHtml(name)}</td><td>${c}</td><td>${a} / ${m}</td><td>${a?p+'%':'—'}</td><td class="${priority==='High'?'priority-high':priority==='Medium'?'priority-medium':priority==='Low'?'priority-low':''}">${priority}</td></tr>`}).join('');const entries=Object.entries(state.manual).filter(([,e])=>e&&(e.notes||Object.keys(e.scores||{}).length));const vals=entries.flatMap(([,e])=>Object.values(e.scores||{})).filter(v=>Number.isFinite(+v)).map(Number);$('#reportManualAvg').textContent=vals.length?(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1)+'/5':'—';$('#reportManualEvidence').innerHTML=entries.length?entries.map(([id,e])=>`<article class="evidence-card"><h4>${escapeHtml(e.title||id)}</h4>${e.notes?`<p><b>Evidence / notes:</b> ${escapeHtml(e.notes).replace(/\n/g,'<br>')}</p>`:''}<div class="evidence-scores">${Object.entries(e.scores||{}).map(([k,v])=>`<span>${escapeHtml(k)}: <b>${v}/5</b></span>`).join('')||'<span>No rating entered</span>'}</div></article>`).join(''):'<p>No manual evidence saved yet.</p>';}
function reportHtml(){updateReport();const clone=$('#reportPaper').cloneNode(true);$$('textarea',clone).forEach(t=>{const p=document.createElement('div');p.style='white-space:pre-wrap;border:1px solid #ddd;padding:8px;min-height:45px';p.textContent=t.value||'—';t.replaceWith(p)});return `<!doctype html><html><head><meta charset="utf-8"><title>Mamadou Diallo - Lesson 1 Progress Report</title><style>${reportCss()}</style></head><body>${clone.outerHTML}</body></html>`;}
function reportCss(){return `body{font-family:Arial,sans-serif;color:#102a35;margin:28px}.report-paper{max-width:900px;margin:auto}.report-head{display:flex;justify-content:space-between;border-bottom:3px solid #0f7b79;padding-bottom:10px}.brand-script{font-family:cursive;font-size:28px}.report-meta-grid,.report-columns{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:12px 0}.report-meta-grid div,.report-columns>div{border:1px solid #d7e0de;padding:8px}.report-meta-grid span{display:block;font-size:10px;text-transform:uppercase;color:#617883}.report-score-row{display:flex;gap:15px;background:#0d2f3c;color:#fff;padding:14px;border-radius:8px}.report-score-ring{border:6px solid #36aaa2;border-radius:50%;width:100px;height:100px;display:flex;flex-direction:column;align-items:center;justify-content:center}.report-score-ring b{font-size:24px}.report-score-ring span{font-size:9px;text-align:center}.report-table{width:100%;border-collapse:collapse;font-size:12px}.report-table th,.report-table td{border:1px solid #d7e0de;padding:6px}.evidence-card{border:1px solid #d7e0de;padding:8px;margin:6px 0}.evidence-scores span{display:inline-block;background:#eef5f3;padding:3px 5px;margin:2px;font-size:11px}.report-footnote{font-size:10px;border-top:1px solid #ccc;margin-top:16px;padding-top:8px}.report-logo{color:#0d2f3c}`;}
function downloadBlob(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500);}
function setupReportButtons(){$('#refreshReport').addEventListener('click',()=>{updateReport();toast('Report refreshed')});$('#openReportTop').addEventListener('click',()=>{$('#report').scrollIntoView({behavior:'smooth'});updateReport()});$('#downloadReportHtml').addEventListener('click',()=>downloadBlob('Mamadou_Diallo_Lesson_1_Progress_Report.html',reportHtml(),'text/html'));$('#downloadReportPdf').addEventListener('click',()=>{updateReport();setTimeout(()=>window.print(),100)});$('#copyReport').addEventListener('click',async()=>{updateReport();const s=scoreSummary();const txt=`Mamadou Diallo — Lesson 1\nInteractive: ${s.correct}/${s.attempted} attempted (${s.attempted?s.pct:0}%)\nObjectives: ${state.objectives.join(', ')||'—'}\nHomework: ${state.homework.join(', ')||'—'}\nStrengths: ${state.reportFields.strengths||'—'}\nPriority grammar: ${state.reportFields.grammar||'—'}\nPriority communication: ${state.reportFields.communication||'—'}\nNext focus: ${state.reportFields.next||'—'}`;try{await navigator.clipboard.writeText(txt);toast('Report summary copied')}catch(e){toast('Copy unavailable in this browser')}});}

function clearQuiz(name){Object.keys(state.answers).filter(k=>k.startsWith(`quiz:${name}:`)).forEach(k=>delete state.answers[k]);save();renderQuiz(name);toast(`${pretty(name)} reset`);}
function resetManualIds(ids){ids.forEach(id=>delete state.manual[id]);}
function resetSection(name){const messages={objectives:'Reset today’s objective checks?',syllabus:'This section has no scored work. Reset its local UI state?',diagnostic:'Reset only the baseline diagnostic?',intro:'Reset your self-introduction fields and speaking evidence?',grammar:'Reset grammar micro-practice?',vocab:'Reset vocabulary filter/search?',practice:'Reset all controlled-practice answers?',reading:'Reset the reading answers?',listening:'Reset listening answers and close support panels?',speaking:'Reset speaking notes and ratings?',writing:'Reset the writing text, checklist and rating?',homework:'Reset homework checks and homework evidence?',report:'Reset only the teacher report comment fields?'};if(!confirmReset(messages[name]||'Reset this section?'))return;switch(name){case'objectives':state.objectives=[];break;case'intro':['intro-role','intro-sector','intro-exp','intro-studies','intro-goal','intro-output'].forEach(k=>delete state.fields[k]);resetManualIds(['self_intro']);break;case'grammar':state.grammarMicro={};break;case'vocab':$('#vocabSearch').value='';$('#vocabCategory').selectedIndex=0;$('#vocabSearch').dispatchEvent(new Event('input'));break;case'practice':['present','perfect','future'].forEach(q=>Object.keys(state.answers).filter(k=>k.startsWith(`quiz:${q}:`)).forEach(k=>delete state.answers[k]));state.order={};state.repair={};break;case'diagnostic':Object.keys(state.answers).filter(k=>k.startsWith('quiz:diagnostic:')).forEach(k=>delete state.answers[k]);break;case'reading':Object.keys(state.answers).filter(k=>k.startsWith('quiz:reading:')).forEach(k=>delete state.answers[k]);$('#readingFrench').classList.remove('open');break;case'listening':Object.keys(state.answers).filter(k=>k.startsWith('quiz:listening:')).forEach(k=>delete state.answers[k]);$('#listeningScript').setAttribute('hidden','');$('#toggleTranscript').textContent='📄 Show transcript';$('#listeningFrench').classList.remove('open');break;case'speaking':resetManualIds(['speaking_role','speaking_hazard','speaking_studies']);break;case'writing':delete state.fields['writing-text'];['write-situation','write-risk','write-action','write-next'].forEach(k=>delete state.checks[k]);resetManualIds(['writing_hazard']);break;case'homework':state.homework=[];resetManualIds(['homework_log']);break;case'report':state.reportFields={};break;}save();location.reload();}
function setupResets(){$$('[data-reset-section]').forEach(b=>b.addEventListener('click',()=>resetSection(b.dataset.resetSection)));$$('[data-reset-quiz]').forEach(b=>b.addEventListener('click',()=>{if(confirmReset('Reset only this exercise block?'))clearQuiz(b.dataset.resetQuiz)}));$('[data-reset-order]').addEventListener('click',()=>{if(confirmReset('Reset only the sentence-order block?'))resetOrder()});$('[data-reset-repair]').addEventListener('click',()=>{if(confirmReset('Reset only the error-repair block?')){state.repair={};save();renderRepair();toast('Error-repair block reset')}});$('#resetLesson').addEventListener('click',()=>{if(confirmReset('Reset the WHOLE lesson? This will erase all saved answers, notes, ratings, report comments and homework checks from this browser.')){localStorage.removeItem(STORE);location.reload();}});}

function setupBackToTop(){const b=$('#backToTop');window.addEventListener('scroll',()=>b.classList.toggle('show',window.scrollY>600),{passive:true});b.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));}

function init(){['diagnostic','present','perfect','future','reading','listening'].forEach(renderQuiz);renderOrder();renderRepair();setupGrammar();setupVocab();setupSpeech();setupFrench();setupTranscript();setupPersistentFields();setupObjectivesHomework();setupManual();setupReportFields();setupReportButtons();setupResets();setupBackToTop();updateScore();updateReport();save();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
