const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE_KEY='eden_lesson_7_delegation_v1';
const sectionMeta={
 flight:['Flight plan','Manual'],baseline:['Baseline response','Manual'],delegation:['Delegation architecture','Auto + manual'],vocabulary:['Leadership vocabulary','Manual'],framework:['ASK → TEST → DECIDE → ALIGN','Manual'],language:['Language precision','Auto + manual'],accountability:['Accountability','Manual'],challenge:['Challenge lab','Manual'],scenarios:['Scenario lab','Manual'],meeting:['Expert disagreement meeting','Manual'],rewrite:['Rewrite the manager','Manual'],compression:['Executive compression','Manual'],cloe:['CLOE transfer','Manual'],final:['Final mission','Manual'],rule:['Personal leadership rule','Manual']
};
const vocab=[
 {c:'delegation',w:'outcome',fr:'résultat attendu',d:'The result that must be achieved, without prescribing every step.',e:'“The outcome we need is a decision-ready recommendation by Friday.”'},
 {c:'delegation',w:'guardrail',fr:'garde-fou / limite',d:'A boundary that defines what cannot be compromised.',e:'“Compliance is the main guardrail; the technical route is yours.”'},
 {c:'delegation',w:'decision space',fr:'marge / espace de décision',d:'The area in which someone has authority to decide independently.',e:'“Within that decision space, I expect you to use your judgement.”'},
 {c:'delegation',w:'autonomy',fr:'autonomie',d:'Freedom to choose how to perform work within agreed boundaries.',e:'“Autonomy works when the escalation triggers are clear.”'},
 {c:'delegation',w:'non-negotiable',fr:'non négociable',d:'A condition that cannot be traded away.',e:'“Traceability is non-negotiable.”'},
 {c:'accountability',w:'ownership',fr:'responsabilité / prise en charge',d:'Clear responsibility for producing or resolving something.',e:'“You keep technical ownership of the analysis.”'},
 {c:'accountability',w:'accountability',fr:'redevabilité / responsabilité finale',d:'Responsibility for the result and for explaining how commitments are met.',e:'“Expertise informs the decision; management accountability remains clear.”'},
 {c:'accountability',w:'follow-through',fr:'suivi jusqu’au bout',d:'Ensuring that an agreed action is actually completed.',e:'“Strong follow-through matters more than frequent checking.”'},
 {c:'accountability',w:'check-in',fr:'point de suivi',d:'A short, agreed moment to review progress or exceptions.',e:'“Let’s have a ten-minute check-in Thursday.”'},
 {c:'accountability',w:'escalation trigger',fr:'seuil / déclencheur d’escalade',d:'A pre-agreed condition that requires management attention.',e:'“A change in safety risk is an immediate escalation trigger.”'},
 {c:'decision',w:'decision owner',fr:'responsable de la décision',d:'The person accountable for making or confirming a decision.',e:'“The technical lead owns the recommendation; I remain the decision owner for the programme trade-off.”'},
 {c:'decision',w:'decision criteria',fr:'critères de décision',d:'The standards used to compare options.',e:'“Let’s agree the decision criteria before debating the options.”'},
 {c:'decision',w:'reopen a decision',fr:'rouvrir une décision',d:'To reconsider a decision because a material condition has changed.',e:'“Reopen the decision only if the validation evidence changes.”'},
 {c:'decision',w:'sign-off',fr:'validation finale',d:'Formal approval confirming that a decision or deliverable is accepted.',e:'“The technical sign-off remains with the authorised specialist.”'},
 {c:'risk',w:'trade-off',fr:'compromis / arbitrage',d:'A balance where improving one factor creates a cost elsewhere.',e:'“The key trade-off is technical risk versus schedule exposure.”'},
 {c:'risk',w:'residual risk',fr:'risque résiduel',d:'The risk that remains after mitigation actions.',e:'“Where is the residual risk after the mitigation?”'},
 {c:'risk',w:'assumption',fr:'hypothèse',d:'Something treated as true when making an analysis or decision.',e:'“Which assumption would be most damaging if it proved false?”'},
 {c:'risk',w:'mitigation',fr:'mesure de réduction du risque',d:'An action that reduces the likelihood or impact of a risk.',e:'“Please document the mitigation and the remaining exposure.”'},
 {c:'risk',w:'reversibility',fr:'réversibilité',d:'How easily a decision can be changed later.',e:'“How reversible is this choice if the next test fails?”'},
 {c:'challenge',w:'pressure-test',fr:'mettre à l’épreuve',d:'To test whether an idea remains strong under difficult questions or scenarios.',e:'“I want to pressure-test the recommendation before we close.”'},
 {c:'challenge',w:'challenge the assumption',fr:'remettre en question l’hypothèse',d:'To test whether a key assumption is still justified.',e:'“I’m challenging the assumption, not your expertise.”'},
 {c:'challenge',w:'disconfirming evidence',fr:'preuve contradictoire',d:'Evidence that would show a belief or recommendation may be wrong.',e:'“What disconfirming evidence would make you change your view?”'},
 {c:'challenge',w:'walk me through',fr:'expliquez-moi / guidez-moi à travers',d:'A collaborative way to ask someone to explain reasoning step by step.',e:'“Could you walk me through the main trade-off?”'},
 {c:'challenge',w:'surface a risk',fr:'faire ressortir un risque',d:'To make a hidden or implicit risk visible for decision-making.',e:'“Your role is to surface the risk before it becomes a surprise.”'}
];
const scenarios=[
 {type:'Delegation',title:'The expert asks for detailed instructions',s:'A highly experienced technical lead says: “Just tell me exactly how you want this done so we don’t waste time.” You want ownership, not compliance.',b2:'I do not need you to follow my method. I need a robust recommendation by Friday that protects compliance and shows the schedule impact. I’ll leave the technical route to you. Bring me in earlier only if the risk or scope changes.',c1:'I’m not delegating a procedure; I’m delegating an outcome. The guardrails are compliance, traceability and the Friday decision point. Within that space, use your judgement. I only need to re-enter if one of those constraints moves.'},
 {type:'Accountability',title:'The senior lead rejects check-ins',s:'A senior lead says: “If you trust me, you should not need updates. I’ll tell you when it’s finished.”',b2:'I do trust your technical ownership. The check-in is not about checking your work; it is about keeping project dependencies and risks visible. Let’s agree one short update Thursday, and earlier only if a milestone or risk changes.',c1:'Trust and visibility are not opposites. You own the technical work; I own the interfaces and programme exposure. A short Thursday check-in protects both roles. If delivery becomes fully predictable, we can reduce the cadence.'},
 {type:'Expert challenge',title:'The recommendation is confident but weakly evidenced',s:'The expert says: “I’ve done this for twenty years. I know it will work.” There is little documented evidence.',b2:'I respect the experience behind the recommendation. I still need the decision to be traceable. What evidence gives you the most confidence, and what would make you change your view? We can close once that evidence is documented.',c1:'Your experience is valuable input, but the decision cannot rest on confidence alone. Which evidence should carry the decision, and what would disconfirm the recommendation? Once that is explicit, we can decide and keep the rationale traceable.'},
 {type:'Trade-off',title:'Technically best, operationally impossible',s:'An expert proposes the technically strongest solution, but it adds eight weeks and threatens a customer commitment.',b2:'Technically, I understand why this is the strongest option. I need to understand what risk those eight weeks remove and whether there is a lower-impact alternative. We will decide based on both the technical risk and the programme consequence.',c1:'I accept that this may be the technically cleanest answer. The management question is whether the risk reduction is proportionate to eight weeks of programme exposure. Quantify what we buy down, identify the reversible alternatives, and I will make the wider trade-off.'},
 {type:'Missed commitment',title:'Two milestones have been missed',s:'A respected expert has missed two milestones and says the original dates were unrealistic anyway.',b2:'If the dates were unrealistic, I need that risk surfaced before the commitment is missed. You keep ownership of the work, but I need a recovery plan today and short check-ins until delivery becomes predictable again.',c1:'The issue is not that the plan changed; it is that the change became visible after two missed commitments. Technical ownership stays with you. Management visibility increases until we have a credible recovery path and an agreed escalation trigger.'},
 {type:'Disagreement',title:'Two senior experts disagree in the meeting',s:'Both experts are credible. One wants to protect the current milestone; the other wants to redesign now to reduce long-term risk.',b2:'Let’s separate the decision criteria before debating the options. I want the strongest evidence, the main risk and the schedule impact for each recommendation. Then we will make one decision and agree the owner and next action.',c1:'We are not deciding whose expertise is stronger. We are deciding which risk profile the programme should accept. We will use the same criteria for both options: compliance, residual risk, reversibility and schedule exposure, then close with one owner and one decision.'}
];
const microPrompts=[
 {p:'Delegate an urgent analysis without prescribing the method.',b2:'I need a recommendation by tomorrow that shows the main risk. The technical method is yours; bring me in if the safety position changes.',c1:'Own the recommendation and the route to it. I need the risk position tomorrow; escalate only if the safety or decision space changes.'},
 {p:'Ask two questions that test a confident recommendation.',b2:'What is the strongest evidence behind the recommendation? What would make you change your view?',c1:'Which assumption is carrying the recommendation, and what evidence would invalidate it?'},
 {p:'Close a decision in one sentence: decision + owner + date.',b2:'We will keep the current design; you own the mitigation note by Thursday.',c1:'Decision: retain the design. You own the evidence trace by Thursday; reopen only on material change.'},
 {p:'Explain why a check-in is not micromanagement.',b2:'The check-in is not about controlling your method; it is about keeping risks and dependencies visible.',c1:'Technical autonomy remains yours; the check-in protects the management visibility required for programme accountability.'},
 {p:'State one non-negotiable without sounding aggressive.',b2:'The technical approach is flexible, but traceability is not negotiable.',c1:'The route is yours; traceability is a governance boundary and must be complete before closure.'},
 {p:'Respond when an expert says: “Trust me, I know this system.”',b2:'I trust your experience. I still need the evidence and residual risk to be clear for the decision.',c1:'I value the experience behind the judgement; now make the evidence and disconfirming condition explicit so the decision is traceable.'},
 {p:'Say what would make you reopen a decision.',b2:'We will reopen the decision if the validation evidence or safety risk changes.',c1:'The decision stays closed unless a material assumption, validation result or risk threshold changes.'},
 {p:'Give autonomy while protecting a safety boundary.',b2:'Use the technical method you judge best, but the safety requirement cannot be compromised.',c1:'You own the technical route within one hard guardrail: the safety requirement remains non-negotiable.'}
];
let correct=0, attempted=0;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function initNav(){$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));$('#printPage').onclick=()=>window.print();$('#printReport').onclick=()=>window.print()}
function populateVoices(){const ss=window.speechSynthesis;if(!ss)return;const lang=$('#accentSelect').value;const voices=ss.getVoices().filter(v=>v.lang?.toLowerCase().startsWith(lang.toLowerCase()));const all=voices.length?voices:ss.getVoices().filter(v=>v.lang?.toLowerCase().startsWith('en'));const sel=$('#voiceSelect');sel.innerHTML='';all.forEach((v,i)=>{const o=document.createElement('option');o.value=v.name;o.textContent=`${v.name} (${v.lang})`;sel.appendChild(o)});if(!all.length){const o=document.createElement('option');o.textContent='Default browser voice';sel.appendChild(o)}}
function speakText(text,style='natural'){if(!('speechSynthesis'in window))return toast('Speech synthesis is not available on this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/→/g,' to '));u.lang=$('#accentSelect').value;const v=speechSynthesis.getVoices().find(v=>v.name===$('#voiceSelect').value);if(v)u.voice=v;const styles={natural:[.96,1],firm:[.88,.95],calm:[.82,.98],clear:[.9,1]};[u.rate,u.pitch]=styles[style]||styles.natural;speechSynthesis.speak(u)}
function initAudio(){populateVoices();if('speechSynthesis'in window){speechSynthesis.onvoiceschanged=populateVoices;setTimeout(populateVoices,500)}$('#accentSelect').onchange=populateVoices;$('#refreshVoices').onclick=populateVoices;$('#stopAudio').onclick=()=>speechSynthesis?.cancel();$('#audioTest').onclick=()=>speakText('Audio test. If you can hear this sentence, the listening tools are working correctly.');document.addEventListener('click',e=>{const b=e.target.closest('[data-speak-text],[data-speak-id]');if(!b)return;const t=b.dataset.speakText||$(('#'+b.dataset.speakId))?.textContent||'';speakText(t,b.dataset.style||'natural')})}
function initToggles(){$('#toggleFrench').onclick=()=>{document.body.classList.toggle('translations-on');const on=document.body.classList.contains('translations-on');$('#toggleFrench').textContent=on?'Hide French support':'Show French support'};$('#toggleModels').onclick=()=>{const open=document.body.classList.toggle('all-models');$$('details.model-block').forEach(d=>d.open=open);$$('.inline-model').forEach(m=>m.classList.toggle('hidden',!open));$('#toggleModels').textContent=open?'Hide all models':'Show all models'};document.addEventListener('click',e=>{const b=e.target.closest('.random-model');if(!b)return;$('#'+b.dataset.model)?.classList.toggle('hidden')})}
function updateScores(){const total=attempted;$('#liveScore').textContent=`${correct}/${total}`;$('#autoScore').textContent=`${correct}/${total}`;$$('.auto-cell').forEach(c=>{if(c.dataset.kind==='auto')c.textContent=`${correct}/${total}`});updateProgress()}
function initChoices(){$$('.choice-list').forEach(list=>{[...list.children].sort(()=>Math.random()-.5).forEach(x=>list.appendChild(x));list.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||list.dataset.done)return;list.dataset.done='1';attempted++;const ok=b.dataset.correct==='true';if(ok)correct++;[...list.children].forEach(x=>{x.disabled=true;if(x.dataset.correct==='true')x.classList.add('correct')});if(!ok)b.classList.add('incorrect');const f=list.parentElement.querySelector('.feedback');f.textContent=ok?'Correct — clear, proportionate and management-focused.':'Not quite. Compare the decision space, force and accountability in the stronger option.';f.className='feedback '+(ok?'ok':'no');updateScores();autoSave()})})}
function renderVocab(filter='all'){const grid=$('#vocabGrid');grid.innerHTML='';vocab.filter(v=>filter==='all'||v.c===filter).forEach(v=>{const a=document.createElement('article');a.className='vocab-card';a.innerHTML=`<span class="vocab-cat">${v.c}</span><h3>${v.w}</h3><div class="vocab-fr">${v.fr}</div><p class="vocab-def">${v.d}</p><p class="vocab-example">${v.e}</p><button class="btn small" data-speak-text="${v.w}. ${v.d} Example: ${v.e.replace(/"/g,'&quot;')}">Listen</button>`;grid.appendChild(a)})}
function initVocab(){renderVocab();$('#vocabFilter').onchange=e=>renderVocab(e.target.value);$('#randomVocab').onclick=()=>{const v=vocab[Math.floor(Math.random()*vocab.length)];$('#vocabFilter').value=v.c;renderVocab(v.c);setTimeout(()=>{const card=$$('.vocab-card').find(c=>$('h3',c).textContent===v.w);card?.scrollIntoView({behavior:'smooth',block:'center'});card?.animate([{outline:'2px solid #f3c96b'},{outline:'0 solid transparent'}],{duration:1800})},50)}}
function initTimers(){
  $$('.timer-btn').forEach(btn=>{
    btn.onclick=()=>{
      if(btn._timer){clearInterval(btn._timer);btn._timer=null;}
      let sec=Number(btn.dataset.seconds);
      const d=btn.parentElement.querySelector('.timer-display');
      const fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
      d.textContent=fmt(sec); d.classList.add('running'); btn.textContent='Restart';
      btn._timer=setInterval(()=>{
        sec--; d.textContent=fmt(Math.max(sec,0));
        if(sec<=0){
          clearInterval(btn._timer); btn._timer=null; d.classList.remove('running'); btn.textContent='Start again';
          toast('Time. Stop and close your answer.');
        }
      },1000);
    };
  });
}
function initRecorders(){if(!navigator.mediaDevices?.getUserMedia){$$('.recorder').forEach(r=>r.querySelector('.rec-status').textContent='Recording is not supported in this browser.');return}$$('.recorder').forEach(box=>{let stream,rec,chunks=[];const start=$('.startRec',box),stop=$('.stopRec',box),link=$('.downloadRec',box),audio=$('.playback',box),status=$('.rec-status',box);start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);audio.src=url;audio.classList.remove('hidden');link.href=url;link.classList.remove('hidden');stream.getTracks().forEach(t=>t.stop());box.classList.remove('recording');status.innerHTML='<span class="recording-light"></span> Recording ready';autoSave()};rec.start();box.classList.add('recording');start.disabled=true;stop.disabled=false;status.innerHTML='<span class="recording-light"></span> Recording…'}catch(err){toast('Microphone access was not available.')}};stop.onclick=()=>{if(rec?.state==='recording')rec.stop();start.disabled=false;stop.disabled=true}})}
function renderScenario(i=0){const s=scenarios[i];$('#scenarioType').textContent=s.type;$('#scenarioTitle').textContent=s.title;$('#scenarioSituation').textContent=s.s;$('#scenarioB2').textContent=s.b2;$('#scenarioC1').textContent=s.c1;$('#scenarioModels').classList.add('hidden');$('#revealScenarioModels').textContent='Reveal model answers';$('#scenarioSurprise').textContent='No surprise challenge yet.'}
function initScenarios(){const sel=$('#scenarioSelect');scenarios.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${s.type} — ${s.title}`;sel.appendChild(o)});renderScenario(0);sel.onchange=e=>renderScenario(Number(e.target.value));$('#randomScenario').onclick=()=>{const i=Math.floor(Math.random()*scenarios.length);sel.value=i;renderScenario(i)};const surprises=['The expert interrupts: “You are overcomplicating this.”','Senior management asks for a decision immediately.','New evidence appears that weakens the preferred option.','The expert says the deadline is impossible.','Another team will be affected by the decision.','The expert challenges the need for documentation.'];$('#newChallenge').onclick=()=>{$('#scenarioSurprise').textContent='SURPRISE: '+surprises[Math.floor(Math.random()*surprises.length)]};$('#revealScenarioModels').onclick=()=>{const m=$('#scenarioModels');m.classList.toggle('hidden');$('#revealScenarioModels').textContent=m.classList.contains('hidden')?'Reveal model answers':'Hide model answers'}}
function initSurprises(){$$('.surprise-btn').forEach(b=>b.onclick=()=>$('#surpriseDisplay').textContent=b.dataset.surprise)}
function renderMicro(){const x=microPrompts[Math.floor(Math.random()*microPrompts.length)];$('#microPrompts').innerHTML=`<article class="micro-card"><span class="tiny-label">Live micro-prompt</span><h3>${x.p}</h3><p>Target: 15–25 seconds. One idea. One close.</p><details class="model-block"><summary>Reveal models after your attempt</summary><div class="model-grid two"><article><span class="level-tag">B2</span><p>${x.b2}</p></article><article><span class="level-tag advanced">C1</span><p>${x.c1}</p></article></div></details></article>`}function initMicro(){renderMicro();$('#newMicroPrompt').onclick=renderMicro}
function updateFinalRubric(){const score=$$('[data-final-rubric]').reduce((a,x)=>a+Number(x.value),0);$('#finalRubricScore').textContent=`${score}/12`;$('#finalScoreSummary').textContent=`${score}/12`;autoSave(false)}
function sectionStatus(sec){return $('[data-status]',sec)?.value||'not-started'}
function updateProgress(){const sections=$$('[data-eval-id]');const started=sections.filter(s=>sectionStatus(s)!=='not-started').length;const pct=sections.length?Math.round(started/sections.length*100):0;$('#liveProgress').textContent=pct+'%';$('#completionRate').textContent=pct+'%';const statuses=sections.map(sectionStatus);let overall='Not started';if(started){overall=statuses.every(s=>s==='achieved')?'Achieved':statuses.some(s=>s==='not-achieved')?'Needs attention':'In progress'}$('#overallStatus').textContent=overall;return pct}
function buildEvalTable(){const body=$('#evaluationBody');body.innerHTML='';Object.entries(sectionMeta).forEach(([id,[label,mode]])=>{const sec=$(`[data-eval-id="${id}"]`);const tr=document.createElement('tr');tr.dataset.evalRow=id;const kind=mode.includes('Auto')?'auto':'manual';tr.innerHTML=`<td>${label}</td><td>${mode}</td><td class="auto-cell" data-kind="${kind}">${kind==='auto'?`${correct}/${attempted}`:'—'}</td><td><select data-table-status><option value="not-started">Not started</option><option value="progress">In progress</option><option value="achieved">Achieved</option><option value="not-achieved">Not achieved</option></select></td><td><input data-table-comment placeholder="Observation"></td>`;body.appendChild(tr);const tableSel=$('[data-table-status]',tr);if(sec){tableSel.value=sectionStatus(sec);tableSel.onchange=()=>{$('[data-status]',sec).value=tableSel.value;updateProgress();autoSave()};const secSel=$('[data-status]',sec);secSel.addEventListener('change',()=>{tableSel.value=secSel.value;updateProgress();autoSave()});const note=$('[data-note]',sec);const c=$('[data-table-comment]',tr);if(note){c.value=note.value;c.oninput=()=>{note.value=c.value;autoSave()};note.oninput=()=>{c.value=note.value;autoSave()}}}})}
function serialize(){const fields={};$$('[data-save],#learnerName,#trainerName,#evaluationDate,#trainerComments,#surveyUseful,#surveyConfidence,#surveyBest,#surveyComments').forEach((el,i)=>fields[el.id||`field_${i}`]=el.value);const sections={};$$('[data-eval-id]').forEach(sec=>sections[sec.dataset.evalId]={status:sectionStatus(sec),note:$('[data-note]',sec)?.value||''});const table={};$$('[data-eval-row]').forEach(row=>table[row.dataset.evalRow]={status:$('[data-table-status]',row).value,comment:$('[data-table-comment]',row).value});const choices=$$('.choice-list').map(l=>({done:!!l.dataset.done,correct:[...l.children].findIndex(b=>b.classList.contains('correct')),incorrect:[...l.children].findIndex(b=>b.classList.contains('incorrect'))}));return {fields,sections,table,choices,correct,attempted,final:$$('[data-final-rubric]').map(x=>x.value),lastSaved:new Date().toISOString()}}
let saveTimer;function autoSave(show=false){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{const s=serialize();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));$('#lastSaved').textContent=new Date(s.lastSaved).toLocaleString();if(show)toast('Progress saved locally.')},250)}
function restore(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!s)return;correct=s.correct||0;attempted=s.attempted||0;const inputs=$$('[data-save],#learnerName,#trainerName,#evaluationDate,#trainerComments,#surveyUseful,#surveyConfidence,#surveyBest,#surveyComments');inputs.forEach((el,i)=>{const k=el.id||`field_${i}`;if(k in (s.fields||{}))el.value=s.fields[k]});Object.entries(s.sections||{}).forEach(([id,v])=>{const sec=$(`[data-eval-id="${id}"]`);if(sec){const st=$('[data-status]',sec),n=$('[data-note]',sec);if(st)st.value=v.status;if(n)n.value=v.note||''}});(s.final||[]).forEach((v,i)=>{if($$('[data-final-rubric]')[i])$$('[data-final-rubric]')[i].value=v});if(s.lastSaved)$('#lastSaved').textContent=new Date(s.lastSaved).toLocaleString()}catch(e){console.warn('Could not restore',e)}}
function reportText(){const pct=updateProgress(),score=$$('[data-final-rubric]').reduce((a,x)=>a+Number(x.value),0);const lines=[`Qualiopi learning tracking — Lesson 7`,`Lesson: Delegation, Accountability & Challenge`,`Learner: ${$('#learnerName').value}`,`Trainer: ${$('#trainerName').value}`,`Date: ${$('#evaluationDate').value}`,`Automatic exercise score: ${correct}/${attempted}`,`Completion: ${pct}%`,`Final mission score: ${score}/12`,`Overall: ${$('#overallStatus').textContent}`,'','SECTION RESULTS'];Object.entries(sectionMeta).forEach(([id,[label,mode]])=>{const sec=$(`[data-eval-id="${id}"]`);const note=$('[data-note]',sec)?.value.trim();lines.push(`- ${label} | ${mode} | ${sectionStatus(sec)}`);if(note)lines.push(`  Note: ${note}`)});lines.push('','PERSONAL LEADERSHIP RULE',$('#personalRule').value||'—','','GENERAL OBSERVATIONS',$('#trainerComments').value||'—');return lines.join('\n')}
function reportHtml(){return `<!doctype html><html><head><meta charset="utf-8"><title>Lesson 7 — Qualiopi report</title><style>body{font-family:Arial,sans-serif;max-width:900px;margin:40px auto;color:#162938;line-height:1.55}pre{white-space:pre-wrap;border:1px solid #ccd8df;padding:22px;border-radius:12px}</style></head><body><h1>Lesson 7 — Delegation, Accountability & Challenge</h1><pre>${reportText().replace(/&/g,'&amp;').replace(/</g,'&lt;')}</pre></body></html>`}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('Copied.')}catch{const ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied.')}}
function surveyText(){return `Lesson 7 feedback\nUseful for real work: ${$('#surveyUseful').value}\nConfidence after lesson: ${$('#surveyConfidence').value}\nMost useful focus: ${$('#surveyBest').value}\n\nComments:\n${$('#surveyComments').value||'—'}`}
function updateSurvey(){$('#surveyPreview').textContent=surveyText();autoSave()}
function initReporting(){const d=$('#evaluationDate');if(!d.value)d.value=new Date().toISOString().slice(0,10);buildEvalTable();$('#saveProgress').onclick=()=>autoSave(true);$('#copyReport').onclick=()=>{const t=reportText();$('#reportPreview').textContent=t;copyText(t)};$('#downloadReportTxt').onclick=()=>download('lesson-7-qualiopi-report.txt',reportText());$('#downloadReportHtml').onclick=()=>download('lesson-7-qualiopi-report.html',reportHtml(),'text/html');$('#resetProgress').onclick=()=>{if(confirm('Reset all locally saved progress for this lesson?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};['#surveyUseful','#surveyConfidence','#surveyBest','#surveyComments'].forEach(s=>$(s).addEventListener('input',updateSurvey));$('#copySurvey').onclick=()=>copyText(surveyText());$('#downloadSurvey').onclick=()=>download('lesson-7-feedback.txt',surveyText());updateSurvey();$('#reportPreview').textContent=reportText()}
function initSectionResets(){$$('.section-reset').forEach(b=>b.onclick=()=>{const sec=$(`[data-eval-id="${b.dataset.resetSection}"]`);if(!sec)return;$$('textarea,input[type="text"]',sec).forEach(x=>x.value='');$$('select[data-status]',sec).forEach(x=>x.value='not-started');$$('.choice-list',sec).forEach(l=>{delete l.dataset.done;[...l.children].forEach(x=>{x.disabled=false;x.classList.remove('correct','incorrect')});const f=l.parentElement.querySelector('.feedback');if(f){f.textContent='';f.className='feedback'}});const row=$(`[data-eval-row="${b.dataset.resetSection}"]`);if(row){$('[data-table-status]',row).value='not-started';$('[data-table-comment]',row).value=''}updateProgress();autoSave();toast('Section reset.')})}
function bindAutosave(){document.addEventListener('input',e=>{if(e.target.matches('textarea,input,select'))autoSave()});document.addEventListener('change',e=>{if(e.target.matches('select,input'))autoSave()});$$('[data-final-rubric]').forEach(x=>x.onchange=updateFinalRubric)}
function init(){initNav();initAudio();initToggles();initChoices();initVocab();initTimers();initRecorders();initScenarios();initSurprises();initMicro();restore();buildEvalTable();updateScores();updateFinalRubric();initReporting();initSectionResets();bindAutosave();updateProgress()}
document.addEventListener('DOMContentLoaded',init);
