(() => {
'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const state={accent:'en-AU',mode:'guided',completed:new Set(),correct:0,attempted:0,sectionStats:{},manualStatus:{},manualComments:{},missionNotes:{},interviewIndex:0,listeningIndex:0};
const norm=s=>String(s||'').toLowerCase().replace(/[’]/g,"'").replace(/\s+/g,' ').trim();
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

function speak(text){if(!('speechSynthesis' in window))return alert('Speech synthesis is not available in this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.accent;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang===state.accent)||voices.find(v=>v.lang?.startsWith(state.accent.slice(0,2)))||null;u.rate=state.accent==='en-AU'?.94:.96;speechSynthesis.speak(u)}

const activation=[
{q:'I ___ as a process analyst for six years before the reorganisation.',o:['worked','have worked','have work'],a:'worked',h:'The six-year job period is finished.',e:'Past Simple: the job period is closed and belongs to a finished part of your career.'},
{q:'Since my role ended, I ___ more time to improving my English.',o:['gave','have given','give'],a:'have given',h:'“Since” connects a starting point in the past to now.',e:'Present Perfect: the period started after the role ended and continues to connect to the present.'},
{q:'Last year, the team ___ a new workflow.',o:['introduced','has introduced','introduce'],a:'introduced',h:'“Last year” is a finished time.',e:'Past Simple: finished action + finished time.'},
{q:'I ___ several ways to present my experience more clearly so far.',o:['tried','have tried','try'],a:'have tried',h:'“So far” means up to now.',e:'Present Perfect: “so far” describes progress up to the present.'},
{q:'Marine and I ___ several trips together.',o:['have taken','took last year','takes'],a:'have taken',h:'No finished date is given. This is life experience.',e:'Present Perfect: experience at an unspecified time before now.'},
{q:'On one of those trips, we ___ our plans at the last minute.',o:['changed','have changed','change'],a:'changed',h:'“On one of those trips” points to one specific finished event.',e:'Past Simple: once the experience becomes a specific story, switch to Past Simple.'},
{q:'I ___ more confident about explaining my career since we started this grammar work.',o:['became','have become','become'],a:'have become',h:'The change develops from a past starting point to now.',e:'Present Perfect: a change with a clear result now.'},
{q:'When I first started working, I ___ everything immediately.',o:["didn't know","haven't known","don't knew"],a:"didn't know",h:'“When I first started” is a finished past moment.',e:'Past Simple negative: did not + base verb.'},
{q:'My responsibilities ___ over the six years I spent in the company.',o:['changed','have changed','change'],a:'changed',h:'Those six years are a finished period.',e:'Past Simple: the time period is complete.'},
{q:'My priorities ___ a lot recently.',o:['changed','have changed','changes'],a:'have changed',h:'“Recently” keeps the time connected to now.',e:'Present Perfect: recent change with current relevance.'},
{q:'___ you ever had to explain a complex process to someone outside your team?',o:['Have','Did','Has'],a:'Have',h:'“Ever” asks about life experience.',e:'Present Perfect question: Have + subject + past participle?'},
{q:'When ___ that happen?',o:['did','has','have'],a:'did',h:'Now you are asking for the specific finished event.',e:'Past Simple question: Did + subject + base verb?'},
{q:'The reorganisation ___ my role, but it also created a new opportunity.',o:['ended','has ended','end'],a:'ended',h:'The reorganisation is a finished event.',e:'Past Simple: a specific completed event.'},
{q:'That transition ___ me think more carefully about my next step.',o:['has made','made in 2025','make'],a:'has made',h:'The effect is still important now.',e:'Present Perfect: past cause with a result that still matters.'},
{q:'I ___ Australia before, but I have researched it carefully.',o:["haven't lived in","didn't lived in","haven't live in"],a:"haven't lived in",h:'No finished time; this is experience up to now.',e:'Present Perfect negative: have not + past participle.'},
{q:'I ___ my previous company three months ago.',o:['left','have left','leave'],a:'left',h:'“Three months ago” is a finished-time marker.',e:'Past Simple: never use the Present Perfect with “ago”.'},
{q:'Since then, I ___ a more structured routine.',o:['developed','have developed','develop'],a:'have developed',h:'“Since then” links the past change to now.',e:'Present Perfect: development from then until now.'},
{q:'How long ___ you interested in working abroad?',o:['have you been','were you','did you be'],a:'have you been',h:'The interest started before now and still exists.',e:'Present Perfect with “How long” for an unfinished situation.'}
];

const pastStory=[
{q:'You want to start a story about a finished process project. Which opening is clearest?',o:['In 2023, our team had a problem with a reporting process.','I have had a problem in 2023.','There is a process problem maybe.'],a:'In 2023, our team had a problem with a reporting process.',h:'Start with a finished-time marker and clear context.',e:'A good Past Simple story begins by locating the listener in a finished time.'},
{q:'Next, explain your role.',o:['I was responsible for understanding where the delays came from.','I have been responsible yesterday.','I am responsible at this time.'],a:'I was responsible for understanding where the delays came from.',h:'The project and role are finished.',e:'Use Past Simple / was for the role you had in that specific project.'},
{q:'Move the story forward with an action.',o:['First, I spoke to the teams that used the process every day.','First, I have spoken to them last week.','First, I speak the teams.'],a:'First, I spoke to the teams that used the process every day.',h:'Use a sequence connector + Past Simple.',e:'“First” helps the listener follow the chronology; “spoke” marks the finished action.'},
{q:'Add the next action.',o:['After that, I mapped the workflow and identified two unnecessary steps.','After that, I have mapped it in 2023.','After that, I map it yesterday.'],a:'After that, I mapped the workflow and identified two unnecessary steps.',h:'Two completed actions in the same finished project.',e:'Keep the Past Simple for the chain of actions.'},
{q:'Explain the result.',o:['As a result, the team simplified the process and reduced delays.','As a result, the team has simplified it in 2023.','As a result, the team simplify.'],a:'As a result, the team simplified the process and reduced delays.',h:'The result happened inside the finished story.',e:'Past Simple keeps the result inside the same closed timeline.'},
{q:'Finish the past-event part with reflection at that time.',o:['I learned that practical feedback was essential before changing a process.','I have learned it yesterday.','I learn it in that project.'],a:'I learned that practical feedback was essential before changing a process.',h:'The learning happened in the finished event.',e:'Past Simple can describe what you learned during that specific event.'},
{q:'Tell a university story. Which sentence sets the scene?',o:['When I was studying, I had to manage several deadlines at the same time.','When I have studied, I manage deadlines.','When I was study, I had deadlines.'],a:'When I was studying, I had to manage several deadlines at the same time.',h:'“When I was studying” sets a past context.',e:'The background can use Past Continuous, while the main fact is in the Past Simple. The key timeline is still finished.'},
{q:'What is the best next sentence?',o:['One semester, I underestimated how much time one project would take.','One semester, I have underestimated the project.','I underestimate it one semester.'],a:'One semester, I underestimated how much time one project would take.',h:'“One semester” introduces one specific completed event.',e:'Past Simple: specific event in a finished period.'},
{q:'Explain what you did next.',o:['I reorganised my schedule and asked for clarification early.','I have reorganised my schedule that semester.','I reorganise my schedule then.'],a:'I reorganised my schedule and asked for clarification early.',h:'Keep the sequence in Past Simple.',e:'Multiple finished actions can be linked in one Past Simple sequence.'},
{q:'Finish the study story.',o:['The project went well, and I became more realistic about planning my time.','The project has gone well in that semester.','The project go well.'],a:'The project went well, and I became more realistic about planning my time.',h:'Both results belong to that finished period.',e:'Past Simple closes the story cleanly.'},
{q:'Start a sports challenge story.',o:['Last month, I took part in a demanding race and had to manage my energy carefully.','I have taken part last month.','Last month I have take part.'],a:'Last month, I took part in a demanding race and had to manage my energy carefully.',h:'“Last month” = closed time.',e:'Past Simple with irregular “took”.'},
{q:'Add the difficult moment.',o:['Halfway through, I felt tired but decided to keep the same pace.','Halfway through, I have felt tired.','I feel tired halfway last month.'],a:'Halfway through, I felt tired but decided to keep the same pace.',h:'These actions happened at a precise point in the event.',e:'Past Simple advances the story through the difficult moment.'},
{q:'Add the result.',o:['I finished the event and was pleased with the way I managed the pressure.','I have finished the event last month.','I finish and was pleased.'],a:'I finished the event and was pleased with the way I managed the pressure.',h:'The event is over.',e:'Past Simple for completed result and feeling at that time.'},
{q:'Start a travel problem story.',o:['During one trip, our plans changed unexpectedly.','Our plans have changed during one trip.','During one trip our plans change.'],a:'During one trip, our plans changed unexpectedly.',h:'“During one trip” identifies a finished experience.',e:'Once you choose a specific trip, Past Simple is the natural storytelling tense.'},
{q:'Explain the reaction.',o:['We looked at the options, changed the itinerary and found another solution.','We have looked at the options that day.','We look and found.'],a:'We looked at the options, changed the itinerary and found another solution.',h:'Three completed actions in sequence.',e:'Past Simple is ideal for a chain of completed actions.'},
{q:'End the travel story.',o:['In the end, the change made the trip more memorable.','In the end, the change has made it memorable that day.','In the end it make memorable.'],a:'In the end, the change made the trip more memorable.',h:'“In the end” closes a finished story.',e:'Past Simple completes the narrative.'},
{q:'Start the story of leaving a job.',o:['My role ended after a wider reorganisation.','My role has ended three months ago.','My role end after reorganisation.'],a:'My role ended after a wider reorganisation.',h:'The end of the role is a completed event.',e:'Past Simple states the finished event clearly and neutrally.'},
{q:'What is a strong next sentence?',o:['I decided not to rush into the first opportunity and took time to think about my next step.','I have decided at that moment and took time.','I decide and taked time.'],a:'I decided not to rush into the first opportunity and took time to think about my next step.',h:'Describe your decisions at that finished moment.',e:'Past Simple “decided / took” continues the story.'}
];

const bridge=[
{q:'Complete the natural sequence: “I ___ with many stakeholders over my career. In my previous role, I ___ with teams from several departments.”',o:['have worked / worked','worked / have worked','have work / worked'],a:'have worked / worked',h:'General experience first; specific previous role second.',e:'Present Perfect introduces overall experience; Past Simple gives the concrete finished example.'},
{q:'“I ___ difficult projects before. In 2024, one project ___ especially challenging.”',o:['have managed / was','managed / has been','have manage / was'],a:'have managed / was',h:'Experience up to now → specific year.',e:'Use Present Perfect for experience, then Past Simple with “in 2024”.'},
{q:'“I ___ a lot from team disagreements. One time, two departments ___ completely different priorities.”',o:['have learned / had','learned / have had','have learn / had'],a:'have learned / had',h:'Current accumulated learning → one specific past situation.',e:'The tense switch signals the move from general experience to one story.'},
{q:'“I ___ several endurance challenges. Last month, I ___ one that required a very different pacing strategy.”',o:['have completed / did','completed / have done','have complete / did'],a:'have completed / did',h:'No date for the overall experience; “last month” for the example.',e:'Present Perfect + Past Simple is a common experience-to-example pattern.'},
{q:'“Marine and I ___ a lot from travelling together. On one trip, we ___ our plans completely.”',o:['have learned / changed','learned / have changed','have learn / changed'],a:'have learned / changed',h:'Overall impact now → specific trip.',e:'Use Present Perfect for what the experiences have taught you; Past Simple for the event.'},
{q:'“I ___ my English more seriously since my role ended. Last week, I ___ a full interview answer without notes.”',o:['have practised / gave','practised / have given','have practice / gave'],a:'have practised / gave',h:'Since = unfinished period; last week = finished time.',e:'The two time markers force the two different tenses.'},
{q:'“My career ___ me how important clear communication is. Early in my career, I ___ this the hard way.”',o:['has taught / learned','taught / have learned','has teach / learned'],a:'has taught / learned',h:'Career impact up to now → one early finished lesson.',e:'Present Perfect shows accumulated career impact; Past Simple gives the specific past experience.'},
{q:'“I ___ my professional pitch several times so far. Yesterday, I ___ one version to a friend.”',o:['have rewritten / showed','rewrote / have shown','have rewrite / showed'],a:'have rewritten / showed',h:'“So far” vs “yesterday”.',e:'Present Perfect for progress up to now; Past Simple for yesterday.'},
{q:'“I ___ interested in an international move for some time. A few months ago, I ___ to focus seriously on Australia.”',o:['have been / decided','was / have decided','have be / decided'],a:'have been / decided',h:'Ongoing interest → specific decision.',e:'Present Perfect for an unfinished state; Past Simple for the decision moment.'},
{q:'“I ___ many changes in my work. The biggest one ___ when my position ended.”',o:['have experienced / happened','experienced / has happened','have experience / happened'],a:'have experienced / happened',h:'Life/career experience → specific biggest example.',e:'General experience uses Present Perfect; the example uses Past Simple.'},
{q:'“I ___ to explain my work more simply recently. In my last role, I often ___ too much technical detail.”',o:['have learned / used','learned / have used','have learn / used'],a:'have learned / used',h:'Recent learning connected to now → finished previous role.',e:'Present Perfect describes recent progress; Past Simple describes your old habit in a closed role.'},
{q:'“I ___ several mistakes that improved the way I work. Once, I ___ an important detail in a first draft.”',o:['have made / missed','made / have missed','have make / missed'],a:'have made / missed',h:'General experience → one specific mistake.',e:'The Present Perfect can introduce mistakes as experience; Past Simple tells what happened.'},
{q:'“The transition ___ me more time to think. When my role ended, I ___ unsure about the next step.”',o:['has given / felt','gave / have felt','has gave / felt'],a:'has given / felt',h:'Ongoing benefit now → feeling at the finished moment.',e:'Present Perfect connects the transition to now; Past Simple describes the past reaction.'},
{q:'“I ___ more disciplined through sport. During one difficult event, I ___ how important pacing was.”',o:['have become / realised','became / have realised','have became / realised'],a:'have become / realised',h:'Current development → one specific event.',e:'Present Perfect describes who you have become; Past Simple gives the event that taught the lesson.'},
{q:'“We ___ several possible plans for Australia. Last weekend, we ___ one option in more detail.”',o:['have discussed / explored','discussed / have explored','have discuss / explored'],a:'have discussed / explored',h:'Overall planning up to now → last weekend.',e:'Present Perfect for the ongoing project; Past Simple for a finished discussion.'},
{q:'“I ___ new vocabulary for interviews. In the last lesson, I ___ several expressions for explaining experience.”',o:['have learned / practised','learned / have practised','have learn / practised'],a:'have learned / practised',h:'Accumulated learning → one finished lesson.',e:'Present Perfect summarises learning; Past Simple locates practice in a specific lesson.'},
{q:'“My priorities ___ since the reorganisation. Before it happened, I ___ mainly on my current role.”',o:['have changed / focused','changed / have focused','have change / focused'],a:'have changed / focused',h:'Since then → finished period before then.',e:'Present Perfect shows change up to now; Past Simple describes the old finished situation.'},
{q:'“I ___ more comfortable speaking spontaneously. At the beginning, I ___ much more time to prepare.”',o:['have become / needed','became / have needed','have became / needed'],a:'have become / needed',h:'Current progress → earlier finished phase.',e:'Present Perfect describes improvement; Past Simple describes how things were at the start.'},
{q:'“I ___ several different ways of explaining my job. Last session, one explanation ___ particularly well.”',o:['have tried / worked','tried / has worked','have try / worked'],a:'have tried / worked',h:'Several attempts up to now → one finished session.',e:'Present Perfect for repeated experience; Past Simple for the specific result.'},
{q:'“This career change ___ me think differently about work. When I first stopped working, I ___ mainly about finding another job quickly.”',o:['has made / thought','made / have thought','has make / thought'],a:'has made / thought',h:'Current effect → initial finished reaction.',e:'Present Perfect explains the continuing impact; Past Simple tells the first reaction.'}
];

const upgrade=[
{q:'Choose the best connector: “___, I spoke to the teams. After that, I mapped the workflow.”',o:['First','Since then','So far'],a:'First',h:'You are starting a finished sequence.',e:'“First” clearly opens a chronological story.'},
{q:'“The first solution did not work. ___, we tested a simpler approach.”',o:['After that','Ever','For'],a:'After that',h:'You need the next step in a finished sequence.',e:'“After that” moves the listener forward in time.'},
{q:'“The role ended three months ago. ___, I’ve focused on my English and Australia preparation.”',o:['Since then','Last year','At the time'],a:'Since then',h:'Connect the finished event to the period up to now.',e:'“Since then” is a natural bridge from Past Simple to Present Perfect.'},
{q:'“___, I was mainly focused on doing my job well. I wasn’t planning a major move abroad.”',o:['At the time','So far','Already'],a:'At the time',h:'Describe the situation around a specific past period.',e:'“At the time” sets past context.'},
{q:'“We had several options. ___, we chose the one that was easiest to implement.”',o:['Eventually','Ever','For'],a:'Eventually',h:'Show the final outcome after a process.',e:'“Eventually” works well for the final decision in a story.'},
{q:'“The experience was difficult. ___, it taught me to prepare more carefully.”',o:['However','Since','Yesterday'],a:'However',h:'Show contrast between difficulty and benefit.',e:'“However” introduces a contrasting positive consequence.'},
{q:'“The new process reduced delays. ___, the teams found it easier to use.”',o:['Moreover','Ago','Yet'],a:'Moreover',h:'Add another supporting result.',e:'“Moreover” adds a second point in more formal B2 speech.'},
{q:'“I’ve improved my interview answers. ___, I’ve become faster at choosing the right tense.”',o:['In addition','Last month','Then in 2024'],a:'In addition',h:'Add another current improvement.',e:'“In addition” links two present results cleanly.'},
{q:'“We changed the plan because the original option was no longer possible. ___, we found a better solution.”',o:['As a result','Ever','Since 2020'],a:'As a result',h:'Show consequence.',e:'“As a result” makes cause and consequence explicit.'},
{q:'“I didn’t understand the problem immediately. ___, I asked more questions and found the real cause.”',o:['So','For','Already'],a:'So',h:'Show the action caused by the problem.',e:'“So” is natural and conversational for cause → action.'},
{q:'Choose the clearest B2 upgrade: “I did a project. It was difficult. I learned a lot.”',o:['I worked on a challenging project, and the experience taught me a great deal.','I have done a project yesterday and learn a lot.','Project difficult, so much learning.'],a:'I worked on a challenging project, and the experience taught me a great deal.',h:'Keep the finished project in Past Simple and connect the ideas.',e:'A stronger answer combines precise vocabulary with a clear completed timeline.'},
{q:'Choose the clearest upgrade: “I have experience. In 2023 I managed a problem.”',o:['I’ve dealt with similar situations before; for example, in 2023 I managed a difficult process issue.','I dealt with situations before and have managed in 2023.','I experience a problem in 2023.'],a:'I’ve dealt with similar situations before; for example, in 2023 I managed a difficult process issue.',h:'General experience first, specific example second.',e:'This sentence demonstrates the key Present Perfect → Past Simple transfer pattern.'},
{q:'“I started preparing after the reorganisation, and ___ I’ve become much clearer about my goals.”',o:['since then','last year','ago'],a:'since then',h:'The preparation continues to influence now.',e:'“Since then” naturally introduces Present Perfect.'},
{q:'“The event was physically demanding. ___, I stayed focused on one stage at a time.”',o:['Nevertheless','For','Ever'],a:'Nevertheless',h:'Contrast the difficulty with your response.',e:'“Nevertheless” is a useful B2 connector for concession.'},
{q:'“I’ve worked with different teams, and ___ I’ve learned to adapt my communication style.”',o:['as a result','two years ago','yesterday'],a:'as a result',h:'Show the consequence of the accumulated experience.',e:'The Present Perfect can link experience to what it has taught you now.'},
{q:'Best ending for a story that matters now:',o:['That experience has made me more confident about handling change.','That experience made me more confident yesterday only.','That experience make confidence.'],a:'That experience has made me more confident about handling change.',h:'End by connecting the past story to your current ability.',e:'Present Perfect is effective for the lasting impact of a finished experience.'}
];

const vocab={
'Sequence & time':[
['🧭','at the time','à l’époque / à ce moment-là','during that specific past period','At the time, I was focused on improving the existing process.'],
['➡️','after that','après cela','the next step in a sequence','After that, I spoke to the teams and compared their feedback.'],
['🏁','eventually','finalement','after a process or a period of difficulty','Eventually, we agreed on a simpler solution.'],
['🔗','since then','depuis lors','from that past moment until now','Since then, I’ve become more comfortable with change.'],
['📍','so far','jusqu’à présent','up to the present moment','So far, I’ve focused on English and my Australia preparation.'],
['⚡','as a result','par conséquent','to introduce a consequence','As a result, the process became easier to use.']
],
'Experience & learning':[
['🧠','to learn from','tirer des enseignements de','to gain useful knowledge from an experience','I’ve learned a lot from projects that did not go exactly as planned.'],
['🔄','to adapt to','s’adapter à','to change your behaviour for a new situation','I had to adapt to a new team structure.'],
['💡','to realise','se rendre compte','to suddenly understand something important','I realised that the problem was not the tool itself.'],
['📈','to develop','développer','to improve a skill or quality over time','The experience has helped me develop more patience.'],
['🎯','to take away from','retenir de','to keep an important lesson from an experience','The main thing I took away from the project was the importance of listening first.'],
['🧱','to overcome','surmonter','to successfully deal with a difficulty','We overcame the problem by changing the plan early.']
],
'Career & studies':[
['⚙️','workflow','flux de travail','the sequence of steps used to complete work','I mapped the workflow before proposing any change.'],
['👥','stakeholder','partie prenante','a person or group affected by a project','I worked with stakeholders from several departments.'],
['📚','coursework','travaux / matières de formation','work completed as part of studies','My coursework taught me to organise information clearly.'],
['🧩','transferable skill','compétence transférable','a skill useful in different jobs and sectors','Problem solving is a transferable skill I can bring to a new role.'],
['🛠️','hands-on experience','expérience pratique','practical experience doing something directly','The role gave me hands-on experience of process improvement.'],
['🚪','transition','transition','a period between two stages','I’ve used the transition to prepare for my next step.']
],
'Challenge & sport':[
['🏃','to pace yourself','gérer son rythme','to control your effort so you can continue effectively','I had to pace myself carefully during the event.'],
['🔥','to push through','tenir bon / continuer malgré la difficulté','to continue despite fatigue or difficulty','I pushed through the difficult part without changing my plan.'],
['📊','to assess','évaluer','to judge a situation before deciding','I assessed how I felt before increasing the pace.'],
['🧘','to stay composed','rester calme','to remain calm under pressure','The challenge taught me to stay composed when I’m tired.'],
['🏅','milestone','étape importante','an important stage or achievement','Finishing the event was an important milestone.'],
['🔋','endurance','endurance','the ability to continue for a long time','Training has improved both my physical and mental endurance.']
],
'Australia & next step':[
['🇦🇺','to explore opportunities','explorer des opportunités','to investigate possible jobs or options','I’ve started exploring opportunities in Australia.'],
['🧳','to relocate','déménager / s’installer ailleurs','to move to another place to live or work','I’m open to relocating for the right opportunity.'],
['🌏','international exposure','exposition / expérience internationale','experience with other countries or cultures','I’m looking for more international exposure in my next step.'],
['🎯','to clarify your goals','clarifier ses objectifs','to become more precise about what you want','The transition has helped me clarify my goals.'],
['🌱','to build on experience','s’appuyer sur son expérience','to use previous experience as a base for progress','I want to build on my process-analysis experience in a new environment.'],
['🗣️','to articulate','exprimer clairement','to express an idea clearly and effectively','I’ve learned to articulate my experience more clearly in English.']
]};

const missions=[
{id:'studies',title:'Your studies → what they gave you',k:'STUDIES',prompt:'Explain what you studied, where or in what type of institution, how long you studied, one important project or challenge, and what the experience has given you now.',questions:['What did you study and for how long?','What was one memorable project or challenge?','What did you do?','What did you learn at the time?','How has that experience helped you since?'],must:'Use at least 4 Past Simple verbs + 2 Present Perfect forms. Add one finished-time marker and one “since / so far / over the years” idea.',b1:'I studied [your subject] for [length of time]. During my studies, I worked on several projects and learned how to organise information and meet deadlines. One project was especially difficult because we had limited time. I changed my plan, focused on the most important tasks and finished the work on time. The experience taught me to be more organised. Since then, I’ve used those skills in different professional situations.',b2:'I completed my studies in [your field] over [length of time]. One experience that stands out was a project that required me to manage several priorities at once. At first, I underestimated the amount of work involved, so I reorganised my approach and clarified the key requirements before moving forward. The project went well, and it taught me to plan more realistically. Since then, I’ve built on that experience in professional situations where structure and prioritisation have been essential.'},
{id:'career',title:'Six years of process analysis → one concrete success',k:'CAREER',prompt:'Summarise your six years in process analysis, then choose one specific project where you improved a workflow or helped teams work more effectively.',questions:['What did your role involve overall?','When did the specific project happen?','What problem did you identify?','What actions did you take?','What result did you get?','What has the experience taught you about your strengths?'],must:'Open with experience, then move to one finished Past Simple story. Finish with “It has taught me…” or “I’ve learned…”.',b1:'I’ve worked on many process-improvement situations during my career. In one project, the workflow involved several teams and created unnecessary delays. I spoke to the people who used the process, mapped the main steps and identified where the problems came from. We simplified the workflow and made the responsibilities clearer. The project went well, and it has taught me that practical feedback is essential before changing a process.',b2:'Over the course of my career, I’ve dealt with a wide range of process-improvement challenges. One project in particular involved a cross-functional workflow that had become unnecessarily complex. I interviewed the teams using it, mapped the existing process and identified several friction points. We then simplified the sequence and clarified ownership between departments. The result was a more practical workflow, and the experience has reinforced my belief that effective process work starts with understanding how people actually use a system.'},
{id:'transition',title:'Leaving your previous role → what you have done since',k:'TRANSITION',prompt:'Explain how your previous role ended, what you decided at the time, and how you have used the transition since then.',questions:['What happened to the role?','How did you react at first?','What did you decide to do?','What have you focused on since then?','What has become clearer?'],must:'Past Simple for the end of the role and your first decisions; Present Perfect for everything from then until now.',b1:'My role ended after a reorganisation. At first, it was a big change because I had worked in the same company for six years. I decided not to rush into another job immediately. Since then, I’ve improved my English, prepared for Australia and thought more carefully about the kind of role I want next. The transition has helped me become clearer about my priorities.',b2:'My previous position ended as part of a wider reorganisation after six years with the same company. Although the change was unexpected, I decided to use the transition deliberately rather than move straight into the first available role. Since then, I’ve strengthened my English, refined the way I present my experience and explored my options for Australia. The period has given me a clearer sense of the environment and responsibilities I want in my next role.'},
{id:'sport',title:'A demanding race or training challenge',k:'CHALLENGE',prompt:'Tell the story of a demanding race, training session or fitness challenge. Explain what made it difficult, how you reacted and what the experience has taught you.',questions:['When did it happen?','What was the objective?','What became difficult?','What did you do in response?','How did it end?','What has it taught you about yourself?'],must:'Use precise action verbs in the Past Simple. Finish with a Present Perfect reflection.',b1:'I’ve done several difficult sports challenges. In one event, I started well but became tired halfway through. I decided not to change my plan too quickly, so I focused on one stage at a time and controlled my pace. I finished the event and felt satisfied with the way I managed the pressure. The experience has taught me that I perform better when I stay calm and focus on the next step.',b2:'Sport has given me several opportunities to test how I react under pressure. During one demanding event, I felt strong at the start but began to lose energy halfway through. Instead of reacting emotionally, I reassessed my pace and focused on completing one stage at a time. I managed to finish consistently rather than pushing too hard too early. The experience has reinforced the importance of discipline, pacing and staying composed when the situation becomes uncomfortable.'},
{id:'marine',title:'A trip or challenge you shared with Marine',k:'TRAVEL',prompt:'Choose a trip, race, plan or unexpected situation you experienced with Marine. Tell what happened and explain what you have learned from managing things together.',questions:['Where or when did it happen?','What was the original plan?','What changed or became difficult?','How did you respond together?','What was the outcome?','What have you learned from the experience?'],must:'Tell the specific event in the Past Simple; use Present Perfect for the shared experience or what it has taught you.',b1:'Marine and I have shared several trips and challenges together. On one trip, our original plan changed at the last minute. We looked at the different options, discussed what was most practical and changed the itinerary. In the end, everything worked out well and the change made the trip more memorable. Experiences like that have taught us to stay flexible when plans change.',b2:'Marine and I have had a number of experiences where we needed to adapt quickly. On one trip, an unexpected change made our original plan impossible, so we compared the alternatives and reorganised the itinerary together. The situation was inconvenient at first, but we found a practical solution and ultimately enjoyed the revised plan. Experiences like that have shown me how useful calm communication and flexibility are when circumstances change unexpectedly.'},
{id:'unexpected',title:'A time you had to adapt quickly',k:'ADAPTABILITY',prompt:'Tell a story about an unexpected change at work or in everyday life. Show how you analysed the situation, what you did and what you have taken away from it.',questions:['What changed unexpectedly?','Why was it a problem?','What did you do first?','What solution did you choose?','What happened in the end?','How has it influenced the way you react now?'],must:'Use “at first / then / eventually / since then” to make the timeline easy to follow.',b1:'I’ve had to adapt to unexpected changes several times. In one situation, a plan changed just before we needed to act. At first, I was frustrated, but I looked at the available options and focused on what we could still control. We changed the plan and found another solution. Since then, I’ve become better at separating the problem from the emotion and looking for the next practical step.',b2:'I’ve encountered a number of situations where a last-minute change forced me to reconsider the original plan. In one case, an important assumption changed just before implementation. I first assessed what was still possible, then spoke to the people involved and helped define a workable alternative. We eventually delivered a solution without creating additional disruption. Since then, I’ve become much more deliberate about staying calm, clarifying constraints and identifying what can still be controlled.'},
{id:'mistake',title:'A mistake that improved the way you work',k:'LEARNING',prompt:'Choose a real mistake or an approach that did not work as expected. Explain what happened, how you corrected it and what you have done differently since.',questions:['What did you expect?','What went wrong?','How did you notice?','What did you change?','What was the final result?','What have you done differently since?'],must:'Keep the story constructive: problem → action → learning, not self-criticism.',b1:'I’ve made mistakes that helped me improve the way I work. In one project, I started with a solution before I had asked enough questions. Later, I realised that I had misunderstood one part of the problem. I went back to the team, clarified their needs and changed the proposal. The final solution was much better. Since then, I’ve made a point of understanding the situation fully before proposing a change.',b2:'Some of the most useful lessons in my career have come from approaches that did not work as expected. In one project, I moved too quickly toward a solution before I had fully understood the users’ constraints. Once I realised the gap, I reopened the discussion, gathered more detailed feedback and revised the proposal. The final outcome was stronger, and the experience has changed the way I approach improvement work: I now spend more time validating the problem before designing the solution.'},
{id:'team',title:'A time you brought different people together',k:'COLLABORATION',prompt:'Tell a story about people who had different priorities or opinions. Explain how you helped the situation move forward and what you have learned about communication.',questions:['Who was involved?','Why did they disagree?','What did you do?','How did the discussion change?','What result did you reach?','What has it taught you?'],must:'Use verbs such as clarify, listen, compare, agree, propose, align.',b1:'I’ve worked with teams that did not always have the same priorities. In one project, two departments wanted different solutions. I listened to both sides, clarified what each team really needed and helped compare the options. We agreed on a solution that was not perfect for either side but worked well for the overall process. The experience has taught me that listening carefully can make disagreement much easier to manage.',b2:'Throughout my career, I’ve often worked with stakeholders whose priorities did not initially align. In one project, two departments supported different approaches and the discussion had started to become unproductive. I reframed the conversation around the shared objective, clarified the constraints on both sides and helped the group compare the practical consequences of each option. We eventually agreed on a workable compromise. The experience has strengthened my ability to facilitate discussions without losing sight of the operational goal.'}
];

const interviewQs=[
{q:'Have you ever had to convince people to change the way they worked?',b1:'Yes, I have. In one project, some people were not convinced that a process needed to change. I listened to their concerns, showed them where the delays came from and proposed a simpler approach. We tested it and the team accepted the change. The experience has taught me that people usually need to understand the reason behind a change before they support it.',b2:'Yes, I have. In one process-improvement project, several users were sceptical because the existing method was familiar even though it created delays. I first listened to their concerns, then used concrete examples to show where the friction occurred and involved them in testing a simpler approach. The revised process was adopted more easily because the users had contributed to it. The experience has reinforced how important involvement and practical evidence are when introducing change.'},
{q:'Have you ever worked with people who strongly disagreed with each other?',b1:'Yes, I have. In one project, two teams wanted different solutions. I asked questions, clarified their priorities and helped them compare the options. We eventually found a solution they could both accept. It has taught me to focus on the shared objective instead of the disagreement itself.',b2:'Yes. I’ve worked in situations where stakeholders had genuinely competing priorities. In one case, I helped both teams separate their preferences from the actual operational requirements, then compare the impact of each option. That shifted the conversation from positions to practical consequences, and we reached a workable compromise. It has made me much more comfortable facilitating difficult discussions.'},
{q:'Have you ever learned something important from a mistake?',b1:'Yes, I have. Once, I proposed a solution too quickly and later realised I had missed an important detail. I went back, asked more questions and changed the proposal. Since then, I’ve taken more time to understand the problem before suggesting a solution.',b2:'Absolutely. In one project, I moved toward a solution before I had fully understood one user constraint. I caught the issue during the review stage, reopened the discussion and revised the proposal. Since then, I’ve become much more disciplined about validating assumptions early. That mistake has improved the way I approach analysis rather than simply making me more cautious.'},
{q:'Have you ever faced an unexpected problem during a trip or personal project?',b1:'Yes, I have. During one trip, our original plan changed unexpectedly. We checked the alternatives, changed the itinerary and found another solution. Everything worked out well in the end. It has taught me to stay flexible when plans change.',b2:'Yes. On one trip, an unexpected change made the original plan impossible. We quickly assessed the alternatives, prioritised what mattered most and reorganised the itinerary. The revised plan actually worked very well. Experiences like that have made me more comfortable adapting quickly without letting the initial frustration affect the decision.'},
{q:'Have you ever pushed yourself outside your comfort zone?',b1:'Yes, I have. Sport has given me several opportunities to do that. In one difficult event, I became very tired but stayed focused on one stage at a time and finished it. The experience has shown me that I can keep going when I stay calm and manage my effort.',b2:'Yes, particularly through endurance and fitness challenges. During one demanding event, I reached a point where continuing at the original pace was no longer realistic, so I adjusted my strategy rather than reacting emotionally. I completed the event consistently, and it has reinforced my confidence in dealing with discomfort by focusing on the next controllable step.'},
{q:'Have you ever changed an important plan because you received new information?',b1:'Yes, I have. In one project, new information showed that our first solution would not work. We stopped, reviewed the situation and chose another approach. The final result was better because we changed direction early. It has taught me not to stay attached to a plan when the facts change.',b2:'Yes. In one project, new operational information undermined one of the assumptions behind our initial solution. Rather than trying to protect the original plan, I helped the team reassess the constraints and redesign the approach. The final solution was stronger, and the experience has made me more comfortable treating a plan as something to test rather than something to defend.'},
{q:'Have you ever prepared for a major life change?',b1:'Yes, I have. My current transition is one example. When my previous role ended, I decided to think carefully about what I wanted next. Since then, I’ve improved my English, explored Australia and prepared more seriously for a new professional step.',b2:'Yes. My current transition has involved both professional and personal preparation. When my previous role ended, I chose not to treat the situation simply as a job search. Since then, I’ve strengthened my English, clarified the type of work environment I want and explored the practical steps involved in moving to Australia. The process has made the next move much more deliberate.'},
{q:'Have you ever had to explain something complex in a simple way?',b1:'Yes, I have. In my previous role, I often had to explain process problems to people from different teams. In one meeting, I used a simple example instead of technical language, and the discussion became much clearer. It has taught me to adapt the explanation to the person I’m speaking to.',b2:'Yes, frequently. Process work often required me to translate a complex workflow into something that made sense to people with different levels of technical knowledge. In one meeting, I replaced a detailed process description with a simple user journey and concrete examples. The discussion became much more productive. It has taught me that clarity is often more valuable than technical completeness.'}
];

const listeningStories=[
{title:'A process change that did not start well',text:'I have worked on several projects where the first solution did not work as expected. In one project two years ago, we introduced a new reporting step, but the teams found it too complicated. We collected their feedback, removed two unnecessary actions and tested the process again. Since then, I have become much more careful about involving users before a change is final.',q:'Why did the team change the first solution?',opts:['Because users found it too complicated.','Because the project had no deadline.','Because the company closed.'],a:'Because users found it too complicated.',retell:'Retell the story in 4–5 sentences. Start with the general experience, tell the specific event, then finish with the lesson that still matters now.',b1:'The speaker has worked on projects where the first solution did not work. Two years ago, the team introduced a new reporting step, but users found it too complicated. They collected feedback, removed unnecessary actions and tested it again. Since then, the speaker has become more careful about involving users early.',b2:'The speaker has experienced several projects where an initial solution needed to be revised. In one case two years ago, a new reporting step proved too complex for the teams using it. The team gathered feedback, simplified the process and tested the revised version. Since then, the speaker has placed much more emphasis on user involvement before finalising a change.'},
{title:'A training challenge',text:'I have taken part in several demanding fitness challenges. In one event last month, I started too quickly and felt tired earlier than expected. I reduced my pace, focused on one stage at a time and recovered enough to finish strongly. The experience has reminded me that good pacing is more useful than reacting emotionally when things become difficult.',q:'What did the speaker change during the event?',opts:['The speaker reduced the pace.','The speaker stopped immediately.','The speaker changed the event.'],a:'The speaker reduced the pace.',retell:'Retell the event and explain the lesson using the correct tense switch.',b1:'The speaker has done several difficult fitness challenges. Last month, one event became difficult because the speaker started too quickly. The speaker reduced the pace, focused on one stage at a time and finished strongly. The experience has shown the importance of pacing.',b2:'The speaker has completed a number of demanding fitness challenges. During one event last month, an overly fast start caused early fatigue. The speaker adjusted the pace, narrowed the focus to one stage at a time and recovered enough to finish well. The experience has reinforced the value of staying composed and adapting the strategy rather than reacting emotionally.'},
{title:'A career transition',text:'My career has changed significantly over the past few months. My previous role ended after a reorganisation, and I decided not to rush into another position. Since then, I have spent more time improving my English, clarifying my goals and preparing for Australia. The change was unexpected, but it has given me a useful opportunity to think more deliberately about my next step.',q:'What did the speaker decide when the role ended?',opts:['Not to rush into another position.','To stop learning English.','To return immediately to the same role.'],a:'Not to rush into another position.',retell:'Explain the finished event first, then what has happened since.',b1:'The speaker’s previous role ended after a reorganisation. The speaker decided not to take another job immediately. Since then, the speaker has improved English, clarified goals and prepared for Australia. The transition has created time to think about the next step.',b2:'The speaker’s previous position ended as part of a reorganisation, and instead of immediately moving into another role, the speaker chose to use the transition deliberately. Since then, the speaker has focused on English, career goals and Australia preparation. Although the change was unexpected, it has created space for a more considered next move.'},
{title:'A travel plan that changed',text:'Marine and I have had several trips where we needed to adapt quickly. On one trip, a transport problem changed our plan at the last minute. We compared the alternatives, booked a different route and adjusted the rest of the itinerary. The day was stressful at first, but everything worked out. Experiences like that have taught us to stay flexible and focus on practical solutions.',q:'How did they respond to the transport problem?',opts:['They compared alternatives and changed the route.','They cancelled every future trip.','They ignored the problem.'],a:'They compared alternatives and changed the route.',retell:'Retell the specific trip, then explain what experiences like this have taught them.',b1:'They have had several trips where they needed to adapt. On one trip, a transport problem changed the plan. They compared alternatives, booked another route and changed the itinerary. Everything worked out. Experiences like that have taught them to stay flexible.',b2:'They have experienced several trips that required quick adaptation. In this particular case, a transport problem disrupted the original plan at the last minute. They assessed the alternatives, booked a different route and reorganised the itinerary. The situation was initially stressful, but it ended well, and similar experiences have strengthened their ability to focus on practical solutions when plans change.'}
];

const vtestPrompts=[
{title:'A professional challenge you solved',prompt:'Describe a professional challenge you have faced. Tell one specific example, explain what you did and say what the experience has taught you.',b1:'I’ve faced several challenges in process work. In one project, two teams did not agree about the best solution. I listened to both sides, clarified the priorities and helped them compare the options. We agreed on a practical compromise. The experience has taught me to focus on the shared objective and keep the discussion concrete.',b2:'I’ve encountered several situations where stakeholders had competing priorities. In one project, two teams supported different solutions and the discussion had stalled. I clarified the constraints on both sides, reframed the conversation around the shared operational objective and helped the group compare the practical impact of each option. We eventually reached a workable compromise. The experience has strengthened my ability to facilitate disagreement without losing sight of the outcome.'},
{title:'An experience that changed the way you work',prompt:'Describe an experience that changed the way you approach your work. What happened, and what have you done differently since?',b1:'One experience changed the way I approach process improvement. In a project, I proposed a solution before I had asked enough questions. Later, I realised that I had missed an important user need. I went back, collected more feedback and changed the proposal. Since then, I’ve spent more time understanding the problem before designing the solution.',b2:'One project significantly changed the way I approach improvement work. I moved too quickly toward a solution before validating one of the user constraints. Once I identified the gap, I reopened the discussion, gathered more detailed feedback and revised the proposal. The final solution was much stronger. Since then, I’ve become more disciplined about validating assumptions before moving into solution design.'},
{title:'A challenge outside work',prompt:'Talk about a difficult sport, travel or personal challenge. Explain what happened and what it has shown you about yourself.',b1:'I’ve completed several difficult sports challenges. In one event, I became very tired halfway through. I reduced my pace, stayed focused on one stage at a time and finished the event. It has shown me that I can handle difficult moments better when I stay calm and concentrate on what I can control.',b2:'I’ve used sport as a way to test how I respond when things become uncomfortable. During one demanding event, I lost energy earlier than expected and had to adjust my strategy. I reduced the pace, focused on the next stage rather than the finish and recovered enough to complete the event consistently. It has reinforced my confidence in staying composed and making practical adjustments under pressure.'},
{title:'A major change you have prepared for',prompt:'Describe a major change you have prepared for. What triggered it, what have you done since, and what are you aiming for now?',b1:'My current professional transition is a major change. My previous role ended after a reorganisation, and I decided to think carefully about my next step. Since then, I’ve improved my English, researched Australia and prepared my professional story. I’m now aiming to find a role where I can use my experience in a new environment.',b2:'My current transition has involved a significant professional and personal change. It began when my previous role ended as part of a wider reorganisation. Rather than moving immediately into another position, I chose to use the time deliberately. Since then, I’ve strengthened my English, clarified the value I can bring to a new team and explored the Australian job market. I’m now aiming for a role that builds on my experience while giving me broader international exposure.'},
{title:'A time you had to adapt',prompt:'Describe a time when a plan changed unexpectedly. How did you respond, and how has the experience influenced the way you deal with change now?',b1:'I’ve had to adapt to unexpected changes several times. In one situation, an important part of the plan changed just before we needed to act. I looked at the alternatives, discussed the options with the people involved and helped choose another solution. Since then, I’ve become better at staying calm and focusing on what can still be controlled.',b2:'I’ve dealt with a number of situations where a late change made the original plan unrealistic. In one case, a key assumption changed shortly before implementation. I reassessed what was still possible, clarified the new constraints with the stakeholders and helped define an alternative approach. Since then, I’ve become much more deliberate about separating the initial frustration from the practical decision that needs to be made.'},
{title:'A skill you have developed over time',prompt:'Choose one skill you have developed over time. Give a specific example of when you used it and explain why it matters for your next step.',b1:'I’ve developed my ability to explain complex ideas more clearly. In my previous role, I sometimes had to present process problems to people from different teams. In one meeting, I used a simple example instead of technical language, and the discussion became easier. This skill has become important because I want to communicate confidently in an international environment.',b2:'One skill I’ve developed over time is the ability to translate complex information into clear, practical language. In my previous role, I often worked with people who had very different levels of familiarity with a process. In one meeting, I replaced a technical explanation with a simple user journey, which immediately improved the discussion. That ability has become increasingly important as I prepare for a more international professional environment.'}
];

const writingPrompts=[
{title:'Career transition',prompt:'Write about how your previous role ended, what you decided at the time and what you have done since to prepare for your next step.',hint:'Paragraph 1: Past Simple event + first reaction. Paragraph 2: since then + Present Perfect actions. Finish with what the transition has taught you.',b1:'My previous role ended after a reorganisation. I had worked in the same company for six years, so the change was important. I decided not to rush into another position immediately. Since then, I’ve focused on improving my English and preparing for Australia. I’ve also spent time thinking about the type of role I want and the strengths I can bring to a new team. The transition has helped me become clearer about my priorities and more confident about making a professional change.',b2:'My previous position ended as part of a wider reorganisation after six years with the same company. Although the change was unexpected, I decided not to move immediately into the first available role. Since then, I’ve used the transition productively: I’ve strengthened my English, refined the way I present my experience and explored opportunities in Australia. I’ve also become much clearer about the type of environment in which I work best. The experience has shown me that an unexpected transition can create space for a more deliberate next step.'},
{title:'A challenge and what it taught you',prompt:'Write about a professional, sport or travel challenge. Tell the specific story, then explain what the experience has taught you or changed since.',hint:'Open with “I’ve faced…” or “I’ve completed…”. Switch to Past Simple for one event. End with “It has taught me…”',b1:'I’ve faced several situations that required me to stay calm under pressure. One example was a difficult fitness event. I started well but became tired earlier than expected. I reduced my pace, focused on one stage at a time and continued without panicking. I finished the event and felt satisfied with the way I managed the difficult part. The experience has taught me that I make better decisions when I stay calm and focus on the next step instead of the whole problem.',b2:'I’ve had several experiences that tested the way I respond under pressure. During one demanding fitness event, I lost energy earlier than expected because I had started too quickly. Rather than forcing the original pace, I reassessed the situation, adjusted my effort and focused on completing one stage at a time. I recovered enough to finish consistently. The experience has reinforced the importance of staying composed, adapting the plan when the facts change and concentrating on what can still be controlled.'},
{title:'An experience that improved a skill',prompt:'Choose a skill such as communication, organisation, adaptability or problem solving. Tell a past event that developed it and explain how you have used the skill since.',hint:'Present Perfect: “I’ve developed…” → Past Simple example → Present Perfect: “Since then, I’ve…”',b1:'I’ve developed my ability to communicate with different teams. In one project, two departments had different priorities and the discussion became difficult. I listened to both sides, clarified what each team needed and helped them compare the options. We eventually found a solution that worked for everyone. Since then, I’ve used the same approach in other discussions. The experience has helped me become more patient and more focused on the shared objective.',b2:'I’ve developed a much stronger ability to manage conversations between people with different priorities. One project was particularly useful because two departments supported competing solutions and the discussion had become unproductive. I clarified the constraints on both sides, reframed the conversation around the shared operational objective and helped the teams compare the consequences of each option. We eventually reached a practical compromise. Since then, I’ve applied the same principle in other situations: understand the interests first, then move the discussion toward a common outcome.'}
];

function initStats(){state.sectionStats={activation:{c:0,a:0,max:activation.length},pastStory:{c:0,a:0,max:pastStory.length},bridge:{c:0,a:0,max:bridge.length},listening:{c:0,a:0,max:listeningStories.length},upgrade:{c:0,a:0,max:upgrade.length}}}
initStats();

function renderDeck(containerId,data,section){const box=$('#'+containerId);let idx=0,answered=false;function draw(){const item=data[idx];const opts=shuffle(item.o);box.innerHTML=`<div class="deck-shell" data-section="${section}"><div class="deck-top"><span class="deck-count">${idx+1} / ${data.length}</span><button class="btn ghost deck-hint" type="button">Hint</button></div><div class="deck-question">${esc(item.q)}</div><div class="deck-options">${opts.map(o=>`<button class="deck-option" type="button" data-value="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="deck-feedback neutral">Choose an answer.</div><div class="deck-actions"><button class="btn secondary deck-next" type="button" ${idx===data.length-1?'disabled':''}>Next →</button><button class="btn ghost deck-restart" type="button">↻ Restart bank</button></div></div>`;answered=false}
box.addEventListener('click',e=>{const item=data[idx];const opt=e.target.closest('.deck-option');if(opt&&!answered){answered=true;const ok=norm(opt.dataset.value)===norm(item.a);$$('.deck-option',box).forEach(b=>{b.disabled=true;if(norm(b.dataset.value)===norm(item.a))b.classList.add('correct')});if(!ok)opt.classList.add('wrong');const fb=$('.deck-feedback',box);fb.className='deck-feedback '+(ok?'ok':'bad');fb.textContent=(ok?'Correct. ':'Not quite. ')+item.e;state.attempted++;if(ok)state.correct++;const st=state.sectionStats[section];st.a++;if(ok)st.c++;updateOverall();renderQualiopi()}
if(e.target.closest('.deck-hint')){const fb=$('.deck-feedback',box);fb.className='deck-feedback hint';fb.textContent='Hint: '+item.h}
if(e.target.closest('.deck-next')&&idx<data.length-1){idx++;draw()}
if(e.target.closest('.deck-restart')){idx=0;draw()}});draw()}

function setupVocab(){const sel=$('#vocabCategory');sel.innerHTML=Object.keys(vocab).map(k=>`<option>${esc(k)}</option>`).join('');function draw(){const list=vocab[sel.value];$('#vocabCards').innerHTML=list.map(([icon,word,fr,def,ex])=>`<article class="vocab-card"><h3><span>${icon} ${esc(word)}</span><button class="listen-chip" type="button" data-speak="${esc(ex)}">🔊</button></h3><p class="fr french-help">${esc(fr)}</p><p>${esc(def)}</p><p class="example">“${esc(ex)}”</p></article>`).join('')}sel.onchange=draw;draw()}

function renderMission(){const m=missions.find(x=>x.id===$('#missionSelect').value)||missions[0];const saved=state.missionNotes[m.id]||'';$('#missionPanel').innerHTML=`<article class="mission-panel"><span class="mission-kicker">${esc(m.k)}</span><h3>${esc(m.title)}</h3><p>${esc(m.prompt)}</p><div class="prompt-list">${m.questions.map((q,i)=>`<div><b>${i+1}.</b> ${esc(q)}</div>`).join('')}</div><div class="must-use"><b>Accuracy target:</b> ${esc(m.must)}</div><div class="timer-box" data-seconds="90"><span class="timer-display">01:30</span><div><button class="btn primary timer-start" type="button">▶ Start</button><button class="btn ghost timer-reset" type="button">↻ Reset</button></div></div><textarea class="notes-box" id="missionNotes" placeholder="Keywords only — do not write a full script...">${esc(saved)}</textarea><div class="button-row"><button class="btn ghost" type="button" data-speak="${esc(m.prompt)}">🔊 Listen to prompt</button><button class="btn secondary model-toggle" data-model="missionModels" type="button">Show two models</button></div><div id="missionModels" class="models hidden"><article><h4>Strong B1</h4><p>${esc(m.b1)}</p><button class="listen-chip" type="button" data-speak="${esc(m.b1)}">🔊</button></article><article><h4>B2 / VTest target</h4><p>${esc(m.b2)}</p><button class="listen-chip" type="button" data-speak="${esc(m.b2)}">🔊</button></article></div></article>`;$('#missionNotes').oninput=e=>{state.missionNotes[m.id]=e.target.value;saveLearner()}}
function setupMissions(){const sel=$('#missionSelect');sel.innerHTML=missions.map(m=>`<option value="${m.id}">${esc(m.title)}</option>`).join('');sel.onchange=renderMission;renderMission()}

function renderInterview(){const x=interviewQs[state.interviewIndex];$('#interviewPanel').innerHTML=`<article class="interview-card"><div class="deck-count">QUESTION ${state.interviewIndex+1} / ${interviewQs.length}</div><p class="question">${esc(x.q)}</p><div class="interview-answer-map"><article><span>1 · EXPERIENCE</span><b>Yes, I have / No, I haven't...</b></article><article><span>2 · EXAMPLE</span><b>When / what happened / what you did</b></article><article><span>3 · NOW</span><b>It has taught me... / Since then...</b></article></div><div class="timer-box" data-seconds="75"><span class="timer-display">01:15</span><div><button class="btn primary timer-start" type="button">▶ Start</button><button class="btn ghost timer-reset" type="button">↻ Reset</button></div></div><textarea class="interview-notes" placeholder="Keywords / correction notes..."></textarea><button class="btn secondary model-toggle" data-model="interviewModels" type="button">Show two models</button><div id="interviewModels" class="models hidden"><article><h4>Strong B1</h4><p>${esc(x.b1)}</p><button class="listen-chip" data-speak="${esc(x.b1)}" type="button">🔊</button></article><article><h4>B2 / VTest target</h4><p>${esc(x.b2)}</p><button class="listen-chip" data-speak="${esc(x.b2)}" type="button">🔊</button></article></div></article>`}

function renderListening(){const x=listeningStories[state.listeningIndex];$('#listeningPanel').innerHTML=`<article class="listening-card"><div class="deck-count">STORY ${state.listeningIndex+1} / ${listeningStories.length}</div><h3>${esc(x.title)}</h3><div class="audio-row"><button class="btn primary" type="button" data-speak="${esc(x.text)}">🔊 Play story</button><button class="btn ghost transcript-toggle" type="button">Show transcript</button></div><div class="transcript hidden">${esc(x.text)}</div><div><b>Comprehension:</b> ${esc(x.q)}</div><div class="deck-options listening-options">${x.opts.map(o=>`<button class="deck-option listening-option" data-value="${esc(o)}" type="button">${esc(o)}</button>`).join('')}</div><div class="deck-feedback neutral listening-feedback">Listen first, then answer.</div><div class="retell-box"><b>Retell:</b> ${esc(x.retell)}<textarea placeholder="Keywords for your retell..."></textarea><button class="btn secondary model-toggle" data-model="listenModels" type="button">Show two retell models</button><div id="listenModels" class="models hidden"><article><h4>Strong B1</h4><p>${esc(x.b1)}</p><button class="listen-chip" type="button" data-speak="${esc(x.b1)}">🔊</button></article><article><h4>B2 / VTest target</h4><p>${esc(x.b2)}</p><button class="listen-chip" type="button" data-speak="${esc(x.b2)}">🔊</button></article></div></div></article>`}

function setupListeningEvents(){let answeredSet=new Set();$('#listeningPanel').addEventListener('click',e=>{const x=listeningStories[state.listeningIndex];const t=e.target.closest('.transcript-toggle');if(t){const tr=$('.transcript',$('#listeningPanel'));tr.classList.toggle('hidden');t.textContent=tr.classList.contains('hidden')?'Show transcript':'Hide transcript'}const o=e.target.closest('.listening-option');if(o&&!answeredSet.has(state.listeningIndex)){answeredSet.add(state.listeningIndex);const ok=norm(o.dataset.value)===norm(x.a);$$('.listening-option',$('#listeningPanel')).forEach(b=>{b.disabled=true;if(norm(b.dataset.value)===norm(x.a))b.classList.add('correct')});if(!ok)o.classList.add('wrong');const fb=$('.listening-feedback',$('#listeningPanel'));fb.className='deck-feedback '+(ok?'ok':'bad');fb.textContent=ok?'Correct. You caught the key action.':'Not quite. Replay the story and listen for the action after the problem.';state.attempted++;if(ok)state.correct++;state.sectionStats.listening.a++;if(ok)state.sectionStats.listening.c++;updateOverall();renderQualiopi()}});$('#nextListening').onclick=()=>{state.listeningIndex=(state.listeningIndex+1)%listeningStories.length;renderListening()}}

function renderVtest(){const x=vtestPrompts[Number($('#vtestPromptSelect').value)||0];$('#vtestPromptPanel').innerHTML=`<article class="vtest-prompt-card"><h3>${esc(x.title)}</h3><p>${esc(x.prompt)}</p><div class="must-use"><b>Structure:</b> experience → one specific finished example → result → impact now.</div><div class="timer-box" data-seconds="90"><span class="timer-display">01:30</span><div><button class="btn primary timer-start" type="button">▶ Start</button><button class="btn ghost timer-reset" type="button">↻ Reset</button></div></div><textarea placeholder="Preparation keywords only..."></textarea><div class="button-row"><button class="btn ghost" data-speak="${esc(x.prompt)}" type="button">🔊 Listen</button><button class="btn secondary model-toggle" data-model="vtestModels" type="button">Show two models</button></div><div id="vtestModels" class="models hidden"><article><h4>Strong B1</h4><p>${esc(x.b1)}</p><button class="listen-chip" type="button" data-speak="${esc(x.b1)}">🔊</button></article><article><h4>B2 / VTest target</h4><p>${esc(x.b2)}</p><button class="listen-chip" type="button" data-speak="${esc(x.b2)}">🔊</button></article></div></article>`}
function setupVtest(){const s=$('#vtestPromptSelect');s.innerHTML=vtestPrompts.map((x,i)=>`<option value="${i}">${esc(x.title)}</option>`).join('');s.onchange=renderVtest;renderVtest()}

function renderWritingPrompt(){const x=writingPrompts[Number($('#writingPromptSelect').value)||0];$('#writingPromptText').textContent=x.prompt;$('#writingModels').innerHTML=`<article><h4>Strong B1</h4><p>${esc(x.b1)}</p><button class="listen-chip" type="button" data-speak="${esc(x.b1)}">🔊</button></article><article><h4>B2 / VTest target</h4><p>${esc(x.b2)}</p><button class="listen-chip" type="button" data-speak="${esc(x.b2)}">🔊</button></article>`;$('#writingModels').classList.add('hidden');$('#showWritingModels').textContent='Show two models';$('#writingFeedback').className='feedback neutral';$('#writingFeedback').textContent='Write first, then check your structure.'}
function setupWriting(){const s=$('#writingPromptSelect');s.innerHTML=writingPrompts.map((x,i)=>`<option value="${i}">${esc(x.title)}</option>`).join('');s.onchange=renderWritingPrompt;const ta=$('#writingAnswer');ta.value=localStorage.getItem('antoine-story-writing')||'';function wc(){const n=ta.value.trim()?ta.value.trim().split(/\s+/).length:0;$('#wordCount').textContent=n+' words';localStorage.setItem('antoine-story-writing',ta.value)}ta.oninput=wc;wc();$('#writingHint').onclick=()=>{$('#writingFeedback').className='feedback hint';$('#writingFeedback').textContent='Hint: '+writingPrompts[Number(s.value)||0].hint};$('#checkWriting').onclick=()=>{const text=ta.value,words=text.trim()?text.trim().split(/\s+/).length:0;const perfect=/(have|has|'ve|'s)\s+(been|had|worked|learned|developed|done|made|become|improved|prepared|used|faced|completed|changed|helped|shown|taken|given|built|dealt)/i.test(text);const past=/\b(worked|ended|decided|spoke|changed|looked|found|went|took|made|felt|became|realised|learned|started|finished|managed|helped|asked|clarified|agreed|tested|introduced|reorganised|focused)\b/i.test(text);const marker=/\b(last|ago|in 20\d\d|when|one time|during|at the time)\b/i.test(text);const connector=/\b(first|then|after that|eventually|however|as a result|since then|so far|in the end)\b/i.test(text);const now=/\b(since then|so far|recently|has taught|have learned|has helped|have become|has made)\b/i.test(text);let score=[perfect,past,marker,connector,now].filter(Boolean).length;$('#writingFeedback').className='feedback '+(score>=4?'ok':score>=2?'hint':'bad');$('#writingFeedback').textContent=`Structure check: ${score}/5 signals found. ${words<100?'Develop the answer more. ':words>170?'Try to be more concise. ':''}${!perfect?'Add a clear Present Perfect experience/current-impact sentence. ':''}${!past?'Add a specific finished Past Simple event. ':''}${!marker?'Add a finished-time marker. ':''}${!connector?'Use clearer sequencing connectors. ':''}${!now?'Finish by connecting the experience to now. ':''}`};$('#showWritingModels').onclick=()=>{$('#writingModels').classList.toggle('hidden');$('#showWritingModels').textContent=$('#writingModels').classList.contains('hidden')?'Show two models':'Hide models'};renderWritingPrompt()}

function setupTimers(){document.addEventListener('click',e=>{const start=e.target.closest('.timer-start'),reset=e.target.closest('.timer-reset');if(start){const box=start.closest('.timer-box');if(box._timer)return;box._remaining=box._remaining??Number(box.dataset.seconds||90);box._timer=setInterval(()=>{box._remaining--;const m=String(Math.floor(box._remaining/60)).padStart(2,'0'),s=String(box._remaining%60).padStart(2,'0');$('.timer-display',box).textContent=`${m}:${s}`;if(box._remaining<=0){clearInterval(box._timer);box._timer=null;speak('Time. Finish your final sentence.')}},1000)}if(reset){const box=reset.closest('.timer-box');if(box._timer)clearInterval(box._timer);box._timer=null;box._remaining=Number(box.dataset.seconds||90);const m=String(Math.floor(box._remaining/60)).padStart(2,'0'),s=String(box._remaining%60).padStart(2,'0');$('.timer-display',box).textContent=`${m}:${s}`}})}

function toggleDone(btn){const sec=btn.closest('[data-track="section"]'),idx=$$('[data-track="section"]').indexOf(sec);if(state.completed.has(idx)){state.completed.delete(idx);btn.classList.remove('completed');btn.textContent='✓ Mark complete'}else{state.completed.add(idx);btn.classList.add('completed');btn.textContent='✓ Completed'}updateProgress()}
function updateProgress(){const total=$$('[data-track="section"]').length,p=Math.round(state.completed.size/total*100);$('#progressBar').style.width=p+'%';$('#progressText').textContent=p+'%'}
function updateOverall(){$('#overallScore').textContent=`${state.correct} / ${state.attempted}`}

const sectionDefs=[
{id:'activation',objective:'Choisir correctement Past Simple ou Present Perfect avant de raconter une expérience',subject:'Marqueurs temporels, expérience générale, événements finis',method:'18 QCM un par un avec feedback et indices',max:activation.length},
{id:'pastStory',objective:'Construire une chronologie claire au Past Simple',subject:'When → context → action → result → reflection',method:'18 exercices de progression narrative',max:pastStory.length},
{id:'bridge',objective:'Passer naturellement du Present Perfect au Past Simple puis revenir au présent',subject:'Experience → specific story → impact now',method:'20 exercices contrastifs guidés',max:bridge.length},
{id:'listening',objective:'Identifier les changements de temps dans un récit oral et reformuler',subject:'Carrière, sport, transition, voyage',method:'Écoute, QCM, transcription facultative, reformulation',max:listeningStories.length},
{id:'upgrade',objective:'Structurer un récit avec des connecteurs et marqueurs chronologiques précis',subject:'first, after that, eventually, since then, as a result, nevertheless',method:'16 QCM de précision et enrichissement',max:upgrade.length},
{id:'oral-story',objective:'Raconter une expérience personnelle ou professionnelle structurée',subject:'Études, carrière, sport, voyage, adaptation, apprentissage',method:'Évaluation orale manuelle',manual:true},
{id:'oral-vtest',objective:'Répondre spontanément à une consigne de type VTest avec une chronologie claire',subject:'Expérience → exemple → impact actuel',method:'Production orale chronométrée',manual:true},
{id:'writing',objective:'Rédiger un récit cohérent en combinant les deux temps',subject:'Transition, challenge ou développement d’une compétence',method:'Production écrite 120–150 mots',manual:true}
];
function statusFrom(c,max,a){if(!a)return'not-started';const p=Math.round(c/max*100);return p>=80?'achieved':p>=50?'progress':'not-achieved'}
function statusLabel(s){return{achieved:'Objectif atteint',progress:'Objectif en cours d’acquisition','not-achieved':'Objectif non atteint','not-started':'Non commencé'}[s]||s}
function renderQualiopi(){const rows=$('#evaluationRows');if(!rows)return;rows.innerHTML=sectionDefs.map(d=>{if(d.manual){const s=state.manualStatus[d.id]||'not-started';return `<tr><td>${esc(d.objective)}</td><td>${esc(d.subject)}</td><td>${esc(d.method)}</td><td>Évaluation manuelle</td><td><span class="status ${s}">${statusLabel(s)}</span></td></tr>`}const st=state.sectionStats[d.id]||{c:0,a:0,max:d.max},s=statusFrom(st.c,d.max,st.a),pct=d.max?Math.round(st.c/d.max*100):0;return `<tr><td>${esc(d.objective)}</td><td>${esc(d.subject)}</td><td>${esc(d.method)}</td><td>${st.c}/${d.max} — ${pct}%</td><td><span class="status ${s}">${statusLabel(s)}</span></td></tr>`}).join('');refreshAdmin(false)}
function setupAdmin(){const saved=JSON.parse(localStorage.getItem('antoine-story-admin')||'{}');$('#adminDate').value=new Date().toISOString().slice(0,10);['adminSession','adminDuration','adminRemaining','adminDate'].forEach(id=>{if(saved[id]!=null)$('#'+id).value=saved[id];$('#'+id).oninput=saveAdmin});$$('[data-manual-status]').forEach(sel=>{const id=sel.dataset.manualStatus;if(saved.manualStatus?.[id])sel.value=saved.manualStatus[id];state.manualStatus[id]=sel.value;sel.onchange=()=>{state.manualStatus[id]=sel.value;saveAdmin();renderQualiopi()}});$$('[data-manual-comment]').forEach(t=>{const id=t.dataset.manualComment;t.value=saved.manualComments?.[id]||'';state.manualComments[id]=t.value;t.oninput=()=>{state.manualComments[id]=t.value;saveAdmin();refreshAdmin(false)}});$('#refreshAdmin').onclick=()=>refreshAdmin(true);$('#copySpreadsheetRow').onclick=copySpreadsheetRow;$('#copyAdminSummary').onclick=copyAdminSummary;$$('.copy-btn').forEach(b=>b.onclick=()=>copyText($('#'+b.dataset.copy).value));renderQualiopi()}
function saveAdmin(){const x={};['adminSession','adminDuration','adminRemaining','adminDate'].forEach(id=>x[id]=$('#'+id).value);x.manualStatus=state.manualStatus;x.manualComments=state.manualComments;localStorage.setItem('antoine-story-admin',JSON.stringify(x))}
function refreshAdmin(show){if(!$('#adminObjectives'))return;$('#adminObjectives').value='Transférer la maîtrise du Past Simple et du Present Perfect vers des récits réels ; raconter des événements passés avec une chronologie claire ; présenter une expérience générale puis développer un exemple précis ; relier une expérience passée à son impact actuel ; développer la fluidité et la précision en production orale et écrite dans des contextes personnels et professionnels.';$('#adminContent').value='Réactivation ciblée Past Simple / Present Perfect ; vocabulaire de narration, expérience, carrière, études, challenge et Australie ; construction d’un événement fini au Past Simple ; schéma Present Perfect → Past Simple → Present Perfect ; récits liés aux études, six années de process analysis, transition professionnelle, sport, voyages avec Marine, adaptation et apprentissage ; questions Have you ever…? ; compréhension orale et reformulation ; connecteurs narratifs ; production orale chronométrée type VTest ; production écrite 120–150 mots.';$('#adminMethods').value='Progression du guidé vers l’autonome ; exercices interactifs un par un ; feedback immédiat et bouton indice ; vocabulaire FR/EN avec exemples et audio manuel ; modèles Strong B1 et B2/VTest pour chaque mission ouverte ; écoute sans transcription puis transcription facultative ; minuteurs de production orale ; reformulation ; challenge mode ; auto-évaluation ; suivi automatique des résultats et évaluation manuelle de l’oral/écrit.';const auto=sectionDefs.filter(d=>!d.manual).map(d=>{const st=state.sectionStats[d.id]||{c:0,a:0,max:d.max};return `${d.objective}: ${statusLabel(statusFrom(st.c,d.max,st.a))} (${st.c}/${d.max})`}).join(' | ');const man=sectionDefs.filter(d=>d.manual).map(d=>`${d.objective}: ${statusLabel(state.manualStatus[d.id]||'not-started')}${state.manualComments[d.id]?` — ${state.manualComments[d.id]}`:''}`).join(' | ');$('#adminEvaluation').value=auto+' | '+man;$('#adminResource').value='Page web interactive : '+(location.protocol==='file:'?'[ajouter le lien publié de la leçon]':location.href)+' — HTML/CSS/JS, exercices interactifs, vocabulaire, audio manuel, feedback immédiat, indices, modèles à deux niveaux, production orale/écrite et suivi Qualiopi.';if(show){$('#copyStatus').textContent='Admin text refreshed.';setTimeout(()=>$('#copyStatus').textContent='',1800)}}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}$('#copyStatus').textContent='Copied.';setTimeout(()=>$('#copyStatus').textContent='',1800)}
function copySpreadsheetRow(){refreshAdmin(false);copyText([$('#adminSession').value,$('#adminDuration').value,$('#adminRemaining').value,$('#adminDate').value,$('#adminObjectives').value,$('#adminContent').value,$('#adminMethods').value,$('#adminEvaluation').value,$('#adminResource').value].join('\t'))}
function copyAdminSummary(){refreshAdmin(false);copyText(`Session: ${$('#adminSession').value}\nDurée: ${$('#adminDuration').value}\nHeures restantes: ${$('#adminRemaining').value}\nDate: ${$('#adminDate').value}\n\nObjectifs:\n${$('#adminObjectives').value}\n\nContenu:\n${$('#adminContent').value}\n\nMéthodes:\n${$('#adminMethods').value}\n\nÉvaluation:\n${$('#adminEvaluation').value}\n\nRessource:\n${$('#adminResource').value}`)}
function saveLearner(){localStorage.setItem('antoine-story-notes',JSON.stringify(state.missionNotes))}
function loadLearner(){try{state.missionNotes=JSON.parse(localStorage.getItem('antoine-story-notes')||'{}')}catch{state.missionNotes={}}}
function downloadResults(){refreshAdmin(false);const text=['ANTOINE · EXPERIENCE STORYTELLING CAREER SPRINT','==============================================',`Interactive score: ${state.correct}/${state.attempted}`,`Progress: ${$('#progressText').textContent}`,'','STORY MISSION NOTES',...Object.entries(state.missionNotes).flatMap(([k,v])=>[k.toUpperCase(),v||'(blank)','']),'WRITING',$('#writingAnswer').value||'(blank)','','FINAL NOTES',$('#finalNotes').value||'(blank)','','EXIT CHECK',`Present Perfect: ${$('#exitPerfect').value||'(blank)'}`,`Past Simple: ${$('#exitPast').value||'(blank)'}`,`Next target: ${$('#exitTarget').value||'(blank)'}`,'','QUALIOPI',$('#adminEvaluation').value].join('\n');const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Antoine_Experience_Storytelling_results.txt';a.click();URL.revokeObjectURL(a.href)}
function resetAll(){if(!confirm('Reset learner answers, scores and progress? Teacher/admin fields will be kept.'))return;localStorage.removeItem('antoine-story-notes');localStorage.removeItem('antoine-story-writing');location.reload()}

document.addEventListener('click',e=>{const sp=e.target.closest('[data-speak]');if(sp)speak(sp.dataset.speak);const done=e.target.closest('.done-btn');if(done)toggleDone(done);const model=e.target.closest('.model-toggle');if(model){const b=$('#'+model.dataset.model);if(b){b.classList.toggle('hidden');model.textContent=b.classList.contains('hidden')?'Show two models':'Hide models'}}});
$('#accentSelect').onchange=e=>state.accent=e.target.value;$('#modeSelect').onchange=e=>{state.mode=e.target.value;document.body.classList.toggle('challenge-mode',state.mode==='challenge')};$('#toggleFrench').onclick=()=>{document.body.classList.toggle('show-french');$('#toggleFrench').textContent=`🇫🇷 French help: ${document.body.classList.contains('show-french')?'ON':'OFF'}`};$('#downloadResults').onclick=downloadResults;$('#resetLesson').onclick=resetAll;
$('#nextInterview').onclick=()=>{state.interviewIndex=(state.interviewIndex+1)%interviewQs.length;renderInterview()};$('#listenInterview').onclick=()=>speak(interviewQs[state.interviewIndex].q);

loadLearner();renderDeck('activationDeck',activation,'activation');renderDeck('pastStoryDeck',pastStory,'pastStory');renderDeck('bridgeDeck',bridge,'bridge');renderDeck('upgradeDeck',upgrade,'upgrade');setupVocab();setupMissions();renderInterview();renderListening();setupListeningEvents();setupVtest();setupWriting();setupTimers();setupAdmin();updateOverall();updateProgress();
})();
