'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={mode:'practice',timer:null,time:20,score:0,total:0,answers:{}};
const STORAGE='eden_lesson_10_progress_v1';

const headlineQuestions=[
 {q:'You need to know who approves a technical decision. Which opening is strongest?', options:['I wanted to give you the background first because there have been several changes…','I need to clarify one point: who has final approval for this decision?','There are many things happening at the moment and I am not completely sure…'], a:1, hint:'Make the question visible immediately.', why:'The listener knows the exact decision you need before hearing any history.'},
 {q:'A workstream is late. Which structure is clearest?', options:['We started three weeks ago, then the supplier sent…','The workstream is two days late. The main cause is supplier data. I need a decision today on whether we protect scope or deadline.','I want to explain everything that happened so you can understand the situation.'], a:1, hint:'Headline → cause → decision needed.', why:'It gives status, essential evidence and the ask in three moves.'},
 {q:'You disagree with a senior expert. What should come first?', options:['Your conclusion or concern','The complete technical history','An apology for disagreeing'], a:0, hint:'Respect does not require hiding your point.', why:'State the concern first, then support it with evidence and invite challenge.'}
];
const discQuestions=[
 {q:'Someone repeatedly asks, “What do you recommend? Can we decide now?” What should you adapt first?', options:['Give more chronology','Lead with outcome, options and recommendation','Slow down and explain every technical criterion before the conclusion'],a:1,hint:'This sounds like a strong preference for speed and decision.',why:'A D-style preference often responds better to concise options and a decision point.'},
 {q:'Someone asks for criteria, evidence and exact assumptions. What is the best response?',options:['Give the conclusion, then organise the evidence by criterion','Use a highly energetic story and avoid numbers','Tell them the details are not important'],a:0,hint:'Think C: accuracy and logic.',why:'Headline first still applies, but the listener may want deeper evidence after the headline.'},
 {q:'Someone is worried about how a change will affect the team. What helps most?',options:['Pressure them to decide immediately','Explain what stays stable, the transition steps and available support','Give only a technical table'],a:1,hint:'Think stability and transition.',why:'An S-style preference may need predictability and a cooperative path through change.'}
];
const languageQuestions=[
 {q:'Choose the most authoritative cooperative sentence.',options:['Maybe, if it is okay, perhaps we could decide who does it?','Let’s clarify ownership before we close: who will lead the technical action, and who will close the decision?','You need to do what I say because I am responsible now.'],a:1,hint:'Firm structure + neutral language + clear action.',why:'It is explicit without becoming territorial or aggressive.'},
 {q:'A colleague gives too much detail before the decision point. What can you say?',options:['Stop. This is too long.','Let me pause you there so I can make the decision point explicit. Then we can come back to the technical detail.','I do not understand anything you are saying.'],a:1,hint:'Interrupt the process, not the person.',why:'It protects time and structure while respecting expertise.'},
 {q:'The hierarchy is temporarily unclear. Which phrase keeps work moving without inventing authority?',options:['Until the reporting line is confirmed, I suggest we use this working rule and review it next week.','I am the boss now, so follow my rule.','We cannot do anything until someone above us decides.'],a:0,hint:'Propose a temporary operating rule, not a power claim.',why:'It creates a reversible coordination mechanism while acknowledging uncertainty.'}
];
const sprints=[
 {title:'The technical leader takes over',prompt:'You want to keep the technical expert in the lead on substance while you retain coordination. Give a 20-second message.',hint:'Recognition → boundary → cooperation.',model:'Your technical lead on this topic is valuable. I’d like you to own the technical recommendation; I’ll frame the decision, coordinate interfaces and close the actions. That keeps expertise strong and ownership clear.'},
 {title:'The team asks why another meeting is needed',prompt:'Convince them that a short biweekly alignment is useful without sounding bureaucratic.',hint:'Why → lightweight method → test period.',model:'We need one reliable place to surface decisions while the organisation is changing. I’m proposing twenty minutes every two weeks, not another reporting layer. Let’s test it for one month and keep it only if it helps us move faster.'},
 {title:'Senior management has partial information',prompt:'Ask for clarity from a senior manager who may know more about the organisation.',hint:'Question first → reason → deadline.',model:'I need to clarify one organisational point: who will arbitrate cross-team decisions during the transition? I’m asking because two workstreams now have overlapping instructions. Can we confirm the escalation route today?'},
 {title:'A disagreement gets personal',prompt:'Bring the discussion back to facts and next steps.',hint:'Acknowledge → fact → test → decision.',model:'I hear the disagreement. I’d like us to separate the person from the issue and test the assumption behind the two positions. Once we agree on the facts, we can decide the owner and next step.'}
];
const vocab=[
 ['clarity','🎯','bottom line','l’essentiel / conclusion','the most important message or result','Bottom line: we need a decision by Thursday.'],
 ['clarity','🧭','frame the issue','cadrer le sujet','define the problem and decision before discussing details','Let me frame the issue before we go into the technical options.'],
 ['clarity','🔎','decision point','point de décision','the exact question or choice that must be resolved','The decision point is whether we protect scope or schedule.'],
 ['clarity','✂️','strip back','simplifier / épurer','remove non-essential detail','I need to strip the explanation back to the two facts that matter.'],
 ['clarity','📌','make explicit','rendre explicite','state something clearly instead of leaving it implied','Let’s make the ownership explicit before we close.'],
 ['influence','⚡','land a message','faire passer un message','make a message understood and remembered','Pause after the headline so the message can land.'],
 ['influence','🧲','buy-in','adhésion','active support for an idea or plan','We need technical buy-in before changing the process.'],
 ['influence','🌱','bring people with you','embarquer les gens','help others understand and support a change','Explain the purpose first if you want to bring people with you.'],
 ['influence','🧠','reframe','reformuler / recadrer','present the same issue from a more useful angle','I’d like to reframe this as a role-clarity issue, not a competence issue.'],
 ['influence','📣','make the case','défendre / argumenter en faveur','give convincing reasons for a recommendation','You need to make the case in twenty seconds before adding detail.'],
 ['authority','🧱','boundary','limite / périmètre','a clear limit between roles or responsibilities','The boundary between technical ownership and management ownership needs to be clear.'],
 ['authority','🪪','mandate','mandat / légitimité','formal or practical authority to act','The temporary mandate is to coordinate priorities until the structure is confirmed.'],
 ['authority','🧩','ownership','responsabilité claire','clear responsibility for an action or decision','We need one owner for each open decision.'],
 ['authority','🚦','escalation route','circuit d’escalade','the path for raising an unresolved issue to the right level','Let’s confirm the escalation route before the next conflict.'],
 ['authority','🤝','delegate','déléguer','give responsibility and authority for a task or decision','You can delegate technical analysis without delegating overall accountability.'],
 ['collaboration','🔗','alignment','alignement','shared understanding of goals, roles and actions','The meeting created alignment even before the hierarchy was fully clear.'],
 ['collaboration','🛠️','working rule','règle de fonctionnement','a practical temporary rule for how people will work','Until the organisation is confirmed, we need a simple working rule.'],
 ['collaboration','🗣️','surface a disagreement','faire émerger un désaccord','make a hidden disagreement visible so it can be addressed','It is better to surface a disagreement early than let it slow the team silently.'],
 ['collaboration','🔄','check-in','point de suivi','a short recurring conversation to review progress or concerns','Let’s use a weekly check-in for the first month.'],
 ['collaboration','🧾','close the loop','boucler / assurer le suivi','confirm the action, owner and outcome after a discussion','Before we leave, let’s close the loop on the three open points.'],
 ['disc','🔴','directness','franchise / style direct','communication that reaches the point quickly and clearly','Directness works best when it is paired with respect and a clear purpose.'],
 ['disc','🔵','evidence','preuves / éléments factuels','facts or information that support a conclusion','Give the conclusion first, then the evidence by criterion.'],
 ['disc','🟢','predictability','prévisibilité','a sense that process and expectations are stable','Predictability can reduce resistance during a transition.'],
 ['disc','🟡','engagement','engagement / implication','active interest and participation','Invite reaction when engagement is more important than technical depth.']
];

function populateVoices(){ if(!('speechSynthesis' in window))return; const vs=speechSynthesis.getVoices(); const lang=$('#accentSelect').value; const filtered=vs.filter(v=>v.lang&&v.lang.toLowerCase().startsWith(lang.toLowerCase().slice(0,2))); $('#voiceSelect').innerHTML=''; (filtered.length?filtered:vs).forEach((v,i)=>{const o=document.createElement('option');o.value=v.name;o.textContent=`${v.name} — ${v.lang}`;$('#voiceSelect').appendChild(o)});}
function speak(text){if(!('speechSynthesis' in window))return alert('Speech synthesis is not supported on this browser.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=$('#accentSelect').value;const voice=speechSynthesis.getVoices().find(v=>v.name===$('#voiceSelect').value);if(voice)u.voice=voice;u.rate=.94;speechSynthesis.speak(u)}
function textOf(id){return ($('#'+id)?.innerText||'').trim()}
function toggle(id){$('#'+id)?.classList.toggle('hidden')}
function renderQuiz(target,data,prefix){const host=$(target);host.innerHTML='';data.forEach((item,i)=>{const card=document.createElement('article');card.className='question-card';card.innerHTML=`<h3>${i+1}. ${item.q}</h3><div class="quiz-options">${item.options.map((o,j)=>`<button data-quiz="${prefix}${i}" data-choice="${j}">${o}</button>`).join('')}</div><div class="buttons"><button class="secondary hint-button" data-hint="${prefix}hint${i}">Hint</button></div><p id="${prefix}hint${i}" class="mini-model hidden">${item.hint}</p><p class="quiz-feedback" id="${prefix}fb${i}"></p>`;host.appendChild(card)});}
function answerQuiz(key,choice,data,prefix){const i=Number(key.replace(prefix,''));const item=data[i];const correct=choice===item.a;const fb=$(`#${prefix}fb${i}`);fb.textContent=(correct?'Correct. ':'Not quite. ')+item.why;fb.className='quiz-feedback '+(correct?'good':'bad');$$(`[data-quiz="${key}"]`).forEach(b=>{b.disabled=true;const c=Number(b.dataset.choice);if(c===item.a)b.classList.add('correct');else if(c===choice&&!correct)b.classList.add('wrong')});if(!(key in state.answers)){state.answers[key]=correct;state.total++;if(correct)state.score++;updateScore();}}
function renderSprints(){const h=$('#sprintCards');h.innerHTML='';sprints.forEach((s,i)=>{const a=document.createElement('article');a.className='mission-card';a.innerHTML=`<span class="pill pressure">20 seconds</span><h3>${s.title}</h3><p class="prompt">${s.prompt}</p><textarea rows="3" placeholder="Write only 3 cue words or your first sentence..."></textarea><div class="buttons"><button class="secondary hint-button" data-hint="sHint${i}">Hint</button><button class="secondary model-trigger" data-toggle="sModel${i}">Model</button></div><p id="sHint${i}" class="mini-model hidden">${s.hint}</p><div id="sModel${i}" class="model-block hidden"><p>${s.model}</p><button data-speak-text="${encodeURIComponent(s.model)}" data-encoded="1">Listen</button></div>`;h.appendChild(a)});}
function renderVocab(){const cat=$('#vocabFilter').value;const h=$('#vocabGrid');h.innerHTML='';vocab.filter(v=>cat==='all'||v[0]===cat).forEach(v=>{const a=document.createElement('article');a.className='vocab-card';a.innerHTML=`<span class="tag">${v[0]}</span><div class="icon">${v[1]}</div><h3>${v[2]}</h3><p class="translation"><strong>FR:</strong> ${v[3]}</p><p class="definition">${v[4]}</p><p class="sentence">${v[5]}</p><div class="audio-row"><button data-speak-text="${encodeURIComponent(v[2]+'. '+v[5])}" data-encoded="1">Listen</button></div>`;h.appendChild(a)});}
function buildMessage(){const vals=['msgPoint','msgImpact','msgEvidence','msgAsk'].map(id=>$('#'+id).value.trim()).filter(Boolean);$('#builtMessage').textContent=vals.length?vals.join(' '):'Add at least one element to build your message.';}
function checkRewrite(){const t=$('#rewriteQuestion').value.trim();const qmark=t.includes('?');const concise=t.split(/\s+/).length<=35;const direct=/clarify|question|who|what|when|which|how|can we|could you/i.test(t.slice(0,100));const good=qmark&&concise&&direct;const f=$('#rewriteFeedback');f.textContent=good?'Good structure: the question is visible, direct and concise.':'Try again: put the question or clarification in the first sentence and keep the whole message under about 35 words.';f.className='feedback-line '+(good?'good':'bad');const key='rewrite';if(!(key in state.answers)){state.answers[key]=good;state.total++;if(good)state.score++;updateScore();}}
function updateScore(){const val=state.score,total=state.total;$('#scoreValue').textContent=val;$('#scoreTotal').textContent='/ '+total;const pct=total?val/total:0;$('#scoreLabel').textContent=!total?'Complete the interactive checks':pct>=.8?'Strong structure choices':pct>=.6?'Good base — keep sharpening the headline':'Keep practising headline-first structure';$('#scoreAdvice').textContent=!total?'The score tracks structure choices in the lesson. It is not an English level.':pct>=.8?'Your choices consistently prioritise clarity, ownership and useful adaptation.':pct>=.6?'You understand the method; the next step is making it automatic under pressure.':'Focus on point first, minimum context, and one clear ask.';}
function setMode(){state.mode=state.mode==='practice'?'challenge':'practice';document.body.classList.toggle('challenge-mode',state.mode==='challenge');$('#toggleMode').textContent='Mode: '+(state.mode==='practice'?'Practice':'Challenge');$('#modeHelp').textContent=state.mode==='practice'?'Practice mode: hints and models are available.':'Challenge mode: hints and sprint models are hidden. Speak first, analyse second.';$$('.mini-model,.model-block').forEach(el=>{if(state.mode==='challenge'&&!el.classList.contains('always-visible'))el.classList.add('hidden')});}
function startTimer(){clearInterval(state.timer);state.time=20;const d=$('#timerDisplay');d.textContent=20;d.className='timer-display running';state.timer=setInterval(()=>{state.time--;d.textContent=state.time;if(state.time<=5)d.classList.add('danger');if(state.time<=0){clearInterval(state.timer);d.textContent='STOP';d.className='timer-display danger';}},1000)}
function resetTimer(){clearInterval(state.timer);state.time=20;const d=$('#timerDisplay');d.textContent='20';d.className='timer-display';}
function buildFinal(){const labels=[['WHY',$('#finalWhy').value.trim()],['ROLES',$('#finalRoles').value.trim()],['RULE',$('#finalRule').value.trim()],['ASK',$('#finalAsk').value.trim()]].filter(x=>x[1]);$('#finalCueOutput').textContent=labels.length?labels.map(x=>`${x[0]} → ${x[1]}`).join('  |  '):'Add your four building blocks first.';}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function resultsText(){return [`Lesson 10 — Communication Results`,`Date: ${new Date().toLocaleDateString()}`,`Interactive score: ${state.score}/${state.total}`,`Mode: ${state.mode}`,`Presence checklist: ${$$('.presence-check:checked').length}/${$$('.presence-check').length}`,``,`Structured message:`,textOf('builtMessage'),``,`Final speaking cues:`,textOf('finalCueOutput')].join('\n')}
function resetActivities(){state.score=0;state.total=0;state.answers={};$$('.quiz-feedback').forEach(x=>{x.textContent='';x.className='quiz-feedback'});$$('[data-quiz]').forEach(b=>{b.disabled=false;b.classList.remove('correct','wrong')});$$('textarea').forEach(t=>{if(!t.closest('#qualiopi'))t.value=''});$$('.presence-check').forEach(x=>x.checked=false);$('#builtMessage').textContent='Your structured message will appear here.';$('#finalCueOutput').textContent='Your cue structure will appear here.';$('#rewriteFeedback').textContent='';updateScore();resetTimer();}
const objectives=[
 ['obj1','Turn complex context into a clear management message'],['obj2','Define authority, technical leadership and role clarity'],['obj3','Use headline-first structure instead of chronological explanation'],['obj4','Ask a clear question with only the context needed'],['obj5','Use purpose to make a message convincing'],['obj6','Adapt detail, pace and evidence to communication preferences'],['obj7','Use clear, cooperative authority language'],['obj8','Align body language, pause and voice with the message'],['obj9','Deliver a convincing management message in 20 seconds'],['obj10','Set clear expectations and check-ins during the first month'],['obj11','Use leadership and influence vocabulary accurately'],['obj12','Lead a realistic management conversation']
];
function statusLabel(v){return {'achieved':'Acquis','progress':'En cours d’acquisition','not-achieved':'Non acquis','not-started':'Non commencé'}[v]||v}
function renderProgress(){const h=$('#manualGrid');h.innerHTML='';objectives.forEach(([id,label])=>{const l=document.createElement('label');l.textContent=label;l.innerHTML+=`<select class="progress-select" data-progress="${id}"><option value="not-started">Non commencé</option><option value="progress">En cours d’acquisition</option><option value="achieved">Acquis</option><option value="not-achieved">Non acquis</option></select><textarea rows="2" data-note="${id}" placeholder="Evidence / notes"></textarea>`;h.appendChild(l)});}
function collectProgress(){const statuses={};objectives.forEach(([id])=>statuses[id]={status:$(`[data-progress="${id}"]`).value,note:$(`[data-note="${id}"]`).value});return{learner:$('#learnerName').value,trainer:$('#trainerName').value,date:$('#evaluationDate').value,comments:$('#trainerComments').value,statuses,lastSaved:new Date().toISOString()}}
function updateProgressSummary(){const vals=$$('[data-progress]').map(s=>s.value);const started=vals.filter(v=>v!=='not-started').length;const completion=Math.round(started/vals.length*100)||0;$('#completionRate').value=completion+'%';$('#completionRateText').textContent=completion+'%';let overall='not-started';if(started){overall=vals.every(v=>v==='achieved')?'achieved':vals.some(v=>v==='not-achieved')?'not-achieved':'progress'}const el=$('#overallStatus');el.textContent=statusLabel(overall);el.className='status '+overall;$('#reportPreview').textContent=progressReport();}
function progressReport(){const p=collectProgress();const lines=['Qualiopi learning tracking — Lesson 10',`Learner: ${p.learner||'—'}`,`Trainer: ${p.trainer||'—'}`,`Date: ${p.date||'—'}`,'','Objectives:'];objectives.forEach(([id,label])=>{const o=p.statuses[id];lines.push(`- ${label}: ${statusLabel(o.status)}${o.note?' — '+o.note:''}`)});lines.push('','General observations:',p.comments||'—');return lines.join('\n')}
function saveProgress(show=true){const p=collectProgress();localStorage.setItem(STORAGE,JSON.stringify(p));$('#lastSaved').textContent=new Date(p.lastSaved).toLocaleString();updateProgressSummary();if(show)alert('Progress saved in this browser.');}
function loadProgress(){try{const p=JSON.parse(localStorage.getItem(STORAGE)||'null');if(!p)return;$('#learnerName').value=p.learner||'';$('#trainerName').value=p.trainer||'Tisha DOUTY-DOSIERE';$('#evaluationDate').value=p.date||new Date().toISOString().slice(0,10);$('#trainerComments').value=p.comments||'';Object.entries(p.statuses||{}).forEach(([id,o])=>{const s=$(`[data-progress="${id}"]`),n=$(`[data-note="${id}"]`);if(s)s.value=o.status||'not-started';if(n)n.value=o.note||''});if(p.lastSaved)$('#lastSaved').textContent=new Date(p.lastSaved).toLocaleString()}catch(e){console.warn(e)}updateProgressSummary()}
function initRecorder(){const box=$('#finalRecorder');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){box.querySelector('.rec-status').textContent='Recording is not supported on this browser.';box.querySelector('.recordBtn').disabled=true;return}let rec,chunks=[],stream=null;const start=box.querySelector('.recordBtn'),stop=box.querySelector('.stopRecBtn'),audio=box.querySelector('.recordedAudio'),link=box.querySelector('.downloadRec');start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];rec=new MediaRecorder(stream);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});audio.src=URL.createObjectURL(blob);audio.classList.remove('hidden');link.href=audio.src;link.download='eden-lesson-10-rehearsal.webm';link.classList.remove('hidden');stream.getTracks().forEach(t=>t.stop());box.querySelector('.rec-status').textContent='Recording ready. Play it back when you want.'};rec.start();start.disabled=true;stop.disabled=false;box.classList.add('recording');box.querySelector('.rec-status').textContent='Recording…'}catch(e){box.querySelector('.rec-status').textContent='Microphone permission was not granted.'}};stop.onclick=()=>{if(rec&&rec.state!=='inactive')rec.stop();start.disabled=false;stop.disabled=true;box.classList.remove('recording')}}
function bind(){document.addEventListener('click',e=>{const sc=e.target.closest('[data-scroll]');if(sc){$(sc.dataset.scroll)?.scrollIntoView({behavior:'smooth'});return}const t=e.target.closest('[data-toggle]');if(t){toggle(t.dataset.toggle);return}const h=e.target.closest('[data-hint]');if(h){toggle(h.dataset.hint);return}const sp=e.target.closest('[data-speak-text]');if(sp){const raw=sp.dataset.speakText;speak(sp.dataset.encoded?decodeURIComponent(raw):raw);return}const si=e.target.closest('[data-speak-id]');if(si){speak(textOf(si.dataset.speakId));return}const q=e.target.closest('[data-quiz]');if(q){const key=q.dataset.quiz,choice=Number(q.dataset.choice);if(key.startsWith('h'))answerQuiz(key,choice,headlineQuestions,'h');else if(key.startsWith('d'))answerQuiz(key,choice,discQuestions,'d');else if(key.startsWith('l'))answerQuiz(key,choice,languageQuestions,'l');return}const sq=e.target.closest('.surprise-question');if(sq){$('#surpriseDisplay').textContent=sq.dataset.q;startTimer();}});$('#toggleFrench').onclick=()=>{document.body.classList.toggle('all-french');$('#toggleFrench').textContent=document.body.classList.contains('all-french')?'Hide French support':'Show French support'};$('#toggleModels').onclick=()=>{document.body.classList.toggle('all-models');$('#toggleModels').textContent=document.body.classList.contains('all-models')?'Hide all models':'Show all models'};$('#toggleMode').onclick=setMode;$('#stopAudio').onclick=()=>speechSynthesis?.cancel();$('#audioTest').onclick=()=>speak('Audio test. The listen buttons are ready.');$('#accentSelect').onchange=populateVoices;$('#vocabFilter').onchange=renderVocab;$('#buildMessage').onclick=buildMessage;$('#clearMessage').onclick=()=>{['msgPoint','msgImpact','msgEvidence','msgAsk'].forEach(id=>$('#'+id).value='');buildMessage()};$('#listenBuilt').onclick=()=>speak(textOf('builtMessage'));$('#checkRewrite').onclick=checkRewrite;$('#startTimer').onclick=startTimer;$('#resetTimer').onclick=resetTimer;$('#buildFinal').onclick=buildFinal;$('#downloadResults').onclick=()=>download('eden-lesson-10-results.txt',resultsText());$('#resetActivities').onclick=()=>{if(confirm('Reset all interactive answers for this lesson?'))resetActivities()};$('#saveProgress').onclick=()=>saveProgress(true);$('#downloadProgress').onclick=()=>download('eden-lesson-10-qualiopi-report.txt',progressReport());$('#printReport').onclick=()=>window.print();$('#resetProgress').onclick=()=>{if(confirm('Reset saved Qualiopi progress?')){localStorage.removeItem(STORAGE);$$('[data-progress]').forEach(s=>s.value='not-started');$$('[data-note]').forEach(n=>n.value='');$('#trainerComments').value='';$('#learnerName').value='';$('#lastSaved').textContent='—';updateProgressSummary()}};document.addEventListener('input',e=>{if(e.target.matches('[data-progress],[data-note],#trainerComments,#learnerName,#trainerName,#evaluationDate'))updateProgressSummary()});}
function init(){renderQuiz('#headlineQuiz',headlineQuestions,'h');renderQuiz('#discQuiz',discQuestions,'d');renderQuiz('#languageQuiz',languageQuestions,'l');renderSprints();renderVocab();renderProgress();$('#evaluationDate').value=new Date().toISOString().slice(0,10);populateVoices();if('speechSynthesis' in window) speechSynthesis.onvoiceschanged=populateVoices;bind();initRecorder();loadProgress();updateScore();}
document.addEventListener('DOMContentLoaded',init);
