(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE='isabelleFinalInterviewV1';
const STATUS_LABELS={'not-started':'Non commencé','progress':'En cours d’acquisition','achieved':'Objectif atteint','not-achieved':'Objectif non atteint'};
const LEVEL_NOTES={b1:'B1 secure: clear, correct and easy to reproduce.',b2:'B2 strong: more precise structure, stronger verbs and clearer professional relevance.',b2p:'B2+ polished: concise, nuanced and interview-ready without sounding memorised.'};

const QUESTION_DATA={
 intro:[
  {id:'intro1',q:'Tell me about yourself and your professional background.',cue:'identity · 24+ years · legal + commercial · real estate · Netherlands',hint:'Aim for a professional map, not your complete CV.',models:{
   b1:'I am a real estate legal and commercial professional with more than 24 years of experience in France. I have worked in property development, contract negotiation, legal advice and sales management. I am now looking for a new professional challenge in the Netherlands, ideally in a role where I can use both my legal and commercial experience.',
   b2:'I am a real estate professional with more than 24 years of experience combining legal advisory work, property development and sales management. Over the years, I have negotiated contracts, supported operational teams, analysed risks and coordinated with a wide range of stakeholders. I am now looking to bring that dual legal and commercial perspective to the Dutch real-estate market in an international environment.',
   b2p:'My background sits at the intersection of real-estate law and business. For more than 24 years, I have advised development teams, negotiated contracts, assessed risk and managed commercial relationships, so I am used to translating legal constraints into practical decisions. I am now looking for a Netherlands-based role where that combination of legal judgement, commercial awareness and stakeholder coordination can add value from day one.'}}
 ],
 recruiter:[
  {id:'rec1',q:'Why do you want to work in the Netherlands?',cue:'international environment · professional challenge · Dutch market · adaptability',hint:'Avoid making the answer only about lifestyle. Keep a professional reason at the centre.',models:{b1:'I want to work in the Netherlands because I am looking for a new professional challenge in an international environment. I am interested in the Dutch real-estate market and I would like to use my experience while discovering a different way of working.',b2:'The Netherlands appeals to me because it offers an international and pragmatic business environment, particularly in real estate. After a long career in France, I am ready for a new challenge and I would like to apply my experience in contracts, development and stakeholder coordination in a different market while continuing to learn.',b2p:'I am deliberately looking for a market where my experience can transfer but where I will also be challenged to adapt. The Dutch real-estate environment is attractive to me because of its international outlook, collaborative working style and strong focus on practical solutions. That combination makes the move professionally meaningful rather than simply geographical.'}},
  {id:'rec2',q:'What type of role are you looking for?',cue:'real estate · legal + commercial · transactions · development · stakeholders',hint:'Do not say “anything”. Give a clear target and leave room for adjacent roles.',models:{b1:'I am looking for a role in real estate, ideally combining legal and commercial responsibilities. I am interested in contracts, transactions, property development and work with different stakeholders.',b2:'I am targeting real-estate roles where legal knowledge and commercial judgement are both useful — for example transaction support, development, contract management or a property-related legal position. I am also open to adjacent roles if they involve negotiation, risk analysis and stakeholder coordination.',b2p:'My strongest fit is a role at the interface between legal, commercial and operational teams. Titles can vary, but I am particularly interested in positions involving transactions, contract negotiation, development risk and stakeholder management, because that is where my dual background creates the most value.'}},
  {id:'rec3',q:'Why should we consider you for this role?',cue:'dual expertise · practical judgement · negotiation · risk · communication',hint:'Choose 2–3 differentiators and support them. Do not list every skill.',models:{b1:'You should consider me because I have long experience in real estate and I understand both legal and commercial issues. I can negotiate contracts, analyse risks and work with many different partners.',b2:'I would bring a combination that is useful in complex real-estate projects: strong legal analysis, commercial awareness and practical coordination. I have spent many years helping operational teams make decisions, negotiating with external stakeholders and identifying risks before they become problems.',b2p:'My main differentiator is that I do not look at a real-estate issue from only one angle. I can understand the legal exposure, the commercial objective and the operational reality at the same time. That allows me to negotiate pragmatically, communicate clearly with different stakeholders and help teams reach decisions that are both secure and workable.'}},
  {id:'rec4',q:'What are your main strengths?',cue:'analytical · synthesis · negotiation · adaptability · stakeholder communication',hint:'Give three strengths maximum, each with a short proof.',models:{b1:'My main strengths are analysis, negotiation and communication. I am used to studying complex files, finding practical solutions and working with different people such as lawyers, notaries, investors and operational teams.',b2:'I would highlight three strengths: analytical judgement, negotiation and adaptability. I can quickly identify the key legal or commercial risk, explain it in a practical way and adjust my communication depending on whether I am speaking to an operational team, a client or an external adviser.',b2p:'I would probably choose judgement, translation and adaptability. By translation, I mean the ability to turn technical legal issues into clear business choices for non-legal colleagues. Combined with strong negotiation skills and experience across very different stakeholders, that has helped me stay effective in complex and sometimes sensitive projects.'}},
  {id:'rec5',q:'What would you need to learn quickly if you joined us?',cue:'Dutch legal framework · market practices · internal processes · Dutch language',hint:'Show self-awareness without undermining your candidacy.',models:{b1:'I would need to learn the Dutch legal framework, your internal procedures and continue improving my Dutch. I am used to learning new regulations and adapting to new professional environments.',b2:'My priority would be to understand the Dutch regulatory and market framework, your internal decision-making processes and the way teams collaborate. I would also continue developing my Dutch. I see those as normal onboarding priorities, and my experience with changing regulations means I am comfortable learning quickly.',b2p:'The transferable part of my expertise is strong, but I would not assume the French and Dutch markets operate in the same way. I would therefore prioritise the local legal framework, market conventions and your internal governance, while accelerating my Dutch. I am comfortable with that learning curve because regulatory monitoring and adaptation have always been part of my work.'}},
  {id:'rec6',q:'Where do you see yourself in three years?',cue:'integrated · effective in Dutch market · stronger Dutch · broader responsibility',hint:'Keep it credible and connected to contribution, not title chasing.',models:{b1:'In three years, I would like to be fully integrated into the Dutch real-estate environment, confident in my role and able to work more independently in Dutch as well as English.',b2:'In three years, I would like to have built strong knowledge of the Dutch market, be fully effective in the team and have developed my Dutch to a level that gives me more professional independence. I would also hope to take on broader responsibility as I prove my value.',b2p:'My priority would be depth before title: I would want to understand the market well, earn trust internally and become genuinely effective in the Dutch context. If I achieve that, I would expect my responsibilities to broaden naturally — particularly in complex negotiations, cross-functional projects or mentoring colleagues.'}}
 ],
 star:[
  {id:'star1',q:'Tell me about a difficult situation you had to manage.',cue:'S context · T responsibility · A decisions · R outcome',hint:'Choose one real case. Keep confidential details anonymous.',models:{b1:'In one project, there was a disagreement about a contract risk before an important deadline. My responsibility was to explain the risk and help the team find a solution. I reviewed the documents, discussed the issue with the operational team and proposed a safer option. We were able to continue the project with a clearer agreement.',b2:'On a development project, the operational team wanted to move quickly but a contractual point created significant risk. I needed to protect the company without simply blocking the project. I isolated the key risk, explained it in practical terms, consulted the relevant stakeholders and proposed alternative wording. That allowed the project to move forward while reducing the exposure and keeping the relationship constructive.',b2p:'A recurring challenge in development work is balancing timing pressure with legal security. In one case, an operational team was ready to proceed, but the proposed contractual position left us exposed. Rather than give a simple “no”, I reframed the issue around the business risk, worked with the stakeholders on alternative wording and clarified the conditions under which we could proceed. We protected the company’s position without derailing the timetable, which also strengthened trust between legal and operational teams.'}},
  {id:'star2',q:'Tell me about a time you had to adapt quickly.',cue:'change · new information · action · result',hint:'Focus on what changed in your behaviour, not only what changed around you.',models:{b1:'I had to adapt when regulations or project conditions changed. I reviewed the new information, updated the documents and explained the impact to the teams. This helped everyone continue with the correct information.',b2:'In real-estate development, regulatory or project changes can happen quickly. In one situation, new information affected documents that were already being used by several teams. I reviewed the impact, updated the relevant material, prioritised the most urgent changes and communicated them clearly. The teams were able to continue without creating unnecessary delay.',b2p:'I once had to respond to a regulatory change that affected both documentation and operational decisions across several projects. I first separated what was immediately critical from what could be handled later, then updated the standard documents and gave the teams a concise explanation of the practical consequences. That prioritisation prevented confusion and showed me again that adaptation is as much about communication as technical accuracy.'}},
  {id:'star3',q:'Tell me about a disagreement with a colleague or stakeholder.',cue:'different priorities · listen · clarify · common objective · outcome',hint:'Do not make the other person the villain. Show professional disagreement management.',models:{b1:'I sometimes had disagreements because legal and commercial teams had different priorities. I listened to the other person, explained my concerns and tried to find a solution that protected the project. Usually we could agree on a practical compromise.',b2:'I have often worked with colleagues whose priority was speed while mine included legal risk. In one case, I first made sure I understood the operational objective, then explained which part of the risk was essential and which part was negotiable. By separating those points, we found a solution that was both workable and sufficiently secure.',b2p:'One disagreement involved a stakeholder who saw legal review as an obstacle to a commercial deadline. I avoided turning it into a legal-versus-business discussion. Instead, I asked what outcome was non-negotiable for them, explained the risk in terms of business consequences and identified where we had flexibility. Once we reframed the conversation around a shared objective, the disagreement became much easier to resolve.'}},
  {id:'star4',q:'Tell me about a mistake or something you would do differently now.',cue:'real but not catastrophic · ownership · correction · lesson',hint:'Do not choose “I work too hard”. Show reflection and learning.',models:{b1:'Earlier in my career, I sometimes gave too much technical detail when explaining legal issues. I realised that some colleagues needed a shorter and more practical explanation. I changed my communication and now I focus first on the decision, the risk and the next step.',b2:'One thing I would do differently is adapt my communication earlier. In the past, I sometimes assumed that giving a complete legal explanation was the best way to help. I learned that operational teams often need the key risk, the consequence and the options first. Since then, I have become much more concise and audience-focused.',b2p:'A lesson I learned over time is that accuracy alone is not enough if the message is not usable. Earlier in my career, I occasionally over-explained the legal reasoning before making the practical recommendation clear. I now reverse that order: decision first, risk second, detail if needed. That has made my advice faster to understand and more influential.'}},
  {id:'star5',q:'Tell me about a time you took initiative.',cue:'identified need · acted before being asked · stakeholders · impact',hint:'Choose an example where your action created value beyond your basic task.',models:{b1:'I took initiative when I saw that teams needed clearer standard documents. I helped update them and shared the changes with the people who used them. This made the documents more consistent and easier to use.',b2:'I noticed that recurring questions were creating inefficiency, so I helped improve standard documents and guidance used by operational teams. I gathered the recurring issues, updated the wording and explained the changes. This reduced uncertainty and gave colleagues a more reliable starting point.',b2p:'I identified that several teams were repeatedly facing the same contractual questions, which meant legal time was being spent on avoidable clarification. I consolidated the recurring issues, updated the standard documentation and communicated the practical changes to users. It was a relatively simple initiative, but it improved consistency and allowed legal support to focus on genuinely complex points.'}}
 ],
 pressure:[
  {id:'press1',q:'You say you are adaptable. Can you give me one very specific example?',cue:'one example only · what changed · your action · measurable/observable result',hint:'The recruiter is testing evidence, not asking for another general strength.',models:{b1:'Yes. When a regulation changed, I had to update documents quickly and explain the change to several teams. I organised the most urgent points first and helped the teams continue their work with the correct information.',b2:'Yes. A good example was a regulatory change that affected documents already used by several operational teams. I prioritised the high-risk items, updated the relevant templates and gave colleagues a short practical briefing. They were able to adapt without stopping the projects.',b2p:'Certainly. One regulatory change affected both standard documentation and live projects. I triaged the impact by urgency, updated the documents that created immediate exposure and gave teams a concise “what changes for you” briefing. That kept implementation moving while protecting consistency across projects.'}},
  {id:'press2',q:'What exactly did you personally do in that situation?',cue:'use I · decisions · actions · no “we” fog',hint:'Replace vague team language with your own responsibility.',models:{b1:'I reviewed the documents, identified the main risk, spoke with the operational team and proposed new wording.',b2:'My role was to identify the legal exposure, decide which points were essential, draft alternative wording and explain the options to the operational team so they could make an informed decision.',b2p:'I personally isolated the risk, translated it into business consequences, drafted the alternative clauses and led the discussion on which trade-offs were acceptable. Other stakeholders contributed, but I was responsible for framing the legal options and recommendation.'}},
  {id:'press3',q:'What would you do differently if the same situation happened today?',cue:'reflection · one improvement · why',hint:'Do not say “nothing”. Strong candidates show learning.',models:{b1:'I would communicate the key point earlier and make the explanation shorter from the beginning.',b2:'I would involve the operational stakeholders slightly earlier and start with a one-page summary of the options. That would make the decision process faster without reducing the quality of the analysis.',b2p:'I would front-load stakeholder alignment. Technically, the solution worked, but today I would clarify the decision criteria earlier and give a concise options summary before the detailed legal analysis. That would reduce back-and-forth and make ownership of the final decision clearer.'}},
  {id:'press4',q:'Why did that result matter to the business?',cue:'time · risk · cost · relationship · decision quality',hint:'Translate your professional action into business impact.',models:{b1:'It mattered because the project could continue without creating an unnecessary legal risk.',b2:'It mattered because we protected the company’s position while keeping the project moving. The team had a clearer basis for decision-making and we avoided a delay caused by uncertainty.',b2p:'The value was not only legal protection. By resolving the issue quickly and clearly, we preserved the timetable, reduced decision uncertainty and maintained trust between the legal and operational teams — all of which directly affects project efficiency.'}}
 ],
 dutch:[
  {id:'dutch1',q:'Your Dutch is not yet strong. Why should that not be a problem?',cue:'acknowledge · current contribution · learning plan · realistic boundaries',hint:'Do not say it is “not a problem”. Explain how you would manage it responsibly.',models:{b1:'I understand that Dutch can be important. My Dutch is still developing, but I am actively learning it. I can already work professionally in English and I would continue improving Dutch so that I can integrate better and become more independent.',b2:'I would not say it is irrelevant — Dutch is clearly important for integration and some responsibilities. My current strength is that I can contribute in English from the beginning in an international environment, while following a serious Dutch-learning plan. I would also be transparent about situations where local-language support is necessary.',b2p:'I see Dutch as a development priority, not something to minimise. In the short term, I can contribute through my real-estate expertise and professional English, particularly in international or cross-functional contexts. At the same time, I would invest seriously in Dutch and be very clear about any task where language precision is legally or commercially critical until my level is strong enough.'}},
  {id:'dutch2',q:'How are you currently improving your Dutch?',cue:'regular study · practical exposure · measurable routine',hint:'Specific habits sound more credible than “I am motivated”.',models:{b1:'I am studying Dutch regularly and I try to practise vocabulary and everyday communication. I want to increase the amount of Dutch I use as I prepare for the move.',b2:'I am working on Dutch consistently through structured study and practical exposure. My objective is not only general conversation; I also want to build the professional vocabulary I would need for everyday workplace communication.',b2p:'I am treating Dutch as a professional integration project: regular structured study, active listening and targeted vocabulary for work situations. As I get closer to a role, I would also adapt the learning plan to the company’s real communication needs so that progress is directly relevant.'}},
  {id:'dutch3',q:'What if this role requires Dutch from the first day?',cue:'respect requirement · clarify tasks · alternative roles · no pressure',hint:'A mature answer can accept that one role may not be the right fit.',models:{b1:'If Dutch is essential from the first day, I understand that this position may not be the best fit now. I would still be interested in other opportunities where English is sufficient initially while I continue learning Dutch.',b2:'If fluent Dutch is genuinely essential from day one for core responsibilities, I would respect that requirement rather than overstate my level. I would be interested in understanding whether there are adjacent roles where my experience could be useful while I continue progressing.',b2p:'If the role depends on immediate Dutch-language precision, especially for legal or client-facing work, I would rather be realistic than create risk for either side. I would ask which responsibilities make Dutch essential and, if the gap is too large today, explore roles where my expertise can contribute immediately while I continue building the language.'}}
 ],
 unexpected:[
  {id:'un1',q:'What would your previous manager say about you?',cue:'2 strengths · evidence · one human trait',hint:'Answer with credible observations, not exaggerated praise.',models:{b1:'I think my previous manager would say that I am reliable, analytical and committed. They could trust me to study a complex issue carefully and support the team with practical advice.',b2:'I think they would describe me as rigorous, dependable and solution-focused. They knew I would take time to understand the risk, but also that I would look for a practical route forward rather than simply identify problems.',b2p:'I suspect they would say I combine rigour with pragmatism. I was someone they could rely on for complex or sensitive files because I would challenge weak assumptions, but I would also stay focused on helping the team reach a workable decision.'}},
  {id:'un2',q:'What type of colleague is difficult for you to work with?',cue:'behaviour not personality · how you adapt · professional boundary',hint:'Never attack a type of person. Describe a behaviour and your response.',models:{b1:'I find it more difficult when communication is unclear and decisions are not followed up. I try to solve this by confirming priorities and next steps so that everyone understands what has been agreed.',b2:'The most difficult situation for me is not a personality type, but when responsibilities or decisions remain unclear. I usually address that by summarising what we have agreed, clarifying ownership and checking deadlines rather than letting frustration build.',b2p:'I can work with very different personalities, but persistent ambiguity around ownership can be challenging because it creates risk. My response is to make the process explicit — decision, owner, deadline and next step — while keeping the conversation factual rather than personal.'}},
  {id:'un3',q:'What motivates you when the work becomes repetitive?',cue:'quality · purpose · improvement · discipline',hint:'Do not pretend every task is exciting.',models:{b1:'Not every task is exciting, but I stay motivated by doing the work correctly and understanding how it supports the larger project. I also look for ways to make recurring tasks more efficient.',b2:'I do not expect every task to be stimulating. What keeps me engaged is understanding its purpose and maintaining a high standard. If something is genuinely repetitive, I also look for ways to simplify the process or improve the tools around it.',b2p:'I separate motivation from novelty. Some recurring tasks are important precisely because consistency matters. I stay focused on the outcome, and where repetition reveals inefficiency, I tend to ask whether the process, template or guidance can be improved.'}},
  {id:'un4',q:'What would you do in your first 90 days?',cue:'listen · learn · relationships · quick wins · priorities',hint:'Think 30 / 60 / 90 without sounding like a consulting presentation.',models:{b1:'First, I would learn the company, the team and the main procedures. Then I would understand the current projects and build relationships with the people I work with. After that, I would try to contribute more independently.',b2:'In the first month, I would focus on understanding the team, active projects, internal processes and the Dutch context. During the second phase, I would build relationships with key stakeholders and take ownership of clearly defined work. By 90 days, I would want to be contributing independently and to have identified a few practical improvements.',b2p:'My first priority would be context before change: understand the portfolio, decision processes, risk appetite and key relationships. Once I had that foundation, I would take ownership of defined matters and look for a few credible quick wins. By 90 days, I would want colleagues to see me as reliable, increasingly autonomous and well integrated into how the team actually works.'}},
  {id:'un5',q:'If we do not hire you, what will you do next?',cue:'resilience · continue project · learn · no desperation',hint:'Stay positive and self-directed.',models:{b1:'I would be disappointed, but I would continue my job search in the Netherlands, keep improving my English and Dutch and use the experience from this interview to prepare better for the next opportunity.',b2:'Of course I would be disappointed if the role felt like a strong match, but I would continue the project. I would ask for feedback if possible, keep developing Dutch and focus on opportunities where my legal and commercial background is relevant.',b2p:'I would treat the decision as information, not as the end of the project. If feedback were available, I would use it to refine my positioning, continue developing Dutch and keep targeting roles where my transferability is strongest. The move to the Netherlands is a considered professional objective, not dependent on one application.'}},
  {id:'un6',q:'What is one assumption people may make about you that is wrong?',cue:'safe misconception · evidence · positive nuance',hint:'Choose something professional and recoverable.',models:{b1:'Because I have a legal background, people may think I am only focused on rules. In reality, I have also worked in sales and commercial roles, so I always try to find practical solutions.',b2:'People may initially assume that, because I have spent many years in legal roles, I take a purely legal approach. My earlier commercial experience is actually very important to how I work: I think about the client, the operational objective and the practical consequences as well as the legal position.',b2p:'A common assumption about experienced legal professionals is that they are primarily risk-averse. My career has been much more hybrid than that. Because I also spent years in sales management and property development, I tend to see legal analysis as a tool for enabling sound business decisions, not simply preventing action.'}}
 ],
 candidate:[
  {id:'cand1',q:'What would you like to understand about success in this role?',cue:'first 6 months · priorities · success measures',hint:'Ask something that helps you understand the role, not something easily found on the website.',models:{b1:'What would be the main priorities for the person in this role during the first six months?',b2:'What would you consider the most important priorities for the person in this role during the first six months, and how would you know they were succeeding?',b2p:'If I joined, which outcomes would matter most in the first six months, and what would distinguish someone who is simply doing the job from someone who is really adding value?'}},
  {id:'cand2',q:'What would you like to understand about the team?',cue:'collaboration · interfaces · decision-making',hint:'Show curiosity about how work actually gets done.',models:{b1:'Could you tell me how the team works together and which departments this role works with most often?',b2:'How is the team structured, and which internal stakeholders would this role collaborate with most closely on a typical project?',b2p:'Could you describe how decisions are usually made across legal, commercial and operational teams, and where this role has the most influence in that process?'}},
  {id:'cand3',q:'What would you like to understand about current challenges?',cue:'business challenge · role contribution · realistic',hint:'This can reveal what the company actually needs you to solve.',models:{b1:'What are the main challenges the team is working on at the moment?',b2:'What are the main challenges facing the team this year, and where could the person in this role make the most useful contribution?',b2p:'Which challenge is currently taking more time or attention than you would like, and what would you hope the person joining this role could improve?'}}
 ],
 closing:[
  {id:'close1',q:'Before we finish, is there anything else you would like us to know?',cue:'motivation · value · Netherlands · concise close',hint:'Do not repeat the whole interview. Leave one strong final message.',models:{b1:'I would just like to say that I am very motivated by the opportunity to work in the Netherlands. I believe my legal and commercial real-estate experience could be useful, and I would be happy to continue the discussion if you think my profile fits your needs.',b2:'I would add that this move is a serious professional project for me. I believe my combination of legal expertise, commercial experience and stakeholder management could transfer well to your environment, and I am motivated to learn the Dutch context quickly. I would be very pleased to continue to the next stage.',b2p:'The main point I would leave you with is that I am not looking simply to reproduce my French career in another country. I am looking to bring a strong, transferable real-estate skill set into a new environment, learn the Dutch context seriously and contribute with both rigour and commercial judgement. From what we have discussed, that is why this opportunity feels particularly relevant to me.'}}
 ]
};


const VOCAB=[
 ['impact','deliver results','obtenir des résultats','To produce a useful, observable outcome.','I focus on practical decisions that deliver results without losing control of risk.'],
 ['impact','add value','apporter de la valeur','To contribute something useful beyond completing tasks.','My objective would be to understand quickly where my experience can add the most value.'],
 ['impact','streamline','rationaliser / simplifier','To make a process simpler and more efficient.','I helped streamline recurring legal guidance by improving standard documents.'],
 ['impact','mitigate risk','réduire / maîtriser un risque','To reduce the likelihood or impact of a risk.','We changed the contractual wording to mitigate the main exposure.'],
 ['legal','commercial judgement','jugement / discernement commercial','The ability to make sensible business decisions, not only technical ones.','My legal background is reinforced by commercial judgement from ten years in sales management.'],
 ['legal','stakeholder coordination','coordination des parties prenantes','Organising communication and decisions among people with different roles.','Stakeholder coordination has been central to my work on complex projects.'],
 ['legal','risk assessment','évaluation des risques','A structured evaluation of possible exposure or problems.','I carried out risk assessment before recommending a contractual position.'],
 ['legal','workable solution','solution réalisable / praticable','A solution that is secure enough and can work operationally.','I try to find a workable solution rather than simply identify the legal problem.'],
 ['diplomatic','I would approach that by…','J’aborderais cela en…','A professional way to explain a hypothetical response.','I would approach that by clarifying the priorities and decision criteria first.'],
 ['diplomatic','Although…, I…','Bien que…, je…','A contrast structure that acknowledges a limitation before pivoting.','Although my Dutch is still developing, I am actively building professional vocabulary.'],
 ['diplomatic','From my perspective…','De mon point de vue…','A measured way to introduce an opinion.','From my perspective, the main issue is not only legal risk but decision clarity.'],
 ['diplomatic','I would not assume that…','Je ne partirais pas du principe que…','A useful phrase for showing nuance and humility.','I would not assume that the Dutch market works in the same way as the French market.'],
 ['adaptation','learning curve','courbe d’apprentissage','The time and effort needed to become effective in a new context.','I am realistic about the learning curve involved in a new legal framework.'],
 ['adaptation','transferable skills','compétences transférables','Skills that remain useful in a different role or market.','Negotiation and stakeholder management are highly transferable skills.'],
 ['adaptation','adapt quickly','s’adapter rapidement','To change effectively when the context changes.','I have had to adapt quickly to regulatory and project changes throughout my career.'],
 ['adaptation','build local knowledge','développer la connaissance locale','To learn the rules, practices and expectations of a new market.','My first priority would be to build local knowledge while contributing through my existing expertise.'],
 ['interview','Could you clarify what you mean by…?','Pouvez-vous préciser ce que vous entendez par… ?','A professional recovery phrase when a question is unclear.','Could you clarify what you mean by full autonomy in the first months?'],
 ['interview','Let me give you one specific example.','Permettez-moi de vous donner un exemple précis.','A phrase that creates structure before evidence.','Let me give you one specific example from a development project.'],
 ['interview','The result was…','Le résultat a été…','A direct way to close a STAR example.','The result was that the project moved forward with a clearer allocation of risk.'],
 ['interview','What would success look like…?','À quoi ressemblerait la réussite… ?','A strong candidate question about expectations.','What would success look like in this role after the first six months?']
];

const GRAMMAR=[
 {id:'g1',title:'Experience connected to now',sentence:'I ___ with many different stakeholders throughout my career.',verb:'work',answer:'have worked',hint:'Use the present perfect: have + past participle.'},
 {id:'g2',title:'Relevant negotiation experience',sentence:'Over the years, I ___ complex real-estate contracts.',verb:'negotiate',answer:'have negotiated',hint:'Experience up to now → present perfect.'},
 {id:'g3',title:'Diplomatic hypothetical',sentence:'I ___ the issue by clarifying the priorities first.',verb:'approach',answer:'would approach',hint:'Use would + base verb.'},
 {id:'g4',title:'Professional response',sentence:'If I joined the team, I ___ time in understanding the local framework.',verb:'invest',answer:'would invest',hint:'Second conditional / hypothetical professional situation.'},
 {id:'g5',title:'Contrast + limitation',sentence:'___ my Dutch is still developing, I am actively studying it.',verb:'although',answer:'although',hint:'Use a linker that introduces a contrast before a clause.'},
 {id:'g6',title:'Contrast + pivot',sentence:'My Dutch is still developing. ___, I can contribute professionally in English from the start.',verb:'however',answer:'however',hint:'Use a sentence linker followed by a comma.'},
 {id:'g7',title:'Purpose',sentence:'I am improving my Dutch ___ integrate more effectively into the workplace.',verb:'integrate',answer:'to integrate',hint:'Purpose → to + base verb.'},
 {id:'g8',title:'Past specific action',sentence:'In that project, I ___ the risk and proposed alternative wording.',verb:'identify',answer:'identified',hint:'Finished event in a finished past situation → past simple.'},
 {id:'g9',title:'Present perfect + duration',sentence:'I ___ in the real-estate sector for more than 24 years.',verb:'work',answer:'have worked',hint:'For + duration continuing to the present → present perfect.'}
];

const LISTENING=[
 {id:'l1',title:'Dutch requirement',script:'Your background is very relevant, but this position includes regular contact with Dutch-speaking municipalities and external advisers. How would you manage the language requirement during your first months?',fr:'Votre parcours est très pertinent, mais ce poste implique des contacts réguliers avec des municipalités et des conseils néerlandophones. Comment géreriez-vous cette exigence linguistique pendant vos premiers mois ?',q:'What is the recruiter really testing?',answer:1,options:['Whether you can avoid speaking Dutch completely','Whether you understand the risk and have a realistic integration plan','Whether you have worked in a municipality before'],model:'They are testing whether I understand that Dutch matters operationally and whether I can manage the transition responsibly while improving my level.'},
 {id:'l2',title:'Transferability challenge',script:'Most of your experience is in France. What makes you confident that your legal and commercial expertise will transfer to the Dutch property market?',fr:'La majeure partie de votre expérience est en France. Qu’est-ce qui vous rend confiante sur le fait que votre expertise juridique et commerciale sera transférable au marché immobilier néerlandais ?',q:'What must your answer include?',answer:2,options:['A statement that French law is the same as Dutch law','A long list of every contract you have drafted','Transferable skills plus humility about learning the local framework'],model:'I should explain that negotiation, risk analysis and stakeholder coordination transfer well, while being clear that I would need to learn the Dutch legal and market framework.'},
 {id:'l3',title:'Salary pressure',script:'I understand you would like to know the range, but I also need to understand whether your expectations are broadly compatible with our budget. Could you give me an indication?',fr:'Je comprends que vous souhaitiez connaître la fourchette, mais j’ai aussi besoin de savoir si vos attentes sont globalement compatibles avec notre budget. Pouvez-vous me donner une indication ?',q:'What is the best strategy?',answer:0,options:['Give a reasonable indication or range while keeping context','Refuse to discuss salary at all','Change the subject to Dutch lessons'],model:'I can give a broad indication based on the responsibilities while explaining that I would like to consider the full package and scope of the role.'},
 {id:'l4',title:'Precision follow-up',script:'You said you are good at managing complex stakeholders. Can you tell me about one situation where your first approach did not work and you had to change it?',fr:'Vous avez dit que vous gérez bien des parties prenantes complexes. Pouvez-vous me parler d’une situation où votre première approche n’a pas fonctionné et où vous avez dû la modifier ?',q:'What extra difficulty has the recruiter added?',answer:1,options:['You must talk about your strongest success only','You must show adaptability after an initial approach failed','You must give the names of the stakeholders'],model:'The recruiter wants evidence of self-correction. I need to show that I noticed the first approach was not effective, changed it and explain what improved.'}
];

const CANDIDATE_QUIZ=[
 {id:'cq1',q:'Which question creates the strongest discussion?',answer:1,options:['How many holidays do I get?','What would success look like in the first six months?','Is the office nice?']},
 {id:'cq2',q:'Which question is strongest for understanding team culture?',answer:2,options:['Do people like working here?','Is the manager strict?','How do legal, commercial and operational teams usually work together on a project?']},
 {id:'cq3',q:'Which question shows business curiosity?',answer:0,options:['What is the biggest challenge you would like the person in this role to help solve?','When can I be promoted?','Do you have many meetings?']},
 {id:'cq4',q:'Which language question sounds most mature?',answer:1,options:['Can I avoid Dutch?','Which responsibilities require Dutch immediately, and which could be handled in English while I continue learning?','Will you pay for lessons?']}
];

const SECTIONS={
 route:{objective:'Understand the final interview method and comparison process',evidence:'Route, timing and response strategy',mode:'Trainer validation'},
 language:{objective:'Mobilise precise B2 interview vocabulary without overloading answers',evidence:'Filtered language bank with EN/FR definitions and reusable examples',mode:'Trainer validation'},
 intro:{objective:'Deliver a concise 60-second professional introduction',evidence:'Self-introduction with career map and Netherlands objective',mode:'Oral production'},
 recruiter:{objective:'Answer core recruiter questions with clear evidence and relevance',evidence:'Motivation, role fit, strengths, learning curve, 3-year outlook',mode:'Oral simulation'},
 star:{objective:'Use STAR to give structured competency evidence',evidence:'Difficulty, adaptation, disagreement, mistake, initiative',mode:'Oral simulation'},
 pressure:{objective:'Respond to probing follow-up questions without losing structure',evidence:'Specific evidence, personal action, reflection and business impact',mode:'Oral pressure simulation'},
 dutch:{objective:'Present Dutch as a credible development area',evidence:'Language requirement, learning plan, first-day requirement',mode:'Oral simulation'},
 grammar:{objective:'Use B2 grammar tools accurately in interview language',evidence:'Present perfect, conditionals, contrast, purpose, past simple',mode:'Automatic exercises'},
 listening:{objective:'Understand recruiter questions under pressure and identify intent',evidence:'Four listening scenarios with reformulation focus',mode:'Listening QCM'},
 unexpected:{objective:'Handle unexpected interview questions with confidence and evidence',evidence:'Six surprise questions',mode:'Oral simulation'},
 candidate:{objective:'Ask intelligent candidate questions at the end of an interview',evidence:'Question quality + candidate question builder',mode:'QCM + oral production'},
 closing:{objective:'Close an interview with motivation, value and professional confidence',evidence:'30–45 second closing statement',mode:'Oral production'},
 recorder:{objective:'Self-assess one recorded interview answer',evidence:'Recorded answer + trainer notes',mode:'Recorded oral evidence'}
};

const RUBRICS=['Clarity','Relevance','Structure','Grammar accuracy','Professional vocabulary','Fluency','Confidence / recovery'];
let state={answers:{},corrections:{},evals:{},auto:{},rubric:{},fields:{},savedAt:null};
let timerSeconds=0,timerHandle=null,timerRunning=true,mediaRecorder=null,chunks=[],recordingUrl='';

function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function normalize(s){return String(s||'').trim().toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ')}
function statusClass(v){return v||'not-started'}
function statusLabel(v){return STATUS_LABELS[v]||STATUS_LABELS['not-started']}

function renderQuestionGroup(containerId,items){
 const c=$('#'+containerId); if(!c)return;
 c.innerHTML=items.map((item,i)=>{
  const cue=item.cue.split('·').map(x=>`<span>${esc(x.trim())}</span>`).join('');
  return `<article class="q-card" data-qid="${esc(item.id)}">
   <div class="q-head"><div class="q-number">${String(i+1).padStart(2,'0')}</div><div><h3>${esc(item.q)}</h3><p>${esc(item.hint)}</p></div><div class="q-tools"><button type="button" data-say="${esc(item.q)}">🔊 Question</button><button type="button" class="hint-btn">💡 Cues</button></div></div>
   <div class="q-body"><div class="cue-box">${cue}</div>
    <div class="answer-grid"><label>Your answer<textarea data-answer="${esc(item.id)}" rows="5" placeholder="Answer in your own words before opening a model..."></textarea></label><label>Trainer correction / improved version<textarea data-correction="${esc(item.id)}" rows="5" placeholder="Correct grammar, vocabulary, structure, pronunciation notes or rewrite here..."></textarea></label></div>
    <div class="model-zone"><div class="model-controls"><button type="button" data-model="b1">B1 secure</button><button type="button" data-model="b2">B2 strong</button><button type="button" data-model="b2p">B2+ polished</button><button type="button" class="close-model">Hide model</button></div>
    ${['b1','b2','b2p'].map(level=>`<div class="model-panel" data-panel="${level}"><strong>${level==='b1'?'B1 secure':level==='b2'?'B2 strong':'B2+ polished'}</strong><p>${esc(item.models[level])}</p><div class="level-note">${esc(LEVEL_NOTES[level])}</div></div>`).join('')}
    <div class="micro-analysis"><strong>Compare:</strong> structure → specificity → verbs → linking → professional relevance. Keep Isabelle’s own voice; do not replace it with a memorised script.</div></div>
   </div></article>`
 }).join('');
}


function renderVocab(){const c=$('#vocabGrid');if(!c)return;const filter=$('#vocabFilter')?.value||'all',q=normalize($('#vocabSearch')?.value||'');const rows=VOCAB.filter(v=>(filter==='all'||v[0]===filter)&&(!q||normalize(v.join(' ')).includes(q)));c.innerHTML=rows.map(v=>`<article class="vocab-card"><div class="cat">${esc(v[0])}</div><h3>${esc(v[1])}</h3><div class="fr-word">${esc(v[2])}</div><div class="definition">${esc(v[3])}</div><div class="vexample"><strong>Example:</strong> ${esc(v[4])}</div><button type="button" data-say="${esc(v[4])}">🔊 Example</button></article>`).join('')||'<p>No vocabulary matches this filter.</p>'}

function renderSectionEvals(){
 $$('.section-eval').forEach(box=>{const id=box.dataset.eval,d=SECTIONS[id];
  box.innerHTML=`<div class="eval-card"><div><h4>Trainer validation · ${esc(d.objective)}</h4><div class="mini-note">${esc(d.evidence)}</div><div class="eval-scoreline"><label>Clarity /4<input type="number" min="1" max="4" data-eval-score="${id}:clarity"></label><label>Accuracy /4<input type="number" min="1" max="4" data-eval-score="${id}:accuracy"></label><label>Impact /4<input type="number" min="1" max="4" data-eval-score="${id}:impact"></label></div></div><div><label class="full-label">Status<select data-eval-status="${id}"><option value="not-started">Non commencé</option><option value="progress">En cours d’acquisition</option><option value="achieved">Objectif atteint</option><option value="not-achieved">Objectif non atteint</option></select></label></div><div><label class="full-label">Evidence / comment<textarea rows="3" data-eval-comment="${id}" placeholder="What Isabelle did well, error pattern, correction, next priority..."></textarea></label></div></div>`;
 });
 $('#manualTotal').textContent=Object.keys(SECTIONS).length;
}

function renderGrammar(){const c=$('#grammarGrid');c.innerHTML=GRAMMAR.map((g,i)=>`<article class="grammar-item" data-gid="${g.id}"><h4>${i+1}. ${esc(g.title)}</h4><p>${esc(g.sentence)}</p><button type="button" class="hint-toggle">💡 Hint</button><div class="hint">${esc(g.hint)}</div><div class="verb-chip">Verb / word to use: ${esc(g.verb)}</div><div class="grammar-row"><input data-grammar-input="${g.id}" autocomplete="off" placeholder="Type the correct form"><button type="button" data-check-grammar="${g.id}">Check</button></div><div class="feedback" data-feedback="${g.id}"></div></article>`).join('')}

function renderListening(){const c=$('#listeningLab');c.innerHTML=LISTENING.map((l,i)=>`<article class="listen-card" data-lid="${l.id}"><div class="listen-top"><span class="tag professional">${i+1}. ${esc(l.title)}</span><button type="button" data-listen="${l.id}">🔊 Listen</button><button type="button" data-transcript="${l.id}">📄 Transcript</button><button type="button" data-listen-fr="${l.id}">🇫🇷 French help</button></div><h3>${esc(l.q)}</h3><div class="options">${l.options.map((o,j)=>`<button type="button" data-listen-option="${l.id}:${j}">${esc(o)}</button>`).join('')}</div><div class="feedback" data-listen-feedback="${l.id}"></div><div class="listen-script"><strong>Transcript:</strong> ${esc(l.script)}<div class="model-zone"><strong>Model reformulation:</strong> ${esc(l.model)}</div></div><div class="listen-fr"><strong>FR :</strong> ${esc(l.fr)}</div></article>`).join('')}

function renderCandidateQuiz(){const c=$('#candidateQuiz');c.innerHTML=CANDIDATE_QUIZ.map((q,i)=>`<article class="quiz-card"><h4>${i+1}. ${esc(q.q)}</h4><div class="options">${q.options.map((o,j)=>`<button type="button" data-candidate-option="${q.id}:${j}">${esc(o)}</button>`).join('')}</div><div class="feedback" data-candidate-feedback="${q.id}"></div></article>`).join('')}

function renderRubric(){const c=$('#rubricGrid');c.innerHTML=RUBRICS.map((r,i)=>`<div class="rubric-item"><label>${esc(r)}</label><select data-rubric="r${i}"><option value="">Not assessed</option><option value="1">1 · Fragile</option><option value="2">2 · Developing</option><option value="3">3 · Strong B2</option><option value="4">4 · Interview-ready</option></select></div>`).join('')}

function renderAll(){
 renderVocab();renderQuestionGroup('introQuestions',QUESTION_DATA.intro);renderQuestionGroup('recruiterQuestions',QUESTION_DATA.recruiter);renderQuestionGroup('starQuestions',QUESTION_DATA.star);renderQuestionGroup('pressureQuestions',QUESTION_DATA.pressure);renderQuestionGroup('dutchQuestions',QUESTION_DATA.dutch);renderQuestionGroup('unexpectedQuestions',QUESTION_DATA.unexpected);renderQuestionGroup('candidateQuestions',QUESTION_DATA.candidate);renderQuestionGroup('closingQuestions',QUESTION_DATA.closing);renderSectionEvals();renderGrammar();renderListening();renderCandidateQuiz();renderRubric();
}

function speak(text){if(!('speechSynthesis' in window)){toast('Speech is not supported in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=$('#accent').value||'en-GB';const voices=speechSynthesis.getVoices();const preferred=voices.find(v=>v.lang===u.lang)||voices.find(v=>v.lang?.startsWith(u.lang.slice(0,2)));if(preferred)u.voice=preferred;u.rate=.92;speechSynthesis.speak(u)}

function bindQuestionModels(){
 document.addEventListener('click',e=>{
  const say=e.target.closest('[data-say]');if(say){speak(say.dataset.say);return}
  const model=e.target.closest('[data-model]');if(model){const card=model.closest('.q-card');$$('.model-panel',card).forEach(p=>p.classList.toggle('open',p.dataset.panel===model.dataset.model));$$('[data-model]',card).forEach(b=>b.classList.toggle('active',b===model));return}
  if(e.target.closest('.close-model')){const card=e.target.closest('.q-card');$$('.model-panel',card).forEach(p=>p.classList.remove('open'));$$('[data-model]',card).forEach(b=>b.classList.remove('active'));return}
  if(e.target.closest('.hint-btn')){const card=e.target.closest('.q-card'),cue=$('.cue-box',card);cue.style.display=cue.style.display==='none'?'flex':'none';return}
 });
}

function bindGrammar(){
 document.addEventListener('click',e=>{const h=e.target.closest('.hint-toggle');if(h){h.closest('.grammar-item').classList.toggle('show-hint');return}const b=e.target.closest('[data-check-grammar]');if(!b)return;const id=b.dataset.checkGrammar,g=GRAMMAR.find(x=>x.id===id),inp=$(`[data-grammar-input="${id}"]`),fb=$(`[data-feedback="${id}"]`);const ok=normalize(inp.value)===normalize(g.answer);state.auto[id]=ok?1:0;fb.textContent=ok?'✓ Correct.':'✗ Not yet. Correct answer: '+g.answer;fb.className='feedback '+(ok?'good':'bad');saveState(false);refreshDashboard()});
}

function bindListening(){document.addEventListener('click',e=>{let b=e.target.closest('[data-listen]');if(b){const l=LISTENING.find(x=>x.id===b.dataset.listen);speak(l.script);return}b=e.target.closest('[data-transcript]');if(b){b.closest('.listen-card').classList.toggle('show-script');return}b=e.target.closest('[data-listen-fr]');if(b){b.closest('.listen-card').classList.toggle('show-fr-local');return}b=e.target.closest('[data-listen-option]');if(b){const [id,idxS]=b.dataset.listenOption.split(':'),idx=+idxS,l=LISTENING.find(x=>x.id===id),card=b.closest('.listen-card');$$('[data-listen-option]',card).forEach((x,j)=>{x.classList.remove('correct','wrong');if(j===l.answer)x.classList.add('correct')});if(idx!==l.answer)b.classList.add('wrong');state.auto[id]=idx===l.answer?1:0;const fb=$(`[data-listen-feedback="${id}"]`);fb.textContent=idx===l.answer?'✓ Correct. Now reformulate the recruiter’s intent aloud.':'✗ Not quite. Read the feedback in the correct option and listen again.';fb.className='feedback '+(idx===l.answer?'good':'bad');saveState(false);refreshDashboard()}})}

function bindCandidateQuiz(){document.addEventListener('click',e=>{const b=e.target.closest('[data-candidate-option]');if(!b)return;const [id,idxS]=b.dataset.candidateOption.split(':'),idx=+idxS,q=CANDIDATE_QUIZ.find(x=>x.id===id),card=b.closest('.quiz-card');$$('[data-candidate-option]',card).forEach((x,j)=>{x.classList.remove('correct','wrong');if(j===q.answer)x.classList.add('correct')});if(idx!==q.answer)b.classList.add('wrong');state.auto[id]=idx===q.answer?1:0;const fb=$(`[data-candidate-feedback="${id}"]`);fb.textContent=idx===q.answer?'✓ Correct — specific, useful and professional.':'✗ Choose the question that reveals useful information about the role or team.';fb.className='feedback '+(idx===q.answer?'good':'bad');saveState(false);refreshDashboard()})}

function bindInputs(){document.addEventListener('input',e=>{if(e.target.matches('[data-answer]'))state.answers[e.target.dataset.answer]=e.target.value;else if(e.target.matches('[data-correction]'))state.corrections[e.target.dataset.correction]=e.target.value;else if(e.target.matches('[data-eval-comment]')){const id=e.target.dataset.evalComment;state.evals[id]=state.evals[id]||{};state.evals[id].comment=e.target.value}else if(e.target.matches('[data-eval-score]')){const [id,key]=e.target.dataset.evalScore.split(':');state.evals[id]=state.evals[id]||{};state.evals[id][key]=e.target.value}else if(e.target.matches('[data-save]'))state.fields[e.target.dataset.save]=e.target.value;saveState(false);refreshDashboard()});document.addEventListener('change',e=>{if(e.target.matches('[data-eval-status]')){const id=e.target.dataset.evalStatus;state.evals[id]=state.evals[id]||{};state.evals[id].status=e.target.value}else if(e.target.matches('[data-rubric]'))state.rubric[e.target.dataset.rubric]=e.target.value;saveState(false);refreshDashboard()})}

function loadState(){try{const raw=localStorage.getItem(STORAGE);if(raw)state=Object.assign(state,JSON.parse(raw))}catch(e){console.warn(e)}
 $$('[data-answer]').forEach(x=>x.value=state.answers[x.dataset.answer]||'');$$('[data-correction]').forEach(x=>x.value=state.corrections[x.dataset.correction]||'');$$('[data-eval-status]').forEach(x=>x.value=state.evals[x.dataset.evalStatus]?.status||'not-started');$$('[data-eval-comment]').forEach(x=>x.value=state.evals[x.dataset.evalComment]?.comment||'');$$('[data-eval-score]').forEach(x=>{const [id,key]=x.dataset.evalScore.split(':');x.value=state.evals[id]?.[key]||''});$$('[data-rubric]').forEach(x=>x.value=state.rubric[x.dataset.rubric]||'');$$('[data-save]').forEach(x=>x.value=state.fields[x.dataset.save]||'');
 const f=['learnerName','trainerName','evaluationDate','sessionDuration','readinessSelect','priorityField','generalTrainerComments','nextStepComments'];f.forEach(id=>{if(state.fields[id]!==undefined&&$('#'+id))$('#'+id).value=state.fields[id]});if(!$('#evaluationDate').value)$('#evaluationDate').value=new Date().toISOString().slice(0,10);if(state.savedAt)$('#lastSaved').textContent=new Date(state.savedAt).toLocaleString();
 // restore auto feedback visually
 GRAMMAR.forEach(g=>{if(g.id in state.auto){const fb=$(`[data-feedback="${g.id}"]`);const ok=state.auto[g.id]===1;fb.textContent=ok?'✓ Correct.':'Previously attempted — correct answer: '+g.answer;fb.className='feedback '+(ok?'good':'bad')}});
}

function saveState(show=true){['learnerName','trainerName','evaluationDate','sessionDuration','readinessSelect','priorityField','generalTrainerComments','nextStepComments'].forEach(id=>{if($('#'+id))state.fields[id]=$('#'+id).value});state.savedAt=new Date().toISOString();let stored=true;try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch(e){stored=false;console.warn('Local storage unavailable',e)}if($('#lastSaved'))$('#lastSaved').textContent=new Date(state.savedAt).toLocaleString();if(show)toast(stored?'Progress saved in this browser.':'Progress updated, but browser storage is unavailable.')}

function autoStats(){const ids=[...GRAMMAR.map(x=>x.id),...LISTENING.map(x=>x.id),...CANDIDATE_QUIZ.map(x=>x.id)];const done=ids.filter(id=>id in state.auto),correct=done.reduce((a,id)=>a+(state.auto[id]||0),0);return {total:ids.length,done:done.length,correct}}
function manualStats(){const ids=Object.keys(SECTIONS),done=ids.filter(id=>state.evals[id]?.status&&state.evals[id].status!=='not-started');const achieved=ids.filter(id=>state.evals[id]?.status==='achieved').length;return{total:ids.length,done:done.length,achieved}}
function rubricAverage(){const vals=Object.values(state.rubric).map(Number).filter(Boolean);return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0}

function refreshDashboard(){const a=autoStats(),m=manualStats();$('#score').textContent=a.correct;$('#maxScore').textContent=a.total;$('#manualDone').textContent=m.done;$('#manualTotal').textContent=m.total;const autoPct=a.total?Math.round(a.correct/a.total*100):0,manualPct=m.total?Math.round(m.done/m.total*100):0,completion=Math.round((a.done/a.total*.45+m.done/m.total*.55)*100);$('#autoRate').textContent=autoPct+'%';$('#manualRate').textContent=manualPct+'%';$('#completionRate').textContent=completion+'%';$('#progressText').textContent=completion+'%';$('#progressFill').style.width=completion+'%';const avg=rubricAverage();let readiness=$('#readinessSelect')?.value||'';if(!readiness){readiness=avg>=3.4?'Ready':avg>=2.6?'Nearly ready':avg>0?'Needs targeted work':'Not assessed'}$('#readinessLabel').textContent=readiness;let overall='not-started';if(m.done||a.done)overall='progress';if(m.done===m.total&&a.done===a.total)overall=(autoPct>=75&&m.achieved>=Math.ceil(m.total*.65))?'achieved':'progress';const el=$('#overallStatus');el.textContent=statusLabel(overall);el.className='status-badge '+overall;renderEvaluationRows()}

function renderEvaluationRows(){const tbody=$('#evaluationRows');if(!tbody)return;const a=autoStats();tbody.innerHTML=Object.entries(SECTIONS).map(([id,d])=>{const ev=state.evals[id]||{},st=ev.status||'not-started';let score='Trainer validation';if(id==='grammar'){const ids=GRAMMAR.map(x=>x.id),done=ids.filter(x=>x in state.auto),correct=done.reduce((n,x)=>n+(state.auto[x]||0),0);score=`${correct}/${ids.length} correct`;}if(id==='listening'){const ids=LISTENING.map(x=>x.id),correct=ids.reduce((n,x)=>n+(state.auto[x]||0),0);score=`${correct}/${ids.length} correct`;}if(id==='candidate'){const ids=CANDIDATE_QUIZ.map(x=>x.id),correct=ids.reduce((n,x)=>n+(state.auto[x]||0),0);score=`${correct}/${ids.length} QCM + trainer validation`;}const nums=['clarity','accuracy','impact'].map(k=>ev[k]).filter(Boolean);if(nums.length)score+=` · Manual ${nums.join('/')}/4`;return `<tr><td>${esc(d.objective)}</td><td>${esc(d.evidence)}</td><td>${esc(d.mode)}</td><td>${esc(score)}</td><td><span class="status-badge ${statusClass(st)}">${esc(statusLabel(st))}</span></td><td>${esc(ev.comment||'')}</td></tr>`}).join('')}

function bindGlobal(){
 $('#vocabFilter')?.addEventListener('change',renderVocab);$('#vocabSearch')?.addEventListener('input',renderVocab);
 $('#toggleFrench').addEventListener('click',()=>{document.body.classList.toggle('show-fr');$('#toggleFrench').textContent=document.body.classList.contains('show-fr')?'🇫🇷 Hide French':'🇫🇷 French help'});$('#stopSpeech').addEventListener('click',()=>speechSynthesis?.cancel());$('#printPage').addEventListener('click',()=>window.print());$('#saveAll').addEventListener('click',()=>saveState(true));$('#saveEvaluation').addEventListener('click',()=>saveState(true));$('#resetAll').addEventListener('click',()=>{if(confirm('Reset all Isabelle lesson answers and evaluation data in this browser?')){localStorage.removeItem(STORAGE);location.reload()}});$('#backToTop').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));window.addEventListener('scroll',()=>$('#backToTop').classList.toggle('show',scrollY>500));
 $('#pauseTimer').addEventListener('click',()=>{timerRunning=!timerRunning;$('#pauseTimer').textContent=timerRunning?'Pause':'Resume'});$('#randomUnexpected').addEventListener('click',()=>{const list=QUESTION_DATA.unexpected,q=list[Math.floor(Math.random()*list.length)];$('#surpriseStage').innerHTML=`<strong>Recruiter:</strong> ${esc(q.q)}`;speak(q.q)});
 ['learnerName','trainerName','evaluationDate','sessionDuration','readinessSelect','priorityField','generalTrainerComments','nextStepComments'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{state.fields[id]=$('#'+id).value;saveState(false);refreshDashboard()}));
 $('#copyReport').addEventListener('click',async()=>{const txt=plainSummary();try{await navigator.clipboard.writeText(txt);toast('Report summary copied.')}catch{toast('Copy is not available in this browser.')}});$('#downloadHtml').addEventListener('click',downloadHTMLReport);$('#downloadPdf').addEventListener('click',downloadPDFReport);
}

function startTimer(){timerHandle=setInterval(()=>{if(!timerRunning)return;timerSeconds++;const m=Math.floor(timerSeconds/60).toString().padStart(2,'0'),s=(timerSeconds%60).toString().padStart(2,'0');$('#timer').textContent=`${m}:${s}`},1000)}

async function setupRecorder(){const start=$('#startRec'),stop=$('#stopRec'),clear=$('#clearRec');if(!navigator.mediaDevices?.getUserMedia){start.disabled=true;$('#recStatus').textContent='Microphone recording is not supported in this browser.';return}start.addEventListener('click',async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>chunks.push(e.data);mediaRecorder.onstop=()=>{const blob=new Blob(chunks,{type:mediaRecorder.mimeType||'audio/webm'});if(recordingUrl)URL.revokeObjectURL(recordingUrl);recordingUrl=URL.createObjectURL(blob);$('#audioPlayback').src=recordingUrl;$('#audioPlayback').hidden=false;$('#downloadRecording').href=recordingUrl;$('#downloadRecording').classList.remove('hidden');stream.getTracks().forEach(t=>t.stop());$('#recStatus').textContent='Recording ready. Listen once and identify one improvement.'};mediaRecorder.start();start.disabled=true;stop.disabled=false;$('#recStatus').textContent='Recording…';}catch(e){$('#recStatus').textContent='Microphone permission was not granted or recording is unavailable.'}});stop.addEventListener('click',()=>{if(mediaRecorder?.state==='recording')mediaRecorder.stop();start.disabled=false;stop.disabled=true});clear.addEventListener('click',()=>{if(recordingUrl)URL.revokeObjectURL(recordingUrl);recordingUrl='';$('#audioPlayback').src='';$('#audioPlayback').hidden=true;$('#downloadRecording').classList.add('hidden');$('#recStatus').textContent='Recording cleared.'})}

function plainSummary(){const a=autoStats(),m=manualStats(),avg=rubricAverage();const lines=[`QUALIOPI – Isabelle Final Interview Simulation`,`Apprenante: ${$('#learnerName').value}`,`Formatrice: ${$('#trainerName').value}`,`Date: ${$('#evaluationDate').value}`,`Completion: ${$('#completionRate').textContent}`,`Automatic score: ${a.correct}/${a.total}`,`Manual sections evaluated: ${m.done}/${m.total}`,`Final readiness: ${$('#readinessLabel').textContent}`,`Rubric average: ${avg?avg.toFixed(1)+'/4':'Not assessed'}`,''];Object.entries(SECTIONS).forEach(([id,d],i)=>{const ev=state.evals[id]||{};lines.push(`${i+1}. ${d.objective}`);lines.push(`Status: ${statusLabel(ev.status||'not-started')}`);if(ev.comment)lines.push(`Comment: ${ev.comment}`)});lines.push('',`Priority: ${$('#priorityField').value||''}`,`General observations: ${$('#generalTrainerComments').value||''}`,`Next step: ${$('#nextStepComments').value||''}`);return lines.join('\n')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function safeName(s){return String(s||'Isabelle').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')}
function downloadHTMLReport(){saveState(false);const rows=$('#evaluationRows').innerHTML;const answerEvidence=Object.entries(state.corrections).filter(([,v])=>v.trim()).map(([id,v])=>`<h3>${esc(id)} — trainer correction</h3><div class="box">${esc(v).replace(/\n/g,'<br>')}</div>`).join('');const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Qualiopi - Isabelle Final Interview</title><style>body{font-family:Arial,sans-serif;max-width:1100px;margin:32px auto;padding:0 20px;color:#1c2b32}h1,h2{color:#10384b}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #bbcaca;padding:8px;vertical-align:top}th{background:#eef6f4}.meta{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.box{border:1px solid #ccd8d7;border-radius:8px;padding:10px;margin:8px 0;white-space:pre-wrap}.badge{display:inline-block;padding:4px 7px;border-radius:10px;background:#eef6f4}@media print{body{max-width:none;margin:0}}</style></head><body><h1>Bilan d’évaluation des acquis — Qualiopi</h1><h2>Isabelle · Final Interview Simulation</h2><div class="meta"><div class="box"><b>Apprenante:</b> ${esc($('#learnerName').value)}</div><div class="box"><b>Formatrice:</b> ${esc($('#trainerName').value)}</div><div class="box"><b>Date:</b> ${esc($('#evaluationDate').value)}</div><div class="box"><b>Durée:</b> ${esc($('#sessionDuration').value)}</div><div class="box"><b>Completion:</b> ${esc($('#completionRate').textContent)}</div><div class="box"><b>Readiness:</b> ${esc($('#readinessLabel').textContent)}</div></div><h2>Objectifs et résultats</h2><table><thead><tr><th>Objectif</th><th>Evidence</th><th>Mode</th><th>Score / validation</th><th>Résultat</th><th>Commentaire</th></tr></thead><tbody>${rows}</tbody></table><h2>Observations générales</h2><div class="box">${esc($('#generalTrainerComments').value)}</div><h2>Priority / next step</h2><div class="box"><b>Priority:</b> ${esc($('#priorityField').value)}<br><br><b>Next step:</b> ${esc($('#nextStepComments').value)}</div>${answerEvidence?'<h2>Trainer corrections saved during the lesson</h2>'+answerEvidence:''}<p><small>Generated from the interactive Isabelle interview lesson. Data was recorded through automatic exercises and trainer validation.</small></p></body></html>`;downloadBlob(new Blob([html],{type:'text/html;charset=utf-8'}),`${safeName($('#learnerName').value)}-Final-Interview-Qualiopi.html`)}

function latin(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").replace(/[“”]/g,'"').replace(/[–—]/g,'-').replace(/[^\x20-\x7E]/g,' ')}
function pdfEsc(s){return latin(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function wrap(text,max=88){const words=latin(text).split(/\s+/),out=[];let line='';for(const w of words){if(!w)continue;const n=line?line+' '+w:w;if(n.length>max&&line){out.push(line);line=w}else line=n}if(line)out.push(line);return out.length?out:['']}
function buildPDF(text){const W=595,H=842,left=42,top=798,bottom=48;let pages=[[]],y=top;const add=(t,size=10,bold=false)=>{for(const line of wrap(t,size>=14?70:88)){if(y<bottom){pages.push([]);y=top}pages.at(-1).push({t:line,x:left,y,size,bold});y-=size>=14?20:14}};const gap=(n=7)=>y-=n;text.split('\n').forEach(line=>{if(line.startsWith('QUALIOPI')){add(line,16,true);gap(4)}else if(/^\d+\./.test(line)){gap(4);add(line,11,true)}else if(/^(Apprenante|Formatrice|Date|Completion|Automatic|Manual|Final readiness|Rubric average|Priority|General observations|Next step|Status|Comment):/.test(line)){add(line,10,line.startsWith('Priority')||line.startsWith('Status'))}else add(line,10,false)});const objs=[];const obj=b=>(objs.push(b),objs.length);const f1=obj('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),f2=obj('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');const pageRefs=[],contentRefs=[];for(const lines of pages){let stream='';for(const l of lines)stream+=`BT /${l.bold?'F2':'F1'} ${l.size} Tf 1 0 0 1 ${l.x} ${l.y} Tm (${pdfEsc(l.t)}) Tj ET\n`;contentRefs.push(obj(`<< /Length ${stream.length} >>\nstream\n${stream}endstream`));pageRefs.push(obj('PLACEHOLDER'))}const pagesRef=obj('PLACEHOLDER_PAGES');pageRefs.forEach((ref,i)=>objs[ref-1]=`<< /Type /Page /Parent ${pagesRef} 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 ${f1} 0 R /F2 ${f2} 0 R >> >> /Contents ${contentRefs[i]} 0 R >>`);objs[pagesRef-1]=`<< /Type /Pages /Kids [${pageRefs.map(r=>r+' 0 R').join(' ')}] /Count ${pageRefs.length} >>`;const catalog=obj(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`);let pdf='%PDF-1.4\n';const offsets=[0];objs.forEach((b,i)=>{offsets[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${b}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function downloadPDFReport(){saveState(false);downloadBlob(buildPDF(plainSummary()),`${safeName($('#learnerName').value)}-Final-Interview-Qualiopi.pdf`)}

function init(){renderAll();bindQuestionModels();bindGrammar();bindListening();bindCandidateQuiz();bindInputs();bindGlobal();loadState();setupRecorder();startTimer();refreshDashboard();}
document.addEventListener('DOMContentLoaded',init);
})();
