(() => {
  const STORAGE_KEY='mireille_gallery_lesson4_fields_v1';
  const TRACKING_KEY='mireille_gallery_lesson4_tracking_v1';
  const sections=[...document.querySelectorAll('.lesson-section')], navItems=[...document.querySelectorAll('.nav-item')];
  const title=document.getElementById('sectionTitle'), progressBar=document.getElementById('progressBar'), progressLabel=document.getElementById('progressLabel'), progressPercent=document.getElementById('progressPercent'), footerProgress=document.getElementById('footerProgress');
  const prevBtn=document.getElementById('prevSection'), nextBtn=document.getElementById('nextSection'), saveStatus=document.getElementById('saveStatus');
  const trackables=[...document.querySelectorAll('.trackable')];
  let current=0, trainerMode=false, fieldState={}, tracking={exercises:{},tasks:{}};
  const visibleSections=()=>sections.filter(sec=>trainerMode||!sec.classList.contains('trainer-section'));
  function showSection(index){const available=visibleSections();index=Math.max(0,Math.min(index,available.length-1));const target=available[index];sections.forEach(s=>s.classList.remove('active'));target.classList.add('active');current=index;navItems.forEach(n=>n.classList.toggle('active',Number(n.dataset.section)===Number(target.dataset.index)));title.textContent=target.dataset.title;const pct=Math.round(((index+1)/available.length)*100);progressBar.style.width=`${pct}%`;progressLabel.textContent=`${index+1} / ${available.length}`;progressPercent.textContent=`${pct}%`;footerProgress.textContent=`Section ${index+1} of ${available.length}`;prevBtn.disabled=index===0;nextBtn.disabled=index===available.length-1;window.scrollTo({top:0,behavior:'smooth'});updateMetrics();}
  navItems.forEach(item=>item.addEventListener('click',()=>{const idx=visibleSections().findIndex(sec=>Number(sec.dataset.index)===Number(item.dataset.section));if(idx>=0)showSection(idx);}));prevBtn.addEventListener('click',()=>showSection(current-1));nextBtn.addEventListener('click',()=>showSection(current+1));
  document.getElementById('frToggle').addEventListener('click',e=>{document.body.classList.toggle('show-fr');const on=document.body.classList.contains('show-fr');e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=`FR help: ${on?'ON':'OFF'}`;});
  document.getElementById('trainerToggle').addEventListener('click',e=>{trainerMode=!trainerMode;document.body.classList.toggle('trainer-mode',trainerMode);e.currentTarget.setAttribute('aria-pressed',String(trainerMode));e.currentTarget.textContent=`Trainer view: ${trainerMode?'ON':'OFF'}`;const activeTrainer=sections.find(s=>s.classList.contains('active')&&s.classList.contains('trainer-section'));if(!trainerMode&&activeTrainer)showSection(0);else showSection(Math.min(current,visibleSections().length-1));});
  function storageId(el){if(el.id)return `id:${el.id}`;if(el.name)return `name:${el.name}:${el.value}`;const all=[...document.querySelectorAll('[data-save]')];return `idx:${all.indexOf(el)}`;}
  function saveFields(){fieldState={};document.querySelectorAll('[data-save]').forEach(el=>{fieldState[storageId(el)]=(el.type==='checkbox'||el.type==='radio')?el.checked:el.value;});localStorage.setItem(STORAGE_KEY,JSON.stringify(fieldState));saveStatus.textContent='● Saved';setTimeout(()=>saveStatus.textContent='● Autosave ready',800);calculateRemaining();updateMetrics();}
  function loadFields(){try{fieldState=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');}catch{fieldState={};}document.querySelectorAll('[data-save]').forEach(el=>{const k=storageId(el);if(!(k in fieldState))return;if(el.type==='checkbox'||el.type==='radio')el.checked=Boolean(fieldState[k]);else el.value=fieldState[k];});}
  function saveTracking(){localStorage.setItem(TRACKING_KEY,JSON.stringify(tracking));updateMetrics();}
  function loadTracking(){try{tracking=JSON.parse(localStorage.getItem(TRACKING_KEY)||'{"exercises":{},"tasks":{}}');}catch{tracking={exercises:{},tasks:{}};}tracking.exercises ||= {};tracking.tasks ||= {};trackables.forEach((el,i)=>{const saved=tracking.exercises[String(i)];if(saved?.checked){const fb=el.querySelector('.feedback');if(fb){fb.className=`feedback ${saved.correct?'correct':'incorrect'}`;fb.textContent=saved.correct?'✓ Correct.':'Checked — review or try again.';}}});}
  document.addEventListener('input',e=>{if(e.target.matches('[data-save]'))saveFields();updateCounter(e.target);});document.addEventListener('change',e=>{if(e.target.matches('[data-save]'))saveFields();});
  document.getElementById('resetAll').addEventListener('click',()=>{if(!confirm('Reset all saved lesson answers, progress data and trainer notes?'))return;localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(TRACKING_KEY);location.reload();});
  const trackKey=el=>String(trackables.indexOf(el));function recordExercise(el,correct){tracking.exercises[trackKey(el)]={checked:true,correct:Boolean(correct)};saveTracking();}
  const normalise=s=>(s||'').toLowerCase().trim().replace(/[’]/g,"'").replace(/\s+/g,' ').replace(/[.!?]+$/,'');
  document.querySelectorAll('.check-question').forEach(btn=>btn.addEventListener('click',()=>{const q=btn.closest('.quiz-question'), chosen=q.querySelector('input[type="radio"]:checked'), fb=q.querySelector('.feedback');if(!chosen){fb.className='feedback incorrect';fb.textContent='Choose an answer first.';return;}const ok=chosen.value===q.dataset.correct;recordExercise(q,ok);fb.className=`feedback ${ok?'correct':'incorrect'}`;fb.textContent=ok?'✓ Correct. Explain why this form fits the situation.':'Not quite. Try again — use the hint if you need it.';}));
  document.querySelectorAll('.hint-question').forEach(btn=>btn.addEventListener('click',()=>{const q=btn.closest('.quiz-question'),fb=q.querySelector('.feedback');fb.className='feedback hint';fb.textContent=`Hint: ${q.dataset.hint}`;}));
  document.querySelectorAll('.check-select').forEach(btn=>btn.addEventListener('click',()=>{const q=btn.closest('.select-question'),chosen=q.querySelector('select').value,fb=q.querySelector('.feedback');if(!chosen){fb.className='feedback incorrect';fb.textContent='Choose an answer first.';return;}const ok=chosen===q.dataset.answer;recordExercise(q,ok);fb.className=`feedback ${ok?'correct':'incorrect'}`;fb.textContent=ok?'✓ Correct.':'Not quite. Try again.';}));
  document.querySelectorAll('.hint-select').forEach(btn=>btn.addEventListener('click',()=>{const q=btn.closest('.select-question'),fb=q.querySelector('.feedback');fb.className='feedback hint';fb.textContent=`Hint: ${q.dataset.hint}`;}));
  document.querySelectorAll('.check-repair').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.closest('.repair-item'),input=item.querySelector('input'),fb=item.querySelector('.feedback');if(!input.value.trim()){fb.className='feedback incorrect';fb.textContent='Write your correction first.';return;}const ok=normalise(input.value)===normalise(item.dataset.answer);recordExercise(item,ok);fb.className=`feedback ${ok?'correct':'incorrect'}`;fb.textContent=ok?'✓ Excellent — that is the target structure.':`Compare with the model: ${item.dataset.answer}`;}));
  document.querySelectorAll('.hint-repair').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.closest('.repair-item'),fb=item.querySelector('.feedback');fb.className='feedback hint';fb.textContent=`Hint: ${item.dataset.hint}`;}));
  function speak(text){if(!('speechSynthesis'in window)){alert('Speech playback is not supported in this browser.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.86;speechSynthesis.speak(u);}document.querySelectorAll('[data-speak]').forEach(btn=>btn.addEventListener('click',()=>speak(btn.dataset.speak)));
  document.querySelectorAll('.model-toggle').forEach(btn=>btn.addEventListener('click',()=>{const panel=document.getElementById(btn.dataset.target);if(!panel)return;panel.classList.toggle('hidden');btn.textContent=panel.classList.contains('hidden')?'Show models':'Hide models';}));
  function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function val(id){return(document.getElementById(id)?.value||'').trim();}
  document.getElementById('buildPitch').addEventListener('click',()=>{const name=val('pitchName')||'our cultural project', type=val('pitchType')||'a cultural project', audience=val('pitchAudience')||'local visitors', aim=val('pitchAim')||'create a meaningful cultural experience', place=val('pitchPlace')||'a local cultural venue', partners=val('pitchPartners')||'We would like to work with local partners.';document.getElementById('pitchOutput').textContent=`The project is called “${name}”. It is ${type} for ${audience}. The aim is to ${aim}. It will take place ${place}. ${partners}`;tracking.tasks.pitchBuilder=true;saveTracking();});
  document.querySelectorAll('.timer-btn').forEach(btn=>btn.addEventListener('click',()=>{let seconds=Number(btn.dataset.seconds||60);const wrap=btn.parentElement;const display=wrap.querySelector('.timer-display')||btn.closest('.lilate-task')?.querySelector('.timer-display')||btn.closest('.reading-toolbar')?.querySelector('.timer-display');if(!display)return;btn.disabled=true;const render=()=>display.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;render();const int=setInterval(()=>{seconds--;render();if(seconds<=0){clearInterval(int);btn.disabled=false;display.textContent='Time!';}},1000);}));
  function setupRecorder(recordId,stopId,playbackId,taskKey){const recordBtn=document.getElementById(recordId),stopBtn=document.getElementById(stopId),playback=document.getElementById(playbackId);if(!recordBtn||!stopBtn||!playback||!navigator.mediaDevices||!window.MediaRecorder)return;let recorder,chunks=[],stream;recordBtn.addEventListener('click',async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{const blob=new Blob(chunks,{type:'audio/webm'});playback.src=URL.createObjectURL(blob);playback.hidden=false;stream.getTracks().forEach(t=>t.stop());tracking.tasks[taskKey]=true;saveTracking();};recorder.start();recordBtn.disabled=true;stopBtn.disabled=false;}catch{alert('Microphone access was not available. You can still complete the speaking task without recording.');}});stopBtn.addEventListener('click',()=>{if(recorder&&recorder.state!=='inactive')recorder.stop();recordBtn.disabled=false;stopBtn.disabled=true;});}
  setupRecorder('recordScenario','stopScenario','scenarioPlayback','scenarioRecording');setupRecorder('recordPitch','stopPitch','pitchPlayback','pitchRecording');setupRecorder('recordLILATE','stopLILATE','lilatePlayback','lilateRecording');
  document.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.vocab-card').forEach(c=>c.style.display=(f==='all'||c.dataset.category===f)?'flex':'none');}));
  const scenarios=[
    {avatar:'A',person:'Alice Martin',role:'Local visual artist',situation:'Alice is preparing a video installation. She wants to know whether the venue can provide a projector and blackout curtains.',objective:'Clarify exactly what equipment is needed.',grammar:'need to · can · Present Continuous',avoid:'Promise new equipment before checking.',close:'a clear next step.',clear:'Of course. Can you tell me exactly what equipment you need and when you need it? We have a projector in another room, but I need to check if it is available. I will confirm this with you after I speak to the venue team.',stretch:'Thanks for letting me know. Could you confirm the technical requirements for the video installation? We may be able to move a projector from another room, but I need to check availability and the budget first. I’ll speak to the venue team and come back to you with the best option.'},
    {avatar:'V',person:'Vincent Roy',role:'Cultural centre manager',situation:'Vincent tells you the main gallery is needed for another event on Friday afternoon. He asks whether your installation schedule can change.',objective:'Understand the time conflict and suggest an alternative.',grammar:'have to · can · time questions',avoid:'Say yes before checking with the artists.',close:'who will confirm the revised schedule.',clear:'I understand. What time do you need the main gallery on Friday? We can look at another installation time, but I have to check with the artists first. I will confirm the new schedule with you this afternoon.',stretch:'Thanks for letting me know. Could you confirm exactly when the main gallery becomes unavailable? We may be able to adjust the installation schedule or use another space temporarily. I need to check with the artists before confirming the change, and I’ll send you an updated schedule this afternoon.'},
    {avatar:'C',person:'Claire Dubois',role:'Municipal cultural officer',situation:'Claire wants a short update before a funding meeting. She asks what is ready, what is happening now and what still needs attention.',objective:'Give a structured 3-part progress update.',grammar:'Present Simple · Present Continuous · need to',avoid:'Give every small detail.',close:'one clear priority.',clear:'The project is progressing well. The venue and programme are confirmed. This week, we are preparing the exhibition and visitor information. We still need to solve one equipment problem before the opening.',stretch:'Overall, the project is progressing well. The main programme and venue arrangements are confirmed, and the team is currently preparing the installation and visitor information. Our main outstanding point is the projector request, which we need to resolve after checking the available equipment and budget.'},
    {avatar:'H',person:'Hugo Bernard',role:'Heritage association partner',situation:'Hugo has historical photographs for the exhibition, but he needs to know the final deadline and format for sending them.',objective:'Ask about the material, explain the deadline and confirm the format.',grammar:'could · have to · question forms',avoid:'Leave the deadline vague.',close:'repeat the agreed deadline.',clear:'Thank you. How many photographs do you have? Could you send them as high-quality digital files, please? We need to receive the final files by Friday. Let me confirm: digital files by Friday, correct?',stretch:'That sounds excellent. Could you tell me how many photographs you are planning to provide? We need the final material as high-resolution digital files by Friday so the design team can prepare the display. I’ll send you the technical details today, and we can confirm the final selection once we receive the files.'}
  ];let scenarioIndex=0;function renderScenario(){const s=scenarios[scenarioIndex];['Avatar','Person','Role','Situation','Objective','Grammar','Avoid','Close'].forEach(k=>{const el=document.getElementById(`scenario${k}`);if(el)el.textContent=s[k.toLowerCase()];});const cm=document.getElementById('scenarioClearModel'),sm=document.getElementById('scenarioStretchModel');if(cm)cm.textContent=s.clear;if(sm)sm.textContent=s.stretch;document.getElementById('scenarioCount').textContent=`${scenarioIndex+1} / ${scenarios.length}`;}document.getElementById('prevScenario').addEventListener('click',()=>{scenarioIndex=(scenarioIndex-1+scenarios.length)%scenarios.length;renderScenario();});document.getElementById('nextScenario').addEventListener('click',()=>{scenarioIndex=(scenarioIndex+1)%scenarios.length;renderScenario();});renderScenario();
  document.getElementById('generateProject').addEventListener('click',()=>{const name=val('projectName')||'My Cultural Project', type=val('projectType'), audience=val('projectAudience')||'local residents and visitors', venue=val('projectVenue')||'a cultural venue in Vendée', aim=val('projectAim')||'connect people with local culture and heritage', partners=val('projectPartners')||'local artists and cultural partners', activities=val('projectActivities')||'guided activities and cultural content', now=val('projectNow')||'We are currently preparing the programme and visitor information.', needs=val('projectNeeds')||'We need to confirm the timeline and partners.';document.getElementById('projectPreview').innerHTML=`<span class="project-tag">YOUR PERFECT PROJECT</span><h3>${escapeHtml(name)}</h3><p>${escapeHtml(name)} is ${escapeHtml(type)} for ${escapeHtml(audience)}. The aim is to ${escapeHtml(aim)}.</p><div class="preview-grid"><div><strong>Venue</strong><br>${escapeHtml(venue)}</div><div><strong>Partners</strong><br>${escapeHtml(partners)}</div><div><strong>Activities</strong><br>${escapeHtml(activities)}</div><div><strong>Now</strong><br>${escapeHtml(now)}</div></div><div class="pitch"><strong>Next steps:</strong> ${escapeHtml(needs)}</div>`;tracking.tasks.projectCard=true;saveTracking();});
  const guided=document.getElementById('guidedMode'), challenge=document.getElementById('challengeMode'), guidedHelp=document.getElementById('guidedHelp');guided.addEventListener('click',()=>{guided.classList.add('active');challenge.classList.remove('active');guidedHelp.classList.remove('hidden');});challenge.addEventListener('click',()=>{challenge.classList.add('active');guided.classList.remove('active');guidedHelp.classList.add('hidden');});
  function updateCounter(el){if(!el?.id)return;const c=document.querySelector(`[data-counter-for="${el.id}"]`);if(c){const n=el.value.trim()?el.value.trim().split(/\s+/).length:0;c.textContent=`${n} word${n===1?'':'s'}`;}}
  document.querySelectorAll('[data-counter-for]').forEach(c=>{const el=document.getElementById(c.dataset.counterFor);if(el)updateCounter(el);});
  document.querySelectorAll('.admin-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.admin-pane').forEach(p=>p.classList.toggle('active',p.dataset.adminPane===btn.dataset.adminTab));updateMetrics();}));
  function calculateRemaining(){const total=parseFloat(val('adminTotalHours'))||0,before=parseFloat(val('adminHoursBefore'))||0,duration=parseFloat(val('adminDuration'))||0;const el=document.getElementById('adminHoursRemaining');if(el)el.value=Math.max(0,total-before-duration).toFixed(2).replace(/\.00$/,'');}
  function currentTaskFlags(){tracking.tasks.projectRules=(val('projectRulesWriting').split(/\s+/).filter(Boolean).length>=12);tracking.tasks.briefUpdate=(val('briefUpdate').split(/\s+/).filter(Boolean).length>=15);tracking.tasks.scenarioWritten=(val('scenarioResponse').split(/\s+/).filter(Boolean).length>=15);tracking.tasks.problemWritten=(val('problemResponse').split(/\s+/).filter(Boolean).length>=15);tracking.tasks.lilateWritten=(val('lilateResponse').split(/\s+/).filter(Boolean).length>=20);return tracking.tasks;}
  function metrics(){currentTaskFlags();const results=Object.values(tracking.exercises).filter(x=>x&&x.checked),checked=results.length,correct=results.filter(x=>x.correct).length,accuracy=checked?Math.round(correct/checked*100):null;const taskKeys=['pitchBuilder','briefUpdate','scenarioWritten','problemWritten','projectCard','lilateWritten'];const tasksDone=taskKeys.filter(k=>tracking.tasks[k]).length;const reflection=[...document.querySelectorAll('[data-task="reflection"]')].filter(x=>x.checked).length;return{checked,correct,accuracy,tasksDone,tasksTotal:taskKeys.length,reflection,totalExercises:trackables.length};}
  function updateMetrics(){calculateRemaining();const m=metrics();const set=(id,txt)=>{const el=document.getElementById(id);if(el)el.textContent=txt;};set('metricChecked',`${m.checked}/${m.totalExercises}`);set('metricCorrect',String(m.correct));set('metricAccuracy',m.accuracy===null?'—':`${m.accuracy}%`);set('metricTasks',`${m.tasksDone}/${m.tasksTotal}`);set('metricReflection',`${m.reflection}/6`);const summary=`Interactive exercises: ${m.checked}/${m.totalExercises} checked; ${m.correct} currently correct${m.accuracy===null?'':` (${m.accuracy}% of checked exercises)`}.\nProduction tasks: ${m.tasksDone}/${m.tasksTotal} completed.\nLearner self-check: ${m.reflection}/6 statements selected.\nFocus: cultural project presentation, Present Simple vs Present Continuous, project obligations/possibilities, professional reading, partner interaction, problem-solving and LILATE information transfer.`;const auto=document.getElementById('adminAutoProgress');if(auto)auto.value=summary;set('progressExerciseText',m.checked?`${m.correct} of ${m.checked} checked exercises are currently correct. ${m.totalExercises-m.checked} exercise(s) remain unchecked.`:'No exercises checked yet.');set('progressTaskText',`${m.tasksDone} of ${m.tasksTotal} tracked production tasks are completed (project builder, brief update, scenario response, problem response, project card, LILATE response).`);set('progressReflectionText',m.reflection?`${m.reflection} of 6 confidence statements selected.`:'No self-checks selected yet.');}
  function formatDateFR(s){if(!s)return'';const d=new Date(`${s}T12:00:00`);return new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(d);}
  async function copyText(text){if(!text)return false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return true;}}catch{}const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();let ok=false;try{ok=document.execCommand('copy');}catch{}ta.remove();return ok;}
  document.getElementById('generateEmail').addEventListener('click',()=>{const date=formatDateFR(val('adminSessionDate'))||'notre dernier cours',link=val('adminLessonUrl')||'[AJOUTER LE LIEN ICI]';document.getElementById('generatedEmail').value=`Bonjour Mireille,\n\nMerci encore pour notre cours du ${date}. Nous avons poursuivi votre progression en anglais en entrant cette fois davantage dans les coulisses d’un projet culturel.\n\nPendant cette séance, nous avons travaillé la manière de présenter un projet de façon claire et structurée : le nom du projet, son type, son public, son objectif, son organisation, ses partenaires et ses besoins. Nous avons ensuite approfondi deux points de grammaire très utiles dans ce contexte : le présent simple pour parler des fonctions, habitudes et faits, et le présent continu pour parler de ce qui se passe actuellement ou d’une situation temporaire. Nous avons également travaillé “have to”, “need to”, “can / can’t” et “could” pour parler des obligations, besoins, possibilités et demandes professionnelles.\n\nNous avons enrichi le vocabulaire lié à la gestion d’un projet culturel : partenaires, calendrier, échéances, matériel, budget, devis, accessibilité, financement et suivi. Vous avez ensuite lu un brief professionnel et identifié les informations essentielles : objectif, personnes concernées, dates, actions en cours et problème à résoudre.\n\nLa deuxième partie du cours était consacrée à des situations professionnelles en direct. Vous avez travaillé la manière d’échanger avec différents interlocuteurs — artiste, responsable de lieu, partenaire institutionnel ou association — puis la façon de réagir à un imprévu en quatre étapes : reconnaître le problème, clarifier, proposer une solution et confirmer la prochaine étape.\n\nEnfin, vous avez créé et présenté votre propre projet culturel et terminé par une courte activité inspirée du LILATE IA, dans laquelle vous deviez recueillir des informations, les reformuler et les transmettre à un partenaire.\n\n👉 Votre leçon : ${link}\n\nVous pouvez reprendre tranquillement les règles de grammaire, le vocabulaire, les modèles et les scénarios. L’objectif est de réutiliser progressivement les mêmes structures jusqu’à ce qu’elles deviennent de plus en plus naturelles et automatiques.\n\nÀ très bientôt pour la suite !\n\nBien cordialement,\nTisha`;});
  document.getElementById('copyEmail').addEventListener('click',async()=>{const ok=await copyText(document.getElementById('generatedEmail').value);document.getElementById('copyStatus').textContent=ok?'Message copied.':'Select the message and copy it manually.';});
  function selectedObjectives(){return[...document.querySelectorAll('.objective-row')].filter(r=>r.querySelector('.objective-check').checked).map(r=>{const label=r.querySelector('label').textContent.trim(),priority=r.querySelector('.objective-priority').value,status=r.querySelector('.objective-status').value,comment=r.querySelector('.objective-comment').value.trim();return`${label} — ${priority} — ${status}${comment?` — ${comment}`:''}`;});}
  function autoProgressInline(){const m=metrics();return`Progression interactive: ${m.checked}/${m.totalExercises} exercices vérifiés, ${m.correct} corrects${m.accuracy===null?'':` (${m.accuracy}%)`}; ${m.tasksDone}/${m.tasksTotal} productions réalisées; auto-évaluation ${m.reflection}/6.`;}
  function centreRowValues(){const obs=[val('adminObservations'),autoProgressInline()].filter(Boolean).join(' | ');return[val('adminSessionNumber'),val('adminDuration'),val('adminHoursRemaining'),val('adminSessionDate'),val('adminObjectives'),val('adminContent'),val('adminSkills'),val('adminEvaluationMode'),val('adminAcquisition'),obs,val('adminLessonUrl')];}
  document.getElementById('copyCentreRow').addEventListener('click',async()=>{const ok=await copyText(centreRowValues().join('\t'));document.getElementById('copyStatus').textContent=ok?'Centre spreadsheet row copied.':'Copy was blocked. Use the CSV download instead.';});
  function download(name,content,type='text/plain;charset=utf-8'){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function fullAdminText(){updateMetrics();return`MIREILLE MAZEY — LESSON 4 SESSION FOLLOW-UP\n\nLEARNER PROFILE\nCentre: ${val('adminCentre')}\nTrainer: ${val('adminTrainer')}\nCertification: ${val('adminCertification')}\nInitial level: ${val('adminInitialLevel')}\nTarget level: ${val('adminTargetLevel')}\nFirst course: ${val('adminStartDate')}\nContract end: ${val('adminEndDate')}\nTotal individual hours: ${val('adminTotalHours')}\n\nPROFESSIONAL DIRECTION\n${val('adminDirection')}\n\nSESSION\nNumber: ${val('adminSessionNumber')}\nDate: ${val('adminSessionDate')}\nDuration: ${val('adminDuration')}\nHours completed before: ${val('adminHoursBefore')}\nHours remaining after: ${val('adminHoursRemaining')}\nLesson URL: ${val('adminLessonUrl')}\n\nOBJECTIVES\n${val('adminObjectives')}\n\nCONTENT / ACTIVITIES\n${val('adminContent')}\n\nSKILLS\n${val('adminSkills')}\n\nEVALUATION METHOD\n${val('adminEvaluationMode')}\n\nACQUISITION\n${val('adminAcquisition')}\nEngagement: ${val('adminEngagement')}\nConfidence: ${val('adminConfidence')}\n\nAUTOMATIC PROGRESS\n${val('adminAutoProgress')}\n\nOBSERVATIONS\n${val('adminObservations')}\n\nTRAINER INTERPRETATION\n${val('adminProgressComment')}\n\nSELECTED CENTRE OBJECTIVES\n${selectedObjectives().join('\n')||'None selected'}\n\nNEXT STEP\n${val('adminNextStep')}\n\nPRIVATE TRAINER NOTES\n${val('adminPrivateNotes')}\n`;}
  document.getElementById('downloadAdminTxt').addEventListener('click',()=>download('Mireille_Lesson_4_session_follow_up.txt',fullAdminText()));document.getElementById('downloadAdminCsv').addEventListener('click',()=>{const esc=v=>`"${String(v).replace(/"/g,'""')}"`,headers=['session','duration','remaining_hours','date','objectives','content_activities','skills','evaluation_mode','acquisition','observations_and_progress','lesson_url'];download('Mireille_Lesson_4_admin.csv',`${headers.map(esc).join(',')}\n${centreRowValues().map(esc).join(',')}\n`,'text/csv;charset=utf-8');});
  function learnerReport(){return`MIREILLE — LESSON 4 · BEHIND THE EXHIBITION\n\nProject presentation:\n${document.getElementById('pitchOutput').textContent}\n\nProject-rule writing:\n${val('projectRulesWriting')||'—'}\n\nBrief meeting update:\n${val('briefUpdate')||'—'}\n\nPartner scenario response:\n${val('scenarioResponse')||'—'}\n\nUnexpected-problem response:\n${val('problemResponse')||'—'}\n\nLILATE bridge response:\n${val('lilateResponse')||'—'}\n\nWhat felt easier:\n${val('easiestToday')||'—'}\n\nWhat to recycle:\n${val('nextFocus')||'—'}\n\n${autoProgressInline()}\n`;}
  document.getElementById('downloadBtn').addEventListener('click',()=>download('Mireille_Lesson_4_results.txt',learnerReport()));document.getElementById('printBtn').addEventListener('click',()=>window.print());
  loadFields();loadTracking();document.querySelectorAll('textarea,input').forEach(updateCounter);calculateRemaining();updateMetrics();showSection(0);
})();
