(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='mamadou_lesson1_v1';
const state=Object.assign({accent:'GB',french:false,answers:{},manual:{},objectives:[],homework:[],intro:'',reportFields:{}},load());
let timerSecs=90,timerInitial=90,timerHandle=null;

function load(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function save(){localStorage.setItem(STORE,JSON.stringify(state));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function cleanText(el){return (typeof el==='string'?$(el):el)?.innerText?.replace(/\s+/g,' ').trim()||''}
function dateText(){return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
function pct(a,b){return b?Math.round((a/b)*100):0}

const quizData={
 diagnostic:[
  {q:'Choose the correct sentence for a usual job.',o:['I am work in railway safety.','I work in railway safety.','I working in railway safety.'],a:1,why:'Use the present simple for a usual job or routine.',fr:'Pour une activité habituelle : I work.'},
  {q:'You are studying for the CLOE this week. Choose the best form.',o:['I study for the CLOE this week.','I am studying for the CLOE this week.','I have study for the CLOE.'],a:1,why:'Present continuous works for a current temporary period.',fr:'Action/période temporaire en cours : I am studying.'},
  {q:'Complete: I ___ in the railway sector for four years.',o:['work','am working','have worked'],a:2,why:'Use present perfect for a duration that connects past to now.',fr:'Durée jusqu’à maintenant : have worked + for.'},
  {q:'Which word means “danger that can cause harm”?',o:['hazard','schedule','meeting'],a:0,why:'A hazard is a source or situation with the potential to cause harm.',fr:'hazard = danger / source de danger.'},
  {q:'Choose the best professional question.',o:['What means this procedure?','What does this procedure mean?','What this procedure means?'],a:1,why:'Present simple question: What + does + subject + base verb?',fr:'Question : What does + sujet + verbe ?'},
  {q:'Choose the correct obligation.',o:['Employees must wear the required PPE.','Employees must to wear the required PPE.','Employees must wearing the required PPE.'],a:0,why:'After must, use the base verb without “to”.',fr:'Après must : verbe à l’infinitif sans to.'},
  {q:'Choose the clearest B1 connector: “The route was blocked, ___ the team used another access point.”',o:['because','so','although'],a:1,why:'“So” introduces the consequence.',fr:'so = donc / conséquence.'},
  {q:'If you do not understand an oral question, what is the best strategy?',o:['Stay silent.','Say any answer quickly.','Ask the examiner to repeat or rephrase.'],a:2,why:'Clarification keeps the interaction active and prevents guessing.',fr:'Demander de répéter/reformuler est une stratégie d’interaction.'}
 ],
 present:[
  {q:'Mamadou usually ___ risk assessments before major work starts.',o:['reviews','is reviewing','review'],a:0,why:'Usually = routine → present simple.',fr:'usually indique une habitude.'},
  {q:'At the moment, Mamadou ___ for the CLOE exam.',o:['prepares','is preparing','prepare'],a:1,why:'At the moment = now/current period → present continuous.',fr:'at the moment = maintenant.'},
  {q:'Our team ___ safety meetings every Monday.',o:['has','is having','have'],a:0,why:'A regular schedule uses present simple.',fr:'Chaque lundi = habitude.'},
  {q:'Today, the team ___ a new environmental procedure.',o:['tests','is testing','test'],a:1,why:'Today + temporary current activity → present continuous.',fr:'Aujourd’hui, action temporaire.'},
  {q:'I ___ in safety and environmental risk management.',o:['am work','work','am working every day'],a:1,why:'Use present simple to state your profession/field.',fr:'Pour votre métier : I work in…'},
  {q:'Why ___ you ___ English now?',o:['do / learn','are / learning','have / learn'],a:1,why:'Now/current goal → present continuous question.',fr:'Why are you learning…?'}
 ],
 perfect:[
  {q:'I ___ six years of professional experience.',o:['have','have had','am having'],a:1,why:'Have had describes accumulated experience up to now.',fr:'Expérience accumulée : I have had…'},
  {q:'I have worked in railway ___ four years.',o:['since','for','during'],a:1,why:'For + duration.',fr:'for + durée.'},
  {q:'I have worked in this field ___ 2022.',o:['for','since','from'],a:1,why:'Since + starting point.',fr:'since + point de départ.'},
  {q:'Choose the best sentence.',o:['I work here since four years.','I have worked here for four years.','I am work here for four years.'],a:1,why:'Present perfect + for expresses a situation continuing until now.',fr:'have worked + for.'},
  {q:'Mamadou ___ several safety projects since joining the railway sector.',o:['has supported','supported always','is support'],a:0,why:'Since + experience continuing to now → present perfect.',fr:'since appelle souvent le present perfect.'},
  {q:'Last year, Mamadou ___ on a specific railway project.',o:['has worked','worked','works'],a:1,why:'Finished past time “last year” → past simple.',fr:'last year = période terminée → past simple.'}
 ],
 reading:[
  {q:'What was the main problem?',o:['A person was injured.','A barrier was too close to an access route.','A vehicle broke down.'],a:1,why:'The barrier position created the potential risk.',fr:'Le problème : la position de la barrière.'},
  {q:'What type of event was recorded?',o:['A near miss','A serious accident','An environmental spill'],a:0,why:'No injury occurred, but there was a potential collision risk.',fr:'Un presqu’accident (near miss).'},
  {q:'What did the supervisor do first?',o:['Ignored the problem.','Stopped the operation.','Called an external company.'],a:1,why:'The text says the supervisor stopped the operation.',fr:'Le superviseur a arrêté l’opération.'},
  {q:'Why was a review organised?',o:['To punish the team.','To understand the cause and prevent recurrence.','To change the maintenance vehicle.'],a:1,why:'The review focused on cause and prevention.',fr:'Comprendre la cause et éviter la répétition.'}
 ],
 listening:[
  {q:'What is the main risk today?',o:['Bad weather','Vehicle movement near the maintenance area','Electrical work'],a:1,why:'The briefing identifies vehicle movement as the main risk.',fr:'Risque principal : circulation de véhicules.'},
  {q:'Where should people walk?',o:['On the marked pedestrian route','Anywhere outside the track','In the access lane'],a:0,why:'The speaker says to use the marked pedestrian route.',fr:'Utiliser le chemin piéton balisé.'},
  {q:'What should you do if you notice a new hazard?',o:['Wait until lunch.','Stop, keep a safe distance and report it.','Move it alone immediately.'],a:1,why:'Those three actions are explicitly stated.',fr:'Arrêter, garder une distance sûre et signaler.'},
  {q:'When will changes to the work area be reviewed?',o:['At nine o’clock','At eleven o’clock','At the end of the week'],a:1,why:'The briefing says eleven o’clock.',fr:'À onze heures.'}
 ]
};

const orderData=[
 {words:['risk','I','railway','management','work','and','in','safety'],answer:'I work in railway safety and risk management.'},
 {words:['four','railway','worked','I','years','the','for','have','sector','in'],answer:'I have worked in the railway sector for four years.'},
 {words:['hazards','role','assessing','My','and','involves','risks','identifying'],answer:'My role involves identifying hazards and assessing risks.'},
 {words:['immediately','new','should','hazard','We','a','report'],answer:'We should report a new hazard immediately.'}
];

const grammar=[
 {cat:'Sentence foundations',name:'Basic word order',icon:'🧱',level:'A1→B1',def:'English normally follows Subject + Verb + Object. Add place and time after the main information.',fr:'Ordre de base : Sujet + Verbe + Complément. Puis lieu et temps.',ex:'I review safety procedures at work every week.',tip:'Do not copy French word order directly.',prompt:'Put in order: every day / I / risks / review',ans:'I review risks every day.'},
 {cat:'Sentence foundations',name:'Verb “be”',icon:'🔩',level:'A1',def:'Use am/is/are for identity, state, location and adjective descriptions.',fr:'am/is/are : identité, état, lieu et adjectifs.',ex:'I am responsible for safety coordination.',tip:'Do not use “be” before another main verb in the present simple: I work, not I am work.',prompt:'Complete: I ___ responsible for risk analysis.',ans:'am'},
 {cat:'Present tenses',name:'Present simple',icon:'🔁',level:'A1→A2',def:'Use it for routines, facts, responsibilities and permanent situations.',fr:'Habitudes, faits, responsabilités, situations stables.',ex:'I work in the railway sector and I analyse operational risks.',tip:'With he/she/it, add -s to most verbs.',prompt:'Complete: Mamadou ___ (work) in the railway sector.',ans:'works'},
 {cat:'Present tenses',name:'Present continuous',icon:'⏳',level:'A1→A2',def:'Use am/is/are + verb-ing for actions happening now or temporary current situations.',fr:'am/is/are + -ing : action en cours ou situation temporaire.',ex:'I am preparing for the CLOE exam this week.',tip:'Do not use it for a permanent job description unless you emphasise a temporary situation.',prompt:'Complete: Mamadou ___ ___ (prepare) for an exam now.',ans:'is preparing'},
 {cat:'Past & experience',name:'Past simple',icon:'↩️',level:'A2',def:'Use it for finished actions at a finished past time.',fr:'Actions terminées dans une période passée terminée.',ex:'Last year, I worked on a railway safety project.',tip:'Time markers: yesterday, last week, in 2024, two days ago.',prompt:'Complete: Yesterday, we ___ (identify) a new hazard.',ans:'identified'},
 {cat:'Past & experience',name:'Present perfect',icon:'🧭',level:'A2→B1',def:'Use have/has + past participle for experience or a situation connected to now.',fr:'have/has + participe passé : expérience ou situation liée au présent.',ex:'I have worked in the railway sector for four years.',tip:'Use for + duration, since + starting point. Avoid a finished time such as “last year”.',prompt:'Complete: I ___ ___ here for four years. (work)',ans:'have worked'},
 {cat:'Past & experience',name:'For vs since',icon:'📏',level:'A2',def:'For introduces a duration; since introduces the starting point.',fr:'for + durée ; since + point de départ.',ex:'I have worked here for four years, since 2022.',tip:'Ask: how long? → for. Since when? → since.',prompt:'Choose one: I have worked here ___ 2022.',ans:'since'},
 {cat:'Future',name:'Going to',icon:'🗓️',level:'A2',def:'Use be going to + verb for intentions and plans already decided.',fr:'Intention ou projet déjà décidé.',ex:'I am going to continue my studies in risk management.',tip:'Form: am/is/are + going to + base verb.',prompt:'Complete: I ___ going to continue my studies.',ans:'am'},
 {cat:'Future',name:'Will',icon:'🔭',level:'A2→B1',def:'Use will + verb for predictions, instant decisions and some future statements.',fr:'Prédictions, décisions spontanées, futur.',ex:'This preventive action will reduce the risk.',tip:'After will, use the base verb.',prompt:'Complete: The new procedure ___ reduce the risk.',ans:'will'},
 {cat:'Modals & rules',name:'Must / mustn’t',icon:'⛔',level:'A2',def:'Must expresses strong obligation. Mustn’t expresses prohibition.',fr:'must = obligation forte ; mustn’t = interdiction.',ex:'Employees must wear PPE. They mustn’t enter a restricted area without authorisation.',tip:'must + base verb; no “to”.',prompt:'Complete: You ___ wear the required PPE.',ans:'must'},
 {cat:'Modals & rules',name:'Have to',icon:'📋',level:'A2',def:'Have to expresses an external rule or necessity.',fr:'Obligation liée à une règle ou nécessité extérieure.',ex:'We have to follow the access procedure.',tip:'Question: Do you have to…? Past: had to.',prompt:'Complete: We ___ to follow the procedure.',ans:'have'},
 {cat:'Modals & rules',name:'Should / shouldn’t',icon:'💡',level:'A2',def:'Use should for advice, recommendation or the best action.',fr:'Conseil ou recommandation.',ex:'We should review the risk assessment before work starts.',tip:'should + base verb.',prompt:'Complete: We ___ report the issue immediately.',ans:'should'},
 {cat:'Questions',name:'Present simple questions',icon:'❓',level:'A1→A2',def:'Use question word + do/does + subject + base verb.',fr:'Mot interrogatif + do/does + sujet + verbe.',ex:'What do you do? Why does this procedure matter?',tip:'The main verb stays in the base form after do/does.',prompt:'Correct: What you do at work?',ans:'What do you do at work?'},
 {cat:'Questions',name:'Present perfect questions',icon:'🗣️',level:'A2→B1',def:'Use Have/Has + subject + past participle?',fr:'Have/Has + sujet + participe passé ?',ex:'How long have you worked in the railway sector?',tip:'Very useful for professional experience interviews.',prompt:'Complete: How long ___ you worked here?',ans:'have'},
 {cat:'Articles & nouns',name:'A / an / the',icon:'🏷️',level:'A1→A2',def:'Use a/an for one non-specific singular countable noun; the for something specific or already known.',fr:'a/an = un/une non spécifique ; the = élément précis/connu.',ex:'We identified a hazard near the access route. The hazard was removed.',tip:'Use an before a vowel sound: an incident, an audit.',prompt:'Complete: We recorded ___ incident.',ans:'an'},
 {cat:'Articles & nouns',name:'Countable / uncountable',icon:'🔢',level:'A2',def:'Countable nouns have singular/plural forms. Uncountable nouns generally do not use a/an.',fr:'Noms dénombrables vs indénombrables.',ex:'We need two barriers. We also need more information.',tip:'information, advice, equipment are usually uncountable.',prompt:'Choose: We need more ___ (informations / information).',ans:'information'},
 {cat:'Prepositions',name:'In / on / at',icon:'📍',level:'A1→A2',def:'Common pattern: in a sector/country/month; on a day/surface; at a specific point/time/place.',fr:'in / on / at selon lieu et temps.',ex:'I work in the railway sector. The meeting is on Monday at 9 a.m.',tip:'Learn prepositions in chunks, not alone.',prompt:'Complete: The meeting is ___ Monday.',ans:'on'},
 {cat:'Comparing',name:'Comparatives',icon:'⚖️',level:'A2',def:'Use -er or more + adjective to compare two things.',fr:'Comparatif : -er ou more + adjectif.',ex:'This access route is safer than the temporary route.',tip:'safe → safer; important → more important.',prompt:'Complete: Prevention is ___ (effective) than reaction.',ans:'more effective'},
 {cat:'Connectors',name:'Because / so',icon:'🔗',level:'A2',def:'Because introduces a reason; so introduces a result or consequence.',fr:'because = parce que ; so = donc.',ex:'We stopped the operation because the route was unsafe, so the team could correct the problem.',tip:'Use these to extend B1 answers logically.',prompt:'Complete: The route was blocked, ___ we used another route.',ans:'so'},
 {cat:'Connectors',name:'Although / however',icon:'↔️',level:'B1',def:'Use although or however to show contrast.',fr:'although / however = contraste.',ex:'Although no one was injured, the event was serious. However, the controls worked correctly.',tip:'Although joins clauses; however often starts a new sentence.',prompt:'Complete: ___ no one was injured, we reviewed the event.',ans:'Although'},
 {cat:'Conditionals',name:'Zero conditional',icon:'⚙️',level:'A2→B1',def:'If + present, present for rules, facts and predictable results.',fr:'If + présent, présent : règle ou résultat habituel.',ex:'If we identify a new hazard, we report it.',tip:'Useful for procedures.',prompt:'Complete: If we ___ a hazard, we report it. (identify)',ans:'identify'},
 {cat:'Conditionals',name:'First conditional',icon:'🚦',level:'B1',def:'If + present, will + verb for a realistic future possibility and consequence.',fr:'If + présent, will + verbe : possibilité future réelle.',ex:'If we improve the barrier position, we will reduce the collision risk.',tip:'Do not use “will” directly after if in this basic pattern.',prompt:'Complete: If we act now, we ___ reduce the risk.',ans:'will'},
 {cat:'Relative clauses',name:'Who / which / that',icon:'🧩',level:'B1',def:'Relative words connect information about a person or thing.',fr:'Pronoms relatifs pour relier deux informations.',ex:'A hazard is something that can cause harm. An auditor is a person who checks compliance.',tip:'who = people; which/that = things.',prompt:'Complete: A hazard is something ___ can cause harm.',ans:'that'},
 {cat:'Passive voice',name:'Basic passive',icon:'📝',level:'B1',def:'Use be + past participle when the action/result is more important than the person doing it.',fr:'be + participe passé : on met l’accent sur l’action/résultat.',ex:'The incident was recorded and the procedure was reviewed.',tip:'Useful in reports and procedures.',prompt:'Complete: The incident was ___ (record).',ans:'recorded'},
 {cat:'Verb patterns',name:'Want / need / plan + to',icon:'🎯',level:'A2',def:'After want, need and plan, use to + base verb.',fr:'want/need/plan + to + verbe.',ex:'I need to reach B1. I plan to continue my studies.',tip:'Avoid “I want continue”.',prompt:'Complete: I want ___ improve my English.',ans:'to'},
 {cat:'Quantifiers',name:'Much / many / a lot of',icon:'📊',level:'A2',def:'Many with countable plural nouns; much with uncountable nouns, especially in questions/negatives; a lot of works with both.',fr:'many + pluriel dénombrable ; much + indénombrable ; a lot of + les deux.',ex:'How many hazards were identified? We do not have much time, but we have a lot of information.',tip:'In affirmative everyday English, “a lot of” is often more natural than “much”.',prompt:'Complete: How ___ incidents were recorded?',ans:'many'}
];

const vocab={
 'Role & organisation':[
  ['risk manager','gestionnaire des risques','a professional who identifies, evaluates and helps control risks','A risk manager helps teams reduce operational and safety risks.','🧑‍💼'],
  ['responsibility','responsabilité','a duty or area you are expected to manage','One of my responsibilities is to support preventive action.','📌'],
  ['procedure','procédure','an agreed series of steps for doing something safely and consistently','We follow the access procedure before entering the work area.','📋'],
  ['compliance','conformité','acting according to rules, standards or legal requirements','The audit checks compliance with safety requirements.','✅'],
  ['stakeholder','partie prenante','a person or organisation affected by or involved in a project or decision','We explain the risk controls to the main stakeholders.','🤝'],
  ['continuous improvement','amélioration continue','ongoing work to make processes safer or more effective','Incident reviews support continuous improvement.','📈']
 ],
 'Safety & hazards':[
  ['hazard','danger / source de danger','something with the potential to cause harm','Vehicle movement is a hazard near the maintenance area.','⚠️'],
  ['risk','risque','the combination of how likely harm is and how serious it could be','We assess the risk before work starts.','🎯'],
  ['near miss','presqu’accident','an event that could have caused harm but did not','The barrier problem was recorded as a near miss.','🟡'],
  ['incident','incident','an unplanned event that affects or could affect safety or operations','The incident was reported to the supervisor.','🚨'],
  ['personal protective equipment (PPE)','équipement de protection individuelle (EPI)','equipment worn to reduce exposure to hazards','Required PPE must be worn in the work area.','🦺'],
  ['control measure','mesure de maîtrise / prévention','an action used to eliminate or reduce a risk','A marked pedestrian route is a control measure.','🛡️'],
  ['restricted area','zone réglementée / interdite','an area with limited authorised access','Do not enter the restricted area without permission.','⛔'],
  ['safe distance','distance de sécurité','enough space to reduce exposure to danger','Keep a safe distance from moving vehicles.','↔️']
 ],
 'Risk management':[
  ['risk assessment','évaluation des risques','a structured process for identifying hazards and evaluating risks','We review the risk assessment when conditions change.','🧠'],
  ['likelihood','probabilité','how likely it is that an event will happen','We consider both likelihood and severity.','🎲'],
  ['severity','gravité','how serious the consequences of an event could be','The severity could be high if a vehicle hits a pedestrian.','📉'],
  ['preventive action','action préventive','action taken to stop a problem from happening','The team introduced a preventive action after the review.','🛡️'],
  ['corrective action','action corrective','action taken to correct a problem and its cause','Repositioning the barrier was an immediate corrective action.','🔧'],
  ['root cause','cause racine','the underlying reason why a problem happened','The review aims to identify the root cause.','🌱'],
  ['mitigate','atténuer / réduire','to reduce the seriousness or impact of a risk','The new control should mitigate the collision risk.','📉']
 ],
 'Environment':[
  ['environmental impact','impact environnemental','an effect that an activity has on the environment','We assess the environmental impact before major work begins.','🌍'],
  ['waste','déchets','materials that are no longer wanted or useful','The team separates waste before disposal.','♻️'],
  ['spill','déversement / fuite','an accidental release of liquid','A fuel spill must be reported immediately.','💧'],
  ['emissions','émissions','gases or substances released into the air','Reducing unnecessary vehicle movements can lower emissions.','🌫️'],
  ['noise pollution','pollution sonore','harmful or disruptive levels of noise','Night work can create noise pollution for nearby residents.','🔊'],
  ['environmental procedure','procédure environnementale','a formal process for controlling environmental impacts','The environmental procedure explains how to manage waste.','🌱']
 ],
 'Railway operations':[
  ['track maintenance','maintenance de la voie','work carried out to inspect, repair or improve railway track','Track maintenance requires careful access control.','🛤️'],
  ['access route','voie / chemin d’accès','a defined way to enter or move through a work area','The access route must remain clear.','➡️'],
  ['maintenance vehicle','véhicule de maintenance','a vehicle used to support inspection or maintenance work','The maintenance vehicle moved slowly through the work area.','🚧'],
  ['work area','zone de travail','the defined area where work is taking place','Only authorised people can enter the work area.','🏗️'],
  ['barrier','barrière','a physical object used to separate or block an area','The barrier protects the pedestrian route.','🚧'],
  ['inspection','inspection / contrôle','a careful check to identify problems or confirm compliance','The inspection starts at nine o’clock.','🔍']
 ],
 'Reporting & meetings':[
  ['report','signaler / rapport','to give formal information about an event; also the document itself','Please report any new hazard immediately.','📝'],
  ['briefing','briefing / point d’information','a short meeting that gives essential information or instructions','The supervisor gives a safety briefing every morning.','🗣️'],
  ['update','mise à jour / faire le point','new information about a situation','I would like to give you a quick safety update.','🔄'],
  ['recommend','recommander','to say what you think should be done','I recommend checking the access route again.','💡'],
  ['follow-up','suivi','an action or communication that happens after an initial event','We scheduled a follow-up after the incident review.','📆'],
  ['action plan','plan d’action','a list of actions, owners and deadlines for achieving an objective','The action plan includes three preventive measures.','🗂️']
 ],
 'CLOE interaction':[
  ['Could you repeat the question, please?','Pourriez-vous répéter la question, s’il vous plaît ?','a polite request for repetition','Could you repeat the question, please?','🔁'],
  ['Could you rephrase that, please?','Pourriez-vous reformuler ?','a polite request to hear the idea in different words','Could you rephrase that, please?','🔄'],
  ['If I understand correctly…','Si je comprends bien…','a phrase used to check your understanding before answering','If I understand correctly, you are asking about our prevention process.','✅'],
  ['Let me think for a moment.','Laissez-moi réfléchir un instant.','a natural way to gain short thinking time','Let me think for a moment. I would say prevention is the main priority.','⏳'],
  ['In my experience…','D’après mon expérience…','a phrase for introducing a professional example or opinion','In my experience, clear procedures reduce misunderstandings.','🧭'],
  ['For example…','Par exemple…','a connector used to support an answer with evidence','For example, a safe route can reduce collision risk.','💬']
 ]
};

const survival=[
 ['🔁','Repeat','Could you repeat the question, please?','Pourriez-vous répéter la question, s’il vous plaît ?'],
 ['🔄','Rephrase','Could you rephrase that, please?','Pourriez-vous reformuler, s’il vous plaît ?'],
 ['✅','Check','If I understand correctly, you are asking about…','Si je comprends bien, vous me demandez…'],
 ['⏳','Think','Let me think for a moment.','Laissez-moi réfléchir un instant.'],
 ['🧩','Reformulate','What I mean is…','Ce que je veux dire, c’est…'],
 ['📌','Clarify','Do you mean…?','Vous voulez dire… ?'],
 ['🧭','Experience','In my experience…','D’après mon expérience…'],
 ['💬','Example','For example…','Par exemple…']
];

function renderQuiz(id,key){const host=$(id);host.innerHTML='';quizData[key].forEach((item,i)=>{const qid=`${key}_${i}`;const saved=state.answers[qid];const card=document.createElement('article');card.className='qcard'+(saved?' done '+(saved.correct?'correct':'wrong'):'');card.dataset.qid=qid;card.innerHTML=`<span class="qnum">QUESTION ${i+1}</span><p>${escapeHtml(item.q)}</p><div class="options">${item.o.map((o,j)=>`<button class="option ${saved&&saved.choice===j?'chosen':''} ${saved&&j===item.a?'correct-answer':''} ${saved&&saved.choice===j&&j!==item.a?'wrong-answer':''}" type="button" data-choice="${j}">${escapeHtml(o)}</button>`).join('')}</div><div class="feedback ${saved?(saved.correct?'good':'bad'):''}">${saved?escapeHtml((saved.correct?'✓ ':'✗ ')+item.why):''}</div><div class="fr-help">${escapeHtml(item.fr)}</div>`;
  host.appendChild(card);$$('.option',card).forEach(btn=>btn.addEventListener('click',()=>answerQuiz(card,item,key,i,+btn.dataset.choice)));
 });updateAll();}
function answerQuiz(card,item,key,i,choice){const qid=`${key}_${i}`,correct=choice===item.a;state.answers[qid]={choice,correct,key};save();renderQuiz('#'+card.parentElement.id,key);toast(correct?'Correct ✓':'Review the rule ✎');}

function renderOrders(){const host=$('#orderExercises');host.innerHTML='';orderData.forEach((x,i)=>{const id=`order_${i}`,saved=state.answers[id];const div=document.createElement('div');div.className='order-card';div.innerHTML=`<span class="qnum">SENTENCE ${i+1}</span><div class="word-bank">${x.words.map(w=>`<span class="word-chip">${escapeHtml(w)}</span>`).join('')}</div><input type="text" placeholder="Type the complete sentence…" value="${saved?escapeHtml(saved.value):''}"><button class="tiny-btn" type="button">Check</button><div class="feedback ${saved?(saved.correct?'good':'bad'):''}">${saved?(saved.correct?'✓ Correct':'✗ Model: '+escapeHtml(x.answer)):''}</div>`;host.appendChild(div);$('button',div).addEventListener('click',()=>{const val=$('input',div).value.trim().replace(/\s+/g,' ');const norm=s=>s.toLowerCase().replace(/[.,!?]/g,'').replace(/\s+/g,' ').trim();const correct=norm(val)===norm(x.answer);state.answers[id]={value:val,correct,key:'order'};save();renderOrders();toast(correct?'Correct ✓':'Check the word order');});});updateAll();}

function setupFrench(){document.body.classList.toggle('show-french',state.french);$('#globalFrenchBtn').setAttribute('aria-pressed',state.french);$('#globalFrenchBtn').textContent=state.french?'🇫🇷 French help: ON':'🇫🇷 French help';$('#globalFrenchBtn').addEventListener('click',()=>{state.french=!state.french;save();setupFrenchStatic();});$$('.help-btn').forEach(b=>b.addEventListener('click',()=>{const h=$('#'+b.dataset.help);if(h)h.classList.toggle('open')}));}
function setupFrenchStatic(){document.body.classList.toggle('show-french',state.french);$('#globalFrenchBtn').setAttribute('aria-pressed',state.french);$('#globalFrenchBtn').textContent=state.french?'🇫🇷 French help: ON':'🇫🇷 French help';}
function setupAccent(){setAccentUI();$$('.accent-btn').forEach(b=>b.addEventListener('click',()=>{state.accent=b.dataset.accent;save();setAccentUI();toast(state.accent==='GB'?'British English selected':'American English selected')}));}
function setAccentUI(){$$('.accent-btn').forEach(b=>{const on=b.dataset.accent===state.accent;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});$('#voiceLabel').textContent=state.accent==='GB'?'UK English':'US English';}
function speak(text){if(!('speechSynthesis'in window)){toast('Speech synthesis is not supported in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.accent==='GB'?'en-GB':'en-US';const voices=speechSynthesis.getVoices();const preferred=voices.find(v=>v.lang===u.lang)||voices.find(v=>v.lang.startsWith(state.accent==='GB'?'en-GB':'en-US'))||voices.find(v=>v.lang.startsWith('en'));if(preferred)u.voice=preferred;u.rate=.88;u.pitch=1;speechSynthesis.speak(u)}
function setupSpeak(){document.addEventListener('click',e=>{const b=e.target.closest('[data-speak]');if(!b)return;const el=$(b.dataset.speak);if(el)speak(cleanText(el));});$('#playBriefing').addEventListener('click',()=>speak(cleanText($('#briefingText'))));$('#showTranscript').addEventListener('click',()=>{const transcript=$('#briefingTranscript'),btn=$('#showTranscript');const open=transcript.classList.toggle('open');btn.textContent=open?'📄 Hide transcript':'📄 Show transcript';btn.setAttribute('aria-expanded',String(open));});}

function buildIntro(){const s=(id)=>$(id).value;const text=`${s('#bRole')}. I have ${s('#bYears')} of professional experience, including ${s('#bRailYears')}. My role involves ${s('#bResp')}. ${s('#bStudy')}, and I would like to ${s('#bGoal')}. My immediate English goal is to ${s('#bEnglish')}.`;state.intro=text;save();$('#introOutput').textContent=text;toast('Introduction built ✓')}
function setupBuilder(){if(state.intro)$('#introOutput').textContent=state.intro;$('#buildIntro').addEventListener('click',buildIntro);$('#clearBuilder').addEventListener('click',()=>{state.intro='';save();$('#introOutput').innerHTML='Complete the builder, then select <b>Build my introduction</b>.'});$('#copyIntro').addEventListener('click',async()=>{await navigator.clipboard.writeText(cleanText($('#introOutput')));toast('Introduction copied')});$('#saveIntroEvidence').addEventListener('click',()=>{if(!state.intro)return toast('Build your introduction first.');state.manual.intro_builder={title:'Generated professional self-introduction',notes:state.intro,scores:{},date:new Date().toISOString()};save();updateReport();toast('Added to report ✓')});}

function setupObjectives(){const checks=$$('.objective-check');checks.forEach(c=>{c.checked=state.objectives.includes(c.dataset.objective);c.addEventListener('change',()=>{state.objectives=checks.filter(x=>x.checked).map(x=>x.dataset.objective);save();updateReport()})})}
function setupHomework(){const checks=$$('.hw-check');checks.forEach(c=>{c.checked=state.homework.includes(c.dataset.homework);c.addEventListener('change',()=>{state.homework=checks.filter(x=>x.checked).map(x=>x.dataset.homework);save();updateReport()})})}

function initGrammar(){const cat=$('#grammarCategory'),point=$('#grammarPoint');const cats=[...new Set(grammar.map(g=>g.cat))];cat.innerHTML=cats.map(c=>`<option>${escapeHtml(c)}</option>`).join('');function fillPoints(){const list=grammar.filter(g=>g.cat===cat.value);point.innerHTML=list.map((g,i)=>`<option value="${grammar.indexOf(g)}">${escapeHtml(g.name)}</option>`).join('');showGrammar(+point.value)}cat.addEventListener('change',fillPoints);point.addEventListener('change',()=>showGrammar(+point.value));$('#grammarRandom').addEventListener('click',()=>{const i=Math.floor(Math.random()*grammar.length),g=grammar[i];cat.value=g.cat;fillPoints();point.value=String(i);showGrammar(i)});fillPoints();}
function showGrammar(i){const g=grammar[i]||grammar[0];$('#grammarDisplay').innerHTML=`<div class="grammar-card-head"><div><div class="grammar-meta"><span class="tag">${escapeHtml(g.cat)}</span><span class="tag">${escapeHtml(g.level)}</span></div><h3>${escapeHtml(g.name)}</h3></div><div class="grammar-icon">${g.icon}</div></div><div class="grammar-columns"><div><h4>Rule / definition</h4><p>${escapeHtml(g.def)}</p></div><div><h4>Français</h4><p>${escapeHtml(g.fr)}</p></div></div><div class="grammar-example"><b>Professional example:</b> <span id="grammarEx">${escapeHtml(g.ex)}</span> <button class="tiny-btn" type="button" data-speak="#grammarEx">🔊 Listen</button></div><p><b>Remember:</b> ${escapeHtml(g.tip)}</p>`;const gid=`micro_${i}`,saved=state.answers[gid];$('#grammarMicro').innerHTML=`<div class="micro-card"><b>30-second practice:</b> ${escapeHtml(g.prompt)}<br><input id="microInput" value="${saved?escapeHtml(saved.value):''}" placeholder="Your answer…"><button class="tiny-btn" id="microCheck" type="button">Check</button> <span class="micro-feedback ${saved?(saved.correct?'good':'bad'):''}">${saved?(saved.correct?'✓ Correct':'Model: '+escapeHtml(g.ans)):''}</span></div>`;$('#microCheck').addEventListener('click',()=>{const val=$('#microInput').value.trim().toLowerCase().replace(/[.?!]/g,'').replace(/\s+/g,' '),ans=g.ans.toLowerCase().replace(/[.?!]/g,'').replace(/\s+/g,' ');state.answers[gid]={value:$('#microInput').value.trim(),correct:val===ans,key:'grammar_library'};save();showGrammar(i);updateAll();});}

function initVocab(){const sel=$('#vocabCategory');const cats=Object.keys(vocab);sel.innerHTML=cats.map(c=>`<option>${escapeHtml(c)}</option>`).join('');sel.addEventListener('change',()=>renderVocab(sel.value));$('#shuffleVocab').addEventListener('click',()=>renderVocab(sel.value,true));renderVocab(cats[0]);}
function renderVocab(cat,shuffle=false){let list=[...vocab[cat]];if(shuffle)list.sort(()=>Math.random()-.5);$('#vocabGrid').innerHTML=list.map((v,i)=>`<article class="vocab-card"><div class="vocab-top"><span>${v[4]}</span><span class="vocab-fr fr-help">${escapeHtml(v[1])}</span></div><div class="vocab-word" id="vw_${i}">${escapeHtml(v[0])}</div><div class="vocab-def">${escapeHtml(v[2])}</div><div class="vocab-example" id="ve_${i}">“${escapeHtml(v[3])}”</div><button class="tiny-btn" type="button" data-speak="#vw_${i}, #ve_${i}">🔊 Listen</button></article>`).join('');$$('#vocabGrid [data-speak]').forEach(b=>b.addEventListener('click',()=>{const sels=b.dataset.speak.split(',').map(x=>cleanText($(x.trim()))).join('. ');speak(sels)}));}
function initSurvival(){$('#survivalPhrases').innerHTML=survival.map((p,i)=>`<article class="phrase-card"><span>${p[0]}</span><h3 id="surv_${i}">${escapeHtml(p[2])}</h3><p class="fr-help">${escapeHtml(p[3])}</p><button class="tiny-btn" type="button" data-speak="#surv_${i}">🔊 Listen</button></article>`).join('')}

function setupManual(){ $$('.manual-task').forEach(task=>{const id=task.dataset.manualId,saved=state.manual[id];const notes=$('.teacher-notes',task);if(saved&&notes)notes.value=saved.notes||'';$$('[data-skill]',task).forEach(sel=>{if(saved?.scores?.[sel.dataset.skill]!=null)sel.value=String(saved.scores[sel.dataset.skill])});$('.save-manual',task)?.addEventListener('click',()=>{const scores={};$$('[data-skill]',task).forEach(sel=>{if(sel.value)scores[sel.dataset.skill]=+sel.value});state.manual[id]={title:manualTitle(task,id),notes:notes?.value.trim()||'',scores,date:new Date().toISOString()};save();$('.saved-state',task).textContent='Saved ✓';updateReport();toast('Evidence saved to report')});});}
function manualTitle(task,id){return $('.task-type',task)?.textContent.trim()||$('h3',task)?.textContent.trim()||id.replaceAll('_',' ')}

function setupWriting(){const box=$('#writingBox');const saved=state.manual.writing_hazard?.notes;if(saved)box.value=saved;function wc(){const n=box.value.trim()?box.value.trim().split(/\s+/).length:0;$('#wordCount').textContent=n;$('#writingRange').textContent=n>=70&&n<=100?'✓ In target range':'Target: 70–100';$('#writingRange').style.color=n>=70&&n<=100?'#2e8b69':''}box.addEventListener('input',wc);wc();}

function setupTimers(){$$('[data-timer]').forEach(b=>b.addEventListener('click',()=>openTimer(+b.dataset.timer)));$('#timerClose').addEventListener('click',closeTimer);$('#timerStart').addEventListener('click',()=>{if(timerHandle){clearInterval(timerHandle);timerHandle=null;$('#timerStart').textContent='Start';return}$('#timerStart').textContent='Pause';timerHandle=setInterval(()=>{timerSecs=Math.max(0,timerSecs-1);drawTimer();if(timerSecs===0){clearInterval(timerHandle);timerHandle=null;$('#timerStart').textContent='Start';toast('Time! Finish your sentence clearly.')}},1000)});$('#timerReset').addEventListener('click',()=>{timerSecs=timerInitial;drawTimer()});}
function openTimer(s){timerInitial=timerSecs=s;drawTimer();$('#timerModal').classList.add('open');$('#timerModal').setAttribute('aria-hidden','false')}
function closeTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}$('#timerModal').classList.remove('open');$('#timerModal').setAttribute('aria-hidden','true');$('#timerStart').textContent='Start'}
function drawTimer(){const m=String(Math.floor(timerSecs/60)).padStart(2,'0'),s=String(timerSecs%60).padStart(2,'0');$('#timerValue').textContent=`${m}:${s}`}

function scoreStats(){const ids=[];Object.entries(state.answers).forEach(([id,a])=>{if(a&&typeof a.correct==='boolean')ids.push([id,a])});const correct=ids.filter(x=>x[1].correct).length;return{correct,attempted:ids.length,max:quizData.diagnostic.length+quizData.present.length+quizData.perfect.length+quizData.reading.length+quizData.listening.length+orderData.length+grammar.length};}
function byCategory(){const cats={Diagnostic:[0,0],Present:[0,0],'Present perfect':[0,0],'Word order':[0,0],Reading:[0,0],Listening:[0,0],'Grammar library':[0,0]};Object.entries(state.answers).forEach(([id,a])=>{if(!a||typeof a.correct!=='boolean')return;let k=a.key||'';let name=k==='diagnostic'?'Diagnostic':k==='present'?'Present':k==='perfect'?'Present perfect':k==='order'?'Word order':k==='reading'?'Reading':k==='listening'?'Listening':k==='grammar_library'?'Grammar library':null;if(name){cats[name][1]++;if(a.correct)cats[name][0]++}});return cats;}
function updateAll(){const s=scoreStats();$('#scoreNow').textContent=s.correct;$('#scoreMax').textContent=s.max;$('#scorePct').textContent=pct(s.correct,s.max)+'%';const diagDone=Object.keys(state.answers).filter(k=>k.startsWith('diagnostic_')).length;$('#diagStatus').textContent=`${diagDone} / ${quizData.diagnostic.length} completed`;updateReport();}

function setupReportFields(){['reportStrengths','reportGrammarPriority','reportCommunicationPriority','reportNextFocus','selfAssessment','teacherRating'].forEach(id=>{const el=$('#'+id);if(state.reportFields[id]!=null)el.value=state.reportFields[id];el.addEventListener('input',()=>{state.reportFields[id]=el.value;save()});el.addEventListener('change',()=>{state.reportFields[id]=el.value;save()})});}
function updateReport(){if(!$('#reportPaper'))return;$('#reportDate').textContent=dateText();const s=scoreStats();const autoPct=pct(s.correct,s.attempted);$('#reportPct').textContent=(s.attempted?autoPct:0)+'%';$('#reportAutoSummary').textContent=s.attempted?`${s.correct} correct answer${s.correct===1?'':'s'} from ${s.attempted} attempted scored items. The page contains ${s.max} available scored practice items, including the grammar reference micro-practice.`:'Complete interactive exercises to populate this section.';$('#reportObjectives').innerHTML=state.objectives.length?state.objectives.map(x=>`<li>${escapeHtml(x)}</li>`).join(''):'<li>No objectives marked yet.</li>';$('#reportHomework').innerHTML=state.homework.length?state.homework.map(x=>`<li>Completed/checked: ${escapeHtml(x)}</li>`).join(''):'<li>Homework not marked yet.</li>';const cats=byCategory();$('#reportExerciseRows').innerHTML=Object.entries(cats).map(([name,[c,a]])=>{const p=pct(c,a),priority=!a?'Not attempted':p<60?'High':p<80?'Medium':'Low';return `<tr><td>${name}</td><td>${c}</td><td>${a}</td><td>${a?p+'%':'—'}</td><td class="${priority==='High'?'priority-high':priority==='Medium'?'priority-medium':priority==='Low'?'priority-low':''}">${priority}</td></tr>`}).join('');const entries=Object.entries(state.manual);const manualVals=entries.flatMap(([,e])=>Object.values(e.scores||{})).filter(v=>Number.isFinite(+v)).map(Number);$('#reportManualAvg').textContent=manualVals.length?(manualVals.reduce((a,b)=>a+b,0)/manualVals.length).toFixed(1)+'/5':'—';$('#reportManualEvidence').innerHTML=entries.length?entries.map(([id,e])=>`<article class="evidence-card"><h4>${escapeHtml(e.title||id)}</h4>${e.notes?`<p><b>Evidence / notes:</b> ${escapeHtml(e.notes).replace(/\n/g,'<br>')}</p>`:''}<div class="evidence-scores">${Object.entries(e.scores||{}).map(([k,v])=>`<span>${escapeHtml(k)}: <b>${v}/5</b></span>`).join('')||'<span>No manual rating entered</span>'}</div></article>`).join(''):'<p>No manual evidence saved yet.</p>';}

function reportHtml(){updateReport();const clone=$('#reportPaper').cloneNode(true);$$('textarea',clone).forEach(t=>{const p=document.createElement('div');p.style='white-space:pre-wrap;border:1px solid #ddd;padding:8px;min-height:45px';p.textContent=t.value||'—';t.replaceWith(p)});$$('select',clone).forEach(s=>{const p=document.createElement('span');p.textContent=s.options[s.selectedIndex]?.text||'—';s.replaceWith(p)});return `<!doctype html><html><head><meta charset="utf-8"><title>Mamadou Diallo - Lesson 1 Progress Report</title><style>${reportCss()}</style></head><body>${clone.outerHTML}</body></html>`}
function reportCss(){return `body{font-family:Arial,sans-serif;color:#102a35;margin:28px}.report-paper{max-width:900px;margin:auto}.report-head{display:flex;justify-content:space-between;border-bottom:3px solid #0f7b79;padding-bottom:10px}.brand-script{font-family:cursive;font-size:28px}.report-meta-grid,.report-columns{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:12px 0}.report-meta-grid div,.report-columns>div{border:1px solid #d7e0de;padding:8px}.report-meta-grid span{display:block;font-size:10px;text-transform:uppercase;color:#617883}.report-score-row{display:flex;gap:15px;background:#0d2f3c;color:#fff;padding:14px;border-radius:8px}.report-score-ring{border:6px solid #36aaa2;border-radius:50%;width:100px;height:100px;display:flex;flex-direction:column;align-items:center;justify-content:center}.report-score-ring b{font-size:24px}.report-score-ring span{font-size:9px;text-align:center}.report-table{width:100%;border-collapse:collapse;font-size:12px}.report-table th,.report-table td{border:1px solid #d7e0de;padding:6px}.evidence-card{border:1px solid #d7e0de;padding:8px;margin:6px 0}.evidence-scores span{display:inline-block;background:#eef5f3;padding:3px 5px;margin:2px;font-size:11px}.report-footnote{font-size:10px;border-top:1px solid #ccc;margin-top:16px;padding-top:8px}.report-logo{color:#0d2f3c}`}
function downloadBlob(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function setupReportButtons(){$('#refreshReport').addEventListener('click',()=>{updateReport();toast('Report refreshed')});$('#openReportTop').addEventListener('click',()=>{$('#report').scrollIntoView({behavior:'smooth'});updateReport()});$('#downloadReportHtml').addEventListener('click',()=>downloadBlob('Mamadou_Diallo_Lesson_1_Progress_Report.html',reportHtml(),'text/html'));$('#downloadReportPdf').addEventListener('click',()=>{updateReport();setTimeout(()=>window.print(),150)});$('#copyReport').addEventListener('click',async()=>{updateReport();await navigator.clipboard.writeText(cleanText($('#reportPaper')));toast('Report summary copied')});}

function setupReset(){$('#resetLesson').addEventListener('click',()=>{if(confirm('Reset all answers, scores and saved evidence for this lesson?')){localStorage.removeItem(STORE);location.reload()}})}
function setupBackToTop(){const btn=$('#backToTop');if(!btn)return;btn.addEventListener('click',()=>{window.scrollTo({top:0,left:0,behavior:'smooth'});const top=$('#top');if(top){try{top.focus({preventScroll:true})}catch{}}});}

function boot(){setupFrench();setupAccent();setupSpeak();setupObjectives();setupHomework();setupBuilder();initGrammar();initVocab();initSurvival();renderQuiz('#diagnosticQuiz','diagnostic');renderQuiz('#presentQuiz','present');renderQuiz('#perfectQuiz','perfect');renderQuiz('#readingQuiz','reading');renderQuiz('#listeningQuiz','listening');renderOrders();setupManual();setupWriting();setupTimers();setupReportFields();setupReportButtons();setupReset();setupBackToTop();updateAll();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
