(() => {
  'use strict';
  const KEY = 'story_first_kaizen_kickoff_v1';
  const sections = [...document.querySelectorAll('.lesson-section')];
  const state = {sectionIndex:0, sessionSeconds:90*60, sessionTimer:null, quizCorrect:{}, questionIndex:0, socialIndex:0};
  const $=(s,root=document)=>root.querySelector(s); const $$=(s,root=document)=>[...root.querySelectorAll(s)];
  const questionBank=[
    {q:'Why is the current lead time 12 days?',hint:'Do not invent a root cause. Separate what the slide shows from what the analysis phase will confirm.',model:'That’s a good question. The slide shows the current P90 lead time and the target, but it does not give the final root cause. The analyze phase is where we will identify the underlying drivers.'},
    {q:'Is the 2-day target realistic?',hint:'Acknowledge ambition and point to roadmap/control.',model:'It is an ambitious target. That is why the project uses a structured DMAIC roadmap and includes control checks at plus 30, plus 60 and plus 90 days.'},
    {q:'Why are GE engineering analysis cases out of scope?',hint:'Explain focus, not exclusion as avoidance.',model:'They are out of scope because the project needs a focused area where the team can act within the Kaizen timeframe. Those cases require a different type of engineering analysis.'},
    {q:'What is the biggest expected benefit?',hint:'Connect to delivery, customer commitments and cost.',model:'The biggest benefit is faster and more controlled treatment of non-conformity cases. That should help protect delivery commitments, customer satisfaction and parts holding costs.'},
    {q:'What does P90 mean in practical terms?',hint:'Use plain English, not statistics jargon.',model:'In practical terms, P90 helps us look at the slower end of the process, not only an average. It tells us whether the difficult cases are still taking too long.'},
    {q:'What will you do if the result improves once but does not last?',hint:'Mention control phase and sustainable improvement.',model:'That is exactly why the control phase matters. The goal is not a one-time improvement; the goal is to make the shorter lead time sustainable over time.'}
  ];
  const socialBank=[
    {p:'A colleague asks: “Is this your first time presenting here?”',m:'Yes, it is, and I’m really glad to be here. I’m looking forward to exchanging with the team. Have you been involved in similar Kaizen projects before?'},
    {p:'Someone says: “That’s quite an ambitious target.”',m:'Yes, it is ambitious, but that’s also what makes the project meaningful. The idea is to focus the team on a clear operational problem. What kind of target do you usually see for this type of process?'},
    {p:'At lunch someone asks: “What do you do outside work?”',m:'I’m pretty active and I enjoy sports and spending time outside. What about you - what do you usually do on weekends?'},
    {p:'A colleague asks: “Have you had a chance to see anything around town?”',m:'A little. I’m still getting my bearings, but I really like the area. Any recommendations while I’m here?'},
    {p:'After the presentation: “That was interesting. How long have you been working on this topic?”',m:'Thanks. The topic is connected to ongoing improvement work, but this Kaizen is a focused project with a clear target. Which part was most relevant to your team?'}
  ];
  document.addEventListener('DOMContentLoaded',init);
  function init(){makeStepDots();bindNav();bindHeader();bindTimer();bindSpeech();bindVocabFilters();randomizeQuizChoices();bindQuizzes();bindBuilders();bindMiniTimers();bindChecks();bindSaveFields();bindResets();bindQuestions();bindSocial();bindReport();restore();setDate();updateBuilders();updateScores();showSection(state.sectionIndex,false)}
  function makeStepDots(){const nav=$('#stepDots');sections.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1);b.title=s.dataset.title||`Section ${i+1}`;b.addEventListener('click',()=>showSection(i));nav.appendChild(b)})}
  function bindNav(){$$('[data-next]').forEach(b=>b.addEventListener('click',()=>showSection(Math.min(state.sectionIndex+1,sections.length-1))));$('#backTop')?.addEventListener('click',()=>showSection(0))}
  function showSection(i,scroll=true){state.sectionIndex=i;sections.forEach((s,idx)=>s.classList.toggle('active',idx===i));$('#progressBar').style.width=`${((i+1)/sections.length)*100}%`;$('#progressLabel').textContent=sections[i]?.dataset.title||'';$$('#stepDots button').forEach((b,idx)=>b.classList.toggle('active',idx===i));save();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
  function bindHeader(){$('#translationToggle')?.addEventListener('click',()=>{const on=document.body.classList.toggle('show-fr');const b=$('#translationToggle');b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.textContent=on?'FR help · ON':'FR help · OFF';save()});$('#printButton')?.addEventListener('click',()=>window.print())}
  function bindTimer(){$('#timerStart')?.addEventListener('click',()=>{if(state.sessionTimer)return;state.sessionTimer=setInterval(()=>{state.sessionSeconds=Math.max(0,state.sessionSeconds-1);updateTimer();if(state.sessionSeconds===0)pauseTimer()},1000)});$('#timerPause')?.addEventListener('click',pauseTimer);$('#timerReset')?.addEventListener('click',()=>{pauseTimer();state.sessionSeconds=90*60;updateTimer();save()});updateTimer()}
  function pauseTimer(){if(state.sessionTimer){clearInterval(state.sessionTimer);state.sessionTimer=null}}function updateTimer(){const m=String(Math.floor(state.sessionSeconds/60)).padStart(2,'0'),s=String(state.sessionSeconds%60).padStart(2,'0');$('#sessionTimer').textContent=`${m}:${s}`}
  function bindSpeech(){document.addEventListener('click',e=>{const b=e.target.closest('.speak-button[data-speak]');if(b)speak(b.dataset.speak);const gen=e.target.closest('.speak-generated');if(gen)speak($('#'+gen.dataset.output)?.textContent||'');const cp=e.target.closest('.copy-generated');if(cp)copyText($('#'+cp.dataset.output)?.textContent||'')})}
  function speak(text){if(!('speechSynthesis'in window)){toast('Speech synthesis is not available.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const lang=$('#accentSelect')?.value||'en-US';u.lang=lang;u.rate=.92;u.pitch=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang===lang)||voices.find(v=>v.lang?.startsWith(lang.slice(0,2)))||null;speechSynthesis.speak(u)}
  function bindVocabFilters(){$('#vocabFilters')?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;$$('#vocabFilters .filter').forEach(x=>x.classList.toggle('active',x===b));const f=b.dataset.filter;$$('#vocabGrid .vocab-card').forEach(c=>c.hidden=!(f==='all'||c.dataset.cat===f))})}
  function randomizeQuizChoices(){$$('.quiz-item').forEach(item=>{const holder=$(':scope > div',item);if(!holder)return;shuffle($$('button[data-choice-text]',holder)).forEach(b=>holder.appendChild(b))})}
  function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function bindQuizzes(){$$('.quiz-item').forEach((item,idx)=>{item.dataset.qid=`q${idx}`;$$('button[data-choice-text]',item).forEach(btn=>btn.addEventListener('click',()=>{const good=btn.dataset.choiceText===item.dataset.answerText;$$('button[data-choice-text]',item).forEach(x=>x.classList.remove('correct','wrong'));btn.classList.add(good?'correct':'wrong');const corr=$$('button[data-choice-text]',item).find(x=>x.dataset.choiceText===item.dataset.answerText);corr?.classList.add('correct');const fb=$('.feedback',item);fb.textContent=good?`✓ Correct — ${item.dataset.explain||''}`:`✗ Not quite — ${item.dataset.explain||''}`;fb.className=`feedback ${good?'good':'bad'}`;if(good)state.quizCorrect[item.dataset.qid]=true;else delete state.quizCorrect[item.dataset.qid];save();updateScores()}))})}
  function bindBuilders(){$$('[data-builder]').forEach(s=>s.addEventListener('change',()=>{updateBuilders();save()}))}
  function updateBuilders(){['opening','story'].forEach(key=>{const out=$(`#${key}Output`);if(out)out.textContent=$$(`[data-builder="${key}"]`).map(x=>x.value).join(' ')})}
  function bindMiniTimers(){$$('.timer-inline').forEach(box=>{const base=Number(box.dataset.seconds||60),display=$('strong',box),start=$('.timer-start',box),reset=$('.timer-reset',box);let remaining=base,interval=null;const render=()=>{display.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`};start?.addEventListener('click',()=>{if(interval)clearInterval(interval);remaining=base;render();interval=setInterval(()=>{remaining=Math.max(0,remaining-1);render();if(remaining===0){clearInterval(interval);interval=null;toast('Time — finish calmly and stop.')}},1000)});reset?.addEventListener('click',()=>{if(interval)clearInterval(interval);interval=null;remaining=base;render()});render()})}
  function bindChecks(){$$('input[data-check-score]').forEach(cb=>cb.addEventListener('change',()=>{save();updateScores()}))}
  function bindSaveFields(){$$('[data-save]').forEach(el=>{el.addEventListener('input',save);el.addEventListener('change',()=>{save();if(el.id==='confidenceSlider')updateConfidence()})});updateConfidence()}
  function bindResets(){$$('.reset-section').forEach(btn=>btn.addEventListener('click',()=>{const section=btn.closest('.lesson-section');if(!section)return;$$('input,textarea,select',section).forEach(el=>{if(el.matches('[type="checkbox"]'))el.checked=false;else if(el.matches('[type="range"]'))el.value=el.defaultValue||6;else if(el.tagName==='SELECT')el.selectedIndex=0;else el.value=''});$$('.quiz-item',section).forEach(item=>{$$('button[data-choice-text]',item).forEach(x=>x.classList.remove('correct','wrong'));const fb=$('.feedback',item);if(fb){fb.textContent='';fb.className='feedback'}delete state.quizCorrect[item.dataset.qid]});updateBuilders();updateConfidence();save();updateScores();toast('Section reset.') }));$('#resetAll')?.addEventListener('click',()=>{if(!confirm('Reset the whole lesson and delete saved progress?'))return;localStorage.removeItem(KEY);location.reload()})}
  function bindQuestions(){$('#newQuestion')?.addEventListener('click',()=>{let n=Math.floor(Math.random()*questionBank.length);if(n===state.questionIndex&&questionBank.length>1)n=(n+1)%questionBank.length;state.questionIndex=n;renderQuestion();save()});$('#hearQuestion')?.addEventListener('click',()=>speak(questionBank[state.questionIndex].q));$('#showQuestionHint')?.addEventListener('click',()=>$('#questionHint')?.classList.toggle('hidden'));$('#showQuestionModel')?.addEventListener('click',()=>$('#questionModel')?.classList.toggle('hidden'));renderQuestion()}
  function renderQuestion(){const q=questionBank[state.questionIndex];if($('#surpriseQuestion'))$('#surpriseQuestion').textContent=q.q;if($('#questionHint')){$('#questionHint').textContent=q.hint;$('#questionHint').classList.add('hidden')}if($('#questionModel')){$('#questionModel').textContent=q.model;$('#questionModel').classList.add('hidden')}}
  function bindSocial(){$('#hearSocial')?.addEventListener('click',()=>speak(socialBank[state.socialIndex].p));$('#socialModelButton')?.addEventListener('click',()=>$('#socialModel')?.classList.toggle('hidden'));$('#nextSocial')?.addEventListener('click',()=>{state.socialIndex=(state.socialIndex+1)%socialBank.length;renderSocial();save()});renderSocial()}
  function renderSocial(){const s=socialBank[state.socialIndex];if($('#socialPrompt'))$('#socialPrompt').textContent=s.p;if($('#socialModel')){$('#socialModel').textContent=s.m;$('#socialModel').classList.add('hidden')}}
  function scoresBySkill(){const out={story:[0,0],grammar:[0,0],qa:[0,0]};$$('.quiz-item').forEach(item=>{const skill=item.dataset.skill;if(out[skill]){out[skill][1]++;if(state.quizCorrect[item.dataset.qid])out[skill][0]++}});return out}
  function updateScores(){const by=scoresBySkill(),manual=$$('input[data-check-score]:checked').length,manualTotal=$$('input[data-check-score]').length;setText('scoreStory',`${by.story[0]} / ${by.story[1]}`);setText('scoreGrammar',`${by.grammar[0]} / ${by.grammar[1]}`);setText('scoreQA',`${by.qa[0]} / ${by.qa[1]}`);setText('scoreManual',`${manual} / ${manualTotal}`);const autoCorrect=Object.values(by).reduce((a,x)=>a+x[0],0),autoTotal=Object.values(by).reduce((a,x)=>a+x[1],0);setText('scoreTop',`${autoCorrect+manual} / ${autoTotal+manualTotal}`);updateReportPreview()}
  function setText(id,text){if($('#'+id))$('#'+id).textContent=text}
  function bindReport(){$('#confidenceSlider')?.addEventListener('input',()=>{updateConfidence();save();updateReportPreview()});$('#copyReport')?.addEventListener('click',()=>copyText(buildReportText()));$('#downloadReport')?.addEventListener('click',downloadReport);$('#printReport')?.addEventListener('click',()=>window.print())}
  function updateConfidence(){if($('#confidenceValue')&&$('#confidenceSlider'))$('#confidenceValue').textContent=`${$('#confidenceSlider').value} / 10`}
  function buildReportText(){const by=scoresBySkill(),manual=$$('input[data-check-score]:checked').length,manualTotal=$$('input[data-check-score]').length,statuses=$$('.manual-evaluation select').map(s=>`${s.parentElement.childNodes[0].textContent.trim()}: ${s.value}`);return `STORY-FIRST KAIZEN KICKOFF LESSON\n${$('#dateStamp')?.textContent||''}\n\nOBJECTIVES\n• Introduce the speaker role and team purpose before the technical slide.\n• Reduce acronym load and explain NNC, P90 and DMAIC in plain English.\n• Present the project as a clear story: problem -> impact -> target -> scope -> roadmap.\n• Handle questions without overclaiming beyond the slide.\n• Practise a U.S.-friendly opening, Q&A style and colleague interaction.\n\nEVIDENCE\nStory logic: ${by.story[0]} / ${by.story[1]}\nGrammar: ${by.grammar[0]} / ${by.grammar[1]}\nQ&A strategy: ${by.qa[0]} / ${by.qa[1]}\nManual speaking checkpoints: ${manual} / ${manualTotal}\nConfidence: ${$('#confidenceSlider')?.value||6} / 10\n\nTRAINER STATUS\n${statuses.join('\n')}\n\nSTRENGTHS\n${$('[data-save="report-strengths"]')?.value.trim()||'—'}\n\nPOINTS TO REINFORCE\n${$('[data-save="report-focus"]')?.value.trim()||'—'}\n\nNEXT LESSON PRIORITY\n${$('[data-save="report-next"]')?.value.trim()||'—'}\n\nCFL Welcome · SpeakEasyTisha · Progression visible`}
  function updateReportPreview(){if($('#reportPreview'))$('#reportPreview').textContent=buildReportText()}
  function downloadReport(){const text=buildReportText(),html=`<!doctype html><meta charset="utf-8"><title>Story-first kickoff report</title><style>body{font-family:Arial,sans-serif;background:#fffaf0;color:#222;line-height:1.55}.page{max-width:900px;margin:28px auto;background:white;border:1px solid #e9e2d5;border-radius:20px;overflow:hidden}.head{background:#111;color:white;padding:26px;border-bottom:6px solid #f2b822}.body{padding:26px}pre{white-space:pre-wrap;font:14px/1.6 Arial}</style><div class="page"><div class="head"><h1>Story-first Kaizen kickoff report</h1></div><div class="body"><pre>${escapeHtml(text)}</pre></div></div>`;const blob=new Blob([html],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Story-First-Kaizen-Kickoff-Report.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800);toast('HTML report downloaded.')}
  function save(){const data={sectionIndex:state.sectionIndex,sessionSeconds:state.sessionSeconds,showFr:document.body.classList.contains('show-fr'),quizCorrect:state.quizCorrect,questionIndex:state.questionIndex,socialIndex:state.socialIndex,fields:{},checks:{}};$$('[data-save]').forEach(el=>data.fields[el.dataset.save]=el.value);$$('input[data-check-score]').forEach((el,i)=>data.checks[i]=el.checked);try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}}
  function restore(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d)return;state.sectionIndex=Math.min(Number(d.sectionIndex)||0,sections.length-1);state.sessionSeconds=Number.isFinite(d.sessionSeconds)?d.sessionSeconds:90*60;state.quizCorrect=d.quizCorrect||{};state.questionIndex=Number.isInteger(d.questionIndex)?d.questionIndex:0;state.socialIndex=Number.isInteger(d.socialIndex)?d.socialIndex:0;document.body.classList.toggle('show-fr',d.showFr!==false);const tb=$('#translationToggle');if(tb){tb.classList.toggle('active',d.showFr!==false);tb.textContent=d.showFr===false?'FR help · OFF':'FR help · ON'}$$('[data-save]').forEach(el=>{if(d.fields&&d.fields[el.dataset.save]!==undefined)el.value=d.fields[el.dataset.save]});$$('input[data-check-score]').forEach((el,i)=>{el.checked=!!(d.checks&&d.checks[i])});$$('.quiz-item').forEach(item=>{if(state.quizCorrect[item.dataset.qid]){const btn=$$('button[data-choice-text]',item).find(x=>x.dataset.choiceText===item.dataset.answerText);btn?.classList.add('correct');const fb=$('.feedback',item);if(fb){fb.textContent=`✓ Correct — ${item.dataset.explain||''}`;fb.className='feedback good'}}});updateTimer();updateConfidence();renderQuestion();renderSocial()}catch(e){}}
  function copyText(text){if(!text.trim()){toast('Nothing to copy.');return}navigator.clipboard?.writeText(text).then(()=>toast('Copied.')).catch(()=>{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied.')})}
  function setDate(){if($('#dateStamp'))$('#dateStamp').textContent=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),1800)}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();