(() => {
  'use strict';
  const KEY='thomas_real_6pack_us_v1';
  const sections=[...document.querySelectorAll('.lesson-section')];
  const state={sectionIndex:0,sessionSeconds:90*60,sessionTimer:null,quizCorrect:{},questionIndex:0,socialIndex:0};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];

  const questionBank=[
    {q:'Why is the current processing time 5.3 days?',hint:'Say what the slide establishes → separate it from root cause → offer the next analysis.',model:'The slide establishes the current average at 5.3 days, but it does not give the detailed root-cause breakdown. I do not want to speculate. The next step is to use the analysis work to identify the main drivers behind that processing time.'},
    {q:'Why was the target set at exactly 2 days?',hint:'The slide gives the target, not its rationale. Do not invent the basis.',model:'The slide defines 2 days as the project target. The rationale behind that exact figure is not shown here, so I would rather verify the agreed basis than invent an explanation.'},
    {q:'Is 31 days the average for all NNC parts?',hint:'Distinguish the overall average from the reworked-parts figure.',model:'No. The overall average shown is 5.3 days. The 31-day figure is specifically associated with reworked parts in the problem statement.'},
    {q:'What is the expected financial saving?',hint:'The slide mentions holding-cost reduction but gives no euro amount.',model:'The slide identifies a reduction in parts holding costs as the financial impact, but it does not quantify the saving here. I would need the financial calculation before giving an exact amount.'},
    {q:'Why are CSC cases out of scope?',hint:'State the boundary. Do not invent the rationale.',model:'The slide shows that parts with a CSC case are out of scope, but it does not explain the reason for that boundary. I can confirm the project rationale separately if needed.'},
    {q:'Have you already completed the Analyze phase?',hint:'Use the real status, not the check mark alone.',model:'I would answer that according to the actual project status at the time of the meeting. The slide lists the Analyze milestone for September 30, but I would not use the check mark alone as proof of completion.'},
    {q:'What is the biggest risk to reaching the 2-day target?',hint:'The slide does not identify a biggest risk. Say so and avoid guessing.',model:'The slide defines the problem, the target and the scope, but it does not identify one single biggest risk. I would rather base that answer on the analysis results than speculate.'},
    {q:'What do you want from us after this meeting?',hint:'Turn presentation into a collaborative next step.',model:'The immediate goal is alignment on the problem, the target and the project framework. If there are concerns about the scope, assumptions or milestones, this is the right moment to surface them so we can address them early.'}
  ];
  const socialBank=[
    {p:'A colleague asks: “How was your trip over?”',m:'It was good, thanks. A little long, but everything went smoothly. How’s your week going so far?'},
    {p:'A colleague asks: “Have you had a chance to see anything around town?”',m:'A little. I’m still getting my bearings, but I really like the area. Is there one place you’d definitely recommend while I’m here?'},
    {p:'At lunch someone asks: “So what do you like to do outside work?”',m:'I’m pretty active. I enjoy sports and getting outside when I can. What about you — what do you usually do on weekends?'},
    {p:'A colleague says: “Traffic was brutal this morning.”',m:'Yeah, I noticed it was pretty busy. Is that normal around this time, or was today especially bad?'},
    {p:'Someone asks: “Have you tried any local food yet?”',m:'Not yet, but I’ve been meaning to. I’d definitely like to try something local. Any recommendations?'},
    {p:'After the meeting: “How did you feel the discussion went?”',m:'I thought it was useful. The questions helped clarify the main priorities. What stood out most to you?'}
  ];

  document.addEventListener('DOMContentLoaded',init);
  function init(){makeStepDots();bindNav();bindHeader();bindSessionTimer();bindSpeech();bindVocabFilters();randomizeQuizChoices();bindQuizzes();bindBuilders();bindMiniTimers();bindManualChecks();bindSaveFields();bindResets();bindQuestions();bindSocial();bindReport();restore();setDate();updateBuilders();updateScores();showSection(state.sectionIndex,false)}
  function makeStepDots(){const nav=$('#stepDots');sections.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1);b.title=s.dataset.title||`Section ${i+1}`;b.addEventListener('click',()=>showSection(i));nav.appendChild(b)})}
  function bindNav(){$$('[data-next]').forEach(b=>b.addEventListener('click',()=>showSection(Math.min(state.sectionIndex+1,sections.length-1))));$('#backTop')?.addEventListener('click',()=>showSection(0))}
  function showSection(i,scroll=true){state.sectionIndex=i;sections.forEach((s,n)=>s.classList.toggle('active',n===i));$('#progressBar').style.width=`${((i+1)/sections.length)*100}%`;$('#progressLabel').textContent=sections[i]?.dataset.title||'';$$('#stepDots button').forEach((b,n)=>b.classList.toggle('active',n===i));save();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
  function bindHeader(){$('#translationToggle')?.addEventListener('click',()=>{const on=document.body.classList.toggle('show-fr');const b=$('#translationToggle');b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.textContent=on?'FR help · ON':'FR help · OFF';save()});$('#printButton')?.addEventListener('click',()=>window.print())}
  function bindSessionTimer(){$('#timerStart')?.addEventListener('click',()=>{if(state.sessionTimer)return;state.sessionTimer=setInterval(()=>{state.sessionSeconds=Math.max(0,state.sessionSeconds-1);updateSessionTimer();if(state.sessionSeconds===0)pauseSessionTimer()},1000)});$('#timerPause')?.addEventListener('click',pauseSessionTimer);$('#timerReset')?.addEventListener('click',()=>{pauseSessionTimer();state.sessionSeconds=90*60;updateSessionTimer();save()});updateSessionTimer()}
  function pauseSessionTimer(){if(state.sessionTimer){clearInterval(state.sessionTimer);state.sessionTimer=null}}
  function updateSessionTimer(){const m=String(Math.floor(state.sessionSeconds/60)).padStart(2,'0'),s=String(state.sessionSeconds%60).padStart(2,'0');$('#sessionTimer').textContent=`${m}:${s}`}
  function bindSpeech(){document.addEventListener('click',e=>{const b=e.target.closest('.speak-button[data-speak]');if(b)speak(b.dataset.speak);const gen=e.target.closest('.speak-generated');if(gen)speak($('#'+gen.dataset.output)?.textContent||'');const cp=e.target.closest('.copy-generated');if(cp)copyText($('#'+cp.dataset.output)?.textContent||'')})}
  function speak(text){if(!('speechSynthesis'in window)){toast('Speech synthesis is not available.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const lang=$('#accentSelect')?.value||'en-US';u.lang=lang;u.rate=.92;u.pitch=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang===lang)||voices.find(v=>v.lang?.startsWith(lang.slice(0,2)))||null;speechSynthesis.speak(u)}
  function bindVocabFilters(){$('#vocabFilters')?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;$$('#vocabFilters .filter').forEach(x=>x.classList.toggle('active',x===b));const f=b.dataset.filter;$$('#vocabGrid .vocab-card').forEach(c=>c.hidden=!(f==='all'||c.dataset.cat===f))})}
  function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function randomizeQuizChoices(){$$('.quiz-item').forEach(item=>{const holder=$(':scope > div',item);if(!holder)return;shuffle($$('button[data-choice-text]',holder)).forEach(b=>holder.appendChild(b))})}
  function bindQuizzes(){$$('.quiz-item').forEach((item,idx)=>{item.dataset.qid=`q${idx}`;$$('button[data-choice-text]',item).forEach(btn=>btn.addEventListener('click',()=>{const good=btn.dataset.choiceText===item.dataset.answerText;$$('button[data-choice-text]',item).forEach(x=>x.classList.remove('correct','wrong'));btn.classList.add(good?'correct':'wrong');const right=$$('button[data-choice-text]',item).find(x=>x.dataset.choiceText===item.dataset.answerText);right?.classList.add('correct');const fb=$('.feedback',item);fb.textContent=good?`✓ Correct — ${item.dataset.explain||''}`:`✗ Not quite — ${item.dataset.explain||''}`;fb.className=`feedback ${good?'good':'bad'}`;if(good)state.quizCorrect[item.dataset.qid]=true;else delete state.quizCorrect[item.dataset.qid];save();updateScores()}))})}
  function bindBuilders(){$$('[data-builder]').forEach(s=>s.addEventListener('change',()=>{updateBuilders();save()}))}
  function updateBuilders(){const map={opening:'openingOutput',problem:'problemOutput',objective:'objectiveOutput',planning:'planningOutput'};Object.entries(map).forEach(([key,id])=>{const out=$('#'+id);if(out)out.textContent=$$(`[data-builder="${key}"]`).map(x=>x.value).join(' ')});if($('#outlineOpening'))$('#outlineOpening').textContent=$('#openingOutput')?.textContent||'';if($('#outlineProblem'))$('#outlineProblem').textContent=$('#problemOutput')?.textContent||'';if($('#outlineObjective'))$('#outlineObjective').textContent=$('#objectiveOutput')?.textContent||'';if($('#outlinePlanning'))$('#outlinePlanning').textContent=$('#planningOutput')?.textContent||''}
  function bindMiniTimers(){$$('.timer-inline').forEach(box=>{const base=Number(box.dataset.seconds||60),display=$('strong',box),start=$('.timer-start',box),reset=$('.timer-reset',box);let remaining=base,interval=null;const render=()=>{const m=String(Math.floor(remaining/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');display.textContent=`${m}:${s}`};start?.addEventListener('click',()=>{if(interval)clearInterval(interval);remaining=base;render();interval=setInterval(()=>{remaining=Math.max(0,remaining-1);render();if(remaining===0){clearInterval(interval);interval=null;toast('Time — finish the sentence calmly, then stop.')}},1000)});reset?.addEventListener('click',()=>{if(interval)clearInterval(interval);interval=null;remaining=base;render()});render()})}
  function bindManualChecks(){$$('input[data-check-score]').forEach(cb=>cb.addEventListener('change',()=>{save();updateScores()}))}
  function bindSaveFields(){$$('[data-save]').forEach(el=>{el.addEventListener('input',save);el.addEventListener('change',()=>{save();if(el.id==='confidenceSlider')updateConfidence()})});updateConfidence()}
  function bindResets(){$$('.reset-section').forEach(btn=>btn.addEventListener('click',()=>{const section=btn.closest('.lesson-section');if(!section)return;$$('input,textarea,select',section).forEach(el=>{if(el.matches('[type="checkbox"]'))el.checked=false;else if(el.matches('[type="range"]'))el.value=el.defaultValue||6;else if(el.tagName==='SELECT')el.selectedIndex=0;else el.value=''});$$('.quiz-item',section).forEach(item=>{$$('button[data-choice-text]',item).forEach(x=>x.classList.remove('correct','wrong'));const fb=$('.feedback',item);if(fb){fb.textContent='';fb.className='feedback'}delete state.quizCorrect[item.dataset.qid]});updateBuilders();updateConfidence();save();updateScores();toast('Section reset.')}));$('#resetAll')?.addEventListener('click',()=>{if(!confirm('Reset the whole lesson and delete saved progress?'))return;localStorage.removeItem(KEY);location.reload()})}
  function bindQuestions(){$('#newQuestion')?.addEventListener('click',()=>{let n=Math.floor(Math.random()*questionBank.length);if(n===state.questionIndex&&questionBank.length>1)n=(n+1)%questionBank.length;state.questionIndex=n;renderQuestion();save()});$('#hearQuestion')?.addEventListener('click',()=>speak(questionBank[state.questionIndex].q));$('#showQuestionHint')?.addEventListener('click',()=>$('#questionHint')?.classList.toggle('hidden'));$('#showQuestionModel')?.addEventListener('click',()=>$('#questionModel')?.classList.toggle('hidden'));renderQuestion()}
  function renderQuestion(){const q=questionBank[state.questionIndex];if($('#surpriseQuestion'))$('#surpriseQuestion').textContent=q.q;if($('#questionHint')){$('#questionHint').textContent=q.hint;$('#questionHint').classList.add('hidden')}if($('#questionModel')){$('#questionModel').textContent=q.model;$('#questionModel').classList.add('hidden')}}
  function bindSocial(){$('#hearSocial')?.addEventListener('click',()=>speak(socialBank[state.socialIndex].p));$('#socialModelButton')?.addEventListener('click',()=>$('#socialModel')?.classList.toggle('hidden'));$('#nextSocial')?.addEventListener('click',()=>{state.socialIndex=(state.socialIndex+1)%socialBank.length;renderSocial();save()});renderSocial()}
  function renderSocial(){const s=socialBank[state.socialIndex];if($('#socialPrompt'))$('#socialPrompt').textContent=s.p;if($('#socialModel')){$('#socialModel').textContent=s.m;$('#socialModel').classList.add('hidden')}}
  function scoresBySkill(){const out={problem:[0,0],objective:[0,0],scope:[0,0],planning:[0,0],grammar:[0,0],meeting:[0,0],qa:[0,0]};$$('.quiz-item').forEach(item=>{const skill=item.dataset.skill;if(out[skill]){out[skill][1]++;if(state.quizCorrect[item.dataset.qid])out[skill][0]++}});return out}
  function updateScores(){const by=scoresBySkill(),manual=$$('input[data-check-score]:checked').length,manualTotal=$$('input[data-check-score]').length;setText('scoreProblem',`${by.problem[0]} / ${by.problem[1]}`);setText('scoreObjective',`${by.objective[0]} / ${by.objective[1]}`);setText('scoreScope',`${by.scope[0]} / ${by.scope[1]}`);setText('scorePlanning',`${by.planning[0]} / ${by.planning[1]}`);setText('scoreGrammar',`${by.grammar[0]} / ${by.grammar[1]}`);setText('scoreMeeting',`${by.meeting[0]} / ${by.meeting[1]}`);setText('scoreQA',`${by.qa[0]} / ${by.qa[1]}`);setText('scoreManual',`${manual} / ${manualTotal}`);const autoC=Object.values(by).reduce((a,x)=>a+x[0],0),autoT=Object.values(by).reduce((a,x)=>a+x[1],0);setText('scoreTop',`${autoC+manual} / ${autoT+manualTotal}`);updateReportPreview()}
  function setText(id,text){if($('#'+id))$('#'+id).textContent=text}
  function bindReport(){$('#confidenceSlider')?.addEventListener('input',()=>{updateConfidence();save();updateReportPreview()});$('#copyReport')?.addEventListener('click',()=>copyText(buildReportText()));$('#downloadReport')?.addEventListener('click',downloadReport);$('#printReport')?.addEventListener('click',()=>window.print())}
  function updateConfidence(){if($('#confidenceValue')&&$('#confidenceSlider'))$('#confidenceValue').textContent=`${$('#confidenceSlider').value} / 10`}
  function buildReportData(){const by=scoresBySkill(),manual=$$('input[data-check-score]:checked').length,manualTotal=$$('input[data-check-score]').length;return{date:$('#dateStamp')?.textContent||'',problem:`${by.problem[0]} / ${by.problem[1]}`,objective:`${by.objective[0]} / ${by.objective[1]}`,scope:`${by.scope[0]} / ${by.scope[1]}`,planning:`${by.planning[0]} / ${by.planning[1]}`,grammar:`${by.grammar[0]} / ${by.grammar[1]}`,meeting:`${by.meeting[0]} / ${by.meeting[1]}`,qa:`${by.qa[0]} / ${by.qa[1]}`,manual:`${manual} / ${manualTotal}`,statuses:$$('.manual-evaluation select').map(s=>`${s.parentElement.childNodes[0].textContent.trim()}: ${s.value}`),strengths:$('[data-save="report-strengths"]')?.value.trim()||'—',focus:$('[data-save="report-focus"]')?.value.trim()||'—',next:$('[data-save="report-next"]')?.value.trim()||'—',confidence:$('#confidenceSlider')?.value||'6'}}
  function buildReportText(){const d=buildReportData();return `REAL 6-PACK U.S. PRESENTATION — PROGRESS REPORT\n${d.date}\n\nOBJECTIVES\n• Guide the audience through the exact 6-pack slide in a logical order.\n• Explain the 5.3-day current state, 2-day target and 31-day reworked-parts figure accurately.\n• Present business impact, project scope, DMAIC planning and team clearly.\n• Use presentation grammar, transitions and careful evidence-based language.\n• Handle questions without guessing beyond what the slide supports.\n• Maintain natural professional conversation with U.S. colleagues.\n\nAUTOMATIC / OBSERVABLE EVIDENCE\nProblem description: ${d.problem}\nObjective & impact: ${d.objective}\nScope: ${d.scope}\nPlanning: ${d.planning}\nGrammar: ${d.grammar}\nMeeting flow: ${d.meeting}\nQ&A strategy: ${d.qa}\nManual speaking checkpoints: ${d.manual}\n\nTRAINER STATUS\n${d.statuses.join('\n')}\n\nSTRENGTHS\n${d.strengths}\n\nPOINTS TO REINFORCE\n${d.focus}\n\nNEXT LESSON PRIORITY\n${d.next}\n\nCONFIDENCE AFTER GUIDED REHEARSAL\n${d.confidence} / 10\n\nREAL PROFESSIONAL TRANSFER\nProject: Shingijutsu – KAIZEN#3 – Improvement of shop processing time for NNC.\nSlide route: Problem → Objective → Business Impact → Scope → Planning → Team → Questions.\n\nCFL Welcome · SpeakEasyTisha · Progression visible`}
  function updateReportPreview(){if($('#reportPreview'))$('#reportPreview').textContent=buildReportText()}
  function downloadReport(){const text=buildReportText();const html=`<!doctype html><html><head><meta charset="utf-8"><title>6-pack U.S. Presentation Report</title><style>body{font-family:Arial,sans-serif;background:#fffaf0;color:#222;line-height:1.55;margin:0}.page{max-width:900px;margin:28px auto;background:#fff;border:1px solid #e9e2d5;border-radius:20px;overflow:hidden}.head{background:#111;color:#fff;padding:26px;border-bottom:6px solid #f2b822}.head small{color:#f2b822;font-weight:bold;letter-spacing:.1em}.body{padding:26px}pre{white-space:pre-wrap;font:14px/1.6 Arial,sans-serif}.foot{padding:18px 26px;background:#111;color:#ddd;font-size:12px}@media print{.page{margin:0;max-width:none;border:0;border-radius:0}}</style></head><body><div class="page"><div class="head"><small>CFL WELCOME · REAL 6-PACK PRESENTATION</small><h1>U.S. Presentation Preparation</h1></div><div class="body"><pre>${escapeHtml(text)}</pre></div><div class="foot">SpeakEasyTisha · Qualiopi progress evidence</div></div></body></html>`;const blob=new Blob([html],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Real-6Pack-US-Presentation-Progress.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800);toast('HTML report downloaded.')}
  function save(){const data={sectionIndex:state.sectionIndex,sessionSeconds:state.sessionSeconds,showFr:document.body.classList.contains('show-fr'),quizCorrect:state.quizCorrect,questionIndex:state.questionIndex,socialIndex:state.socialIndex,fields:{},checks:{}};$$('[data-save]').forEach(el=>data.fields[el.dataset.save]=el.value);$$('input[data-check-score]').forEach((el,i)=>data.checks[i]=el.checked);try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}}
  function restore(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d)return;state.sectionIndex=Math.min(Number(d.sectionIndex)||0,sections.length-1);state.sessionSeconds=Number.isFinite(d.sessionSeconds)?d.sessionSeconds:90*60;state.quizCorrect=d.quizCorrect||{};state.questionIndex=Number.isInteger(d.questionIndex)?d.questionIndex:0;state.socialIndex=Number.isInteger(d.socialIndex)?d.socialIndex:0;document.body.classList.toggle('show-fr',d.showFr!==false);const tb=$('#translationToggle');if(tb){tb.classList.toggle('active',d.showFr!==false);tb.textContent=d.showFr===false?'FR help · OFF':'FR help · ON'}$$('[data-save]').forEach(el=>{if(d.fields&&d.fields[el.dataset.save]!==undefined)el.value=d.fields[el.dataset.save]});$$('input[data-check-score]').forEach((el,i)=>{el.checked=!!(d.checks&&d.checks[i])});$$('.quiz-item').forEach(item=>{if(state.quizCorrect[item.dataset.qid]){const btn=$$('button[data-choice-text]',item).find(x=>x.dataset.choiceText===item.dataset.answerText);btn?.classList.add('correct');const fb=$('.feedback',item);if(fb){fb.textContent=`✓ Correct — ${item.dataset.explain||''}`;fb.className='feedback good'}}});updateSessionTimer();updateConfidence();renderQuestion();renderSocial()}catch(e){}}
  function copyText(text){if(!text.trim()){toast('Nothing to copy.');return}navigator.clipboard?.writeText(text).then(()=>toast('Copied.')).catch(()=>{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied.')})}
  function setDate(){if($('#dateStamp'))$('#dateStamp').textContent=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),1800)}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();