const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={greet:{},modal:{},fill:{},nav:{},sort:false,mode:"practice",place:0,restaurant:"fine",dialogue:"street",navigation:0};

const BOW="https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Bow_Bridge_in_Central_Park%2C_NYC.jpg/960px-Bow_Bridge_in_Central_Park%2C_NYC.jpg?utm_campaign=index&utm_content=thumbnail&utm_source=commons.wikimedia.org";
const BOW_FALLBACK="https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Bow_Bridge_in_Central_Park%2C_NYC.jpg/960px-Bow_Bridge_in_Central_Park%2C_NYC.jpg?utm_campaign=index&utm_content=thumbnail&utm_source=commons.wikimedia.org";

const greetingData=[
 {q:"You walk into a normal hotel reception. Best default?",a:"Hi, I have a reservation under Martin.",o:["Hi, I have a reservation under Martin.","Hey! What's up? I booked a room.","Excuse me, I sincerely apologize for disturbing you."]},
 {q:"You need help from a stranger on the street.",a:"Excuse me, could you help me for a second?",o:["Hey you, where's the subway?","Excuse me, could you help me for a second?","Hello sir or madam, pardon my interruption."]},
 {q:"You arrive at an elegant restaurant in the evening.",a:"Good evening. We have a reservation for 7:30.",o:["Good evening. We have a reservation for 7:30.","Yo, we booked.","Sorry to bother you terribly. We have food reservation."]},
 {q:"You already chatted with a friendly bartender for ten minutes.",a:"Hey, what would you recommend?",o:["Hey, what would you recommend?","Good evening, sir. May I request your recommendation?","Where drink good?"]}
];

const modalData=[
 {q:"You want a normal, friendly request at a coffee counter.",a:"Can I get a small latte, please?",o:["Can I get a small latte, please?","May you give me a small latte?","Should I get me a small latte?"]},
 {q:"You are asking a stranger for directions and want to soften the request.",a:"Could you tell me where the subway entrance is?",o:["Could you tell me where the subway entrance is?","Could you to tell me where the subway entrance is?","May you tell me where the subway entrance is?"]},
 {q:"You want advice about the best train to take.",a:"Which train should I take?",o:["Which train should I take?","Which train may I take?","Which train can I to take?"]},
 {q:"You are asking formal permission at a coat check.",a:"May I leave my coat here?",o:["May I leave my coat here?","May I to leave my coat here?","Should I leave my coat here?"]},
 {q:"A local says: “You should take the local.” What does should mean here?",a:"It is advice / the recommended choice.",o:["It is advice / the recommended choice.","It is a legal obligation.","It describes past ability."]},
 {q:"“Could you help me?” is often used in travel English because…",a:"could can make the request softer and more polite.",o:["could can make the request softer and more polite.","could always means the request happened in the past.","could is slang for can."]}
];

const places=[
 {name:"Central Park",icon:"🌳",photo:BOW,fallback:BOW_FALLBACK,credit:"Bow Bridge photo · Wikimedia Commons; place information · Central Park Conservancy",title:"Central Park · Bow Bridge",facts:"Bow Bridge is around 74th Street. It is one of the best-known places in Central Park. The park is very large, so it is better to choose a few places instead of trying to see everything.",positive:"Visitors like the beautiful views, the walking and the quieter feeling away from busy streets.",critical:"The park is much bigger than many visitors expect. Walking from one famous place to another can take time.",vocab:[["beautiful view","belle vue"],["quiet","calme"],["large","grand / vaste"],["walk","marcher / promenade"],["nearby","à proximité"],["take time","prendre du temps"]],prompt:"Would you spend two hours here, half a day, or skip it? Explain what would make the visit enjoyable for you.",formal:"I would be particularly interested in spending several hours here because it offers a peaceful contrast to Midtown. I would prefer to choose a few specific places rather than try to see the entire park.",polite:"I'd definitely like to spend a couple of hours here. I'd choose two or three places, enjoy the scenery and take my time.",casual:"I'd absolutely go. I'd pick a few nice spots, walk around and just enjoy it without rushing.",slang:"I'd be into this for sure. I'd wander around, chill for a bit and not try to cram everything in."},
 {name:"SUMMIT",icon:"✨",photo:"https://summitov.com/wp-content/uploads/2025/01/air-at-light%401x-1-1024x533.jpg",fallback:"",credit:"SUMMIT One Vanderbilt",title:"SUMMIT One Vanderbilt",facts:"SUMMIT is an observation experience high above Midtown. It has big city views, mirrors, glass and spaces designed for photos.",positive:"Many visitors love the views and say the experience feels different from a normal observation deck.",critical:"Some visitors think the tickets are expensive, and it can feel very crowded at busy times.",vocab:[["view","vue"],["mirror","miroir"],["glass","verre"],["crowded","bondé"],["ticket","billet"],["worth it","valoir le coup"]],prompt:"Does this type of experience attract you, or would you prefer a more classic observation deck?",formal:"The modern design is appealing because it offers more than a standard viewpoint. However, I would choose a quieter time to avoid large crowds.",polite:"I'd probably enjoy it because the views look amazing and the experience is different. I'd just choose the time carefully because I don't like huge crowds.",casual:"I'd try it once. It looks amazing, but I'd avoid the busiest time.",slang:"It looks pretty wild. I'd go for the views, but not if it's insanely packed."},
 {name:"Top of the Rock",icon:"🏙",photo:"https://images.unsplash.com/photo-1761245093712-ffc037acb410?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1600",fallback:"",credit:"NYC skyline photo · Unsplash",title:"Top of the Rock · classic skyline choice",facts:"Top of the Rock gives you a classic New York skyline view. A big advantage is that you can see the Empire State Building in front of you.",positive:"Visitors often like the open-air view and the classic New York photos.",critical:"Sunset is very popular, so lines and viewing areas can be busy.",vocab:[["skyline","silhouette de la ville"],["open-air","en plein air"],["sunset","coucher de soleil"],["line","file d'attente"],["busy","très fréquenté"],["classic","classique / emblématique"]],prompt:"Would you choose this classic view or the more modern SUMMIT experience? Why?",formal:"If my priority were a classic skyline view, I would probably choose Top of the Rock. I would avoid the busiest sunset period.",polite:"I think I'd choose this if I wanted the classic New York view, especially with the Empire State Building in front of me.",casual:"For the classic skyline, this might be my pick. I'd just go at a quieter time.",slang:"For that classic NYC shot, this would probably be my choice. I'd skip the crazy sunset rush."},
 {name:"Times Square",icon:"🎭",photo:"https://images.ctfassets.net/1aemqu6a6t65/7w7xp69KB6TE8fPIyzCihQ/7fae7566ec09ff43ce79975eef5c005c/1-Time-Square-Manhattan-NYC-Photo-Courtesy-Timelapse-Company-12.jpg",fallback:"",credit:"NYC Tourism + Conventions",title:"Times Square · iconic and intense",facts:"Times Square is famous for giant screens, Broadway theatres, crowds and bright lights. It is one of the most recognizable places in New York.",positive:"Many first-time visitors love seeing it once, especially at night.",critical:"It can be very crowded, loud and touristy. Some visitors stay only a short time and then go somewhere calmer.",vocab:[["bright","lumineux"],["crowded","bondé"],["loud","bruyant"],["touristy","très touristique"],["at night","la nuit"],["calmer","plus calme"]],prompt:"Would you enjoy the energy, or would twenty minutes be enough for you?",formal:"I would certainly want to experience it once because it is such a recognizable part of New York. However, I would probably not stay for a long time.",polite:"I'd definitely see it once, especially at night, but I think twenty or thirty minutes might be enough for me.",casual:"I'd check it out for the lights, then probably head somewhere calmer.",slang:"I'd go once because it's iconic, but if it's wall-to-wall people, I'd get out pretty fast."},
 {name:"Liberty",icon:"🗽",photo:"https://www.nps.gov/stli/planyourvisit/images/statue-from-boat-NYC-background.jpg?autorotate=false&format=webp&maxheight=1300&maxwidth=1300",fallback:"",credit:"U.S. National Park Service",title:"Statue of Liberty · the classic symbol",facts:"To visit Liberty Island, you take a ferry. It is better to book in advance, especially if you want special access. The full visit takes several hours.",positive:"Visitors often love the boat ride, the harbor view and seeing the Statue of Liberty up close.",critical:"Security, waiting and ferry times mean that the visit can use a large part of your day.",vocab:[["ferry","ferry / bateau"],["island","île"],["book in advance","réserver à l'avance"],["security","contrôle de sécurité"],["wait","attendre"],["up close","de près"]],prompt:"Would you spend several hours on the full visit, or prefer a shorter harbor view?",formal:"I would choose the full visit if the Statue of Liberty were one of my main priorities, but I would plan enough time for the ferry and security.",polite:"I'd probably do the full visit once because it's such an important New York experience. I'd just plan the day around it.",casual:"I'd do the full visit if it was really important to me. Otherwise, I might just enjoy the harbor view.",slang:"I'd go all in if it was a must-do. Otherwise, I'd catch the view and keep moving."}
];

const reviewFill=[
 {s:"The view was absolutely ________. I couldn't stop looking at it.",a:"breathtaking",hint:"very beautiful / impressive"},
 {s:"It was good, but the sunset time slot was completely ________.",a:"packed",hint:"very crowded"},
 {s:"The ticket was expensive, but I still think it was ________ it.",a:"worth",hint:"___ it = valait le coup"},
 {s:"I'd go early to ________ the crowds.",a:"avoid",hint:"stay away from"}
];

const sortTokens=[
 ["Good evening.","polished"],["Would you mind helping me?","polished"],["Would it be possible to…?","polished"],
 ["Hi, could I get…?","safe"],["I'm all set, thanks.","safe"],["Sounds good.","safe"],
 ["grab a bite","casual"],["pretty good","casual"],["you guys","casual"],
 ["What's up?","slang"],["my bad","slang"],["dude","slang"]
];

const navVocab={
 subway:[["tap","présenter / passer sa carte ou son téléphone sans contact","Tap your card or phone on the reader."],["turnstile","portique / tourniquet d'entrée","Tap at the turnstile."],["platform","quai","Which platform do I need?"],["local train","train qui s'arrête à toutes les stations","Does the local stop at 79th?"],["express train","train qui saute certaines stations","Is this an express train?"],["transfer","correspondance / changer de ligne","Where do I transfer?"],["fare","prix du trajet / tarif","Is the fare the same?"],["entrance","entrée","Does this entrance go downtown?"]],
 directions:[["block","pâté de maisons","It's two blocks away."],["corner","coin de rue","Turn left at the corner."],["intersection","carrefour","It's at the next intersection."],["crosswalk","passage piéton","Cross at the crosswalk."],["within walking distance","accessible à pied","Is it within walking distance?"],["across from","en face de","It's across from the hotel."],["next to","à côté de","It's next to the pharmacy."],["straight ahead","tout droit","Keep going straight ahead."]],
 problems:[["service change","modification du service","There is a service change this weekend."],["skipped stop","station non desservie","This train is skipping my stop."],["delayed","en retard","The train is delayed."],["closed","fermé","This entrance is closed."],["wrong direction","mauvaise direction","I think I'm going in the wrong direction."],["uptown","vers le nord / Uptown","Does this train go uptown?"],["downtown","vers le sud / Downtown","I need a downtown train."],["announcement","annonce","I didn't understand the announcement."]]
};

const navigationData=[
 {icon:"↕",name:"Wrong entrance",sign:"DOWNTOWN & BROOKLYN",situation:"You are outside a subway station and the entrance sign says Downtown & Brooklyn, but you need to travel uptown. You do not want to tap through the wrong entrance.",goal:"Ask whether this entrance connects to the uptown platform or whether you need another entrance.",dialogue:[["You","Excuse me, does this entrance also connect to the uptown platform, or do I need to go across the street?"],["Local","This one is downtown only. Use the entrance on the other side."],["You","Got it—the other side for uptown. Thanks so much."]],question:"What should you check before tapping?",answer:"Whether the entrance serves the direction/platform you need.",options:["Whether the entrance serves the direction/platform you need.","Whether the station has a coffee shop.","Whether every train is express."],formal:"Excuse me, could you tell me whether this entrance also provides access to the uptown platform?",polite:"Excuse me, does this entrance go uptown too, or should I use the one across the street?",casual:"Hi—is uptown through here, or do I need the other entrance?",slang:"Hey, is uptown through here or nah?"},
 {icon:"L/E",name:"Local vs express",sign:"LOCAL / EXPRESS",situation:"You need a station that is served by the local train. An express arrives first and you are not sure whether it stops there.",goal:"Ask whether the express stops at your station and, if not, where to change for the local.",dialogue:[["You","Excuse me, does this express stop at 79th Street?"],["Local","No, you'll need the local."],["You","Okay. Should I wait here for the local, or change later?"],["Local","Just wait here for the 1."],["You","Perfect, thank you."]],question:"Why is “Should I wait here?” useful?",answer:"You are asking for advice about the best choice.",options:["You are asking for advice about the best choice.","You are asking formal permission.","You are describing past ability."],formal:"Could you tell me whether this express train stops at my station, or whether I should take the local?",polite:"Does this express stop at 79th, or should I wait for the local?",casual:"Does this one stop at 79th, or do I need the local?",slang:"Does this hit 79th, or do I gotta grab the local?"},
 {icon:"⚠",name:"Service change",sign:"WEEKEND SERVICE CHANGE",situation:"A sign says your train is running express and will skip several local stops because of planned work. Your destination is one of the skipped stops.",goal:"Explain what you understood and ask for the easiest alternative.",dialogue:[["You","Hi, the sign says this train is running express and skipping my stop. What's the easiest way to get there?"],["Agent","Take it to the next express stop, then come back on the local in the other direction."],["You","So I go past my stop, switch to the local, and come back one stop?"],["Agent","Exactly."],["You","Great, thanks."]],question:"What is the best strategy after a complicated explanation?",answer:"Repeat the route in your own words and confirm it.",options:["Repeat the route in your own words and confirm it.","Pretend you understood and hope for the best.","Ask for every sentence to be translated."],formal:"I understand that the train is skipping my stop. Could you explain the simplest alternative route?",polite:"The sign says my stop is being skipped. What's the easiest way to get there?",casual:"Looks like this is skipping my stop. What's the easiest workaround?",slang:"So this is blowing past my stop—what's the easiest move?"},
 {icon:"💳",name:"OMNY",sign:"TAP & GO",situation:"You are at a turnstile and want to make sure you can pay with your contactless bank card or phone.",goal:"Ask a short question, then react when the screen turns green and says GO.",dialogue:[["You","Hi, can I just tap my contactless card here?"],["Agent","Yep. Tap it on the reader. When it turns green and says GO, you're good."],["You","Perfect—so I don't need to buy a separate ticket first?"],["Agent","That's right."],["You","Great, thanks."]],question:"Which modal sounds most normal for this everyday question?",answer:"Can: “Can I just tap my card here?”",options:["Can: “Can I just tap my card here?”","May: “May you tap my card?”","Should: “Should I can tap?”"],formal:"May I use a contactless bank card at this turnstile?",polite:"Can I just tap my contactless card here?",casual:"I can just tap my card here, right?",slang:"I can just tap and go here, right?"},
 {icon:"🚉",name:"Grand Central",sign:"GRAND CENTRAL–42 ST",situation:"You arrive at Grand Central and want to visit the Main Concourse, then continue to another Midtown attraction. The station is large and you do not want to follow the wrong exit.",goal:"Ask where the Main Concourse is and which exit is best for where you are going next.",dialogue:[["You","Excuse me, could you point me toward the Main Concourse?"],["Staff","Sure—go up those stairs and follow the signs."],["You","Thanks. And after that, which exit should I use for Vanderbilt Avenue?"],["Staff","Follow the Vanderbilt Avenue signs from the concourse."],["You","Perfect, thank you."]],question:"Why is “Could you point me toward…” useful here?",answer:"It is a polite, practical request for directions inside a large station.",options:["It is a polite, practical request for directions inside a large station.","It means the staff member must physically walk with you.","It is slang."],formal:"Could you please direct me to the Main Concourse and advise me which exit would be best afterwards?",polite:"Could you point me toward the Main Concourse? And which exit should I use afterwards?",casual:"Hi—where's the Main Concourse? And what's the best exit after that?",slang:"Hey, which way's the Main Concourse, and what's the best way out after?"},
 {icon:"📍",name:"Street + pickup",sign:"MIDTOWN PICKUP",situation:"You are leaving a busy Midtown attraction. Your rideshare driver cannot stop exactly where you are standing and messages that they are around the corner.",goal:"Clarify the pickup point using a landmark or intersection and confirm where you will meet.",dialogue:[["Driver","I can't stop right in front. I'm around the corner by the hotel entrance."],["You","Okay—do you mean the entrance on 42nd Street?"],["Driver","Yes, next to the hotel awning."],["You","Got it. I'll walk around the corner and meet you there in two minutes."],["Driver","Perfect."]],question:"What makes the confirmation effective?",answer:"You repeat a specific landmark/street and give a clear action.",options:["You repeat a specific landmark/street and give a clear action.","You only say “okay.”","You ask the driver to repeat everything three times."],formal:"Do you mean the hotel entrance on 42nd Street? If so, I will meet you there in approximately two minutes.",polite:"Do you mean the entrance on 42nd Street? Great—I'll meet you there in two minutes.",casual:"You mean the 42nd Street entrance? Got it—I'll be there in two minutes.",slang:"42nd Street entrance? Gotcha—I'll be there in two."}
];

const restaurantData={
 fine:{title:"Sophisticated restaurant",subtitle:"Polished, warm, never stiff",scene:"You arrive for dinner at a high-end Manhattan restaurant. The host is professional; the language is calm and efficient.",open:"Good evening. We have a reservation for 7:30 under Martin.",order:"I'd like the sea bass, please. Could you tell me what it comes with?",problem:"Excuse me, I think there may have been a small mix-up with my order.",finish:"Could we have the check when you have a moment, please?",tip:"“Hi” would not be rude here, but “Good evening” matches the setting beautifully. You do not need exaggerated formality.",dialogue:[["Host","Good evening. Welcome. Do you have a reservation?"],["You","Good evening. We have a reservation for 7:30 under Martin."],["Host","Of course. Right this way."],["Server","May I start you with something to drink?"],["You","Sparkling water, please. And I'd like the sea bass. Could you tell me what it comes with?"],["Server","It comes with roasted vegetables and a lemon butter sauce."],["You","That sounds perfect, thank you."],["You","Excuse me, I think there may have been a small mix-up with my order."],["Server","I'm very sorry. Let me take care of that right away."],["You","Thank you. And when you have a moment, could we have the check, please?"]]},
 casual:{title:"Everyday full-service restaurant",subtitle:"Friendly + straightforward",scene:"You walk into a good neighborhood restaurant. It is busy but relaxed.",open:"Hi! Do you have a table for two?",order:"I'll have the burger, please. Could I get the salad instead of fries?",problem:"Sorry, I think I got the wrong dish.",finish:"Could we get the check, please?",tip:"This is where “Hi” feels completely normal. Short requests + please + thanks = natural, polite English.",dialogue:[["Host","Hi! How are you? Two for dinner?"],["You","Hi, good, thanks. Yes—do you have a table for two?"],["Host","Sure. It'll just be a few minutes."],["Server","Can I get you something to drink?"],["You","Water's great, thanks. I'll have the burger. Could I get the salad instead of fries?"],["Server","Absolutely."],["You","Sorry, I think I got the wrong dish."],["Server","Oh, I'm sorry about that. I'll fix it."],["You","No problem, thanks. And could we get the check when you're ready?"]]},
 counter:{title:"Counter / fast-food / coffee",subtitle:"Short, efficient, still polite",scene:"There is a line behind you. The employee expects a quick order.",open:"Hi!",order:"Can I get a number three with fries and a small Coke, please?",problem:"Hi, sorry—I ordered this without onions.",finish:"That's everything, thanks.",tip:"At a counter, long openings can actually feel less natural. Be ready, be clear, say please/thanks, and keep the line moving.",dialogue:[["Employee","Hi. What can I get for you?"],["You","Hi, can I get a number three with fries and a small Coke, please?"],["Employee","Sure. Anything else?"],["You","No, that's everything, thanks."],["You","Hi, sorry—I ordered this without onions."],["Employee","No problem. We'll remake it."],["You","Perfect, thank you."]]}
};

const dialogues={
 street:{title:"Street · asking a stranger",lines:[["You","Excuse me—sorry to bother you. Do you know if this subway entrance goes downtown?"],["Local","Yeah, but if you're going to Brooklyn, I'd take the A from the next block."],["You","The A from the next block—got it. Is it that way?"],["Local","Yep, straight ahead, then left."],["You","Perfect. Thank you so much!"]],note:"Why it works: the opener acknowledges the interruption; the request is specific; you repeat the key information; you close warmly."},
 hotel:{title:"Hotel · everyday professional",lines:[["You","Hi! I have a reservation under Martin."],["Reception","Absolutely. Can I see a photo ID and the card you used to book?"],["You","Sure. Here you go."],["Reception","Thanks. Your room isn't quite ready yet, but we can hold your bags."],["You","That's perfect. About what time should I come back?"]],note:"Notice how “Hi!” is warm and completely normal in a professional service exchange."},
 restaurant:{title:"Restaurant · normal full-service",lines:[["Server","Hi, how are you guys doing tonight?"],["You","Good, thanks. How are you?"],["Server","Doing great. Can I start you off with something to drink?"],["You","Yes, please. I'll have sparkling water. And what would you recommend for a main course?"],["Server","The salmon's really popular."],["You","That sounds good. I'll go with that."]],note:"“How are you guys doing tonight?” is a service greeting, not a deep personal question. A short “Good, thanks—how are you?” is enough."},
 smalltalk:{title:"Small talk · natural follow-up",lines:[["Local","So, is this your first time in New York?"],["You","Yes, it is. I've been to the U.S. before, but never New York."],["Local","Oh, nice. What are you most excited to see?"],["You","Probably Central Park and the skyline. What about you—what's one place you never get tired of here?"],["Local","Honestly? Brooklyn Bridge Park at sunset."]],note:"The key is return: answer + one detail + a question back. That is how the conversation keeps moving."}
};

function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function speak(text,rate){if(!("speechSynthesis" in window)){alert("Speech synthesis is not supported in this browser.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=rate||parseFloat($("#speedSelect").value);const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==="en-US")||voices.find(v=>v.lang.startsWith("en"))||null;speechSynthesis.speak(u)}
function bindSpeak(root=document){$$('.speak',root).forEach(b=>b.onclick=()=>speak(b.dataset.text||b.textContent))}
function quizRender(target,data,stateKey,prefix){$(target).innerHTML=data.map((x,i)=>`<article class="quiz-card"><p><b>${i+1}.</b> ${x.q}</p><div class="options">${shuffle(x.o).map(o=>`<button class="option" data-i="${i}" data-v="${encodeURIComponent(o)}">${o}</button>`).join("")}</div><div id="${prefix}${i}" class="feedback"></div></article>`).join("");$$(`${target} .option`).forEach(b=>b.onclick=()=>{const i=+b.dataset.i,val=decodeURIComponent(b.dataset.v),ok=val===data[i].a;state[stateKey][i]=ok;const card=b.closest('.quiz-card');$$('.option',card).forEach(x=>{x.disabled=true;if(decodeURIComponent(x.dataset.v)===data[i].a)x.classList.add('correct')});if(!ok)b.classList.add('wrong');$('#'+prefix+i).textContent=ok?'✓ Correct for this meaning/register.':'Not quite. The highlighted answer best matches the intention.';$('#'+prefix+i).className='feedback '+(ok?'good':'bad');updateProgress()})}
function renderGreeting(){quizRender('#greetingQuiz',greetingData,'greet','gf')}
function renderModalQuiz(){quizRender('#modalQuiz',modalData,'modal','mf')}
function safeImgError(){return `onerror="this.onerror=null;${'this.src=\''}${BOW_FALLBACK}${'\''}"`}
function renderPlaces(){
 $('#placeTabs').innerHTML=places.map((p,i)=>`<button class="place-tab ${i===state.place?'active':''}" data-i="${i}">${p.icon} ${p.name}</button>`).join('');const p=places[state.place];
 const fallback=p.fallback?` onerror="this.onerror=null;this.src='${p.fallback}'"`:'';
 $('#placeStage').innerHTML=`<article class="place-card"><div class="place-photo"><img src="${p.photo}"${fallback} alt="${p.title}"><span class="photo-credit">Photo: ${p.credit}</span></div><div class="place-content"><p class="micro">REAL PLACE / SIMPLE REVIEW ENGLISH</p><h3>${p.title}</h3><div class="place-vocab"><h4>Learn these words first</h4><div class="place-vocab-grid">${p.vocab.map(v=>`<span><b>${v[0]}</b><small>${v[1]}</small></span>`).join('')}</div></div><div class="simple-fact"><b>What to know</b><p>${p.facts}</p></div><div class="review-pair"><div class="review-box positive"><b>👍 What visitors like</b><p>${p.positive}</p></div><div class="review-box critical"><b>⚠ What some visitors don't like</b><p>${p.critical}</p></div></div><div class="opinion-frame"><b>Your interpretation</b><p>${p.prompt}</p><textarea rows="4" class="place-answer" placeholder="Give your real opinion..."></textarea><div class="place-register-models practice-support"><details class="formal"><summary>Formal</summary><p>${p.formal}</p></details><details class="polite"><summary>Polite everyday</summary><p>${p.polite}</p></details><details class="casual"><summary>Casual</summary><p>${p.casual}</p></details><details class="slang"><summary>Slang / very casual</summary><p>${p.slang}</p></details></div></div></div></article>`;
 $$('.place-tab').forEach(b=>b.onclick=()=>{state.place=+b.dataset.i;renderPlaces()});
}
function renderReviewFill(){
 $('#reviewFill').innerHTML=reviewFill.map((x,i)=>`<article class="fill-item"><p>${i+1}. ${x.s}</p><div class="review-actions"><input id="rf${i}" autocomplete="off"><button class="primary review-check" data-i="${i}">Check</button><button class="secondary review-hint practice-support" data-i="${i}">Hint</button></div><div id="rh${i}" class="hint-line hidden">Hint: ${x.hint}</div><div id="rff${i}" class="feedback"></div></article>`).join('');
 $$('.review-check').forEach(b=>b.onclick=()=>{let i=+b.dataset.i,val=$('#rf'+i).value.trim().toLowerCase().replace(/[.!?]/g,''),ok=val===reviewFill[i].a;state.fill[i]=ok;$('#rff'+i).textContent=ok?'✓ Correct — that is the natural review expression.':`✗ Not yet. Try again${state.mode==='practice'?' or use the Hint button.':'.'}`;$('#rff'+i).className='feedback '+(ok?'good':'bad');updateProgress()});
 $$('.review-hint').forEach(b=>b.onclick=()=>$('#rh'+b.dataset.i).classList.toggle('hidden'));
}
function renderSort(){
 $('#sortBank').innerHTML=shuffle(sortTokens).map(([t,c])=>`<button class="token" draggable="true" data-cat="${c}" data-text="${encodeURIComponent(t)}">${t}</button>`).join('');
 $$('.token').forEach(t=>{t.onclick=()=>{const z=$$('.register-drop').find(x=>x.dataset.cat===t.dataset.cat);if(z)z.appendChild(t)};t.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',t.dataset.text))});
 $$('.register-drop').forEach(z=>{z.addEventListener('dragover',e=>e.preventDefault());z.addEventListener('drop',e=>{e.preventDefault();const v=e.dataTransfer.getData('text/plain');const t=$$('.token').find(x=>x.dataset.text===v);if(t)z.appendChild(t)})});
 $('#checkSort').onclick=()=>{let all=true;$$('.register-drop').forEach(z=>$$('.token',z).forEach(t=>{if(t.dataset.cat!==z.dataset.cat)all=false}));const placed=$$('.register-drop .token').length===sortTokens.length;state.sort=all&&placed;$('#sortFeedback').textContent=state.sort?'✓ Excellent. Natural does not mean slang.':'Not yet. Make sure every expression is placed, then check the register.';$('#sortFeedback').className='feedback '+(state.sort?'good':'bad');updateProgress()}
}
function renderNavVocab(){
 const cat=$('#navVocabCategory').value;
 $('#navVocabGrid').innerHTML=navVocab[cat].map(v=>`<article><b>${v[0]}</b><span>${v[1]}</span><small>${v[2]}</small><button class="secondary nav-vocab-audio" data-text="${encodeURIComponent(v[0]+'. '+v[2])}">🔊 Listen</button></article>`).join('');
 $$('.nav-vocab-audio').forEach(b=>b.onclick=()=>speak(decodeURIComponent(b.dataset.text),.9));
}

function renderNavigation(){
 $('#navigationTabs').innerHTML=navigationData.map((n,i)=>`<button class="navigation-tab ${i===state.navigation?'active':''}" data-i="${i}">${n.icon} ${n.name}</button>`).join('');const n=navigationData[state.navigation];
 $('#navigationStage').innerHTML=`<div class="navigation-stage"><div class="nav-situation"><div class="nav-sign"><p class="micro">REAL NYC PROBLEM</p><span class="route-badge">${n.icon}</span><h3>${n.sign}</h3><p>${n.situation}</p><b>Your goal:</b><p>${n.goal}</p></div><div class="nav-content"><h3>What the conversation can actually sound like</h3><div class="visible-dialogue">${n.dialogue.map(x=>`<div class="line"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div><button class="secondary nav-audio">▶ Hear full dialogue</button><h4>Same intention, different register</h4><div class="nav-registers practice-support"><div><b>Formal</b><span>${n.formal}</span></div><div><b>Polite everyday</b><span>${n.polite}</span></div><div><b>Casual</b><span>${n.casual}</span></div><div><b>Slang / very casual</b><span>${n.slang}</span></div></div><div class="quiz-card nav-q"><p><b>Quick check:</b> ${n.question}</p><div class="options">${shuffle(n.options).map(o=>`<button class="option nav-option" data-v="${encodeURIComponent(o)}">${o}</button>`).join('')}</div><div class="feedback" id="navFeedback"></div></div></div></div></div>`;
 $('.nav-audio').onclick=()=>speak(n.dialogue.map(x=>x[1]).join(' '),.96);
 $$('.nav-option').forEach(b=>b.onclick=()=>{const val=decodeURIComponent(b.dataset.v),ok=val===n.answer;state.nav[state.navigation]=ok;$$('.nav-option').forEach(x=>{x.disabled=true;if(decodeURIComponent(x.dataset.v)===n.answer)x.classList.add('correct')});if(!ok)b.classList.add('wrong');$('#navFeedback').textContent=ok?'✓ Exactly.':'Not quite. The highlighted answer is the safer strategy.';$('#navFeedback').className='feedback '+(ok?'good':'bad');updateProgress()});
 $$('.navigation-tab').forEach(b=>b.onclick=()=>{state.navigation=+b.dataset.i;renderNavigation()});
}
function renderRestaurant(){
 const r=restaurantData[state.restaurant];
 $('#restaurantStage').innerHTML=`<div class="restaurant-stage"><div class="restaurant-scene ${state.restaurant}"><p class="micro">${r.subtitle}</p><h3>${r.title}</h3><p>${r.scene}</p><div class="register-stack"><span><b>Opening</b> ${r.open}</span><span><b>Ordering</b> ${r.order}</span><span><b>Small problem</b> ${r.problem}</span><span><b>Finishing</b> ${r.finish}</span></div><p><b>Why this register works:</b> ${r.tip}</p></div><div class="restaurant-dialogues"><div class="restaurant-script"><h4>Full dialogue — read it before you listen</h4>${r.dialogue.map(x=>`<div class="line ${x[0]==='You'?'you':''}"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div><button class="secondary restaurant-audio">▶ Hear the full dialogue</button><label><b>Now make it yours</b><textarea rows="6" placeholder="Change the food, problem or request and practise it aloud..."></textarea></label><label>Speaking score / 10 <input type="number" min="0" max="10" class="restaurant-score"></label></div></div>`;
 $('.restaurant-audio').onclick=()=>speak(r.dialogue.map(x=>x[1]).join(' '),.95)
}
function renderDialogue(){
 const d=dialogues[state.dialogue];
 const yourLines=d.lines.filter(x=>x[0]==='You').map(x=>x[1]);
 $('#dialogueStage').innerHTML=`<div class="dialogue-stage"><p class="micro">${d.title}</p><div class="dialogue-layout"><div><h3>Full conversation</h3><div class="dialogue-script">${d.lines.map(x=>`<div class="dialogue-line ${x[0]==='You'?'you-line':''}"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div></div><aside class="your-speech"><p class="micro">WHAT YOU SHOULD PRACTISE</p><h3>Your natural travel version</h3>${yourLines.map((line,i)=>`<div class="your-line"><span>${i+1}</span><p>${line}</p><button class="secondary your-line-audio" data-text="${encodeURIComponent(line)}">🔊</button></div>`).join('')}<div class="reuse-box"><b>Why these lines work</b><p>${d.note}</p></div></aside></div><div class="dialogue-actions"><button class="primary play-dialogue">▶ Natural speed</button><button class="secondary play-dialogue-slow">▶ Clear speed</button></div></div>`;
 const full=d.lines.map(x=>x[1]).join(' ');$('.play-dialogue').onclick=()=>speak(full,.98);$('.play-dialogue-slow').onclick=()=>speak(full,.78);$$('.your-line-audio').forEach(b=>b.onclick=()=>speak(decodeURIComponent(b.dataset.text),.92));
}
function initTimer(){let n=90,int=null;const paint=()=>$('#timer').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;$('#timerStart').onclick=()=>{if(int)return;int=setInterval(()=>{n--;paint();if(n<=0){clearInterval(int);int=null;speak('Time is up.',.9)}},1000)};$('#timerReset').onclick=()=>{clearInterval(int);int=null;n=90;paint()};paint()}
function updateProgress(){const textIds=['interpretAnswer','compareAnswer','reformulateAnswer','oralNotes','finalAnswer','naturalNow','nextFocus'];const texts=textIds.filter(id=>$('#'+id).value.trim()).length;const evals=$$('.eval').filter(x=>x.value).length;const completed=Object.keys(state.greet).length+Object.keys(state.modal).length+Object.keys(state.fill).length+Object.keys(state.nav).length+(state.sort?1:0)+texts+evals;const total=4+6+4+6+1+7+6;const pct=Math.min(100,Math.round(completed/total*100));$('#progressBar').style.width=pct+'%';$('#progressText').textContent=pct+'% complete'}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toolkit(){return `NEW YORK REAL TALK · QUICK TOOLKIT\n\nGREETINGS\nHi = everyday friendly default\nHey = more casual / familiar\nExcuse me = polite attention-getter\nSorry to bother you = extra softener, not obligatory\n\nMODALS\ncan + base verb = ability / possibility / everyday request\ncould + base verb = softer request / possibility / past ability\nshould + base verb = advice / recommended choice\nmay + base verb = permission / possibility, often more formal\n\nGETTING AROUND\n• Does this entrance go uptown too?\n• Does this express stop at 79th, or should I wait for the local?\n• The sign says my stop is being skipped. What's the easiest way to get there?\n• Can I just tap my contactless card here?\n• Could you point me toward the Main Concourse?\n• Do you mean the entrance on 42nd Street?\n\nRECOVERY\n• Sorry, I didn't catch that.\n• Did you say 42nd Street?\n• So I need to take the A, right?\n• Could you say that a little more slowly?\n`}
function report(){const labels=['Choose greeting register appropriately','Explain pragmatic politeness','Distinguish everyday English from slang','Adjust restaurant register','Interpret and compare reviews','Reformulate rather than translate'];const evals=$$('.eval').map((e,i)=>`<li>${labels[i]}: <b>${e.value||'Not completed'}</b></li>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>NY Real Talk Report</title><style>body{font-family:Arial;max-width:850px;margin:40px auto;line-height:1.5}h1{color:#a91422}section{border:1px solid #ddd;padding:16px;margin:12px 0;border-radius:12px}</style></head><body><h1>New York Real Talk · Lesson Report</h1><section><h2>Interactive practice</h2><p>Greeting/register: ${Object.values(state.greet).filter(Boolean).length}/4</p><p>Modal grammar: ${Object.values(state.modal).filter(Boolean).length}/6</p><p>Review vocabulary: ${Object.values(state.fill).filter(Boolean).length}/4</p><p>NYC navigation checks: ${Object.values(state.nav).filter(Boolean).length}/6</p><p>Register sorting: ${state.sort?'Complete':'Not complete'}</p></section><section><h2>Scores</h2><p>Timed oral: ${$('#oralScore').value||'—'}/10</p><p>Final mission: ${$('#finalScore').value||'—'}/10</p></section><section><h2>Self-evaluation</h2><ul>${evals}</ul></section><section><h2>Reflection</h2><p><b>Now feels natural:</b><br>${($('#naturalNow').value||'—').replaceAll('<','&lt;')}</p><p><b>Next focus:</b><br>${($('#nextFocus').value||'—').replaceAll('<','&lt;')}</p></section></body></html>`}
function init(){
 $('#jsWarning').style.display='none';bindSpeak();$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
 $('#modeSelect').onchange=e=>{state.mode=e.target.value;document.body.classList.toggle('lilate-mode',e.target.value==='lilate')};$('#navVocabCategory').onchange=renderNavVocab;$('#resetBtn').onclick=()=>{if(confirm('Reset all lesson progress?'))location.reload()};
 $$('.hint-btn').forEach(b=>b.onclick=()=>$('#'+b.dataset.hint).classList.toggle('hidden'));
 $$('.restaurant-tab').forEach(b=>b.onclick=()=>{$$('.restaurant-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.restaurant=b.dataset.r;renderRestaurant()});
 $$('.dialogue-tab').forEach(b=>b.onclick=()=>{$$('.dialogue-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.dialogue=b.dataset.d;renderDialogue()});
 ['interpretAnswer','compareAnswer','reformulateAnswer','oralNotes','finalAnswer','naturalNow','nextFocus'].forEach(id=>$('#'+id).addEventListener('input',updateProgress));$$('.eval').forEach(e=>e.addEventListener('change',updateProgress));
 $('#downloadToolkit').onclick=()=>download('NY_Real_Talk_Toolkit.txt',toolkit());$('#downloadReport').onclick=()=>download('NY_Real_Talk_Results.html',report(),'text/html');$('#printBtn').onclick=()=>window.print();
 renderGreeting();renderModalQuiz();renderPlaces();renderReviewFill();renderSort();renderNavVocab();renderNavigation();renderRestaurant();renderDialogue();initTimer();updateProgress();
}
document.addEventListener('DOMContentLoaded',init);
