'use strict';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const STORAGE_KEY='eden_lesson_6_leading_the_team_v1';
let voices=[]; let activeTimer=null; let speechToken=0;

const sectionMeta={
  flight:['Team leadership mission understood','Trainer observation'],
  vocab:['Team leadership vocabulary','Reference / self-check'],
  care:['CARE feedback framework','Written + oral'],
  grammar:['Conditionals for consequences & suggestions','Automatic + oral'],
  delegation:['Delegation clarity','Written + oral'],
  language:['Firm and warm language bank','Automatic + oral'],
  presence:['Tone and presence in feedback','Oral observation'],
  pressure:['Team pressure lab','Oral + self-rubric'],
  emotions:['Managing emotional reactions','Automatic + oral'],
  motivation:['Recognition and motivation','Oral'],
  reporting:['Reporting up on team conversations','Oral'],
  cloe:['CLOE spontaneous interaction','Oral'],
  mission:['Full team conversation simulation','Oral + rubric'],
  takeaway:['Personal leadership rule','Reflection']
};

const VOCAB=[
  ['feedback','💬','constructive feedback','retour constructif','feedback focused on specific behaviour and improvement, not personal criticism','I want to give you some constructive feedback about the report.'],
  ['feedback','💬','specific behaviour','comportement précis','the exact observable action, not a general trait or personality judgement','Let’s focus on specific behaviour rather than general impressions.'],
  ['feedback','💬','to acknowledge','reconnaître','to recognise something openly, especially effort or a valid point','I want to acknowledge the effort you put into this deadline.'],
  ['feedback','💬','to address (an issue)','traiter (un problème)','to deal with a problem directly and openly instead of avoiding it','We need to address the recurring delays in your reports.'],
  ['feedback','💬','root cause','cause profonde','the real underlying reason for a problem, not just the visible symptom','Let’s identify the root cause before we discuss solutions.'],
  ['delegation','📋','to delegate','déléguer','to give a task and the authority to complete it to someone else','I’d like to delegate the supplier review to you.'],
  ['delegation','📋','ownership','responsabilité / appropriation','full responsibility for a task, including the decisions inside it','I want you to take full ownership of this validation report.'],
  ['delegation','📋','to hand over','transmettre / passer le relais','to formally transfer a task or responsibility to someone else','I’ll hand over the customer file to you from Monday.'],
  ['delegation','📋','level of autonomy','niveau d’autonomie','how much independence someone has to decide without checking back first','What level of autonomy do you need on this task?'],
  ['delegation','📋','check-in point','point d’étape','a planned moment to review progress together','Let’s set a check-in point for Wednesday.'],
  ['coaching','🌱','to unlock potential','révéler le potentiel','to help someone develop abilities they already have','My role is to unlock the team’s potential, not just assign tasks.'],
  ['coaching','🌱','growth area','axe de progression','a specific skill or behaviour someone is working to improve','Time management is a growth area we identified together.'],
  ['coaching','🌱','to reflect on','réfléchir à / prendre du recul sur','to think carefully about an experience in order to learn from it','Take a moment to reflect on what happened in that meeting.'],
  ['coaching','🌱','open-ended question','question ouverte','a question that invites a full answer, not a simple yes or no','Ask an open-ended question instead of giving the answer directly.'],
  ['coaching','🌱','to follow up','assurer un suivi','to check progress again after an initial conversation','I’ll follow up with you again next week.'],
  ['difficult','⚠️','to stay composed','rester posé(e) / garder son calme','to remain calm and controlled, even under emotional pressure','It’s important to stay composed if the conversation becomes tense.'],
  ['difficult','⚠️','defensive reaction','réaction défensive','a response that protects rather than listens, often from feeling attacked','Try not to trigger a defensive reaction by starting with blame.'],
  ['difficult','⚠️','to de-escalate','désamorcer','to reduce the tension or intensity of a situation','Pausing for a moment can help de-escalate the conversation.'],
  ['difficult','⚠️','underlying concern','préoccupation sous-jacente','the real worry behind what someone is saying','There may be an underlying concern behind his resistance to the new process.'],
  ['difficult','⚠️','to hold your ground','tenir sa position','to remain firm on a decision or standard without becoming aggressive','You can hold your ground without raising your voice.'],
  ['motivation','⭐','to recognise (contribution)','reconnaître (une contribution)','to publicly or privately acknowledge someone’s positive contribution','I want to recognise your work on the interface issue.'],
  ['motivation','⭐','sense of purpose','sentiment d’utilité','the feeling that one’s work matters and connects to a larger goal','Reminding the team of the bigger picture builds a sense of purpose.'],
  ['motivation','⭐','to reassure','rassurer','to reduce someone’s worry or doubt','I reassured the team that the timeline was still realistic.'],
  ['motivation','⭐','momentum','dynamique / élan','a sense of forward progress that motivates continued effort','We need to keep the momentum going after this milestone.'],
  ['motivation','⭐','to empower','responsabiliser / donner les moyens','to give someone the confidence and authority to act independently','Delegating this decision will empower her to lead the next phase.']
];
const CATEGORY_LABELS={feedback:'💬 Feedback',delegation:'📋 Delegation',coaching:'🌱 Coaching',difficult:'⚠️ Difficult conversations',motivation:'⭐ Motivation'};

const scenarios=[
  {q:'A senior engineer becomes defensive when you point out a repeated documentation gap: “I’ve been doing this for fifteen years. I know what I’m doing.”',ctx:'The reaction protects his competence rather than engaging with the specific gap.',coach:'Acknowledge the experience first, then separate the specific behaviour from his overall competence. Stay anchored to CARE: context, action, result, expectation.',b2:'I’m not questioning your experience — it’s one of the reasons I trust you with this scope. In the last two reports, the traceability section was missing, and that means the auditor cannot follow the evidence. Going forward, I need that section completed before you send the report to me.',c1:'Your experience is exactly why I want to flag this directly rather than let it slide. In the last two reports, the traceability section was missing, which puts the audit trail at risk. I’d like us to agree on a quick self-check before submission so this doesn’t happen again.'},
  {q:'One of your engineers has missed three internal deadlines this month, each with a different excuse.',ctx:'The pattern matters more than any single excuse.',coach:'Name the pattern, not the individual excuses. Ask for their view of the root cause before proposing a fix.',b2:'I’ve noticed three missed deadlines this month, and each time the reason has been different. I’d like to understand what’s really behind that. What do you think is making it difficult to plan your time at the moment?',c1:'I want to talk about a pattern rather than any single deadline. Three deliverables have slipped this month for different stated reasons, and that suggests something structural rather than one-off. Before I propose anything, I’d like to hear your read on what’s actually driving it.'},
  {q:'An engineer promises another team’s lead that a task will be ready by Friday, without checking with you first — and you know it will not be ready.',ctx:'The commitment was made publicly and needs to be corrected without undermining him in front of the other team.',coach:'Correct the commitment calmly and quickly with the other team, then address the behaviour privately afterwards — not in front of them.',b2:'Thanks for wanting to help — I just need to adjust that. Realistically it will be ready Tuesday, not Friday, so let me confirm that with the other team. Afterwards, when you’re not sure of a date, check with me first so we always give one clear answer.',c1:'I appreciate the intent, but let’s correct that commitment now so the other team isn’t planning around a date we can’t hit — Tuesday is realistic. Separately, I’d like external commitments on dates to come through me first, so we stay consistent.'},
  {q:'Two engineers on your team have stopped speaking directly to each other and are routing everything through email, which is slowing the project down.',ctx:'The relationship has broken down, and the work is starting to suffer.',coach:'Bring both people together rather than mediating separately. Keep the focus on the impact on the work, not on who is right.',b2:'I’ve noticed the interface decisions are taking longer because they’re going through email instead of a conversation. I’d like the three of us to sit down together this week — not to decide who’s right, but to agree how we’ll work together going forward.',c1:'The current pattern is slowing the interface decisions down, and that’s the part I need to fix regardless of the history between you. I’d like a short session with both of you this week focused only on how we communicate from here, not on the past disagreement.'},
  {q:'You need to delegate a customer-facing task to an engineer who has been at the company far longer than you and has more technical depth.',ctx:'The seniority gap could make the delegation feel awkward if it is handled poorly.',coach:'Frame the delegation around your coordination role and their expertise, not around hierarchy. Be clear about the outcome and deadline, and leave the method to them.',b2:'I’d like you to take the lead on the customer call about the interface issue — you know the history better than anyone. What I need is a clear position we can defend by Thursday. How you get there is entirely up to you.',c1:'This one makes more sense coming from you given the depth of history you have with the customer. My role is to make sure it lands with a clear, defensible position by Thursday — the approach is yours to decide.'},
  {q:'A team member who works remotely rarely speaks in meetings and their camera is usually off. You are not sure whether they are struggling or simply prefer to work quietly.',ctx:'You do not have enough information yet to know what is really happening.',coach:'Check in privately rather than raise it in the group. Ask an open question and avoid assuming the cause.',b2:'I wanted to check in with you one to one rather than in the group meeting. I’ve noticed you’re quieter than the rest of the team in our calls, and I just wanted to ask how things are going for you at the moment.',c1:'I’d rather ask this privately than put you on the spot in the team meeting. I’ve noticed you’re less present in our calls recently, and before I assume anything, I wanted to check how things are going from your side.'},
  {q:'An engineer explains a missed requirement by saying “nobody told me”, when in fact the information was in the shared documentation from the start.',ctx:'The explanation is not accurate, but a public correction could feel like an accusation.',coach:'Address the specific gap calmly and check the process rather than the person’s honesty. Refocus on the fix.',b2:'I hear that it didn’t reach you — it was in the shared documentation from the start, so let’s look at why it didn’t land. For now, the priority is closing the gap; afterwards we can agree how requirements get confirmed with the team.',c1:'Let’s separate two things: the requirement was documented from day one, so I want to understand where the process broke down for you specifically, not assign blame. Right now, closing the gap is the priority; the process question comes after.'},
  {q:'Your strongest engineer has taken on several extra tasks without being asked, and you are starting to see the quality of their work drop.',ctx:'The person is a high performer, and the conversation needs to open with recognition, not concern.',coach:'Recognise the contribution before raising the concern. Ask directly about workload rather than assuming they want less responsibility.',b2:'I want to start by saying how much I value everything you’ve taken on recently — it hasn’t gone unnoticed. I have also noticed a few things slipping in the last two weeks, and I wanted to check honestly: is the current workload sustainable for you?',c1:'Before anything else, I want to acknowledge how much you’ve absorbed over the last month — it’s made a real difference. I have noticed a dip in a couple of deliverables recently, and I’d rather ask directly than guess: how is the current load, honestly?'}
];

function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function normalise(s){return String(s||'').trim().toLowerCase().replace(/[’]/g,"'").replace(/\s+/g,' ')}
function statusLabel(v){return ({'not-started':'Non commencé','progress':'En cours','achieved':'Acquis','not-achieved':'Non acquis'})[v]||v}
function statusClass(v){return v||'not-started'}
function textFromElement(el){if(!el)return'';if('value' in el && /^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName))return el.value;return el.textContent||''}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>toast('Copied.')).catch(()=>fallbackCopy(text))}
function fallbackCopy(text){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied.')}
function downloadText(filename,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function escapeAttr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}

function initNavigation(){$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'})));$('#printPage').onclick=()=>window.print()}

function populateVoices(){if(!('speechSynthesis' in window))return;voices=speechSynthesis.getVoices();const lang=$('#accentSelect').value.toLowerCase();let options=voices.map((v,i)=>({v,i})).filter(x=>(x.v.lang||'').toLowerCase().startsWith(lang));if(!options.length)options=voices.map((v,i)=>({v,i}));$('#voiceSelect').innerHTML=options.map(x=>`<option value="${x.i}">${x.v.name} (${x.v.lang})</option>`).join('')||'<option value="">Default voice</option>'}
function speechSettings(style='natural'){return {natural:[.94,1],calm:[.84,.98],firm:[.88,.94],brisk:[1.07,1.02],slow:[.76,.98]}[style]||[.94,1]}
function makeUtterance(text,style='natural'){const u=new SpeechSynthesisUtterance(text.replace(/\s+/g,' ').trim());const idx=Number($('#voiceSelect').value);if(voices[idx])u.voice=voices[idx];u.lang=$('#accentSelect').value;const [rate,pitch]=speechSettings(style);u.rate=rate;u.pitch=pitch;return u}
function speakPlan(steps,style='natural'){if(!('speechSynthesis' in window)){toast('Text-to-speech is not supported in this browser.');return}speechSynthesis.cancel();const token=++speechToken;let i=0;const run=()=>{if(token!==speechToken||i>=steps.length)return;const step=steps[i++];if(step.type==='pause'){setTimeout(run,step.ms||650);return}const text=(step.text||'').trim();if(!text){run();return}const u=makeUtterance(text,style);u.onend=run;u.onerror=run;speechSynthesis.speak(u)};run()}
function speechPlanFromElement(el){if(!el)return[];if(/^(INPUT|TEXTAREA)$/.test(el.tagName))return[{type:'text',text:el.value||''}];const steps=[];let buffer='';const flush=()=>{const t=buffer.replace(/\s+/g,' ').trim();if(t)steps.push({type:'text',text:t});buffer=''};const walk=node=>{if(node.nodeType===Node.TEXT_NODE){buffer+=' '+node.textContent;return}if(node.nodeType!==Node.ELEMENT_NODE)return;const e=node;if(e.classList.contains('speech-cue')){flush();if(e.classList.contains('pause'))steps.push({type:'pause',ms:850});return}Array.from(e.childNodes).forEach(walk)};Array.from(el.childNodes).forEach(walk);flush();return steps}
function initAudio(){populateVoices();if('speechSynthesis' in window)speechSynthesis.onvoiceschanged=populateVoices;$('#accentSelect').addEventListener('change',populateVoices);$('#refreshVoices').onclick=populateVoices;$('#audioTest').onclick=()=>speakPlan([{type:'text',text:'Audio check. Your selected English voice is ready.'}]);$('#stopAudio').onclick=()=>{speechToken++;speechSynthesis?.cancel()};document.addEventListener('click',e=>{const b=e.target.closest('[data-speak-text],[data-speak-id]');if(!b)return;const style=b.dataset.style||'natural';if(b.dataset.speakId){const el=$('#'+b.dataset.speakId);speakPlan(speechPlanFromElement(el),style)}else speakPlan([{type:'text',text:b.dataset.speakText||''}],style)})}

function initToggles(){const fr=$('#toggleFrench'),models=$('#toggleModels');fr.onclick=()=>{const currentlyVisible=$$('.fr-support').some(x=>!x.classList.contains('hidden'));$$('.fr-support').forEach(x=>x.classList.toggle('hidden',currentlyVisible));fr.textContent=currentlyVisible?'Show French support':'Hide French support'};models.onclick=()=>{const details=$$('details.model-block');const allOpen=details.length&&details.every(d=>d.open);details.forEach(d=>d.open=!allOpen);models.textContent=allOpen?'Show all models':'Hide all models'}}

function shuffleChildren(parent){const arr=Array.from(parent.children);for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}arr.forEach(x=>parent.appendChild(x))}
function initChoices(){$$('[data-shuffle-group] .choice-list').forEach(shuffleChildren);document.addEventListener('click',e=>{const btn=e.target.closest('.choice-list button');if(!btn)return;const card=btn.closest('.instant-card');if(card.dataset.locked==='true')return;card.dataset.locked='true';$$('.choice-list button',card).forEach(b=>{b.disabled=true;if(b.dataset.correct==='true')b.classList.add('correct')});const ok=btn.dataset.correct==='true';btn.classList.add(ok?'correct':'incorrect');card.dataset.result=ok?'correct':'incorrect';const fb=$('.feedback',card);fb.textContent=ok?'✓ Correct — strong team leadership communication.':'✗ Not quite — the stronger response is highlighted.';fb.className='feedback '+(ok?'correct':'incorrect');updateProgress();autoSave()})}

function initGrammar(){$$('.grammar-quiz article').forEach(card=>{const check=$('.check-gap',card),input=$('input',card),hint=$('.hint',card),hintText=$('.hint-text',card);check.onclick=()=>{const ok=normalise(input.value)===normalise(card.dataset.answer);card.dataset.result=ok?'correct':'incorrect';const fb=$('.feedback',card);fb.textContent=ok?'✓ Correct.':`✗ Try again. Correct form: ${card.dataset.answer}`;fb.className='feedback '+(ok?'correct':'incorrect');updateProgress();autoSave()};hint.onclick=()=>{hintText.textContent=hint.dataset.hint;hintText.classList.toggle('hidden')}})}

function initBuilder(){const fields=$$('#careBuilder [data-builder]');const output=$('#careOutput');const update=()=>{const vals=fields.map(x=>x.value.trim()).filter(Boolean);output.textContent=vals.length?vals.join(' '):'Your complete CARE message will appear here.'};fields.forEach(x=>x.addEventListener('input',()=>{update();autoSave()}));$('#copyCare').onclick=()=>copyText(output.textContent);$('#clearCare').onclick=()=>{fields.forEach(x=>x.value='');update();autoSave()};update()}

function initDelegationBuilder(){const fields=$$('#delegationBuilder [data-builder]');const output=$('#delegationOutput');const update=()=>{const vals=fields.map(x=>x.value.trim()).filter(Boolean);output.textContent=vals.length?vals.join(' '):'Your complete delegation message will appear here.'};fields.forEach(x=>x.addEventListener('input',()=>{update();autoSave()}));$('#copyDelegation').onclick=()=>copyText(output.textContent);$('#clearDelegation').onclick=()=>{fields.forEach(x=>x.value='');update();autoSave()};update()}

function initTimers(){document.addEventListener('click',e=>{const btn=e.target.closest('.timer-btn');if(!btn)return;if(activeTimer)clearInterval(activeTimer);let remaining=Number(btn.dataset.seconds)||30;const line=btn.closest('.timer-line');const display=$('.timer-display',line);const render=()=>{const m=Math.floor(remaining/60),s=remaining%60;display.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};render();btn.disabled=true;activeTimer=setInterval(()=>{remaining--;render();if(remaining<=0){clearInterval(activeTimer);activeTimer=null;btn.disabled=false;toast('Time. Land the sentence.')}},1000)})}

function initRecorders(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$$('.recorder').forEach(r=>{$('.rec-status',r).textContent='Recording is not supported in this browser.'});return}$$('.recorder').forEach(r=>{let recorder=null,chunks=[],stream=null;const start=$('.startRec',r),stop=$('.stopRec',r),audio=$('.playback',r),link=$('.downloadRec',r),status=$('.rec-status',r);start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});const url=URL.createObjectURL(blob);audio.src=url;audio.classList.remove('hidden');link.href=url;link.classList.remove('hidden');stream?.getTracks().forEach(t=>t.stop());r.classList.remove('recording');status.innerHTML='<span class="recording-light"></span> Recorded';start.disabled=false;stop.disabled=true};recorder.start();r.classList.add('recording');status.innerHTML='<span class="recording-light"></span> Recording…';start.disabled=true;stop.disabled=false}catch(err){toast('Microphone permission was not available.')}};stop.onclick=()=>{if(recorder&&recorder.state!=='inactive')recorder.stop()}})}

function initScenarios(){let current=-1;const pick=()=>{let next=Math.floor(Math.random()*scenarios.length);if(scenarios.length>1&&next===current)next=(next+1)%scenarios.length;current=next;const s=scenarios[current];$('#scenarioPrompt').textContent=s.q;$('#scenarioContext').textContent=s.ctx;$('#scenarioCoach').classList.add('hidden');$('#revealScenarioCoach').disabled=false};$('#newScenario').onclick=pick;$('#revealScenarioCoach').onclick=()=>{const s=scenarios[current];if(!s)return;$('#coachText').textContent=s.coach;$('#scenarioB2').textContent=s.b2;$('#scenarioC1').textContent=s.c1;$('#scenarioCoach').classList.remove('hidden')};$$('#pressureRubric input[type=checkbox]').forEach(c=>c.addEventListener('change',()=>{updatePressureScore();autoSave()}))}
function updatePressureScore(){const n=$$('#pressureRubric input[type=checkbox]:checked').length;$('#pressureScore').textContent=n;updateProgress()}

function initCloe(){$$('.reveal-cloe').forEach(b=>b.onclick=()=>$('#'+b.dataset.target).classList.toggle('hidden'))}
function initSurprises(){$$('.surprise-btn').forEach(b=>b.onclick=()=>{$('#surpriseDisplay').textContent=b.dataset.surprise})}
function initFinalRubric(){$$('[data-final-rubric]').forEach(s=>s.addEventListener('change',()=>{updateFinalScore();autoSave()}));updateFinalScore()}
function updateFinalScore(){const total=$$('[data-final-rubric]').reduce((a,s)=>a+Number(s.value||0),0);$('#integrationScore').textContent=total;updateProgress()}

function renderVocab(){
  const filter=$('#vocabFilter').value;
  const rows=VOCAB.filter(v=>filter==='all'||v[0]===filter);
  $('#vocabGrid').innerHTML=rows.map(v=>`<article class="vocab-card">
    <span class="tag">${v[1]} ${CATEGORY_LABELS[v[0]].replace(/^\S+\s/,'')}</span>
    <h3>${v[2]}</h3>
    <p class="translation"><strong>FR:</strong> ${v[3]}</p>
    <p class="definition"><strong>Meaning:</strong> ${v[4]}</p>
    <p class="sentence">${v[5]}</p>
    <div class="audio-row">
      <button class="speak secondary" data-speak-text="${escapeAttr(v[2])}" data-style="firm">🔊 Word / phrase</button>
      <button class="speak" data-speak-text="${escapeAttr(v[5])}" data-style="calm">🔊 Sentence</button>
    </div>
  </article>`).join('');
}
function initVocab(){renderVocab();$('#vocabFilter').addEventListener('change',renderVocab)}

function assignSaveKeys(){$$('input,textarea,select').forEach((el,i)=>{if(!el.dataset.saveKey)el.dataset.saveKey=el.id||`field_${i}`})}
function serializeState(){const fields={};$$('[data-save-key]').forEach(el=>{if(el.type==='checkbox')fields[el.dataset.saveKey]=el.checked;else fields[el.dataset.saveKey]=el.value});const cards={};$$('.instant-card,.grammar-quiz article').forEach((el,i)=>cards[`card_${i}`]=el.dataset.result||'');const sectionStatus={};$$('[data-eval-id]').forEach(sec=>{const id=sec.dataset.evalId;sectionStatus[id]={status:$('[data-status]',sec)?.value||'not-started',note:$('[data-note]',sec)?.value||''}});return{fields,cards,sectionStatus,lastSaved:new Date().toISOString()}}
function restoreState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!s)return;$$('[data-save-key]').forEach(el=>{const key=el.dataset.saveKey;if(!(key in (s.fields||{})))return;if(el.type==='checkbox')el.checked=!!s.fields[key];else el.value=s.fields[key];el.dispatchEvent(new Event('input',{bubbles:true}))});$$('.instant-card,.grammar-quiz article').forEach((el,i)=>{const r=s.cards?.[`card_${i}`];if(r)el.dataset.result=r});Object.entries(s.sectionStatus||{}).forEach(([id,v])=>{const sec=$(`[data-eval-id="${id}"]`);if(!sec)return;const st=$('[data-status]',sec),note=$('[data-note]',sec);if(st)st.value=v.status;if(note)note.value=v.note});$('#lastSaved')?.textContent&&( $('#lastSaved').textContent=new Date(s.lastSaved).toLocaleString());updatePressureScore();updateFinalScore();updateProgress()}catch(e){console.warn('Could not restore saved lesson.',e)}}
function touchLastSaved(){const el=$('#lastSaved');if(el)el.textContent=new Date().toLocaleString()}
let saveDebounce=null;function autoSave(){clearTimeout(saveDebounce);saveDebounce=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(serializeState()));updateEvaluationTable();touchLastSaved()},250)}

function choicesStatsFor(sectionId){const scope=sectionId?$(`[data-eval-id="${sectionId}"]`):document;if(!scope)return{correct:0,total:0};const cards=$$('.instant-card',scope);return{correct:cards.filter(c=>c.dataset.result==='correct').length,total:cards.length}}
function automaticStats(){const choicesAll=$$('.instant-card');const choiceCorrect=choicesAll.filter(c=>c.dataset.result==='correct').length;const grammar=$$('.grammar-quiz article');const grammarCorrect=grammar.filter(c=>c.dataset.result==='correct').length;const pressure=$$('#pressureRubric input[type=checkbox]:checked').length;const final=$$('[data-final-rubric]').reduce((a,s)=>a+Number(s.value||0),0);const possible=choicesAll.length+grammar.length+5+10;const earned=choiceCorrect+grammarCorrect+pressure+final;return{choiceCorrect,choiceTotal:choicesAll.length,grammarCorrect,grammarTotal:grammar.length,pressure,final,earned,possible,pct:possible?Math.round(earned/possible*100):0}}
function completionPct(){const sections=$$('[data-eval-id]');if(!sections.length)return 0;const started=sections.filter(sec=>$('[data-status]',sec)?.value!=='not-started').length;return Math.round(started/sections.length*100)}
function overallFromStatuses(){const vals=$$('[data-eval-id] [data-status]').map(s=>s.value);if(!vals.some(v=>v!=='not-started'))return'not-started';if(vals.some(v=>v==='not-achieved'))return'not-achieved';if(vals.every(v=>v==='achieved'))return'achieved';return'progress'}
function updateProgress(){const stats=automaticStats();$('#autoScore').textContent=stats.pct+'%';$('#completionRate').textContent=completionPct()+'%';const overall=overallFromStatuses(),el=$('#overallStatus');el.textContent=statusLabel(overall);el.className='status '+statusClass(overall);updateEvaluationTable()}

function buildEvaluationTable(){const body=$('#evaluationBody');body.innerHTML='';Object.entries(sectionMeta).forEach(([id,[label,mode]])=>{const tr=document.createElement('tr');tr.dataset.evalRow=id;tr.innerHTML=`<td>${label}</td><td>${mode}</td><td class="auto-cell">—</td><td><select data-table-status><option value="not-started">Non commencé</option><option value="progress">En cours</option><option value="achieved">Acquis</option><option value="not-achieved">Non acquis</option></select></td><td><textarea data-table-comment rows="2" placeholder="Observation"></textarea></td>`;body.appendChild(tr);const sec=$(`[data-eval-id="${id}"]`);const tableStatus=$('[data-table-status]',tr),tableComment=$('[data-table-comment]',tr);tableStatus.addEventListener('change',()=>{if(sec&&$('[data-status]',sec))$('[data-status]',sec).value=tableStatus.value;updateProgress();autoSave()});tableComment.addEventListener('input',()=>{if(sec&&$('[data-note]',sec))$('[data-note]',sec).value=tableComment.value;autoSave()})})}
function sectionAutoText(id){const st=automaticStats();if(id==='language')return `${choicesStatsFor('language').correct}/${choicesStatsFor('language').total} choice checks`;if(id==='delegation')return `${choicesStatsFor('delegation').correct}/${choicesStatsFor('delegation').total} choice checks`;if(id==='emotions')return `${choicesStatsFor('emotions').correct}/${choicesStatsFor('emotions').total} choice checks`;if(id==='grammar')return `${st.grammarCorrect}/${st.grammarTotal}`;if(id==='pressure')return `${st.pressure}/5 self-rubric`;if(id==='mission')return `${st.final}/10 rubric`;return'Observation / manual'}
function updateEvaluationTable(){Object.keys(sectionMeta).forEach(id=>{const row=$(`[data-eval-row="${id}"]`),sec=$(`[data-eval-id="${id}"]`);if(!row||!sec)return;$('.auto-cell',row).textContent=sectionAutoText(id);const st=$('[data-status]',sec),note=$('[data-note]',sec),tst=$('[data-table-status]',row),tc=$('[data-table-comment]',row);if(document.activeElement!==tst)tst.value=st?.value||'not-started';if(document.activeElement!==tc)tc.value=note?.value||''})}

function reportText(){const stats=automaticStats();const lines=[
  'Qualiopi learning tracking — Eden Cohen Lesson 6',
  'Lesson: Leading the Team — Feedback, Delegation & Difficult Conversations',
  `Learner: ${$('#learnerName').value}`,
  `Trainer: ${$('#trainerName').value}`,
  `Date: ${$('#evaluationDate').value}`,
  `Automatic score: ${stats.pct}% (${stats.earned}/${stats.possible})`,
  `Completion: ${completionPct()}%`,
  `Overall result: ${$('#overallStatus').textContent}`,'','SECTION RESULTS'
];Object.entries(sectionMeta).forEach(([id,[label,mode]])=>{const sec=$(`[data-eval-id="${id}"]`),row=$(`[data-eval-row="${id}"]`);lines.push(`- ${label} | ${mode} | Auto: ${sectionAutoText(id)} | ${statusLabel($('[data-status]',sec)?.value||'not-started')}`);const c=$('[data-note]',sec)?.value.trim();if(c)lines.push(`  Comment: ${c}`);const tc=$('[data-table-comment]',row)?.value.trim();if(tc&&tc!==c)lines.push(`  Table note: ${tc}`)});lines.push('','ORAL PRODUCTION',`Status: ${statusLabel($('#oralStatusManual').value)}`,`Comment: ${$('#oralCommentManual').value||'—'}`,'','GENERAL OBSERVATIONS',$('#trainerComments').value||'—','',`Automatic detail: choice checks ${stats.choiceCorrect}/${stats.choiceTotal}; grammar ${stats.grammarCorrect}/${stats.grammarTotal}; pressure rubric ${stats.pressure}/5; final rubric ${stats.final}/10.`);return lines.join('\n')}
function initReporting(){const date=$('#evaluationDate');if(!date.value)date.value=new Date().toISOString().slice(0,10);buildEvaluationTable();assignSaveKeys();$$('[data-status]').forEach(s=>s.addEventListener('change',()=>{updateProgress();autoSave()}));$$('[data-note]').forEach(n=>n.addEventListener('input',autoSave));$$('#learnerName,#trainerName,#evaluationDate,#trainerComments,#oralStatusManual,#oralCommentManual,#personalRule').forEach(el=>el.addEventListener('input',autoSave));$('#saveProgress').onclick=()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(serializeState()));touchLastSaved();toast('Progress saved locally.')};$('#copyReport').onclick=()=>{const t=reportText();$('#reportPreview').textContent=t;copyText(t)};$('#downloadReport').onclick=()=>downloadText('eden-lesson-6-qualiopi-report.txt',reportText());$('#printReport').onclick=()=>{const t=reportText();$('#reportPreview').textContent=t;window.print()};$('#resetProgress').onclick=()=>{if(confirm('Reset all locally saved Lesson 6 progress on this browser?')){localStorage.removeItem(STORAGE_KEY);location.reload()}}}

function surveyText(){return `Eden Cohen — Lesson 6 feedback\nUseful for real work: ${$('#surveyUseful').value}\nConfidence after lesson: ${$('#surveyConfidence').value}\nBest focus: ${$('#surveyBest').value}\n\nComments:\n${$('#surveyComments').value||'—'}`}
function initSurvey(){const update=()=>{$('#surveyPreview').textContent=surveyText();autoSave()};['#surveyUseful','#surveyConfidence','#surveyBest','#surveyComments'].forEach(s=>$(s).addEventListener('input',update));$('#copySurvey').onclick=()=>copyText(surveyText());$('#downloadSurvey').onclick=()=>downloadText('eden-lesson-6-feedback.txt',surveyText());update()}

function initGlobalAutosave(){document.addEventListener('input',e=>{if(e.target.matches('input,textarea')&&!e.target.closest('.grammar-quiz'))autoSave()});document.addEventListener('change',e=>{if(e.target.matches('select,input[type=checkbox]'))autoSave()})}

function init(){initNavigation();initAudio();initToggles();initVocab();initChoices();initGrammar();initBuilder();initDelegationBuilder();initTimers();initRecorders();initScenarios();initCloe();initSurprises();initFinalRubric();initReporting();initSurvey();restoreState();initGlobalAutosave();updateProgress()}
document.addEventListener('DOMContentLoaded',init);
