const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let done=new Set(JSON.parse(localStorage.getItem('antoineGrammarDone')||'[]'));
function progress(){let n=$$('[data-track="section"]').length;$('#progressBar').style.width=(done.size/n*100)+'%';$('#progressText').textContent=Math.round(done.size/n*100)+'%'}
$$('[data-track="section"]').forEach((s,i)=>{let b=$('.done-btn',s);if(done.has(i)){b.classList.add('completed');b.textContent='✓ Completed'}b.onclick=()=>{done.has(i)?done.delete(i):done.add(i);localStorage.setItem('antoineGrammarDone',JSON.stringify([...done]));b.classList.toggle('completed',done.has(i));b.textContent=done.has(i)?'✓ Completed':'✓ Mark complete';progress()}});
document.addEventListener('click',e=>{if(e.target.matches('.mcq>button[data-choice]')){let box=e.target.closest('.mcq'),ok=e.target.dataset.choice===box.dataset.answer;$$('button[data-choice]',box).forEach(x=>x.classList.remove('correct','wrong'));e.target.classList.add(ok?'correct':'wrong');let f=$('.feedback',box);f.textContent=ok?'Correct ✓ — now say the rule aloud.':'Not yet. Open the hint, identify the time clue, then try again.';f.className='feedback '+(ok?'ok':'bad')}if(e.target.matches('.hint')){let n=e.target.nextElementSibling;if(n?.classList.contains('hintbox'))n.remove();else{n=document.createElement('div');n.className='hintbox';n.textContent='💡 '+e.target.dataset.hint;e.target.after(n)}}if(e.target.matches('.model')){let b=e.target.nextElementSibling;b.textContent=e.target.dataset.model;b.classList.toggle('show')}});
$('#toggleFrench').onclick=()=>{document.body.classList.toggle('show-french');$('#toggleFrench').textContent='🇫🇷 French help: '+(document.body.classList.contains('show-french')?'ON':'OFF')};
const mixed=[['I usually ___ problems step by step.',['solve','solved','have solved'],'a','Usually → Present Simple.'],['I ___ at Decathlon for six years before my role ended.',['have worked','worked','work'],'b','Finished professional chapter → Past Simple.'],['Since leaving, I ___ more time to prepare.',['have had','had yesterday','am have'],'a','Since → past-to-now connection → Present Perfect.'],['Last month, I ___ more seriously about Australia.',['have thought','thought','thinked'],'b','Last month is finished → Past Simple.'],['I ___ try a hands-on role, but I haven’t decided yet.',['am going','might','did'],'b','Uncertain possibility → might + base verb.'],['I ___ spend about a year in Australia. That is my plan.',['am going to','might to','did'],'a','Existing plan → be going to + base verb.']];
$('#mixedQuiz').innerHTML=mixed.map((q,i)=>`<div class="mcq" data-answer="${q[2]}"><p><b>${i+1}.</b> ${q[0]}</p>${q[1].map((a,j)=>`<button data-choice="${String.fromCharCode(97+j)}">${a}</button>`).join('')}<div class="feedback"></div><button class="hint" data-hint="${q[3]}">💡 Hint</button></div>`).join('');
$('#resetLesson').onclick=()=>{if(confirm('Reset lesson progress and answers?')){localStorage.removeItem('antoineGrammarDone');location.reload()}};
$('#downloadResults').onclick=()=>{let vals=$$('textarea').map(t=>`${t.id}: ${t.value}`).join('\n\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`ANTOINE GRAMMAR FOUNDATIONS\nCompleted: ${done.size}/${$$('[data-track="section"]').length}\n\n${vals}`],{type:'text/plain'}));a.download='Antoine_Grammar_Foundations_results.txt';a.click()};
// Admin
$('#adminLaunch').onclick=()=>{buildAdmin();$('#adminOverlay').classList.add('open')};$('#adminClose').onclick=()=>$('#adminOverlay').classList.remove('open');
function buildAdmin(){let h=$('#adminSections');h.innerHTML='';$$('[data-track="section"]').forEach((s,i)=>{let d=document.createElement('div');d.className='admin-section';d.innerHTML=`<label><input type="checkbox" class="adminCheck" data-i="${i}" ${done.has(i)?'checked':''}> ${i+1}. ${$('h2',s).textContent}</label><small>${s.dataset.objective}</small>`;h.appendChild(d)})}
function sel(){return $$('.adminCheck').filter(c=>c.checked).map(c=>$$('[data-track="section"]')[+c.dataset.i])}
$('#generateAdmin').onclick=()=>{let s=sel(),uniq=a=>[...new Set(a.filter(Boolean))];let fields=[['N° de séance',$('#sessionNo').value||'À compléter'],['Durée du cours',$('#duration').value||'À compléter'],['Heures restantes',$('#hoursRemaining').value||'À compléter'],['Date du cours',$('#lessonDate').value||'À compléter'],['Objectifs de la séance',uniq(s.map(x=>x.dataset.objective)).join(' ; ')||'À compléter'],['Contenu et activités réalisées',(s.length?'Sections travaillées : '+s.map(x=>$('h2',x).textContent).join(' | '):'À compléter')+($('#lessonUrl').value?' — Support : '+$('#lessonUrl').value:'')],['Compétences',uniq(s.flatMap(x=>x.dataset.competence.split(';').map(y=>y.trim()))).join(' ; ')||'À compléter'],['Modalités d’évaluation',uniq(s.map(x=>x.dataset.eval)).join(' ; ')||'À compléter'],["Niveau d’acquisition",$('#acquisition').value||'À compléter'],['Observations ou points à signaler',$('#observation').value||'RAS']];$('#adminPreview').innerHTML=fields.map(f=>`<div class="admin-field"><b>${f[0]}</b><span>${f[1]}</span></div>`).join('');$('#adminOutput').dataset.copy=JSON.stringify(fields.map(f=>f[1]));$('#adminOutput').classList.remove('hidden')};
$('#copyReport').onclick=async()=>{let v=JSON.parse($('#adminOutput').dataset.copy||'[]');await navigator.clipboard.writeText(v.join('\t'));$('#copyReport').textContent='Copied ✓'};
$('#generateEmail').onclick=()=>{let date=$('#lessonDate').value||'[date]',url=$('#lessonUrl').value||'[lesson link]';$('#emailText').value=`Hi Antoine,\n\nThank you for this week's lesson (${date}).\n\nThis week, we slowed the grammar down and worked through the verb system step by step before applying it to your professional experience and your Australia project. The priority is to make the foundations clear and automatic before adding more complex structures.\n\nHere is this week's lesson:\n${url}\n\nYou can review the rules, keywords, verb forms, hints and model answers at your own pace.\n\nHave a great week,\nTisha`;$('#emailOutput').classList.remove('hidden')};
$('#copyEmail').onclick=async()=>{await navigator.clipboard.writeText($('#emailText').value);$('#copyEmail').textContent='Copied ✓'};
progress();